### ISSUE TITLE
Problem transpiling handsontable

### ISSUE THREAD

**Issue by haraleib** [handsontable/handsontable#10149]
### Description
I want to transpile handsontable.full.js using [google closure-compiler](https://github.com/google/closure-compiler) to ES6, but I get the following exception:

```
Cannot convert ECMASCRIPT_2018 feature "RegExp unicode property escape" to targeted output language. 
return arg.replace(/\p{L}+/gu, word => word.charAt(0).toUpperCase() + word.substring(1).toLowerCase());
                   ^^^^^^^^^^
```                                       

The line of code from the exception is placed in handsontable.full.js#60910

**Here you can see tests from goolge closure-compiler covering that case:**

- https://github.com/google/closure-compiler/blob/master/test/com/google/javascript/jscomp/MarkUntranspilableFeaturesAsRemovedTest.java#106

- https://github.com/google/closure-compiler/blob/master/test/com/google/javascript/jscomp/MarkUntranspilableFeaturesAsRemovedTest.java#111

Any ideas I can get around this issue?

### Your environment
* Handsontable version: 12.2.0

**Comment by AMBudnik** [comment]
Hi @haraleib 

Sorry for the delay. We needed to discuss this subject internally. The error you are seeing comes from the fact that Handsontable (or actually one of its dependencies) uses an ES2018. Apparently, the transpiler that you are using cannot transpile that part. It's a pity, because other transpiler (Babel) is able to transpile it to ES6. Our recommendations:

* Are you sure you need transpilation to ES6? My first suggestion is to switch to ES2018 compilation target. Handsontable only supports modern browsers, all of which have ES2018. If you are using Handsontable with an older browser, it might cause more problems.
* Are you using the Formula plugin? If not, maybe import Handsontable by modules. Then you will not load the formula plugin module, which causes the problem.
* If the answer to the above questions is yes, consider patching Handsontable file before compilation. The problematic regexp /\p{L}+/gu can be replaced with https://gist.github.com/warpech/a37b0ec80589be823e77c6bdb6d3ea3c (Babel produces such transpilation for ES6)

**Comment by haraleib** [comment]
@AMBudnik thank you for your answer. I will try it with Babel. I think https://github.com/jarslab/babel-maven-plugin should do the job. And thank you for the workaround, with patching Handsontable.

Which kind of problems can occur, when I use Handsontable with older Browsers, when I use a transpiled version of Handsontable?
