### ISSUE TITLE
validateCells() does not validate hidden/filtered cells

### ISSUE THREAD

**Issue by conschtek** [handsontable/handsontable#10320]
### Description
The idea is to validate all cells before saving the data using the validateCells() function. However, if there is an invalid entry, but by using the filter the given row is filtered out (so the it's not visible), the validateCells() function returns true (all the entries are valid), which is incorrect.

### Steps to reproduce
1. Enter an invalid entry (in a numeric field a character)
2. Using the dropdown filter, filter out the row where this invalid entry is (so the invalid entry is not seen)
3. Press the save button
4. The validateCells() returns true (see console)

### Demo
https://jsfiddle.net/TSchrempf/mbfhnzsc/5/

### Your environment
* Handsontable version: 13.3.3
* Browser name and version: Chrome
* Operating system: macOS / Windows

**Comment by adrianszymanski89** [comment]
Hi @conschtek 

The reason for this behavior is how the filtering plugin is designed. During the filtering operation, the rows are trimmed out and are no longer part of the dataset until they are visible again. Validation works only on visual rows, and that's why it validates currently visible cells as valid after filtering.

**Comment by adrianszymanski89** [comment]
Hi @conschtek 

Yes, this is how it works by design, so this is something we won't change anytime soon. As for the workaround, I'm afraid there's not much we can do about it looking at the nature of the case. We might add the information in our documentation about this limitation.
