### ISSUE TITLE
Vite build issue

### ISSUE THREAD

**Issue by zhmtn** [handsontable/handsontable#10324]
### Steps to reproduce

Use Vite Bundler,there is a issue,when you single-click the cell,the position of the square is wrong.

### Your environment
* Handsontable version: 12.3.3
* Browser name and version: Microsoft Edge 112.0.1722.39
* Operating system: MacOS 13.3

**Comment by zhmtn** [comment]
I use Vite Bundler to build a Vue3 application,there is no issue with Webpack Bundler(vue-cli).
The configuration is in the screenshot,I just use the official demo.
![Uploading 20230413082123.jpg…]()

**Comment by adrianszymanski89** [comment]
Hi @zhmtn 

Thank you for more details. I tested it locally and in a sandbox with the same settings you provided, and I couldn't get the same results. Here's a sandbox I tested it in: 

https://stackblitz.com/edit/vitejs-vite-2a6gmj?file=src%2FApp.vue,src%2Fstyle.css,src%2Fmain.js&terminal=dev

Can you tell if your issue is also present here?

**Comment by AMBudnik** [comment]
Hi @zhmtn do we have any updates regarding this issue?

**Comment by AMBudnik** [comment]
@zhmtn I need to close this topic as we did not get any feedback for a month and cannot replicate the issue ourselves.
