### ISSUE TITLE
First row not validated

### ISSUE THREAD

**Issue by rolandtritsch** [handsontable/handsontable#10395]
### Describe the bug

https://github.com/rolandtritsch/handsontable-first-row-no-validation

Please take a look at the above test case.

The first row does not get validated. It ends up valid, but should not be.

### Video/Screenshots

https://youtu.be/hVFZpiDFaSw

### Provide a link to the demo with the bug reproduction

https://github.com/rolandtritsch/handsontable-first-row-no-validation

### Handsontable version

12.3.2

### Your environment

Ubuntu, Chrome

**Comment by adrianszymanski89** [comment]
Hi @rolandtritsch 

Thank you for contacting us. I managed to solve the issue. How you implemented the validation after loading the data was causing the problem here. 

In my proposed solution, I invoke the validation right after loading the data:

```
function loadRows(reader: FileReader): void {
  const rows = csvStrToArray(reader.result as string)

  sheet.loadData(rows)
  sheet.validateCells()
}
```

I also used `validateCells()` instead of `validateRows()`. Can you please try that solution on your end and let me know if that helped? This is the result I got now after loading the file:

<img width="300" alt="image" src="https://github.com/handsontable/handsontable/assets/92314130/b9398619-5296-4520-8457-27ffb21426df">

**Comment by rolandtritsch** [comment]
Hi Adrian. Yes. This works. Issue closed.
