### ISSUE TITLE
[Bug]: focus on handsontable on iframe will make outer iframe input uneditable

### ISSUE THREAD

**Issue by zcappp** [handsontable/handsontable#10647]
### Describe the bug

in https://codepen.io/kenyxy/pen/OJdqqGW, I have an input box on the page and I create a Handsontable in iframe. if I click one cell on the Handsontable cell and then I try to focus on the input box to remove some text on the input box, no text can't be remove no matter with Backspace or Delete key, instead the content of the Handsontable cell is remove.
by the way it is fine to input other charater. 

### Provide a link to the demo with the bug reproduction

https://codepen.io/kenyxy/pen/OJdqqGW

### Handsontable version

14.0.0

### Your environment

latest chrome

**Comment by AMBudnik** [comment]
Hi @zcappp 

I was thinking that maybe this issue is related to a regression that we found for v14.0.0 but it seems to work the same way in v8. I used this demo for tests https://jsfiddle.net/25redLgk/

Could you please tell me if this demo works for you the same way? 

I used Chrome 119 on macOS Ventura to test it with the following steps.

1. Click A2 cell
2. Click input in the middle of the text
3. Click <kbd> backspace</kbd> key on keyboard

**Result**: The text in input is not altered, but the value from A1 is removed.

**Comment by zcappp** [comment]
yes, this demo works the same way in my side, it has the same effect as my demo: the text can't be altered.

**Comment by AMBudnik** [comment]
Thank you for the confirmation.

I will notify you as soon as we fix it.

**Comment by AMBudnik** [comment]
Hi @zcappp 

It's a great day today.

We published Handsontable v14.2.0, where this issue is fixed.

Here https://github.com/handsontable/handsontable/pull/10752 you can check what we did for this issue. And here, https://handsontable.com/docs/javascript-data-grid/release-notes/#_14-2-0 is a full list of changes.
