### ISSUE TITLE
[Bug]: Formula get changed when moving column

### ISSUE THREAD

**Issue by thanhlevu** [handsontable/handsontable#10702]
### Describe the bug

Hi, 
I am facing to the problem that the formula auto updated unexpectedly when moving the column associated with the cell positions in the formula.

How to repeat the bug:
0. go to the example here: https://jsfiddle.net/handsoncode/hfgL74wt/
1. at the cell D3, I have a formula: =SUM(A2:E2)
2. moving any columns to the column A or E
3. the formula on the cell D3 get changed. 

### Video/Screenshots

https://github.com/handsontable/handsontable/assets/33485829/f3b95ec3-10fa-433d-9875-c4bf57e135d6

### Handsontable version

14.0.0

### Your environment

MacOS Ventura 13.1 - Chrome Version 119.0.6045.159 (Official Build) (x86_64)

**Comment by adrianszymanski89** [comment]
Hi @thanhlevu 

This is actually a feature, but you can bypass it if you need to. There's a method `afterFormulasValuesUpdate` that controls this. You can just make it return if there are any changes in, for example, column order. Here's an example: https://jsfiddle.net/handsoncode/k4qxj6af/

**Comment by thanhlevu** [comment]
Hi @adrianszymanski89,

Thank you so much for your time on my matter again. 

I have reviewed your solution in jsfiddle, 
with `return;`,  I see it does not help to bypass the changes of formula if column moved. 

Do you mean, I need to set a logic to revert the changes of formula in the `afterFormulasValuesUpdate` hook ?

**Comment by adrianszymanski89** [comment]
Hi @thanhlevu 

You are right, when I tested it it seemed to work. I asked our HyperFormula developer if that's indeed an intended behavior, as after more investigation, it seems not to work correctly. I'll let you know once I have more information.

**Comment by thanhlevu** [comment]
wonderful @adrianszymanski89 ,
thank you once again.

**Comment by adrianszymanski89** [comment]
Hi @thanhlevu 

I have an update for you. I get confirmation that this is a desired behavior, and it matches the industry standard, so it behaves the same in Excel, for example. 

Because of that, it's not possible to alter this functionality, as it may break the fundamentals of the plugin behavior and make it unusable in general.

There might be a workaround to restore the initial formula each time the columns are manually moved with the `setDataAtCell` hook, but it's inefficient. Here's an example: https://jsfiddle.net/handsoncode/8wadLzp5/

**Comment by thanhlevu** [comment]
Hi @adrianszymanski89, 

Thank you for your reply. I see what you mean that it is not efficient if using `setDataAtCell`. 
Thank you for your help always.
