### ISSUE TITLE
[Bug]: Column filter configuration is not working right 

### ISSUE THREAD

**Issue by wenlifullstack** [handsontable/handsontable#10711]
### Describe the bug

after upgrading our Handsontable to version 14, it seems like our column filter is acting up and not working as expected. I dug into the issue and found some trouble in the documentation too. https://handsontable.com/docs/react-data-grid/column-filter/  
here is JSFiddle demo for the issue https://jsfiddle.net/api/post/library/pure/

### Handsontable version

14

### Your environment

chrome

**Comment by adrianszymanski89** [comment]
Hi @wenlifullstack 

Thank you for contacting us. This issue is known to us and has already been fixed. It will be available with the next release by the end of January. I will update you once it's released.

**Comment by AMBudnik** [comment]
Hi @wenlifullstack 

We just released v14.1.0, where this issue is fixed. Thank you again for reporting. I will close this issue as solved with that one.

Here you can read more about the changes that we introduced and issues that were fixed https://handsontable.com/blog/handsontable-14-1-0-typescript-ssr-improvements
