### ISSUE TITLE
[Bug]: `AutoColumnSize` plugin gets disabled when `colWidths` is set

### ISSUE THREAD

**Issue by janisdd** [handsontable/handsontable#10764]
### Describe the bug

I'm not entirely sure if this is a bug but here are some things in the current version I noticed while implementing my own features (I'm still on v6.2.2):

- https://github.com/handsontable/handsontable/blob/91f601e1e4c9d7b620f49ccafc43ff67bbbf13fd/handsontable/src/plugins/autoRowSize/autoRowSize.js#L211-L215
- https://github.com/handsontable/handsontable/blob/91f601e1e4c9d7b620f49ccafc43ff67bbbf13fd/handsontable/src/plugins/autoColumnSize/autoColumnSize.js#L226-L228

Judging by the documentation of `autoRowSize` and `autoColumnSize`, they use almost the same format/type.

However, in `autoColumnSize.js` the `colWidths` is check ...

From my testing, it seems that the `autoColumnSize` plugin is disabled when `colWidths` is specified.
Again, I'm not sure if this is a bug or intentional, but the code seems strange to me.

### Handsontable version

14.1.0

### Your environment

browser

**Comment by AMBudnik** [comment]
Hi @janisdd 

Thank you for sharing the issue report.

This one is intentional, you can read about in the `AutoColumnSize` guide at https://handsontable.com/docs/javascript-data-grid/api/auto-column-size/

![Zrzut ekranu 2024-02-5 o 08 35 34](https://github.com/handsontable/handsontable/assets/10757813/941cc3b5-829f-43fd-8795-70cbe9294a64)

**Comment by janisdd** [comment]
Ah, I see. I have read the old documentation, thanks for the clarification.
