### ISSUE TITLE
Table inside iframe does not trigger change when typing and then clicking outside the iframe on in another iframe

### ISSUE THREAD

**Issue by juan-rvty** [handsontable/handsontable#11015]
### Describe the bug

Click on a cell, type "1111" and then click on the other iframe or outside of both iframes, the cell will lose the focus but it will not trigger the afterChange hook. BeforeChange also doesnt work, it seems like the change event is not being triggered.

### Provide a link to the demo with the bug reproduction

https://codepen.io/Juan-Garc-a-de-la-cruz/pen/ZENXzrZ

### Handsontable version

12.2-14.3

### Your environment

Firefox and chrome

**Comment by adrianszymanski89** [comment]
Hi @juan-rvty 

Thank you for contacting us. I checked your example, but I can't reproduce this behavior. The value is correctly saved to the cell wherever I click outside the table, but the focus is switched to an outside element so the newly focused input can be edited. Also, the issue you mentioned has already been fixed and available since v. 14.2.0, and this behavior was altered on purpose to match the requirements I described above.

**Comment by juan-rvty** [comment]
Hello @adrianszymanski89  attaching a recording so that you can see the steps and the bug:
![Bug](https://github.com/handsontable/handsontable/assets/119865371/ef2f5bfb-20e1-41a9-9de6-05b3ec575498)

**Comment by adrianszymanski89** [comment]
Hi @juan-rvty 

I still think it's correct behavior, as the `afterChange` hook will not be called in this case because nothing has changed within the table. It will be called if you click just outside the table because then the editor will get closed. The same will happen if you click on any other outside DOM element that does not contain a Handsontable instance.
