### ISSUE TITLE
copy cell

### ISSUE THREAD

**Issue by 1004834495** [handsontable/handsontable#11155]
### Describe the bug

Copy the cell, but my content reset the copy. The result is how to handle the previous data.
Please check the demonstration below. Select the cell in the first column of the table and hold down ctrl+c. The result will be 0 or 1. The result I want is add or update.

### Provide a link to the demo with the bug reproduction

https://stackblitz.com/edit/react-6ds5cb?file=src%2FExampleComponent.jsx

### Handsontable version

14.4.0

### Your environment

windows10  google

**Comment by adrianszymanski89** [comment]
Hi @1004834495 

Thank you for contacting us. This behavior is caused by our copy-paste plugin operating on the data in the cell and not on what the renderer shows. In your case, it's 0 or 1, and those values are copied.

An issue on the same topic was raised recently. You can check the proposed solution I showed there: https://github.com/handsontable/handsontable/discussions/11150

**Comment by 1004834495** [comment]
But what I want is to get the rendered value when copying (ctrl+c). What should I do with it? If possible, please provide the following code

**Comment by AMBudnik** [comment]
Hi @1004834495 

My colleague took some days off, so I'm here to help with the ticket.

In general, you could use the `this.getCell(coords[0].startRow, coords[0].startCol).textContent` within `beforeCopy` hook to get the rendered value. Demo: https://stackblitz.com/edit/7ksr8e?file=index.js
But then if you'd like to paste that you need to overwrite data within the `beforePaste` hook as well.
