### ISSUE TITLE
manual column move

### ISSUE THREAD

**Issue by popo1221** [handsontable/handsontable#1277]
When there is a horizontal scrollbar, and the scroll bar is moved to center, the Manual column move function is not ok, following errer happens:
Uncaught TypeError: Cannot call method 'querySelector' of undefined.

And i fixed the error by modifying the codes:

var mover = THs[instance.view.wt.wtDom.index(this)].querySelector('.manualColumnMover');

**Comment by AMBudnik** [comment]
I couldn't reproduce this issue. You were using our [demo](http://handsontable.com/demo/column_move.html) or it it an issue in your code? If so, please provide a [JSFiddle](jsfiddle.net/api/post/library/pure/) of it. Since this issue is from an year ago I assume it could not be a problem any more, so I'll keep issue closed but feel free to reply if necessary.
