### ISSUE TITLE
Cannot copy handsontable contents when it's in a modal jQuery dialog.

### ISSUE THREAD

**Issue by phyrisrose** [handsontable/handsontable#1480]
Hi there,

Amazing work, you guys! I am loving handsontable, it works for everything I need and beyond.

I did find an issue though, not sure if it's known or not. I have a handsontable within a jQuery UI modal dialog. Works fine with a non-modal dialog. JSFiddle here: http://jsfiddle.net/734r3/

I tried changing z-index of CopyPasteDiv to a higher number than the jQuery overlay element, but to no avail.

**Comment by nip3o** [comment]
I experience the same issue in Handsontable 0.16.1, and I have not managed to come up with a solution or workaround. Paste does not seem to work either. Any plans on looking at this?

**Comment by nip3o** [comment]
I have found the reason for this problem as well as a workaround. The problem is that jQuery UI dialog disallows any events to elements outside the dialog, such as to the copyPaste textarea. The following snippet overrides jQuery UI dialog to allow focusing on the copyPaste textarea, so that copy paste can work as expected.

    (function($) {
        $.widget("ui.dialog", $.ui.dialog, {
            _allowInteraction: function(event) {
                if(this._super(event)) {
                    return true;
                }
                return $(event.target).hasClass('copyPaste');
            },
        });
    })(jQuery);

Not sure about what the best way of fixing this in Handsontable would be. Check this jQuery UI issue for some background: http://bugs.jqueryui.com/ticket/9271

**Comment by AMBudnik** [comment]
Hi @nip3o 
I would really want to solve this case but wasn't able to reproduce the bug,
could you check it please with the latest (0.24.1) version?

I would appreciate.

**Comment by nip3o** [comment]
I can reproduce it using @phyrisrose's JSFiddle above (http://jsfiddle.net/734r3/) - and it seems to use the latest version of Handsontable. Tested in Chrome Canary, Firefox, Safari (OS X). Copy/paste using keyboard commands cmd + c / cmd + v works as long as the jQuery UI dialog `modal` option is set to `false`, but not when set to `true`.

**Comment by AMBudnik** [comment]
Thanks for sharing details @nip3o I reproduced it also.

**Comment by g0nP** [comment]
Any updates on this?

I have the last version (0.28.3) but i can't still copy&paste when the handsontable is in a jQuery modal dialog.

**Comment by nandaabiz** [comment]
For me, if we move the `CopyPasteDiv`  inside modal dialog rather than append to document.body, the copy-paste function works normally. Maybe we can add an option which override `CopyPasteClass.prototype.init` function by choosing whether append to document body or inside (or sibling) to handsontable's container. Maybe?

Any other workaround?

**Comment by Ir00man** [comment]
As for me I have stopped on this solution:
if you have something like this to run your table:

`handsontable = new Handsontable(container, {...})`

then simply add right after:

`$('#CopyPasteDiv').appendTo(container);`

this will move that problem <textarea> inside the popup and copy/paste will work as usual.

**Comment by wickedrahul** [comment]
@Ir00man It worked for me. Many thanks :)

**Comment by seharri92** [comment]
When using blueprintjs components with react, putting a table inside their overlay component also blocks the copy paste div from being accessed.

**Comment by swistach** [comment]
Hi folks, recent version (0.32.0/1.11.0) of the Handsontable works well in jquery-ui dialog (v1.12.1).
Demo: http://jsfiddle.net/9zwoy5fn/

@seharri92: That would be really helpful, if you could open new issue with necessary description. Did you try to use [reeact-handsontable](/handsontable/react-handsontable)?
