### ISSUE TITLE
Can't exit cell in rightmost column

### ISSUE THREAD

**Issue by csu** [handsontable/handsontable#1556]
When I'm editing a cell in the rightmost column of a handson table, I can't exit the cell. It never deselects the cell and I can't type in any other cells.

This happens to me for the [Validation example](http://handsontable.com/demo/validation.html) as well as this code:

    <div id="dataTable"></div>
    <script>
      var initial = [
        ["Name", "Value"]
      ];
      $("#dataTable").handsontable({
          data: initial,
          minSpareRows: 1,
          contextMenu: true,
          colHeaders: ['Name', 'Value'],
          columns: [
            {data: 'name'},
            {data: 'value', type: 'numeric'}
          ]
      });
    </script>

Tested in Google Chrome and Safari on Mac OS X.

**Comment by AMBudnik** [comment]
I agree, this issue still occurs. Thank you for that report.

**Comment by jansiegel** [comment]
@csu The issue with being stuck in a edited cell might be a problem with validation with `allowInvalid` option turned off. 
Just like in this demo: http://handsontable.com/demo/validation.html - The last column has the `allowInvalid` option turned off, so it *doesn't accept* anything that's not valid, and will not leave the editor until users enters a proper value.
The previous (IP) column however, has the `allowInvalid` option turned *on*, so it accepts invalid data, but marks it red if it doesn't pass validation.

As for your code example, it doesn't work properly, because you define the `column` settings as if you were using an object as the data source, but you pass an array to the `data` config item.

Also, I couldn't reproduce this error you pasted, is it possible to reproduce in in a jsfiddle/codepen? It would help us identify it better.
