### ISSUE TITLE
How can we align text from top to bottom in the cell?

### ISSUE THREAD

**Issue by psgganesh** [handsontable/handsontable#1586]
Can a layout like this be achieved on HOT?

![image](https://cloud.githubusercontent.com/assets/2221525/3526952/617e5a62-0780-11e4-9d7e-d54e55b0720b.png)

**Comment by rharsh** [comment]
Can you post a JSfiddle or similar for the entire code. Thanks. ideally working on TD and not on TH

**Comment by loup-kreidl** [comment]
Hello,
I just used this trick, but I had to do some modifications:
- I used a renderer and applied the jquery methods to $(td).
- Before the 3 Jquery calls I added this line:
    Handsontable.renderers.TextRenderer.apply(this, arguments);
- Bust mostly I had to modify the 12em value in the translation, I guess it depends on the text's length we are trying to apply this (it seems to me that the shorter the text is the lower this value is), and also to modify the height of those td markdown.

But the td's width is still too large, and I can't find anything to modify it, i'm starting to think that it's caused by the application of the default text renderer. Does someone have an idea about this?
Or maybe, another way to archive this?
