### ISSUE TITLE
Scrolling problem - floating header in column sorting demo

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#1614]
When I sort data and then reset the table I end up with header floating underneath the first row. I've also spotted that first column exceeds table's height then.

Chrome ver. 35.0.1916.153, win7, no ext.
http://handsontable.com/demo/sorting.html

Before reset (browser scrollbar is then scrolled down sth about 10% of its height):
![state-1](https://cloud.githubusercontent.com/assets/8048526/3578359/7c9c7280-0ba8-11e4-854e-4a7df30ba2c9.png)

After reset:
![state-2](https://cloud.githubusercontent.com/assets/8048526/3578360/7c9e4a24-0ba8-11e4-8268-59b535d5408f.png)

**Comment by floribon** [comment]
I had the same issue of floating headers while scrolling as of today with version `0.20.1`

I am so happy to finally have found a work around: it turns out Handsontable reads the HTML node style to detect if if is `overflow: auto` and then synchronize the scroll. Using CSS on the element was not enough, **I had to write an inline `style = "height: 100%; overflow: auto"`** (yeah for some reason the height was also involved). I wish that was clearly documented or explained because I spent a lot of time digging the root cause.
