### ISSUE TITLE
Another fixedColumnLeft bug

### ISSUE THREAD

**Issue by phyrisrose** [handsontable/handsontable#1780]
When setting fixed columns, the height of the header of fixed columns doesn't match that of the rest of the table when header spills on two lines:

http://jsbin.com/ginacuyexevo/1/edit

The whole first column shifts up one row.

**Comment by jansiegel** [comment]
Reopening: the headers don't shrink, when header content is dynamically removed.

**Comment by mkcor** [comment]
@jansiegel I believe this commit https://github.com/handsontable/handsontable/commit/b15931ad2da399b09bb124688ac84fd544c2390e should be reverted because it makes the header behave differently and exotically, overriding behaviours that you can otherwise control the expected way.

What I believe is going on, as you can see by adding
```js
document.querySelector('.ht_clone_top').style.display = "none";
document.querySelector('.ht_clone_left').style.display = "none";
document.querySelector('.ht_clone_corner').style.display = "none";
document.querySelector('.ht_master').style.display = "";
```
is that 'new' classes `ht_clone_top`, `ht_clone_left`, and `ht_clone_corner` haven't caught up (yet) to the great ability of resizing/re-rendering/refreshing that `ht_master` offers.

I believe this issue should not be considered a *bug* that needs fixing.  My guess is that it should be approached in terms of extending the original philosophy of dynamical rendering, which underlies the 'old' Handsontable.

/cc @warpech

**Comment by jansiegel** [comment]
@mkcor Simply reverting this (b15931a) commit won't cut it.
As you noticed, the master table renders correctly, because it's a single `table` element - it just takes the data in and renders it. But our current setup with the overlays adds some complexity to that situation, for example:
If 2 columns are fixed and the 'oversized header' is located in the 5th column, the `master` instance has to inform the `left` and `corner` instances, that the column headers need to be resized to the desired height, because they don't have any information about columns 2+.

f4e7efe956f379830ce958db6382261c8589526c should fix the shrinking problem

**Comment by mkcor** [comment]
@jansiegel I never said the solution was to *simply* revert commit b15931a. I didn't write this (and I would never say *simply* -- learnt that with Software Carpentry).

I said b15931a introduced exotic behaviours with side effects. I've said I would expect this resizing issue to bring into play `ht_master`, `ht_clone_corner`, which you seem to be confirming ("the `master` instance has to inform the `left` and `corner` instances...") and which apparently is the case in f4e7efe.

**Comment by jansiegel** [comment]
@mkcor We're currently working at resolving this issue with a different approach (which is using the oversized-rows mechanism for column headers).
At the moment we're facing some difficulties connected with dynamic column rendering, but I think we should be done with it soon.

**Comment by mkcor** [comment]
@jansiegel Great, I'll stay tuned.

**Comment by budnix** [comment]
I prepared a demo http://jsbin.com/gimulimixe/edit?html,js,output and it seams to be OK (using Handsontable 0.15.0). Any one can confirm?
