### ISSUE TITLE
Autocomplete with Handsontable cell type (HOT-in-HOT)

### ISSUE THREAD

**Issue by radusl** [handsontable/handsontable#1855]
Is it possible to have autocomplete function for the "Handsontable cell type". If yes, how? I can't seem to get it to work.
http://jsfiddle.net/api/post/library/pure/

**Comment by AMBudnik** [comment]
We are closing issues related to feature requests to create a full document based on that ideas from all our sources. It is avaiable is our [wiki section](https://github.com/handsontable/handsontable/wiki/Feature-requests).

**Comment by sxchan** [comment]
it's listed on Wiki section , however, no details mention if this request is on-going or banned?

**Comment by AMBudnik** [comment]
@sxchan all `feature` and `improvement suggestions` topics are closed will they get picked by a developer. Then we're reopening topic and updating with other labels (like `in development`).

Currently there are so many ideas on what we can add or change that it is very hard to keep up with following bugs - which have the priority. That's why all the ideas have their own section.

**Comment by AMBudnik** [comment]
As there aren't many comments on closed issues, we decided to reopen the feature requests as Github Discussions. 

Please feel free to share any feedback that will allow us to compose the full list of requirements for the proposed change.
