### ISSUE TITLE
Aligning content causes crash of the browser

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#1897]
Option `Alignment` causes browser's crash if applied to a table containing 1000 rows.

**Steps to reproduce the problem:**

- Go to http://handsontable.com/demo/scroll_window.html
- Invoke context menu by right-click on column header
- Select Alignment: middle
- Wait, wait, wait... until browser (or process) crashes

:information_source:
> Handsontable v. 0.11.4
> Windows 8.1
> Chrome v. 38.0.2125.111 m

![alignment](https://cloud.githubusercontent.com/assets/8048526/5028694/ebb1b644-6b3e-11e4-9fc8-5b9a8deb1951.png)

**Comment by jansiegel** [comment]
This issue had changed a tad since its initial form:

--------
##### Current steps to reproduce:
* go to http://handsontable.com/demo/scroll_window.html
* right-click any cell for the context menu to show up
* hover the cursor the *Alignment* entry

##### Result:
* The entire page scrolls and/or the context menu is moved, resulting in being unable to set the alignment

**Comment by steelstyle** [comment]
Can you please my pull request if it's not relevant anymore ?
