### ISSUE TITLE
Adding beforeRowMove event

### ISSUE THREAD

**Issue by mapinales** [handsontable/handsontable#1904]
Hello,

There is currently no beforeRowMove or beforeColumnMove event. These events should be capturable in case the moving is condition based. I'm trying to set up my sheet where the first 3 rows should not be movable. Also, fixed rows and columns are currently movable and can have columns and rows moved in to them. I thought that by fixing the first 3 rows I would be able to solve my issue, but that is not the case.  Read only rows are also able to be moved.  

If this is intentional and/or a fix for this is not planned, how would I go about writing my own event for this?  

Thank you for your time.
Miguel

**Comment by IntegerMan** [comment]
This feature would be extremely helpful. I noted that there was no comment on adding such a provision. It sounds like there's no hands.

This would have saved me a lot of aggravation in trying to resolve synchronization issues caused by needing to perform manual operations on move that inherently affect the underlying data, causing the HoT to become out of sync with its data source after the source array is resorted.

As it stands, I'll likely need to attempt something similar or to manipulate the manualRowPositions property or other internal grid variables during the afterRowMove or beforeRowMove callback.

Can we please consider adding this feature? I'm coming from a .NET client-side development background where most events have preview callbacks where you can set the event args .cancel to true to prevent something from being executed (either due to invalid action or because you want to take a custom action).

**Comment by AMBudnik** [comment]
Issue transfered to [wiki > feature request](https://github.com/handsontable/handsontable/wiki/Feature-requests)
It'll be reopened when ready to develop.

**Comment by AMBudnik** [comment]
The mentioned hook was added https://docs.handsontable.com/pro/1.10.2/Hooks.html#event:beforeRowMove
