### ISSUE TITLE
Comments not working if used inside update settings

### ISSUE THREAD

**Issue by sumit150989** [handsontable/handsontable#1921]
If while declaration of HOT comments are not initialized . and trying to add from update setting its not updating .

**Comment by donmccurdy** [comment]
This works correctly for me (on v0.12.1). Make sure you're calling updateSettings() *after* loading any data, or comments will be overwritten. Here's what I'm doing, since some settings need to be set before loading data, too:

```javascript
table.updateSettings({maxRows: this.getRowCount()});
table.loadData(this.getData());
table.updateSettings({cell: this.getComments()});
```

If that doesn't work, it might be good if you could include the version of Handsontable and a simple code example to reproduce this!

**Comment by AMBudnik** [comment]
If you would have any other questions, please reply and we'll reopen this issue.
