### ISSUE TITLE
Tables not stretching properly when contained in hidden element

### ISSUE THREAD

**Issue by tikitikifoofoo** [handsontable/handsontable#2026]
Steps to recreate:
1. Visit this link: http://jsfiddle.net/vcakdven/
2. Notice that the table in Tab 1 works fine initially
3. Click on Tab 2 and notice that the table has not stretched properly even though it has been initialized the exact same as the other
4. While still on Tab 2, scroll horizontally
5. Click back to Tab 1 and notice that the table there has now lost it's stretch properties

I've been able to get around this by calling render on the table as soon as the tab is clicked and displayed, but seems a bit hacky.

**Comment by mscreenie** [comment]
+1 seems like its broken when an element is hidden, use case would be using handsontable with bootstrap tabs, very common use.

or any situation requiring an element be hidden then shown later, stretch-h doesn't seem to be working in this case.

**Comment by elmut38** [comment]
I reproduce this case without bootstrap, just with jQuery.

Can help : 
The value reported by .height() is not guaranteed to be accurate when the element or its parent is hidden. To get an accurate value, ensure the element is visible before using .height(). jQuery will attempt to temporarily show and then re-hide an element in order to measure its dimensions, but this is unreliable and (even when accurate) can significantly impact page performance. This show-and-rehide measurement feature may be removed in a future version of jQuery.
Idem for width
(source : https://api.jquery.com/height/  - https://api.jquery.com/width/)

**Comment by nilavghosh** [comment]
Facing the exact issue here! Anyone with a resolution?

**Comment by mscreenie** [comment]
My fix was to render the tab on show. Bootstrap triggers on show events . This was my fix.

**Comment by pgksunilkumar** [comment]
in my page having four bootstrap nav tabs in the Tab 1 works fine initially but remaining tab2 tab3 tab4 is not stretched properly even though it has been initialized the exact same as the other can any way is to adjust the width in remaining tab
