### ISSUE TITLE
Columns' width decreasing while scrolling

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#2048]
On the `stretch_window` demo page after adding one or more new columns the width of columns is decreasing while scrolling down/up.

**Steps to reproduce the problem:**

- Go to http://handsontable.com/demo/stretch_window.html
- Invoke context menu by right-click
- Select "Insert column on the right". Repeat it 2x
- Start scrolling down (using mouse scroll, arrow keys or scrollbar)

:information_source:
> Handsontable v. 0.11.4
> Windows 8.1
> Chrome v. 39.0.2171.95 m

![screenclip](https://cloud.githubusercontent.com/assets/8048526/5703129/8b9c4de8-9a62-11e4-8cd3-2ba8edfaaf6f.png)

**Comment by PassHours** [comment]
I think this is a browser specific issue. 
Running fine in Firefox and IE, but abnormal column decreasing behavior in Chrome as you mentioned.

**Comment by kevin-j-morse** [comment]
@PassHours I agree.

No issues herewith IE11 or Firefox 34

Seeing the issue in Chrome 39 64-bit

**Comment by jansiegel** [comment]
This issue is fixed in #1919.
Although on #1919 it works the same in all browsers, that's not exactly the desired behaviour.

When the table is stretched in a container, adding another column should again trigger stretch, so that the new columns also fits within the container.
Currently, adding another column makes the table exceed the container width.
