### ISSUE TITLE
Problem with cells height on 'wordWrap: true' option

### ISSUE THREAD

**Issue by niks986** [handsontable/handsontable#2107]
When scroll horizontal scrollbar, data cells change his own size... http://jsfiddle.net/o34a9Ly1/3/
![untitled-1](https://cloud.githubusercontent.com/assets/7994942/5915542/546e5c0c-a607-11e4-98d0-127250337e8c.png)

**Comment by AMBudnik** [comment]
Related to #2213

**Comment by krzysztofspilka** [comment]
Connected with #493

**Comment by krzysztofspilka** [comment]
@niks986 there's no simple solution to this problem. Everything we thought about would kill the performance, though the problem is serious enough to give it another thought. Please head to #493 to follow our progress on this.

As for the workaround, please see the demo I've just prepared: http://jsfiddle.net/mwwxaypc/
First off, apply `overflow:hidden` to the main container. Then, use `viewportColumnRenderingOffset: 100` to render first one hundred columns at once. This actually covers your entire table in a horizontal axis. One nuisance here is a bit longer initialization time.

**Comment by krzysztofspilka** [comment]
This is working fine in 0.17.0
