### ISSUE TITLE
using selectCell without gaining focus

### ISSUE THREAD

**Issue by artsince** [handsontable/handsontable#2138]
Is there a way to programmatically highlight a cell/row without handsontable acquiring the focus?

What I am trying to do in my project is that I am going through a list of items with the arrow keys. On each item, I call selectCell on my table to highlight the corresponding row. The problem is that handsontable gains the focus, and the arrow keys move the selected cell on the table instead of my list of items.

thanks a lot

**Comment by PassHours** [comment]
Can you provide a jsfiddle for this for better understanding.

**Comment by artsince** [comment]
@PassHours  here's the link. http://jsfiddle.net/h19fo48h/

thanks a lot.

**Comment by jansiegel** [comment]
@artsince As you noticed, the selectCell by default sets the focus to the Handsontable instance.
However, you can try this simple workaround: 
Instead of using `.selectCell(x1, y1, x2, y2)` you can use `.setRangeStart(x1, y1)` with `.setRangeEnd(x2, y2)`. This way you should select the cells you want, without focusing on the table.

See the modified jsfiddle: http://jsfiddle.net/h19fo48h/2/

**Comment by AMBudnik** [comment]
@artsince if you would have any other question, feel free to contact us on [hello@handsontable.com](mailto:hello@handsontable.com) or simply write an issue.

**Comment by gka** [comment]
Am I wrong or is `setRangeStart` and `setRangeEnd` no longer available in Handsontable?

**Comment by AMBudnik** [comment]
Hi @gka 
there have been some changes related to selection.

Here are the hooks.
https://docs.handsontable.com/pro/1.17.0/Hooks.html#event:beforeSetRangeStart
https://docs.handsontable.com/pro/1.17.0/Hooks.html#event:beforeSetRangeEnd

And here are our release notes https://docs.handsontable.com/pro/1.17.0/tutorial-release-notes.html some of the changes are backward incompatible so I highly encourage to check the list
