### ISSUE TITLE
beforeKeyDown ->  event.stopImmediatePropagation() doesn't work 

### ISSUE THREAD

**Issue by jarben** [handsontable/handsontable#2207]
I've tried the latest 0.12.6 version and noticed: 
beforeKeyDown:function(ev){
     ev.stopImmediatePropagation();
}

doesn't work anymore..

try: http://jsfiddle.net/0bg3cLjy and notice you can make changes in the editor by pressing keydown

**Comment by jarben** [comment]
found a workaround for this by calling: 
ev.isImmediatePropagationEnabled = false;
ev.isImmediatePropagationStopped = function(){
    return true;
};

instead of ev.stopImmediatePropagation();

**Comment by Lukazar** [comment]
You could also add ` Handsontable.Dom.enableImmediatePropagation(ev);` at the top of your function as shown here.

**Comment by AMBudnik** [comment]
I assume it not an issue anymore (in lack of recent activity and any other questions.)

**Comment by FeepingCreature** [comment]
You assume wrong. At least the documentation should be fixed. It advocates ev.stopImmediatePropagation() in places.

**Comment by AMBudnik** [comment]
Ok thanks @FeepingCreature for your suggestion.

**Comment by AMBudnik** [comment]
I'm transferring all the improvement suggestion to our Wiki section at: [improvement suggestions](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions)

Please feel free to add any additional suggestions/tips or investigation results. 

Issue is closed. It will be reopened with a developing update.

**Comment by arfis** [comment]
At the moment im working in angular with handsonetable and i cant make it work.. the version is 2.0.0. It is a very crucial functionality which I need. Can you please help me out with it?

**Comment by AMBudnik** [comment]
Can I ask you to create a demo @arfis ?

**Comment by arfis** [comment]
i have created an demo on git.. https://github.com/arfis/angularTest. The TableComponent contains the table.

**Comment by AMBudnik** [comment]
When I wanted to clone the repository I got an error and a note that I do not have a permission to do this.
Can you use a JS playground to create a demo? If not. Write me at support@handsontable.com

**Comment by arfis** [comment]
I have written you a mail

**Comment by jsessink** [comment]
For those who may come across this having issues with this via Angular and accessing KeyboardEvent with the beforeKeyDown hook, here's are your options to being able to use preventDefault / stopImmediatePropagation as noted in the docs:

- Use the directive, which will supply the HOTInstance and the event list with KeyboardEvent as the first index.

**Eg usage (in the directive):**
![image](https://user-images.githubusercontent.com/2416081/46028698-e72f0780-c0b6-11e8-9925-8f7d3da9a094.png)

![image](https://user-images.githubusercontent.com/2416081/46028612-b18a1e80-c0b6-11e8-880a-5f5d0dbbcbbe.png)


- Use the settings instead of the directive.  This will give you access to the actual KeyboardEvent directly, instead of the HOTInstance and event list.

**Eg usage (in the settings):**
![image](https://user-images.githubusercontent.com/2416081/46028190-88b55980-c0b5-11e8-8def-80f13405a687.png)

![image](https://user-images.githubusercontent.com/2416081/46028765-0cbc1100-c0b7-11e8-8820-c147866ac500.png)

**Comment by AMBudnik** [comment]
To updated the subject I've just check v8.4.0 on
* Vanilla https://jsfiddle.net/handsoncode/v2pzb3dx/
* Angular https://jsfiddle.net/handsoncode/7cv6xbz4/ 
* React https://jsfiddle.net/handsoncode/ftvuszdo/
* Vue https://jsfiddle.net/handsoncode/zm5wt1yu/

and it works well in all of the cases with a simple implementation of 

```js
beforeKeyDown: function(ev) {
            ev.stopImmediatePropagation();
}
```
