### ISSUE TITLE
Add maxSpareCols/ maxSpareRows options

### ISSUE THREAD

**Issue by deeta** [handsontable/handsontable#225]
Is there a way to set a max spare rows property?

For example: start with minSpareRows: 1 and create up to a maximum of n rows

**Comment by jouyuy** [comment]
@warpech Hey man!

As far as I understand none of the mentioned settings addresses the original request. The closest one is `maxCols` but it limits the maximum amount of columns while desired ability is to limit maximum amount of _spare_ columns.

With that, am I missing something or should we re-open this issue?

**Comment by jouyuy** [comment]
@AMBudnik 

Imagine the following scenario:
1. We have a table with single row.
2. `maxCols` is unset because we don't want to limit maximum amount of columns.
3. `minSpareCols` is set to 1 so that every time all cells are filled out a blank one appears.

What I need is to limit the _maximum_ amount of _spare_ columns so that there is _always_ 1 spare column. When using `minSpareCols` with unset `maxCols` you can actually create as many spare columns as you want.

I found a way to achieve desired behaviour by combining dynamic `maxCols` (watch for data changes and set it to current columns count + 1) and `minSpareCols` set to 1. However, I think that `maxSpareCols` would provide a more clean/straightforward solution for this.

**Comment by AMBudnik** [comment]
You should also be able to determine if your table should add a spare column by checking [`isEmptyCol`](https://docs.handsontable.com/pro/4.0.0/Core.html#isEmptyCol) via `beforeCreateCol` hook

**Comment by jouyuy** [comment]
@AMBudnik 

What do I do if I find out that I shouldn't add that column in `beforeCreateCol` hook? After your suggestion I expect to be able to return something like `false` from the `beforeCreateCol` hook in order to prevent that column from being added, but I looked it up in [the documentation](https://docs.handsontable.com/4.0.0/Hooks.html#event:beforeCreateCol) and didn't find anything like that.

**Comment by AMBudnik** [comment]
sorry @jouyuy 

I should have asked you for some details first. How a user is able to add a blank column: menu, data erase, autofill, context menu? It defines a hook that can be used here.

**Comment by jouyuy** [comment]
@AMBudnik User is not explicitly able to add a blank column - it gets added automatically as soon as all cells have values.

**Comment by jouyuy** [comment]
@AMBudnik I can think of at least 3 ways to end up with more than 1 spare columns in [my case](https://github.com/handsontable/handsontable/issues/225#issuecomment-400366475) (i.e. when you have `maxRows`/`minSpareCols` set to 1 and unset `maxCols`):

1. Spam `TAB` key which adds a new cell as soon as you reach the end of a row.
2. Use autofill feature which adds a new cell as soon as you reach the end of a row.
3. Simply clear one of the existing cells.

**Comment by AMBudnik** [comment]
Thank you for sharing the details. We should remember that if a column already had a value but it has been erased manually by a user action it's value is `" "` (an empty string), so we can track it via `afterChange`.
Here is http://jsfiddle.net/fhp859x6/ what I would use to get rid of extra columns.

**Comment by jouyuy** [comment]
@AMBudnik Your example doesn't handle 1st scenario (which is spamming `TAB` key), but as I said I've already found a suitable solution. I just thought that having `maxSpareCols` would make things easier and help to keep the code clean.

**Comment by AMBudnik** [comment]
Actually, I can mark this topic as a feature request.

**Comment by AMBudnik** [comment]
This feature request is closed. It will be automatically reopened after we attach it to a milestone.
Thank you very much for share it. I hope that we'll be able to publish it soon.
