### ISSUE TITLE
Is there something like `onEdit` event? 

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#2287]
I've checked the events wiki but I might be missing something.
I would like to fire an action whenever the user double clicks in a cell to start editing it. (not on selection or after the edition takes place)

I've tried `afterOnCellMouseDown`, `afterSelection`, `afterSelectionEnd`... but none of them does exactly what I'm looking for.

Is this possible? I couldn't find any even making reference to the edition of the cell.

**Comment by zekedroid** [comment]
It's not as easy as an event since there are no afterDoubleClick events. You should look at the Custom Editors. Here's an interesting bit about using them:

    CustomEditor.prototype.open = function(){
        this.editorDiv.style.display = '';
    };

The `open()` function of the default editor gets called whenever the editor needs to be called (so on enter or double clicking). If you declare your own editor, you could use the open function to piggyback off the double click event. I've never done it, test it out and see if it works. You may have issues if you need this event to not trigger on Enter but this will at least be a good start.

**Comment by zekedroid** [comment]
Look at #2266 and follow its progress

**Comment by AMBudnik** [comment]
Thank you @zekedroid for your support and for finding related issue, so I agree to close this one.

**Comment by alvarotrigo** [comment]
Thanks, I'll keep an eye on it.

**Comment by alvarotrigo** [comment]
@zekedroid are you talking about modifying the plugin's code to add a new editor?
