### ISSUE TITLE
Issue with hiding columns that cause value from hidden column to be copied into adjacent column 

### ISSUE THREAD

**Issue by azyubin** [handsontable/handsontable#2311]
Hello,

I was wondering if any one encountered this issue with handsontable and knows how I can fix it. I am using handsontable to create an excel like grind for data entry on my web page. Also, the right most column is delete row column that holds a button for deleting a row. I also include ability in the page hide/remove certain columns but once the column is removed the value from column adjacent to the delete column is copied into the delete column

Here is a simplified fiddler that shows this issue http://jsfiddle.net/5bqwaj94/3/

**Comment by jansiegel** [comment]
Hi, @azyubin!

Your issue seems to be caused by the 'delete column' not having assigned a data source, thus "inheriting" the data from the column which was previously in that position.

The quick workaround is emptying the `TD` before modifying it's contents with a custom renderer.

See the updated demo: http://jsfiddle.net/5bqwaj94/4/ (line 6 in the javascript section)

**Comment by azyubin** [comment]
Thank you very much for the help @jansiegel. Can't believe how simple of the solution this was.

**Comment by jansiegel** [comment]
Glad I could help, @azyubin :)
