### ISSUE TITLE
Cancelling remove row/column in before hook corrupts undo stack

### ISSUE THREAD

**Issue by tmichel** [handsontable/handsontable#2325]
When I try to remove a row or a column but this action is cancelled by returning false from `beforeRemoveRow` or `beforeRemoveCol` hooks, an undo action is still pushed to the undo/redo stack. This corrupts the stack and leads to duplicated row/column when calling undo.

I created a [JSFiddle](http://jsfiddle.net/oanheya4/3/) to reproduce this.

Somehow removing a column does not trigger the bug in the above linked example, but I can reliably reproduce it in my application. I'm using the version 0.13.1. Maybe it's been fixed on master?

My guess is that the undo hook runs before the user supplied hook and this causes that the remove action is placed on the undo stack.

**Comment by AMBudnik** [comment]
Thank you for that report. It occurs at our [main demo](http://handsontable.com/) also. 

Setting `false` to `index` or/and `amount` does not trigger `undo` to stop. It only triggers it to copy first row instead of one that was 'theoretically' removed, cause our arguments look like this:

`[false, false, undefined, undefined, undefined, undefined]`

**Comment by AMBudnik** [comment]
Confirmed with 0.24.1

**Comment by AMBudnik** [comment]
related: https://github.com/handsontable/handsontable/issues/1520

**Comment by mikeb424** [comment]
Similarly, it appears that returning false in beforeRemoveRow will still trigger a cellMetaReset, which is undesirable.  Also, there is no beforeCellMetaReset to quickly remedy this.

**Comment by AMBudnik** [comment]
Thank you for your investigation @tmichel 
You're right - we should also take a look at this hook.

**Comment by AMBudnik** [comment]
The issue is still replicable in v `2.0.0.` Demo http://jsfiddle.net/9nb6f1ns/

This issue is old. It doesn't seem to work in any of previous versions of Handsontable.

**Comment by pnowak** [comment]
This issue is still replicable using v8.0.0. Here's an updated demo - https://jsfiddle.net/un5bv9o1/

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **UndoRedo grouped** issue task reported at https://github.com/handsontable/handsontable/issues/7508

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com
