### ISSUE TITLE
Printing handsontable to pdf

### ISSUE THREAD

**Issue by mukta88** [handsontable/handsontable#2342]
Hey all,
I am showing handsontable with 1000 records in a view.
When I print the page to pdf, only visible items (say 100 )get printed to pdf. ie. Items (rows and columns) hidden in both horizontal and vertical scroll doesnt appear in pdf.
What can be the reason? 
Any help is accepted.

Thanks.

**Comment by slat** [comment]
Handsontable renders only what is visible (and a little beyond a limited threshold) when "overflow: scroll" is set - virtual rendering.
You could try setting the grid to a fixed height before print then setting the height back to the old value afterwards. Although may be slow rendering all cells. 
However, the grid will not look as it does on screen, print styling will be required.

There is an example here of using html2canvas to print the grid:
https://github.com/handsontable/handsontable/issues/1871
Otherwise you could try wkhtmltopdf/wkhtmltoimage or phantomjs on the server side.

Or do something like this:
https://github.com/wmluke/slickgrid-print-plugin/blob/master/src/scripts/slickgrid-print-plugin.js

**Comment by mukta88** [comment]
Thanks for a solution. I will use this, and paste a solution here once works.

**Comment by AMBudnik** [comment]
Issue closed in lack of recent activity.
