### ISSUE TITLE
manualColumnResize should allow to resize column smaller than content

### ISSUE THREAD

**Issue by hohwille** [handsontable/handsontable#2390]
If you use manualColumnResize and have a cell lots of text, you can not make the column width smaller than the required space for that cell. This is IMHO undesired.

Demo:

http://rawgit.com/hohwille/30c3d427d987ef48b962/raw/434ef520c51d42596dc66a76a9420138933dcd68/gistfile1.html

Screenshot:

![handsontable-bug2](https://cloud.githubusercontent.com/assets/1923119/7255302/a07995e8-e848-11e4-834d-b4999576c58a.png)

**Comment by AMBudnik** [comment]
Hi @hohwille you can choose if this text length forces to widen cell or not:

according to docs:
`autoColumnSize : Boolean (default false if colWidths is set, true otherwise)
Setting to true enables the autoColumnSize plugin, which makes sure each column gets enough space to show its content.`

example [demo](https://jsfiddle.net/5yp3zogd/)

**Comment by hohwille** [comment]
Thanks for the feedback. So not a bug. I also updated the gist but due to caching it is not properly updated (yet).

However, this is just a workaround and not the solution I hoped. Setting the option autoColumnSize to false also prevents the initial adjustment of the with and even more effective the feature to auto-adjust width by double-clicking of the resizer - that is actually a very cool feature that I then loose.
