### ISSUE TITLE
Merge Cells act strange near left border.

### ISSUE THREAD

**Issue by alajmo** [handsontable/handsontable#2473]
If you try to merge row wise at the left boundary when you have no row-headers nothing changes for the merged for the merged rows, but the columns to the right of it are halfed in size.

So for instance, imagine this

| ----- | ----- |
| --- | --- |
| ----- | ----- |
| ----- | ----- |

Let's say you merge the second column row-wise, you get:

| ----- | ----- |
| --- | --- |
| ----- |  |
| ----- | ----- |

But if you try to merge them row-wise on the first column, it doesn't produce the right result.

**Comment by AMBudnik** [comment]
Please make a demo, it will be so much better to see working example, you can use [JSFiddle](https://jsfiddle.net/api/post/library/pure/)

**Comment by samiralajmovic** [comment]
Yes of course, http://jsfiddle.net/a8h0xonp/2/

Try to merge cell (row, col)
[1, 1] and [2, 1].

And now try to merge (after refreshing the jsfiddle)
[1, 0] and [2, 0].

See that different things happen, and this is because we set rowHeight, and it only happens after we merge the outer left cells, not the right.

**Comment by AMBudnik** [comment]
Ok, I guess you get this

![zrzut ekranu 2015-06-01 o 09 25 36](https://cloud.githubusercontent.com/assets/10757813/7907994/7451e12e-0840-11e5-9c46-e4ce81bf0435.png)

we will lok at this closer.

**Comment by samiralajmovic** [comment]
Yes precisely.

**Comment by samiralajmovic** [comment]
Any update?

**Comment by AMBudnik** [comment]
Confirmed with 0.24.1

**Comment by jansiegel** [comment]
Might be related to #3837.

**Comment by AMBudnik** [comment]
The issue is still replicable and doesn't occur if we enable `rowHeaders`. Tested with v0.34.0

**Comment by AMBudnik** [comment]
The issue is still replicable in v `2.0.0.`. Updated and simplified demo http://jsfiddle.net/9vd34Lmg/. This issue is old. It doesn't seem to work in any of previous versions of Handsontable.

merge cell `0,0` with `0,1`

**Comment by AMBudnik** [comment]
It remains the same in v 8.0.0 http://jsfiddle.net/AMBudnik/kn6mchwL/

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **MergeCells grouped issue** task reported at https://github.com/handsontable/handsontable/issues/7509

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Comment by AMBudnik** [comment]
Hi @alajmo 

Please check the updated demo https://jsfiddle.net/ztovg2mc/

The issue is no longer replicable.

![Zrzut ekranu 2024-07-3 o 13 36 26](https://github.com/handsontable/handsontable/assets/10757813/cdab8232-b838-4170-9d99-19a2758b474e)
