### ISSUE TITLE
Autocomplete allowInvalid: false backspace issue

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#2477]
Can be reproduced here: http://docs.handsontable.com/0.15.0-beta3/demo-autocomplete.html

---

When we hit <kbd>backspace</kbd> on `allowInvalid: true` autocomplete we get

![zrzut ekranu 2015-05-21 o 14 29 27](https://cloud.githubusercontent.com/assets/10757813/7748559/f4789a88-ffc5-11e4-88f7-2f762d8eb6e7.png)
(red cell bg and erased data - correct)

---

but when he hit <kbd>backspace</kbd> on `allowInvalid: false` autocomplete the result is

![zrzut ekranu 2015-05-21 o 14 31 55](https://cloud.githubusercontent.com/assets/10757813/7748590/3bbf76d2-ffc6-11e4-929d-1bdcb96ba6d3.png)
(red cell bg and unchanged data)

**More info:**
In second case red bg stays only until next rendering.

**Comment by Meitinger** [comment]
Actually, this bug isn't bound to a certain cell type. Have a look at the [data validation](http://docs.handsontable.com/0.20.0/demo-data-validation.html) demo:

1. enter an invalid address into a cell in the *E-Mail* column (`allowInvalid = false`)
2. press `ENTER`: the editor stays open, the value is not applied, so far so good
3. press `ESC`: the original (valid) value is restored _but_ the cell is now red

Since the above is something an average Excel user might do, it really should be fixed to avoid confusion.

**Comment by AMBudnik** [comment]
thanks for investigation @Meitinger

**Comment by AMBudnik** [comment]
Confirmed with 0.24.1

**Comment by abdulwahabplus** [comment]
Is this still exist ? 
I am using version 1.7.0

**Comment by AMBudnik** [comment]
Yes @Meitinger 
Unfortunately this issue is still present.

**Comment by swistach** [comment]
Since 0.30.0 the autocomplete cell type should work as we expected. In this simple example seems to me that autocomplete cells works properly.
But problem which was reported by @Meitinger, it's another bug and we should open new issue for this (I think it's related with [this](https://github.com/handsontable/handsontable/blob/master/src/core.js#L1001))

**Comment by AMBudnik** [comment]
Both issues (mine and @Meitinger ) do not occur in v0.31.0. I'm closing this issue.
