### ISSUE TITLE
Row headers misaligned when checkbox column used

### ISSUE THREAD

**Issue by jlsalmon** [handsontable/handsontable#2517]
Hi,

If a column containing checkboxes is added with `rowHeaders` set to `true`, the row headers are misaligned with the data rows. Example here: http://jsfiddle.net/yr2up2w5/

Removing the margins from the checkboxes via CSS makes the data rows the same height as the row headers, but there is stil 1-2px of misalignment.

Is this a bug in the way that `ht_clone_left` is generated, or is this something that I should fix via CSS?

(Possibly related to #1681.)

**Comment by AMBudnik** [comment]
Chrome seems to be OK, but I got this on FF

![zrzut ekranu 2015-06-02 o 09 04 07](https://cloud.githubusercontent.com/assets/10757813/7930186/8065e57a-0906-11e5-91d9-88574b473288.png)

This issue is a duplicate from https://github.com/handsontable/handsontable/issues/2354 so please track changes to that issue.
