### ISSUE TITLE
Scrolling problem in Firefox with smooth scrolling enabled

### ISSUE THREAD

**Issue by ciffel** [handsontable/handsontable#2520]
Hi,

Scrolling is very slow in Firefox with smooth scrolling enabled (default). I must scroll twice to see the next row. After disabling the smooth scrolling, it works fine. You can try it in [demo page] (http://docs.handsontable.com/0.15.0-beta3/demo-scrollbars.html). 

environment: Firefox 38 in both Windows7 and Ubuntu 14.04

**Comment by AMBudnik** [comment]
Thank you for support. You are right it may scroll little faster.

Video shows 3 cases: scrolling with mouse, scrollbar and keybord navigation.

![issue4](https://cloud.githubusercontent.com/assets/10757813/7955516/37882902-09d9-11e5-9d05-665a81f09cb5.gif)

**Comment by thevasya** [comment]
I also have the issue with slow mousewheel scrolling in Firefox 43 on Ubuntu with smooth scrolling enabled. It works fine in Chrome 46, or when I disable smooth scrolling in Firefox.

This only happens if `rowHeaders` option set to `true` (like in #2713), otherwise scrolling speed is normal.

I'm using Handsontable 0.19.0.

**Comment by krzysztofspilka** [comment]
Connected with #2703

**Comment by vmlf01** [comment]
In my case, I'm using a fixed column (```fixedColumnsLeft: 1```) and even with ```rowHeaders: false``` it still scroll very slowly

http://jsfiddle.net/ruropvma/2/
