### ISSUE TITLE
Add new cell type : DateTime ?

### ISSUE THREAD

**Issue by ledt** [handsontable/handsontable#2698]
How to add new cell editor plugin Datetime using datetime picker  
http://trentrichardson.com/examples/timepicker/

**Comment by AMBudnik** [comment]
All needed information for `date` cell type you can find [here](http://docs.handsontable.com/0.16.1/demo-date.html) if you would have any problems with code implementation please create a [JSFiddle](https://jsfiddle.net/api/post/library/pure/) demo and I'll try to help you.

**Comment by AMBudnik** [comment]
Actually we are planning to develop Custom renderers with a `time` cell type in Handsontable PRO but there is no actual date when this functionality will be released. 

For all those who want to keep in touch with PRO news please subscribe to http://handsontable.com/sign-up.html?utm_source=handsontable.com&utm_medium=notification&utm_campaign=button

**Comment by JPPK** [comment]
Adding datetime support turned out to be rather simple, after picking at the problem for a day.

If you take the handsontable js file (I used 0.18.0), and replace the pikaday section with Owen Mead's pikaday fork ( https://github.com/owenmead/Pikaday ), and specify a date format for the cell that includes time, you will be able to select the time. One can hardcode the new options into the getDatePickerConfig method in handsontable, which I did, since it seemed like too much work to provide actual support from the cell-config level.

**Comment by ledt** [comment]
Thank for your support.
All i have done in this attach file.
New datetime cell type work for editor, but value of editor cell time not
transmit to form...:(

2015-09-25 14:53 GMT+07:00 JPPK <notifications@github.com>:

**Comment by JPPK** [comment]
It definitely works for me. How are you using it? I'm getting the handsontable data by way of .getData(), and then accessing the cell I want for its value. So far as I know, the cells are just text, and the only exercise is to make them understand what kind of text you're allowed to put in there - anything you do write there should be easily accessible.
