### ISSUE TITLE
Undo/Redo clone deep bug

### ISSUE THREAD

**Issue by oleksandr-dakal** [handsontable/handsontable#2699]
``` javascript
Handsontable.UndoRedo.ChangeAction.prototype.undo = function(instance, undoneCallback) {
        var data = helper.deepClone(this.changes),
            emptyRowsAtTheEnd = instance.countEmptyRows(true),
            emptyColsAtTheEnd = instance.countEmptyCols(true);
       ....
    };
```

Instead of Handsontable.helper.deepClone here is used deepClone function:

``` javascript
function deepClone(obj) {
  if (typeof obj === "object") {
    return JSON.parse(JSON.stringify(obj));
  } else {
    return obj;
  }
}
```

This solution is not correct because it's strip methods from Object (JSON stringify remove functions).  
In case when column property specified as function Undo/Redo functionality not working.

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **UndoRedo grouped** issue task reported at https://github.com/handsontable/handsontable/issues/7508

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com
