### ISSUE TITLE
Can not Alter content of read-only cells with populateFromArray

### ISSUE THREAD

**Issue by mudam** [handsontable/handsontable#2701]
I need to set some cells read-only so that user can see the information but not edit. At the same time user needs to edit some other cells. I take the changes, manipulate the table on the server and return new values to the table. Using `populateFromArray` only works for cells where `readOnly=false`. Example here: http://jsfiddle.net/zxtstg3j/

It seems to me like a bug as `readOnly` suggests preventing user interaction and not programmatic change. (If you have access to the table at code level then having read only flag makes little sense anyway).

**Comment by buimatic** [comment]
Adding the following clarifications:

* Tested with version 0.14.1
* `populateFromArray` updates entire table when `readOnly!==true` i.e. can be undefined (or default)
* If `readOnly===true` then locked cells are not updated.

There is a workaround by using `editor=false` instead of `readOnly=true`. Not sure what their difference is supposed to be apart from not being able to copy data from cell and ability to easily attach some styles in the latter case.

Since this is my first message here, I'd like to thank the team for this awesome piece of work.

**Comment by AMBudnik** [comment]
Seams to work fine using 0.24.1 version:http://jsfiddle.net/cou1oxju/2/
I'm closing this issue but if you'll have any difficulties related to this topic please leave a comment.

**Comment by mudam** [comment]
The problem with the workaround is that (at least on Mac) I can hit "delete" key and the contents gets cleared.
