### ISSUE TITLE
fails to load with requirejs

### ISSUE THREAD

**Issue by peller** [handsontable/handsontable#2712]
Adding a script tag for requirejs on the [handsontable/index.html](https://github.com/handsontable/handsontable/blob/master/index.html) page causes a failure to load, e.g.

``` html
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.20/require.js"></script>
```

Because `define.amd` is defined, the top-level conditional follows the branch that loads the code with

``` javascript
define([], f);
```

I'm not sure this is valid.  requirejs responds with:

```
Uncaught Error: Mismatched anonymous define() module: function (){var define,module,exports;return (function init(modules, cache, entry) {
  (function outer (modules, cache, entry) {
    // Save the require from previous bundle to this closure if any
    var previousRequire = typeof require == "function" && require;
    var globalNS = JSON.parse('{"zeroclipboard":"ZeroClipboard","moment":"moment","pikaday":"Pikaday"}') || {};

    function newRequire(name, jumped){
...
```

**Comment by peller** [comment]
...workaround is to `delete define.amd` before loading Handsontable

**Comment by tomsjer** [comment]
Hi, i had the same problem and it seems to be a [MISMATCHED ANONYMOUS DEFINE() MODULES ...](http://requirejs.org/docs/errors.html#mismatch), in case it helps anyone here is my solution:
 - In [this line](https://github.com/handsontable/handsontable/blob/master/dist/handsontable.full.js#L18) you need to change 2 things: 
  - rewrite the define function as follows:  (note the **'handsontable'**)
```
define('handsontable',[],f);
``` 
  - Next, comment/delete the **var define, module,exports;** declaration:
```
/*var define, module,exports;*/
```
According to the [RequireJS Documentation](http://requirejs.org/docs/errors.html#mismatch):

*If you use the loader plugins or anonymous modules (modules that call define() with no string ID) but do not use the RequireJS optimizer to combine files together, this error can occur. The optimizer knows how to name anonymous modules correctly so that they can be combined with other modules in an optimized file.*
*If you use var define; at the top of your file for jshint/jslint purposes, this will cause a problem for the optimizer because it avoids parsing files that declare a define variable, since that may indicate a script that was created by a concatenation of some scripts that use a local define.*

Thanks Handsontable for this great component!

**Comment by AMBudnik** [comment]
I am not sure if we can do anything to solve this as an issue as the fix it to just change the order of the resources.
I am closing this issue.

If there's anything I am missing here please let me know.

**Comment by AMBudnik** [comment]
I am reopening the issue.

It looks like something in version 1.11.0-beta1 has made the change.
DEMO: https://jsfiddle.net/j29ykt6d/

Before the version, we were able to load Handsontable via requireJS

**Comment by AMBudnik** [comment]
There is a quick update.

It looks like the demo should be constructed like this https://jsfiddle.net/j29ykt6d/8/
and then fetch the ``require(["Handsontable"])``

I am closing the issue (again) but if you'd have any issues with the code above please let me know
