### ISSUE TITLE
After setting cell readonly, cell alignment class lost

### ISSUE THREAD

**Issue by fengwei1** [handsontable/handsontable#2897]
After initialize a sheet with setting of alignment, at last step, I set sheet readonly to true ( hot.updateSetting({readOnly: true}); ), the previous alignment classes of cells are lost. After using DOM inspector, I noticed that only htDimmed class is there for TD element, the htLeft alignment class is gone.

The work round I have done is to set sheet readonly in advance of alignment setting, so I would think the set readOnly feature caused the alignment classes lost.

**Comment by AMBudnik** [comment]
Hi @fengwei1 some of alignments are recalculated by HOT after rendering.
Could you make an example code for this issue?

**Comment by fengweijp** [comment]
Sorry for the late! Here is the jsfiddle url http://jsfiddle.net/fengweijp/w4uea19o/13/

if you un-remark the last line of hot.updateSetting({readOnly:true}), you will see the alignment settings of A1:C2 are lost.

**Comment by AMBudnik** [comment]
Hi, maybe you could use conditional formatting, [here's](http://jsfiddle.net/0jq7jmhg/) the example and [there](http://docs.handsontable.com/0.19.0/demo-conditional-formatting.html) you can read more about it.

**Comment by flobuc** [comment]
Hello,
i just found this conversation about the "updateSettings"-method and i would like to reopen this issue.
Because the problem is still there (0.20.1) and I think it is not a minor issue.
It seems that if you call "updateSetting" all settings which affect the "class"-attribute of a td are lost, e.g. the "WordWrap"-setting (which leads to class "htNoWrap") is also lost after calling "updateSettings".
I'am also tried the "init"-parameter of "updateSetting"-method, but it has no effect on this bug. 
The demo from "fengweijp" is still working and shows the bug.
So please reopen the issue and provide a fix soon.
Flo

**Comment by AMBudnik** [comment]
@flobuc can you provide a demo with newest (0.20.2) version where it can be reproducible? 
Thanks in advance!

**Comment by flobuc** [comment]
I updated the demo from "fengweijp" to the newest version.
http://jsfiddle.net/w4uea19o/14/
The bug is still there.
I think a similar problem is:
https://github.com/handsontable/handsontable/issues/3026

Flo

**Comment by AMBudnik** [comment]
Thanks for sharing @flobuc it's definitely related to https://github.com/handsontable/handsontable/issues/3026 also.

**Comment by AMBudnik** [comment]
Still present in 0.24.1

**Comment by AMBudnik** [comment]
Works fine in the latest version
Can you confirm that @flobuc ?
