### ISSUE TITLE
Handsontable header need to be locked on scrolling

### ISSUE THREAD

**Issue by aurelialeo** [handsontable/handsontable#2905]
When we scroll, the header also gets scrolled. Is there any feature to lock the header?
If not, can you bring a feature to lock the header?

**Comment by beauraines** [comment]
I was dealing with something very similar myself and I found that it had to to with the sizes and scrolling behavior of the div I was putting my HOT in.
If you're specifying heights in your CSS for the divs, make sure that your HOT has the same or smaller height as well.
And in my case, because I was picking development up after someone else, I found that there was a custom renderer that would resize the HOT based upon after it was initially rendered.
