### ISSUE TITLE
Publish handsontable to npm

### ISSUE THREAD

**Issue by pmig** [handsontable/handsontable#2906]
Hi,

It seems that you already have a NPM Account ( https://www.npmjs.com/~handsoncode ).

Is there a particular reason not to publish your releases to NPM, especially since NPM is catching up in beeing a FED package manager. See (http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging).

Thanks

**Comment by reidphilpot** [comment]
:+1:

**Comment by mamapitufo** [comment]
:+1:

**Comment by aft-luke** [comment]
:+1:

**Comment by frankbaele** [comment]
+1

**Comment by HelloYie** [comment]
+10086

**Comment by jpravetz** [comment]
Any change of getting a timeline/priority comment from the authors? +1 from me to. Thanks.

**Comment by timwis** [comment]
In the meantime, you can install via npm using:
```
$ npm install handsontable/handsontable
```
As to using it as a CommonJS module, you'll have to specify the file since there's no `main` property in `package.json`, ie. `require('handsontable/dist/handsontable')`

+1 for me by the way :P

**Comment by sandys** [comment]
@timwis - have you used this with npm ? I'm trying to use it with systemjs/jspm and I constantly get an error `Error: Module not already loaded loading "moment" from "undefined"`

I have a small testcase here https://github.com/sandys/systems-handsontable

can you share the package.json that you are using ?

**Comment by timwis** [comment]
@sandys I'm basically using it with a `<script>` tag - webpack lets you still `require` it the CommonJS way and just pull in the external/global variable. [here's](https://github.com/timwis/crud) my repo - you can see package.json and webpack.config.js for the details.

I tried using it via straight `require`, but (a) it's in ES2015 so I had to get webpack + babel to compile _just that module_, and then was erroring out on the `import`s because they're trying to import modules from the `lib/` directory, but it doesn't seem to specify anywhere that the compiler should _look_ in the `lib` directory. Eventually I just gave up (or "postponed" if I'm being optimistic) and used an external script tag.

**Comment by sandys** [comment]
@timwis thanks! that really helped .  Effectively, Handsontable is being used outside of npm.
I'm using Systemjs+jpsm to manage the front-end dependencies - I wonder if that's a good usecase for HOT, in case it ever decides to package itself.

**Comment by timwis** [comment]
@sandys FYI I [got it working](https://github.com/handsontable/handsontable/issues/2804#issuecomment-169173254) with browserify

**Comment by sandys** [comment]
Systems/jspm is working as well!

https://github.com/jspm/registry/issues/697

I still don't know how to use the plugin though...

**Comment by AMBudnik** [comment]
already marked in https://github.com/handsontable/handsontable/issues/2076

**Comment by KonishiLee** [comment]
#2906
