### ISSUE TITLE
Filling a container with a handsontable makes the scrollbar disappear

### ISSUE THREAD

**Issue by samuellapointe** [handsontable/handsontable#2924]
I am working on a project where I need the handsontable to take the width and height of its container, whatever it might be. It works very well with chrome and firefox, but for some reason on IE11 the scrollbar disappears and the mouse scroll doesn't work either.

Here's a fiddle of the issue: http://jsfiddle.net/Knuk/12dpct1b/

We're working with version 16.0 but it seems to be doing it on the latest versions as well. Is there something I'm doing wrong?

**Comment by AMBudnik** [comment]
For IE you can change `overflow: hidden;` for `overflow: scroll;` and then add `-ms-overflow-style: none;`

**Comment by samuellapointe** [comment]
Hello, thanks for your reply. Doing this does enable scroll, but the content doesn't load anymore, I'm limited to the first 15 lines displayed then it becomes blank.

**Comment by AMBudnik** [comment]
Hi, IE will never stop to amaze me. I think [this one](http://jsfiddle.net/12dpct1b/19/) is the best solution.

**Comment by samuellapointe** [comment]
This would work if I had access to the dimensions of the table before I created it. In my case, it needs to fill an existing container. I'll try to see if I can fix the issue straight into HandsOnTable today instead.

**Comment by AMBudnik** [comment]
Hi @samuellapointe do you get the solution?

**Comment by samuellapointe** [comment]
I fixed the problem in this pull request: https://github.com/handsontable/handsontable/pull/2940

**Comment by AMBudnik** [comment]
OK, thanks for sharing @samuellapointe

**Comment by AMBudnik** [comment]
Hi @samuellapointe 

As [support for the Internet Explorer browser is to be deprecated in version 8.0.0](https://github.com/handsontable/handsontable/issues/7026) we decided to close all the issues that are only replicable on that browser. All IE-related workarounds implemented into Handsontable are still a part of the code, and we do not plan to remove them.

However, this issue is also replicable on Edge
<img width="275" alt="edge" src="https://user-images.githubusercontent.com/10757813/85007205-7ddd0b00-b15b-11ea-8bcf-09f986265759.png">

as the desired result (that we can expect from Chrome) is
<img width="276" alt="chrome" src="https://user-images.githubusercontent.com/10757813/85007242-8af9fa00-b15b-11ea-802c-228713bf3c32.png">

**Comment by aninde** [comment]
This issue is no longer reproducible on the current Chromium-based LTS Edge 103.0.1264.77 (x86_64) on macOS and on Windows 10. Hence [legacy Edge is no longer supported](https://www.theverge.com/2021/3/9/22321779/microsoft-edge-legacy-spartan-browser-support-ended). I'm closing this issue. 
<img width="386" alt="Screenshot 2022-08-04 at 15 56 41" src="https://user-images.githubusercontent.com/30186818/182865879-3eea54ab-840d-4e36-b744-aa8758a5a630.png">
