### ISSUE TITLE
afterSelectionEnd hook not fired correctly on mobile

### ISSUE THREAD

**Issue by samuellapointe** [handsontable/handsontable#2942]
Hello again! I have a problem with the afterSelectionEnd (and a few related events) that don't work properly on mobile.

If I set a hook with that event to call a function, and then I click on a cell in the table, that event gets called instantly on chrome. However, on mobile, in only gets called when I click somewhere outside the table.

Here's a fiddle: http://jsfiddle.net/Knuk/am6y3d0x/4/

To reproduce:

First, click on Kia
  *  If you're on chrome desktop, "Hello" will appear in the console.
  *  If you're on mobile (android chrome), nothing will happen.

Second, click outside the table, for example on Default Handsontable Demo above it.
  *  On chrome desktop, nothing will happen, since the event has already fired before
  *  On mobile, "Hello" will appear in the console.

Is there another event I could listen to for mobile, or is it a problem with afterSelectionEnd?

**Comment by AMBudnik** [comment]
Confirmed, although we have a full mobile issue's list [here](https://github.com/handsontable/handsontable/issues?q=milestone%3A%22Mobile+devices%22+is%3Aclosed) is are closed untill the development will continue.

This issue is a note for https://github.com/handsontable/handsontable/issues/3 as a part of issue's details.
