### ISSUE TITLE
Scroll bars appearing on table when opening dropdown editor

### ISSUE THREAD

**Issue by gamask** [handsontable/handsontable#3053]
https://jsfiddle.net/t0o4b6je/

Try editing the second cell in any row. Permanent scroll bars will appear.
Commenting out the colHeaders line will make only a vertical scroll flash, then disappear.

Happens in chrome 47.0.2526.73 (64-bit).
Does not happen in firefox 42.0

**Comment by AMBudnik** [comment]
I confirm it with Firefox 42 on Window 7 (OSX not affected).
It's caused by `overflow:auto`

**Comment by cosmicdust73** [comment]
Issue also confirmed in Chrome 47 with a direct cause being setting 'overflow:auto' on the container div.  

Unfortunately, I need to set 'overflow:auto' instead of 'hidden' in order to make the dropdown cell accessible in the last few rows.  The main issue is that the cell dropdown in the last few rows is getting cut off by the horizontal scrollbar.  Ideally, the dropdown or autocomplete list would work just like the 'context menu' and display OUTSIDE of the container div.  (i.e. on top of the horizontal scrollbar)  This way it would not get cut off.  Is anyone aware of a workaround for this issue?

**Comment by AMBudnik** [comment]
Currently the scroll shows for a split of second so I guess that this issue can be closed.
Here's an updated demo: http://jsfiddle.net/wpkbq11m/
If anyone would experience something similar please leave a comment.

**Comment by theCharann1** [comment]
if the dropdown list has only few or 1 option i can't see the option at all as the scrollbar appear on the screen
In the above mentioned demo ( http://jsfiddle.net/wpkbq11m/ ), reduce the dropdown options to 1 and zoom the window browser window to 110%.

I am using a custom renderer

**Comment by AMBudnik** [comment]
Hi @theCharann1 can I ask you to create a new issue or contact us at support@handsontable? We'd like to avoid updating closed issues from nearly 9 years ago.

I tried to replicate the issue you mentioned and limited the `source` of a `dropdown` to a single record, but I couldn't replicate the issue.

Please share more details on how to replicate the issue, along with your OS/Browser and Zoom/Scaling settings.
