### ISSUE TITLE
getFirstVisibleRow() throwing null pointer after a call to Hot.clear()

### ISSUE THREAD

**Issue by tnrich** [handsontable/handsontable#3160]
Here's the code in question:
```
getFirstVisibleRow: function() {
    return this.wot.wtViewport.rowsVisibleCalculator.startRow;
  },
```

![image](https://cloud.githubusercontent.com/assets/2730609/12605851/860904ca-c47d-11e5-957b-4db481a37128.png)

**Comment by jansiegel** [comment]
@tnrich, could you prepare a demo on JSFiddle/Codepen with this problem happening?
I've tried to reproduce it, but with no luck: http://jsfiddle.net/js_ziggle/nfg1p8xu/

**Comment by tnrich** [comment]
Hey @jansiegel , thanks for looking into the issue. It is no longer causing me issues after several refactors to the handsontable workflow within my app. If it pops up again I'll be sure to document it better.

**Comment by mosross** [comment]
For anyone else who encounters this, it is still an existing error. I was able to diagnose the cause, but not the solution. In my case, using HOT v12.1.3.

Using the hook `afterRenderer` I placed a call to `hot.view.getFirstFullyVisibleRow()` and`hot.view.getLastFullyVisibleRow()`. These throw the error noted above, from the same point in the code. The issue is that during scroll, `rowsVisibleCalculator` is set to null:
https://github.com/handsontable/handsontable/blob/develop/handsontable/src/3rdparty/walkontable/src/viewport.js#L423

That call is issued here: https://github.com/handsontable/handsontable/blob/develop/handsontable/src/3rdparty/walkontable/src/table.js#L293

The same function will redefine `rowsVisibleCalculator`, but before that the `afterRenderer` hook seems to be triggered. I did not dig any deeper than that, so I'm not sure if there's a workaround or if I could use a different hook.

**Comment by AMBudnik** [comment]
Hi @mosross the `getFirstFullyVisibleRow` method is private. I recommend using `getFirstVisibleRow` from the `autoRowSize`. That will be fired for the row that is not fully visible, so you can just use `getFirstVisibleRow() - 1` to get the fully visible row index. If I'm missing something here please feel free to contact us at support@handsontable.com to discuss implementation details and project requirements.
