### ISSUE TITLE
not able to change cell background

### ISSUE THREAD

**Issue by krunalamodi** [handsontable/handsontable#3206]
Hi,

I'm using **Ng**Handsontable.
I'm getting hold of hot instance using after**Init** event callback. In after**Change** callback, I'm doing some cell computation and trying to adjust background of that particular cell. But, background does not change. However, cell computation gets reflected (for example, total in the last row gets updated)
No errors are reported on browser console.

        var afterInit = function () {
            hotInstance = this;
        }

        var onCellEdit = function (changes, source) {
            if (source === 'edit') {
                for (var i = 0 ; i < changes.length ; i++) {
                    var row = changes[i][0];
                    var propertyName = changes[i][1];
                    var oldVal = Number(changes[i][2]);
                    var newVal = Number(changes[i][3]);
                   var col = getCol(propertyName);
                    var td = hotInstance.getCell(row, col);
                    td.style.background = "yellow";
                    // custom code to update cell data
              }
        };

        $scope.adjSettings = {
            afterInit: afterInit,
            afterChange: onCellEdit
        };

I tried, td.style.background**Color** = "yellow"; as well

**Comment by krunalamodi** [comment]
update 01:

when I used after**Render** callback and did same thing, it worked. Not sure, if some default callback overwrites background color.

Hope this fix will help some poor souls in future.

        var changeCellsColor = function (color) {
                    var td = hotInstance.getCell(row, col);
                    td.style.background = color;
        }

        $scope.adjSettings = {
            afterInit: afterInit,
            afterChange: onCellEdit,
            afterRender: afterRender
        };

**Comment by jansiegel** [comment]
@krunalamodi,
Your example should work _temporarily_. What I mean by that is:
When you change the `style` property of a cell in the `afterChange` hook, it works, but only until the next rendering, as rendering redraws all the cells.
See this example: http://jsfiddle.net/js_ziggle/93tcas2z/1/

You can, however, make use of the cell meta mechanism: http://jsfiddle.net/js_ziggle/93tcas2z/2/
It this case, you apply a cell _meta_ instead of a `style` property. And because cell meta is not lost in the rendering process, the background stays with the cell.
Note: as you can see, I added a `this.render();` line to the hook, for the meta changes to be visible.

Adding cell manipulation to the `afterRender` hook works, but it might get a little computation heavy, as this hook is triggered way more than `afterChange`.

Hope this helps!
