### ISSUE TITLE
Context Menu items as a function

### ISSUE THREAD

**Issue by bdr99** [handsontable/handsontable#3226]
I am building an application in which I want the context menu items to vary depending on some conditions. But it doesn't look like I can set the context menu items to a function which returns the items. In other words:

This works:
```javascript
contextMenu: {
  items: {
    "row_below": {}
  }
}
```
But this does not (gives the error `Uncaught TypeError: Cannot read property 'name' of undefined`)
```javascript
contextMenu: {
  items: function(){
    return {
      "row_below": {}
    };
  }
}
```
Is this expected behavior? Is there a way to have the context menu items dynamic?

**Comment by AMBudnik** [comment]
Hi @bdr99, 
updating context menu which will be a must while depending on a condition is currently unavailable, issue: https://github.com/handsontable/handsontable/issues/3191
It is planned to be fixed with newest release.

Here's an example how to add options with a function http://jsfiddle.net/ae6bLo9p/
Full list of options can be found at: https://docs.handsontable.com/0.22.0/demo-context-menu.html
