### ISSUE TITLE
Editing a numeric cell by pressing enter replaces decimal separator

### ISSUE THREAD

**Issue by Sune1337** [handsontable/handsontable#3261]
When you press enter to edit a numeric cell using a non-english locale replaces the local decimal-separator with a period (.)
Double-clicking the cell to edit does not produce the same behaviour.

See https://jsfiddle.net/aqfhr1nf/4/ for an example.

**Comment by AMBudnik** [comment]
related to https://github.com/handsontable/handsontable/issues/2166

**Comment by SuperMario77** [comment]
I have the same problem with language 'de' and copy/paste numeric values (version 0.23.0). There is also a stackoverflow thread for this:
http://stackoverflow.com/questions/35960723/handsontable-i-found-a-bug-when-copying-pasting-a-german-numeric-value

The proposed solution is a fix in the numeral.js library (which is no longer maintained). This fix solves the issue #3285, #2166 and also this issue here #3261. But I don't know if it breaks something else, because I don't know the handsontable/numeral.js library very well.

In handsontable.full.js replace on line 24646 (this is code of embedded numeral.js lib):

```
if (languages[currentLanguage].delimiters.decimal !== '.') {
  string = string.replace(/\./g, '').replace(languages[currentLanguage].delimiters.decimal, '.');
}
```
With this:

```
if (languages[currentLanguage].delimiters.decimal !== '.') {
  string = string.replace(languages[currentLanguage].delimiters.decimal, '.');
}
```

So, simply remove the **.replace(/\./g, '')**

Could you please verify this fix? You will make a lot of german developers very happy who use your incredible handsontable library to show decimal values (e.g. prices) in their grids.

**Comment by AMBudnik** [comment]
Thanks for sharing additional information @SuperMario77

**Comment by AMBudnik** [comment]
Still reproducible in 0.26.0 (switched to Numbro), demo: http://jsfiddle.net/ww7bcdg1/

**Comment by AMBudnik** [comment]
Issue no longer occur: http://jsfiddle.net/z25d4ydm/
