### ISSUE TITLE
Manual column moving + context menu column removal problem.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#3281]
*[ Continued from @naushadkm in #1823 ]*

When using the Context Menu's `Remove Column` option after any column order modifications were made (with the `manualColumnMove` feature), wrong column is being removed.

----------
#### Steps to reproduce:
* Go to http://jsfiddle.net/tomLhdcr/,
* Move the `A` column after column `B`,
* Remove the `B` column using the context menu.

**Result**: First column gets removed.

**Comment by krzysztofspilka** [comment]
@jansiegel please notify me when it's fixed

**Comment by naushadkm** [comment]
Looks like there are major changes done in the v0.24.1 with respect to the column position handling functionalities. i.e: I'm not able to see the "instance.manualColumnPositions".
Can you please provide any documentation available for the same. @jansiegel @AMBudnik

**Comment by AMBudnik** [comment]
Hi @naushadkm It was moved to: https://docs.handsontable.com/0.24.1/ManualColumnMove.html#columnPositions
Please take a minute to check our release note: https://github.com/handsontable/handsontable/releases/tag/0.24.0

**Comment by naushadkm** [comment]
Thank you so much for your reply. @AMBudnik

**Comment by Boggimedes** [comment]
I saw that this was fixed, which is AWESOME, but I is there any way to implement it with an object array, or with columns specified?

**Comment by AMBudnik** [comment]
Hi @Boggimedes If I understand correctly it should work with mentioned above. Can you share a demo?

**Comment by Boggimedes** [comment]
Unfortunately the information I'm populating is confidential company info so I'd have to make some dummy data, but that's not too difficult.  In the meantime I'll see if I can explain it better.

So the default context menu "remove column" is disabled if your data to populate the hot is an array of objects (rather than just a flat array).  It is also disabled if you specify a "columns" array referencing the data and column titles and such.  Unfortunately both of these are absolutely required for what I am trying to accomplish.  I attempted to do manual column removal by splicing elements out of the column array with a custom context menu function, but ran into issues with the manual move column not aligning.  I would remove the correct column, however the manual move array wouldn't adjust accordingly so many columns would change their position.

since the default "remove column" is disabled I assume I'm going to have to use the custom functions in the plugin, but I can't seem to get them to work.  I'm sure I'm doing something wrong, but I can't find any examples to work off of.

**Comment by Boggimedes** [comment]
http://54.213.163.145/#/pricing/spiff

so here is what I am working on.  I have the code splice out the column when remove column is selected.  It works fine, until you start moving a lot of columns around. 

So for example if you arrange the columns Part Number, Description, Weight, Map, etc...
Then remove the "description" column".  It should be Part Number, Weight Map, etc
But instead it is Part Number, On Spiff Sheet, 3D, MAP

I can think of some overly complicated ways of addressing this (reordering the column data, or manually changing the colummove property), but those seem extremely cumbersome and I feel like there has to be something I'm missing or mis-using.

**Comment by AMBudnik** [comment]
Thanks for sharing your website and details @Boggimedes but without having an access to the source code it's hard to say anything.

If you'll have a moment to create a demo using for example JSFiddle/JSBin or CodePen I'd be grateful.
