### ISSUE TITLE
Checkbox in col headers doesn't persist state after sorting

### ISSUE THREAD

**Issue by xfight0** [handsontable/handsontable#3414]
Dear developers, I found checkbox in col headers doesn't persist state after sorting.
I checked these checkbox in col headers, but after sorting all the checkboxes are unchecked.

In addition, I change `checked` attribute by js code, but the checkbox in col header doesn't refresh.

[demo](http://jsfiddle.net/xfight9/q4tjyw9z/)

**Comment by AMBudnik** [comment]
Thanks for sharing @xfight0

**Comment by xfight0** [comment]
Hello @AMBudnik, about the issue, I test ipad in chrome.
I found a bug: can't set check to checkboxes in col headers in any case.

**Comment by AMBudnik** [comment]
When it comes to tablets and mobile phones currently Handsontable doesn't support them fully.

**Comment by jansiegel** [comment]
Hi, @xfight0!

Checkboxes clear themselves because every time you sort a column, the table re-renders. I think the best way around it would be checking the "current" checkbox state before rendering a new one, and applying it to the new checkbox.

I've modified your example slightly, please take a look: http://jsfiddle.net/js_ziggle/q4tjyw9z/5/

Side note: you're assigning `id`s to the checkboxes, which is not the best solution, as they render on 2 layers: the "top" overlay and the "master" overlay. This way the `id`s are duplicated, which can cause all sorts of issues :)

**Comment by xfight0** [comment]
@jansiegel Thank you very much 😃
