### ISSUE TITLE
getData doesn't retrieve hidden columns data

### ISSUE THREAD

**Issue by ignaciomdominguez** [handsontable/handsontable#3418]
Hi,
I'm trying to get hidden data using getData method
I can't get data of hidden columns.

Below you have an example
https://jsfiddle.net/ignaciomdominguez/0vc15ot5/

I appreciate any help or guidance on this.
thanks in advance.

**Comment by AMBudnik** [comment]
Hi @ignaciomdominguez 
Unfortunately your demo link is broken.
Please take a minute to read this article: https://handsontable.com/blog/articles/3-ways-to-hide-rows-in-handsontable
There are 3 ways to hide your data and two of them won't allow you to see them via `getData()`

**Comment by ignaciomdominguez** [comment]
Hi,
Thanks for your answer.

I read the article, but none of the options is what I'm looking for.
I want to store a certain amount of information related to a particular row. For example, the ID of a record.

below you have link of example:
https://jsfiddle.net/ignaciomdominguez/0vc15ot5/

**Comment by AMBudnik** [comment]
So the columns are not hidden they are not included via `columns` option. I guess you're looking for [`getSourceData()`](https://docs.handsontable.com/pro/1.3.3/Core.html#getSourceData)

**Comment by ignaciomdominguez** [comment]
That's just what I was looking for.
I didn't know that the data you get with getDataSource were modified once you update data on grid.
Thank you very much!

**Comment by efeker** [comment]
I think it is still a problem. In case of my situation, I let user select multiple rows to delete (Each row has a checkbox column). Then, they click on a button and delete records. Since "rowIndex" is regenerated every time a row is deleted, I have to rely on "getData" method to get all records, then find "rowIndex" value for each row that user wants to delete. In my case, I have a unique identifier (id) for each row and I rely on that relationship. Due to my requirement, I cannot display "id" column in the grid, thus I created it as a hidden column. However, "getData" method does not return hidden columns which is a big issue for me at the moment.

**Comment by AMBudnik** [comment]
Hi @efeker 

Can you share a demo with your example? It's hard for me to imagine the process.
