### ISSUE TITLE
DropDown is hidden under the other elements

### ISSUE THREAD

**Issue by edifecscda** [handsontable/handsontable#3435]
Hello guys,

I found that in newest version of your awesome product there is a problem with dropdown. In the earlier versions - like 0.20 everything worked perfectly - dropdown appeared over all other elements on the page, but beginning from the 0.21 - it is hidden under other elements. You can review this effect even at your web site here: http://docs.handsontable.com/0.20.3/demo-dropdown.html  - this is the working version. But if you select later release you will see what I'm talking about. 

Thanks,
Andrew

**Comment by AMBudnik** [comment]
Hi @edifecscda 
Thanks for sharing.

We are working on a new CSS structure for Handsontable and like written here https://github.com/handsontable/handsontable/issues/2483 we planning to refactor editors in Q3/Q4 this year.

I will leave this issue as a suggestion for new version of a dropdown.

**Comment by ntunney** [comment]
I have encountered this problem as well.  I tried a few earlier versions (0.19.0, 0.20.0) to see if the problem is a new one, but it seems to exist in prior versions also.  I will work on a workaround, but if anyone figures it out first, please let me know since it looks like a fix to this well be deferred for at least 6 months as per the comment above.  In my case trying to use use z-index to float above all other elements has no effect, but I have not figured out why yet.

**Comment by vergel-mercado** [comment]
I also encountered this issue. I have my fix by adding this css code at the top of my file.
.autocompleteEditor {
    position:fixed !important;
}  

However, when the body gets scroll down, the dropdown is moved too. I hope they will fix this issue as soon as possible. Thanks

**Comment by ntunney** [comment]
For production I ended up using a select editor instead of the dropdown or autocomplete.  It isn't as pretty, but it works as expected for my implementation:

`data: "myColumnDataKey",
title: "My Column",
editor: "select",
selectOptions: ["Item 1", "Item 2"]`

**Comment by vergel-mercado** [comment]
@ntunney what version you use for this editor select? I tried to use that editor but it doesn't shows the list.

**Comment by ntunney** [comment]
I'm on 0.24.3 right now, but it was available prior.  I think the official recommendation from HOT is to use dropdown or autocomplete, but until I can get the CSS/JS stable I'll be stuck with "select".

**Comment by xfliu138** [comment]
Hello everyone, what time the new version released? At present the latest version 0.28.0 still exist the problems, The iframe in the HTML will keep out dropdown can

**Comment by AMBudnik** [comment]
Hi @xfliu138 
unfortunately there's no update on this issue yet.

**Comment by xfliu138** [comment]
Hi @AMBudnik how to solve the problem of dropdown hidden in iframe?
If type is  'select' this function is ok.
I look at the words Q3/Q4 this year

**Comment by AMBudnik** [comment]
Hi @xfliu138 
Unfortunately we did not started the editor refactoring yet.  This issue is one of the most requested and that's why we surely will get back to it as soon as possible. However I cannot give you any precise date of release.

**Comment by jayasimha-c** [comment]
We are using pro version on handsontable. This issue we too facing.
Hope it  will be resolved soon.

**Comment by wszymanski** [comment]
Described problem wasn't connected with Handsontable. Documentation page applied too hight `z-index` value for some content (`pre` tags) on branch `21.0`. Please take a look at latest one version of documentation page: http://docs.handsontable.com/0.31.0/demo-dropdown.html. Problem doesn't occur more since `0.28.3`.

**Comment by MuyBien** [comment]
Hi!
I had the same problem and updating to the 0.31 doesn't resolve the problem. As you can see in this JSFiddle: https://jsfiddle.net/azd0gruv/6/

But using the select type instead of dropdown resolve it...

**Comment by ChuckByram** [comment]
It seems like the issue has something to do with width management. In the JSFiddle above, if the the overflow-y CSS is commented out (as in [https://jsfiddle.net/azd0gruv/7/](https://jsfiddle.net/azd0gruv/7/)), it works.

For my project, I was specifying ```preventOverflow: "horizontal"``` as a table option and having the same bad result. I removed that option and viola! It works.

**Comment by AMBudnik** [comment]
@ChuckByram 
thank you for your opinion. I think that the issue is till present as we do not have the dropdown visible all the time when it's needed but the original issue description doesn't completely describe the situation. We should compose a new issue

**Comment by MuyBien** [comment]
@ChuckByram Yes completely! The problem is that I have to specify a max width for the parent element

**Comment by pflaumingo** [comment]
Have there been any updates to this or another issue filed? I noticed the behaviour from the JSFiddle provided by @ChuckByram is a little off because the dropdown works initially, but when clicking off and then reopening the dropdown it is only partially showing. Opening another cell and returning to the dropdown restores it to the correct behaviour.

Additionally, are there any working examples of how to achieve this when there is scrolling along the x-axis? If I add any overflow, as suggested by the [docs](http://docs.handsontable.com/0.18.0/demo-scrollbars.html) it doesn't behave as desired in that the dropdown is cutoff.

**Comment by AMBudnik** [comment]
Hi @pflaumingo 
Can I ask you to open a new topic? It looks like you know how to replicate the worst scenario which is exactly what we need to discover what is happening there. If you could add a demo or a video it would be great.
