### ISSUE TITLE
Auto column size breaks when hiding columns with custom renderer

### ISSUE THREAD

**Issue by lawrence-laz** [handsontable/handsontable#3455]
###### Reproduce:
- http://jsfiddle.net/aj7m9rvj/1/
- Add some text to "B1" cell. 
###### Expected result:
- "B1" cell expands to fit entered text.
###### Current result:
- "C1" cell expands instead.
###### Note:
- It seems as if hiding the first column doesn't affect columns' indexes. As a result "B1" cell is considered to be a second column even though it is now first.

**Comment by AMBudnik** [comment]
Thanks for sharing @lzsks 
Confirmed. It's an interesting issue.

**Comment by AMBudnik** [comment]
Still present in 0.27.0, demo: http://jsfiddle.net/4or4Ldfg/

**Comment by lzsks** [comment]
May I ask why the issue was closed if bug is still present? Is this part of the process?

**Comment by AMBudnik** [comment]
@lzsks 
My bad, I picked the 'close and comment'. Thanks for noticing.

**Comment by aninde** [comment]
Hi @lawrence-laz 

There have been many changes since you reported that problem. Now, with the correct use of Handsontable, the bug no longer exists. 

![Screenshot 2019-10-03 at 16 16 57](https://user-images.githubusercontent.com/30186818/66135137-c1a5d980-e5f9-11e9-88bf-6d2a4f5ecc27.png)

Hiding columns using your own custom renderers are not recommenced at this time. We introduced plugin [hiddenColumns](https://handsontable.com/docs/7.1.1/HiddenColumns.html). 

The hidden column doesn’t affect the visual index of the table, because a hidden column in really it is still there. We implemented Excel-like behavior. Hidden column have width of 0,1 px. 

**Demo**
v. `7.1.1` fixed http://jsfiddle.net/aninde/6u8hb34z/
v. `8.0.0-rc1` fixed http://jsfiddle.net/aninde/0cfpxLgq/
