### ISSUE TITLE
Switch to Numbro over Numeral

### ISSUE THREAD

**Issue by karellm** [handsontable/handsontable#3487]
Numeral.js hasn't been maintained in years. Is there a reason you still rely on it?

Numeral is extremely limited too. You can't optionally display decimals if present for instance (numbro would do `0,0[.]00`. You are stuck with a fixed number of decimals (`0,0.[00000]` with numbro)...

The API should port quite easily too.

**Comment by rkunnamp** [comment]
A better alternative is to use numberformat.js from google closure library.
Both numbro and numeral.js  has some serious limitation when it comes to internationalisation. for eg numbro does not support Indian style of number formatting. Currency formatting in numbro.js is buggy for some currencies. Another drawback is that numbro does not support 'excel' like number formats.

But backward compatibility will be a problem if numberformat.js from  closure library is used. Just noting down the thoughts, if it helps someone.

**Comment by AMBudnik** [comment]
Thank you both @karellm  and @rkunnamp for your investigation.
I have to say that we were thinking about switching to something else a while ago but it was always something else to do first. 
I hope your hints will help our devs to pick the best solution.

**Comment by krzysztofspilka** [comment]
@karellm @rkunnamp we are working on it right now. Unfortunately some of our custom changes to Numeral are not fixed in Numbro so @budnix decided to make 2 pull requests to Numbro. Hopefully they will be released within the next version.

https://github.com/foretagsplatsen/numbro/pull/182
https://github.com/foretagsplatsen/numbro/pull/183

**Comment by karellm** [comment]
Thanks for the update, looking forward for the release!

**Comment by BenjaminVanRyseghem** [comment]
Hi guys :smile:

I am the main numbro maintainer, and will be happy to discuss with you what you need numbro to address.

@krzysztofspilka what "custom changes" are you talking about?

**Comment by krzysztofspilka** [comment]
@BenjaminVanRyseghem Some of 47 issues you have now opened in Numbro were already fixed in our implementation of numeraljs (aka "custom changes"). Now, as we already switched, we can make PRs to Numbro including those previous fixes (still, we can't wait for the Numbro's release as we have our own schedule so we make PR + workaround in Handsontable at the same time. Then, when the new version of Numbro is released we remove workaround and update our Numbro dependency).

All in all, I'm more than happy that you decided to make a fork and maintain this useful library. I guess that was the reason we finally decide to use Numbro over Numeral. Keep up the good work!

**Comment by BenjaminVanRyseghem** [comment]
I will be happy to review your PRs :smile:

I have to sell to my boss the time I spend on numbro, so having people relying on it helps a lot for that :smile:

Hopefully the release process is quite simple, so if you really need one, it's usually doable :smile:
