### ISSUE TITLE
Custom renderer is being passed the wrong td element upon horizontal scroll

### ISSUE THREAD

**Issue by jprince** [handsontable/handsontable#3512]
I'm using a custom renderer function so that I can compile a custom AngularJS directive which renders HTML within the cells of my table. On initial load, the data is rendered correctly. However, when I scroll horizontally, the renderer re-runs, and when the visible portion of the table is exited, the `td` element that gets passed to the renderer is no longer for the correct cell (it's for the correct row, but not for the correct column). This manifests itself by rendering data in the wrong cells (typically 5-6 cells to left of the correct one). Based on my investigation, this is because the Handsontable internals are accounting for the columnOffset when fetching the `td` element and therefore are not returning the `td` that corresponds to the `columnIndex` of the given cell. 

Here is a link to a fiddle reproducing this issue - https://jsfiddle.net/jprince/6hfdu2j0/
You can clearly see that scrolling right will cause the names (Ron Swanson and Tom Haverford) to be rendered in columns other than 'Name' (this is true of all the columns, but it's easiest to discern for name). 

![image](https://cloud.githubusercontent.com/assets/3384090/15338811/82fd82ae-1c4f-11e6-93ec-43aa02b344c0.png)

If you open a console, you'll also see that I'm logging the name of the column and the `td` that the renderer is being passed. Upon scrolling all the way to the right the `td`'s will no longer correspond to its correct column:

![image](https://cloud.githubusercontent.com/assets/3384090/15338851/ad5e3070-1c4f-11e6-97aa-50d6b75e6e9a.png)

What's interesting is that if I set the `fixedColumnsLeft` setting (commented out in my fiddle), the renderer is no longer called on scroll, which essentially solves my problem. Is that because the column freezing disables virtual scrolling?

Nonetheless, that's not an acceptable workaround for me. Is there something wrong with my configuration? Or my use of the renderer? I'm shocked to have had such little luck finding an issue where someone else has encountered this problem.

**Comment by AMBudnik** [comment]
Indeed the data is 'jumping' between columns.
When it comes to custom renderers it will be difficult to find similar case as the word says it's 'custom' and there are not many cases of custom renders in our docs. Did you tried stackoverflow?

**Comment by jprince** [comment]
I hardly consider this question answered - the nature of what is happening in my custom renderer hardly seems consequential. If you look at my screenshot or the console in my fiddle you'll see that the `td` element being passed into the renderer, by Handsontbale, is incorrect.

**Comment by AMBudnik** [comment]
I think we can leave this issue opened for other team member to look at.

**Comment by jprince** [comment]
Thanks - here's an updated fiddle with a simplified renderer - no Angular compilation. Simply rendering DOM elements: https://jsfiddle.net/jprince/6hfdu2j0/9/

**Comment by budnix** [comment]
Hi @jprince, 

Looking at your demo at https://jsfiddle.net/jprince/6hfdu2j0/9/ I found that your custom renderer was not implemented completely. If you choosing a custom renderer you are responsible for overwriting cell content for every cell (every `TD` element). In your demo in some situations you don't change cell values to newer version (passed as 6th argument) you simply omit `.innerHTML` which causes "jumping" values effect.

I've updated your demo at https://jsfiddle.net/6hfdu2j0/11/.

**Comment by jprince** [comment]
Thanks for the help

**Comment by ihabo01** [comment]
This is a very interesting thread as it shows a use case where performance of the renderer can be significantly enhanced. 

We use 'expensive' renderers. That means once we have calculated a cell's value, we don't want to recalculate it as long as it is shown on the screen, otherwise the cells flicker.

The idea then is very simple, as long as the cell is on the screen (TD is not empty), we want to reuse the value.

But since the value of the TD passed is incorrect, that is impossible.

Even, if we do instance.getCell(row, col) to get the real TD, the result is again wrong.

Do you have a solution for that problem?

**Comment by AMBudnik** [comment]
Hi @ihabo01 

Can you share a demo where this issue can be replicable? I am not sure if I understand it correctly.

**Comment by ihabo01** [comment]
Hi @AMBudnik,

To give you more context, we have complex renderers for cell values, most of them are angular directives that fetch and display data in merged cells: for instance charts and we need to use virtual scrolling (otherwise both starting time and memory footprint become too big for a practical use).

I have added a timeout of 300ms that mimics the behavior that we currently have in the following fiddle: https://jsfiddle.net/1ga5gypn/

When you scroll down, even slowly, you will see that the flags cells are flickering.

From our understanding, Handsontable only reuse the td DOM element, leaving the developer the responsibility to remove child elements and to recreate them when needed.
In our case, it has a dramatical consequences has we need to recreate angular directives everytime that the cell is re rendered. We thought it could have been easier is the DOM elements would have been moved from one cell to another but would not solve events bindings problems (with angular scoping in our case).

Put in other words, and if I reformulate my previous message, are we using Handsontable improperly or is it just a case that is not handled as of today? In such cases, is there a way to handle this today or do you have plans to support this behavior in the future?
