### ISSUE TITLE
Undo/redo is working unstable with minSpareRows

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#3537]
When `minSpareRows` is passed in the configuration, then undo/redo feature works unstable towards the values being removed selectively.

**Steps to reproduce the problem:**
1. Go to http://jsfiddle.net/b4hreush/
2. Delete "Opel" and "BMW" from the first column ("Car"). Do it selectively, one by one.
3. Now press twice <kbd>CTRL</kbd>+A
4. The result: "Opel" is not being restored.

Screencast: https://gyazo.com/d58481504a4df67159d564e8537f9b82

:information_source:

> Handsontable - 0.24.3
> Windows 8.1
> Chrome 50

**Comment by toroc** [comment]
Any update on this bug? I'm seeing this on HOT 0.31.2.

**Comment by AMBudnik** [comment]
Hi @toroc 

Thank you for confirming. I got the same result using Handsontable 0.33.0 (latest).

We are planning to change the way Handsontable adds spare rows. Currently the project is held, however, I'll send you a message as soon as this will change.

ps. in the step 3, it's <kbd>Z</kbd> instead of <kbd>A</kbd> key.

**Comment by AMBudnik** [comment]
Works fine in version 0.35.0/PRO 1.15.0. Updated demo http://jsfiddle.net/cvpddcod/

![gif](https://user-images.githubusercontent.com/10757813/35222455-449d69c0-ff7e-11e7-8640-abe8d1fb884b.gif)
