### ISSUE TITLE
Keyboard horizontal scrolling breaks after editing particular dropdown cell

### ISSUE THREAD

**Issue by lex4ndr** [handsontable/handsontable#3572]
![bug](https://cloud.githubusercontent.com/assets/4733755/15966789/57bbb58e-2f2d-11e6-99ee-e9b343e6f2a4.gif)

We use the last version of handsontable.
There is no errors in devtools.
Bug noticed just now, I do not know when it appeared in fact.

Someone had a similar problem? I do not know where to dig.

I will be grateful for any help!

**Comment by AMBudnik** [comment]
Hi @devxplorer 
Can you prepare a demo where we'll be able to test the code?
Your vid sample is running so fast I'm not able to create a similar case

**Comment by devxplorer** [comment]
ill try

**Comment by devxplorer** [comment]
I probably can not do a demo, because of ajax calls and some other stuff. Not sure hot to make it in jsfiddle.

I found that problem disappears when commenting out setDataAtRowProp which changed whole row data in ajax callback. Looks something like this:

    afterChange: function (changes, source) {
        // some stuff
        $.ajax({
            // some settings
            success: function(data) {
                var сhanged_rows = [];
                 for (var row in data) {
                     for (var prop in data[row]) {
                         var tArr = [];
                          tArr.push(parseInt(row));
                          tArr.push(prop);
                          tArr.push(data[row][prop]);
                          сhanged_rows.push(tArr);
                     }
                 }
                 hot.setDataAtRowProp(сhanged_rows, 'successCallback');
             }
        });
    },

also revert to the 0.20.3 version removes a bug without commenting setDataAtRowProp.

I understand that you probably need more info, but its everything i can give now.

and sorry for my english :)

**Comment by AMBudnik** [comment]
Thank you very much @devxplorer for the effort it won't tell my much but I'll mark your issue as an improvement suggestion.

**Comment by AMBudnik** [comment]
Hi @devxplorer 
Did you investigated this issue further?

**Comment by devxplorer** [comment]
Hi! No, i just left the 0.20.3 version.

**Comment by AMBudnik** [comment]
Oh I see, thanks for a prompt reply @devxplorer
