### ISSUE TITLE
Scrolling is not working for column and row moving

### ISSUE THREAD

**Issue by PaulZadorozhniy** [handsontable/handsontable#3579]
Our users noticed and asked to solve the problem with moving columns/rows more than visible part of the table. So the users have to move several times and scroll manually to make needed order. I didn't find the way how to do it using existing handsontable configuration.

![1465986900966](https://cloud.githubusercontent.com/assets/2473683/16077222/416a84fa-3300-11e6-9796-4625acf37bca.jpg)
![1465986970893](https://cloud.githubusercontent.com/assets/2473683/16077232/4a9d3cf2-3300-11e6-884c-daf713997991.jpg)

to reproduse this issue, please go to the demo - [JsFiddle example](http://jsfiddle.net/013j98Lb/2/)

**Comment by AMBudnik** [comment]
You're right, the cols/rows don't scroll the table. When it comes to rows you can use a mouse wheel but it doesn't do any favors for columns.

**Comment by AMBudnik** [comment]
Hi again @PaulZadorozhniy 
I just got a hint from one of our devs about this case. It's not a solution - rather than workaround but it will definitely help you users until this bug gets fixed. 

You can scroll the table horizontally if you place the cursor on the column header and scroll right < - > left with <kbd>shift</kbd> key pressed.

**Comment by swistach** [comment]
Hi @PaulZadorozhniy 
we fixed problem with scrolling during columns moving. Please take a look at latest release (0.28.4)

**Comment by PaulZadorozhniy** [comment]
Hi @swistach. Thanks, will take a look.
