### ISSUE TITLE
Drag-down value from merged cell

### ISSUE THREAD

**Issue by karl-kallavus** [handsontable/handsontable#3612]
I'm trying to drag-down to repeat the values from the merged cell. 
![screen shot 2016-06-28 at 14 03 13](https://cloud.githubusercontent.com/assets/232199/16413302/df29186c-3d39-11e6-93e6-5a03a097619e.png)

And I get this:
![screen shot 2016-06-28 at 14 03 22](https://cloud.githubusercontent.com/assets/232199/16413315/ec0c71d2-3d39-11e6-9d8f-90795f99d254.png)

But I don't expect values as `B3 C3 D3` etc. I expect `B2` in all cells and something like this:
![screen shot 2016-06-28 at 14 02 56](https://cloud.githubusercontent.com/assets/232199/16413348/16d17764-3d3a-11e6-8e21-9952156d434d.png)

demo: http://jsfiddle.net/3oLnzeLk/

**Comment by AMBudnik** [comment]
That's right @karl-kallavus I get the same exact results. We get those data cause the actual cells inside the B2 area are 2 rows with 3 columns

![bez nazwy](https://cloud.githubusercontent.com/assets/10757813/16414557/981362f8-3d38-11e6-826b-a373443189de.png)

that's why when draging the merged B2 cell you get the same result like after the selection of cells in the blue background.

In the other hand user don't need to know the structure of Handsontable and he will definitely wants to get `B2` as a result (just like you wrote).

**Comment by karl-kallavus** [comment]
@AMBudnik Do you have any ideas how can I implement correct behavior now?

**Comment by AMBudnik** [comment]
It's hard to find a quick workaround, but I guess you could try to use `afterAutofillApplyValues` hook to track changes made by the autofill and by tracking its arguments `startArea`, `entireArea` use `setDataAtCell` at needed cells

**Comment by AMBudnik** [comment]
We're closing all improvement suggestions topics and uploading them to our [wiki section](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions). Issue will be reopened with the first update.
All comments, investigation results or suggestions are welcome.

**Comment by AMBudnik** [comment]
I'm moving this idea to Github Discussions. Please free to continue the conversation there. Thank you.
