### ISSUE TITLE
Allow to declare unformatted numbers

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#3645]
Currently we are not allowed to type numbers in different formats and dynamically switch between them.
This option can be added as a `false` value to the `format` settings.

**Comment by budnix** [comment]
Currently formatting is applied even when `format` is disabled (https://github.com/handsontable/handsontable/blob/master/src/renderers/numericRenderer.js#L25).

**Comment by AMBudnik** [comment]
I'm moving all the improvement suggestions to our [wiki section](https://github.com/handsontable/handsontable/wiki/Improvement-suggestions). Please feel free to leave any additional comments and reflections.

Thanks in advance!

**Comment by eshivakumar878** [comment]
is this issue fixed or still open? i have similar requirement just need to validation any invalid number in the cell value

**Comment by AMBudnik** [comment]
@eshivakumar878 it is not an issue. We have never supported this type of formatting. If you would like to present data that is not formatted currently you need to use 'text' cell type.

**Comment by eshivakumar878** [comment]
we have some German number formats like 1234,45 (equal US format is 1234.45).Here i don't want to do any formating and we don't want use text cell type also because if we get letters in amount fields then it's invalid number format.we want to do a number validation.I can achieve this by doing server-side validations but we don't want wait user to come back with invalid numbers error.

**Comment by AMBudnik** [comment]
Please check the last answer at our forum https://forum.handsontable.com/t/disable-numeric-cell-formatting/1226/3 @eshivakumar878

**Comment by AMBudnik** [comment]
I'm moving this idea to Github Discussions. Please free to continue the conversation there. Thank you.
