### ISSUE TITLE
columnSummary isn't recalculated when filters are applied

### ISSUE THREAD

**Issue by laggingreflex** [handsontable/handsontable#3658]
http://jsfiddle.net/ya2yveda

Bottom row is the sum:

![normal](https://cloud.githubusercontent.com/assets/2523987/16894880/85efaee4-4b82-11e6-818b-1bdfde363836.png)

Filter applied to keep only the top row, the bottom row is still showing the same sum as before

![filtered](https://cloud.githubusercontent.com/assets/2523987/16894886/9f867c0c-4b82-11e6-99b2-d4155678ca8c.png)

**Comment by AMBudnik** [comment]
Thanks for sharing @laggingreflex 
We already have this issue at our internal ticketing system (#77)

**Comment by laggingreflex** [comment]
Is that link correct? It links to an old PR regarding getSelected method

**Comment by AMBudnik** [comment]
Hey @laggingreflex 
I've removed the link. The # 77 stands for an issue in our internal ticketing system (on Gitlab). 

When the issue will be taken on Gitlab it will also be marked here as our users don't have an access to our Gitlab account.

**Comment by AMBudnik** [comment]
Still replicable in v0.30.1. We still have the same old data after filtering.

**Comment by wojciechczerniak** [comment]
Replicable in `v7` and `v8.0.0-rc`: https://jsfiddle.net/poyd1fc8/

But I'm not sure it's a bug. ColumnSummary is using `sourceData` by design:

https://github.com/handsontable/handsontable/blob/98878a6bb6edbed065b7961bc97d4b799e908503/src/plugins/columnSummary/columnSummary.js#L325

You can have summary visible and work with filtered / collapsed rows. If we're going to consider this issue, this should be added as a configuration option.
