### ISSUE TITLE
add class to custom header TH

### ISSUE THREAD

**Issue by varun-dev** [handsontable/handsontable#3693]
Hi,

Can you recommend a nice way to add a css class to custom header TH elements ?

Thanks

**Comment by AMBudnik** [comment]
I guess that the best way would be to add those settings directly in the `colHeaders` option, like here: http://jsfiddle.net/1qrnhbz7/ Just add the class name and make CSS file do the rest.

**Comment by varun-dev** [comment]
thanks for your quick response but as I mentioned in my post, I want to add a class to the parent TH element

**Comment by AMBudnik** [comment]
Ohh right! There's a method called `getColHeader` but it will give you only what's inside the header (demo: http://jsfiddle.net/aeoqqof3/) not the TH element. Then I guess the easiest way to get the col header as a TH element would to this

`var col0 = container2.getElementsByTagName('TH')[0];`

(demo: http://jsfiddle.net/395zuofb/) but... the table is using it's default settings to set headers and this styles and classes are being recalculated with every change and move. 

That's why when we want to change the look we're using the demo I've gave you before. I assume you do not want to add the CSS if the above was insufficient?

**Comment by varun-dev** [comment]
Thanks Aleksandra. I will just have to live with this limitation :)

**Comment by AMBudnik** [comment]
Hey @kevinkam 

the issue got closed. Since that time the schema did not change. 
Have you tested the tips from my last comment? Maybe your case is a bit different and we'd be able to share some other ideas.

As this is a topic from 2016 maybe you could share the scenario with me on emails? I'm on support@handsontable.com
