### ISSUE TITLE
getSourceDataAtRow not returning empty cells

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#3714]
[Reproduction online](http://jsfiddle.net/7u1kxjLe/10/)

Insert any character in the B column of the 1st row.
`getSourceDataAtRow` returns this "funny" array (i we can even call it an array)

```javascript
[null, null, null, null, null, surname: "c"]
```

As you can see, none of the empty values are being retrieved.

This is how the array looks when filling the whole row:

```javascript
[null, null, null, null, null, surname: "c", name: "test", phone: "test", address: "test"]
```

Any way to get the whole list of params even when they are empty? Like so:
```javascript
[null, null, null, null, null, surname: "c", name: "", phone: "", address: ""]
```

Notice that when pasting the row with empty values or when typing them and removing them afterwards, the result is as expected:
```javascript
[null, null, null, null, null, surname: "c", name: "", phone: "", address: ""]
```
Which clearly shows an inconsistent design here. 

Related with #3165

**Comment by AMBudnik** [comment]
thank you very much for the demo and well explained case.
I think that we have already mentioned similar issue but this one for sure has to be marked as a bug.

**Comment by AMBudnik** [comment]
Hi @alvarotrigo 
Sorry that it took so long to fix the following issue. I hope that now it works fine, can you test it? It would help us a lot.

**Comment by jansiegel** [comment]
@alvarotrigo, we've just released version `0.28.4` with a fix for this problem.

We've decided that in an example like yours, it would be best to use the `dataSchema` along with the `columns` property. Take a look at this example: http://jsfiddle.net/js_ziggle/trgtfttk/

I think it makes sense, because defining only the `columns` property might leave us with an inconclusive result. For example, if we declare `columns` as:
```js
[
    {},
    {}, 
    {
    	data: 'phone',
    },
    {}
]
```
we wouldn't know if the underlaying dataset should be an array (as some of the columns don't have a property) or an object (for the *phone* property).

If you'd like to automatically generate the schema based on your `columns` setting, you can do it as easily as this: http://jsfiddle.net/js_ziggle/trgtfttk/2/

Hope this helps!

**Comment by AMBudnik** [comment]
@alvarotrigo @jansiegel I'm closing this issue as there were no concerns about our fix.

**Comment by alvarotrigo** [comment]
@AMBudnik @jansiegel thanks for it! I'll review it whenever I have some time.

**Comment by nishanthjeesoft** [comment]
Working fine and this solves my problem.
