### ISSUE TITLE
Dropdown editor obscures elements on the right

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#3758]
Active editor of the dropdown generates additional, empty space on the right (as on the attachment).
#### Steps to reproduce:
1. Go to: http://jsfiddle.net/0mo2b9do/
2. Open editor of `C1`
3. Try to click <kbd>LMB</kbd> on first ~20px on the left side of `D1` 

![screen shot 2016-09-15 at 14 41 10](https://cloud.githubusercontent.com/assets/11849621/18550210/effafba4-7b52-11e6-930b-441667bb6df6.png)

**Comment by AMBudnik** [comment]
related: https://github.com/handsontable/handsontable/issues/3614

**Comment by AMBudnik** [comment]
Still replicable in v0.35.0 (updated demo http://jsfiddle.net/snjwo3qc/)

**Comment by ElGrimbo** [comment]
The problem is much worse when using trimDropdown:false. Even fairly short options obscure a large portion of the next cell.

![image](https://user-images.githubusercontent.com/10922976/45285863-21f04780-b4dc-11e8-8e1f-ca861270961f.png)

![image](https://user-images.githubusercontent.com/10922976/45285680-ab534a00-b4db-11e8-814a-065263f24708.png)

**Comment by AMBudnik** [comment]
Thank you for reporting that @ElGrimbo

**Comment by swistach** [comment]
> related: #3614

Indeed, `dropdownEditor` bases on `handsontableEditor` - if we improve dimensions calculation there it should help also in this scenario.
I think we can close this issue and mark it in #3614 as a test case.
