### ISSUE TITLE
How to avoid viewport being scrolled to selection?

### ISSUE THREAD

**Issue by Lzystrike** [handsontable/handsontable#3779]
When set `renderAllRows` to true, the viewport will not scroll vertically if a singe cell was selected. However, viewport still scrolled horizontally when a cell was selected no matter what was set on `viewportColumnRenderingOffset`. So how to avoid viewport being scrolled to selection vertically and horizontally (just keep viewport still)?

**Comment by AMBudnik** [comment]
Hi, you would like to not scroll the viewport to a selected cell right? If you are using `selectCell()` method to select cell you can pass `false` argument in `scrollToCell` parameter (docs: https://docs.handsontable.com/pro/1.7.1/Core.html#selectCell) 

In otherwise we do not have a similar option when user what's to select a cell. You could disable arrow navigation but it's more a workaround as not so great if you still want users to navigate between cells.
