### ISSUE TITLE
Prevent specific column resizing with manualColumnResize

### ISSUE THREAD

**Issue by cgatesman** [handsontable/handsontable#3843]
It would be nice to be able to disable column resizing on specific columns when you have `manualColumnResize` enabled.  I have a specific column I would like to be a fixed width, but allow other columns to be resized by the user.

**Comment by AMBudnik** [comment]
Agree, we could allow to pass `false` in the `beforeColumnResize` hook

**Comment by cgatesman** [comment]
I was thinking the same thing.  Would need to fix #3328, first, though.

**Comment by AMBudnik** [comment]
That's correct @cgatesman https://github.com/handsontable/handsontable/issues/3328 is strongly related and as you wrote there (with which I agree) the following callback won't help us a lot without fixing this issue.

The second case is that the handler appears when we enable `manualColumnMove` so the change (as I assume) should be made there as well.

**Comment by AMBudnik** [comment]
We're moving this topic to our [Feature-requests section](https://github.com/handsontable/handsontable/wiki/Feature-requests)

**Comment by wojciechczerniak** [comment]
Done in #3328

**Comment by AMBudnik** [comment]
For anyone interested in this subject. The referenced issue https://github.com/handsontable/handsontable/issues/3328 has been closed as solved in v 8.0.0

**Comment by Maxoudela** [comment]
I am interested in this issue. I'm wondering why it's closed? Should I open another one or could we still discuss on this one?

I believe the idea would be to behave like `colWidths` option and be able to either give a `Function` or an array that would allow to define the property for each column separately:

```
manualColumnResize : function(index) {
  return false;
},
```

Or maybe use the tip that @swistach gave me in #7507, for example something like that:
```
 columns: (index) => {
       return {manualColumnResize: true};
    },
```

I'm wondering if a technical limitation prevents this issue from being resolved? 
Would you be interested in a primitive PR (if I'm able to dig something valuable) in order to discuss further on this subject?

**Comment by AMBudnik** [comment]
Hi @Maxoudela 

That is true. This

```js
manualColumnResize : function(newSize, index) {
  return false;
}
```
is the goal that has been defined here https://github.com/handsontable/handsontable/issues/6581 as an improvement/feature. 

Closed issues are related to the fact that we received false information within the hook.

ps. sorry for the confusion. https://github.com/handsontable/handsontable/issues/6581 should have been linked to this subject to ensure everyone that this subject is still awaiting development.

**Comment by Maxoudela** [comment]
I'm a bit confused by #6581 and I'm not sure this current ticket has the same goal.

If I'm not mistaken, #6581 wants that `beforeColumnResize` disable a resize on manual resize (grab handle and release) or by API call. The way I'm seeing this improvement means:

> I'm authorizing the user to resize the column by grabbing the handle and releasing it. But I can control the resize in the hook by giving false if I think the current resize should not be applied. 

Basically, it means that the `hookNewSize` returned by the hook will be used [here](https://github.com/handsontable/handsontable/blob/a58d4e235c90bb896d7d7488b7a00c197cffa1a4/src/plugins/manualColumnResize/manualColumnResize.js#L512) just like it's being used [here](https://github.com/handsontable/handsontable/blob/a58d4e235c90bb896d7d7488b7a00c197cffa1a4/src/plugins/manualColumnResize/manualColumnResize.js#L415).

But this ticket _seems_ different to me because it aims as **preventing** a specific column to be **resized by the user**. Not controlling whether one specific resize is authorized or not. So any work done on the `beforeColumnResize` is too late IMHO. This concern has already been explained before:

> However, I'm not sure doing it in beforeColumnResize would prevent the resize handle from appearing. Or would it? Visually, I think this functionality should not even allow the user to attempt to resize.

I believe this ticket would rather work on the [onMouseOver](https://github.com/handsontable/handsontable/blob/a58d4e235c90bb896d7d7488b7a00c197cffa1a4/src/plugins/manualColumnResize/manualColumnResize.js#L377) that is putting the "handle" cursor. In that specific code, we should verify whether the column is allowed to be resized or not. And I don't think that calling `beforeColumnResize` would be satisfying.

**Comment by AMBudnik** [comment]
You are right, @Maxoudela 

> However, I'm not sure doing it in beforeColumnResize would prevent the resize handle from appearing. Or would it? Visually, I think this functionality should not even allow the user to attempt to resize.

the `return false` would not block the resize handle. It would just abort the action.

I think that adding some additional options to `columns` settings would follow the overall idea of providing functionalities to Handsontable. Using this scheme we could also
* remove dropdown menu for a column
* remove move handle for a column

What do you think @swistach ?

**Comment by Maxoudela** [comment]
Thanks @AMBudnik .

Since the "handle" is coded in `manualColumnResize`, I would rather see it configured here instead of  `columns`. But I'll leave that decision to you.

I can try a primitive implementation that would allow such a feature and provide a PR if you want? That could be a good starting point for discussing the API, testing the feature etc?

**Comment by AMBudnik** [comment]
Let me share some details on the proposed improvement.

Here we have an example of `readOnly` functionality.
![image](https://user-images.githubusercontent.com/10757813/108479697-544e2380-7296-11eb-85b9-3d82e387bea0.png)
We can set it globally (for the whole instance). But then we can specify that it has to be turned off for a certain column.

This is how I would see the way to exclude a column from:
* resizing 
* moving
* dropdown menu

CODE
![image](https://user-images.githubusercontent.com/10757813/108480357-23222300-7297-11eb-838d-e74aeb2d8642.png)


RESULT
![image](https://user-images.githubusercontent.com/10757813/108480165-e48c6880-7296-11eb-8fcc-2cc3807de755.png)

> I can try a primitive implementation that would allow such a feature and provide a PR if you want?

I'm more than happy to hear that you want us to help with the implementation. But first, we need to specify a way to provide the functionality. It has to meet the project guidelines and follow the pattern that we keep for other options.

**Comment by Maxoudela** [comment]
That seems good to me. I'll let you discuss the API.

We have to keep in mind that `manualRowResize` is the twin of `manualColumnResize` and providing a new functionality to one should also, IMHO, be provided for the other. I don't think there is a `rows` API like we have for ` columns`, therefore my initial idea to keep it configured in their initial plugins.

**Comment by swistach** [comment]
@AMBudnik, extending plugins' options for particular columns and cells looks promising, but it'd need many changes.
Although, for now, we might add a description to every built-in option, in which context you can use them, e.g.:

```
/**
 * ...
 * @availableFor {TableMeta}
 */
manualColumnMove

/**
 * ...
 * @availableFor {TableMeta| ColumnMeta | CellMeta}
 */
readOnly
```

**Comment by AMBudnik** [comment]
>we might add a description to every built-in option, in which context you can use them

I adore this idea. We miss this information in the docs.
