### ISSUE TITLE
IF condition formula seems not to evaluated when enter new value

### ISSUE THREAD

**Issue by jeanmarc78** [handsontable/handsontable#3908]
### Description
IF condition formula seems not to evaluated when enter new value

### Steps to reproduce

1. go to http://jsfiddle.net/jeanmarc/kns3n244/1/
2. enter in E5 , the new value 2
3. the calculated result in F5 remains to -1

### Your environment
* Version:1.8
* Browser Name and version: firefox 50
* Operating System: windows 10

regards
jm

**Comment by AMBudnik** [comment]
thanks for sharing @jeanmarc78 
I got the same result.

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **New formula plugin** task reported at https://github.com/handsontable/handsontable/issues/6466

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Comment by AMBudnik** [comment]
Hi @jeanmarc78 

This issue is no longer replicable using v9 with the new _HyperFormula_ engine. Updated demo http://jsfiddle.net/k19pcraf/1/
For everyone interested, here is a list of changes for the following version https://handsontable.com/docs/9.0.0/tutorial-release-notes.html and here https://handsontable.com/docs/9.0.0/tutorial-migration-guide.html is a migration guide (from v8 to v9)
