### ISSUE TITLE
afterOnCellMouseDown returns coords (0,0) after click on the topleft corner

### ISSUE THREAD

**Issue by stla** [handsontable/handsontable#3978]
Hello,

My hook:
```
hot_instance.addHook('afterOnCellMouseDown', function(event, coords, TD){
    console.log(event);
    console.log(coords);
    console.log(TD);
  });
```
I click on cell (0,0) then I click on the topleft corner ("the cell (-1,-1)", above the row headers and at left of the column headers) :

![capture](https://cloud.githubusercontent.com/assets/4466543/21715247/ad3054ae-d403-11e6-80fb-f92b4ec74d24.PNG)

I expected to get **(-1,-1)**. Wouldn't it be more sensible ?

###  environment
* Handsontable version: `0.28.4` 
* Browser Name and version: Chrome 48
* Operating System: Windows 7

**Comment by AMBudnik** [comment]
You're right I also think that we should get `(-1, -1)`

ps. if you were trying to get the element in the top left corner you can call `afterGetColHeader`, like here: http://jsfiddle.net/9ko2cnLL/

**Comment by gresspav** [comment]
Hi @AMBudnik
Does your demo http://jsfiddle.net/9ko2cnLL/ work correctly for you?
For me it causes following errors. First attached error during initialization and second attached error everytime when any cell is clicked.
I am asking because we have reported the same error "cannot read property startRow of null" in our solution. What could be the problem here?
![image](https://cloud.githubusercontent.com/assets/20515049/21892401/fcb2e6cc-d8d6-11e6-9032-a6cd05f19e84.png)

**Comment by AMBudnik** [comment]
You're right, the `x` is set as a value however we get a class issue.
When I change the innerHTML to 

`TH.innerHTML = '<div class="relative">x</div>'`
 it starts to ask for an element that has to have a class `rowHeader` or a `colHeader`, so if we do not want to get the log we need to nest the following structure (http://jsfiddle.net/m9bk8hk1/):

```
<div class="relative">
   <span class="colHeader">
      x
  </div>
</div>
```

still we get 

`WalkontableCellCoords {row: 0, col: 0}` for the following part of the table.

**Comment by wszymanski** [comment]
Finally, it should be fixed within: https://github.com/handsontable/handsontable/issues/6178.

**Comment by AMBudnik** [comment]
I've added

```
hot.addHook('afterOnCellMouseDown', function(){
    console.log(arguments[1]);
});
```

to the example (8.0.0-beta2-rev7) http://jsfiddle.net/AMBudnik/ub7swhcf/
And we get the right result `(-1, -1)`

**Comment by AMBudnik** [comment]
It also works well for `nestedHeaders` https://jsfiddle.net/f7c32xoj/4/
Tested revision 16 of 8.0.0-beta2

**Comment by pnowak** [comment]
In 8.0.0-rev1 the hook `afterOnCellMouseDown` returns the good coordinates.

But selection for `nestedHeaders` behaves quite different than in beta2.
In 8.0.0-rev1 is selected all headers:

![Jul-28-2020 14-44-56](https://user-images.githubusercontent.com/1555809/88667247-68a3b680-d0e1-11ea-86d2-1a47a264a793.gif)

In 8.0.0-beta2 rev16 is selected only the most top header:
![Zrzut ekranu 2020-07-28 o 14 45 43](https://user-images.githubusercontent.com/1555809/88667311-7c4f1d00-d0e1-11ea-8e26-a30dd0e472a9.png)

**Comment by wszymanski** [comment]
> In 8.0.0-rev1 the hook `afterOnCellMouseDown` returns the good coordinates.
> 
> But selection for `nestedHeaders` behaves quite different than in beta2.

Thanks for your mindfulness and for the investigation. Now it works properly.

**Comment by AMBudnik** [comment]
Hi @stla 

Now it's official. The Handsontable v8.0.0 that solves this issue is live!   

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases  

I highly encourage you to test the new version and leave some feedback. ✍️
