### ISSUE TITLE
Uncaught TypeError: Cannot set property 'forceFullRender' of null

### ISSUE THREAD

**Issue by chengtie** [handsontable/handsontable#4043]
I want to create a textarea besides a handstontable, such that modifying the table affects the text and vice-versa.

Here is the [JSBin](https://jsbin.com/quresud/1/edit?html,console,output).

One thing I realise is that, adding rows will not fire the watcher of `dataJSON`. So I use `$scope.$digest()` in the callback `onAfterCreateRow` to reflect the change of adding rows. But it raises an error `Uncaught TypeError: Cannot set property 'forceFullRender' of null`:

![screen shot 2017-02-01 at 17 07 55](https://cloud.githubusercontent.com/assets/774409/22514884/0b5ffbf4-e8a1-11e6-9e3c-8217ae80e810.png)

Does anyone know how to solve this?

**Comment by AMBudnik** [comment]
Here's a related issue: https://github.com/handsontable/handsontable/issues/3504

**Comment by AMBudnik** [comment]
Hi @chengtie 
here's a demo I got from @swistach 
https://jsbin.com/zegarigego/1/edit?html,output

you would just need to add the action for inserting columns as well.

**Comment by chengtie** [comment]
Thank you... 

So to conclude, 1) my workflow (ie, trigger the digest cycle in a callback event) has no problem; 2) `Cannot set property 'forceFullRender' of null` is a bug; 3) `$timeout` which does a safe `$apply` is a workaround.

Is it correct?

**Comment by budnix** [comment]
Hi @chengtie,

In your case calling `$digest` directly after `onAfterCreateRow` hook probably triggers re-creating internal DataMap manager object so that's why you met `Cannot set property 'forceFullRender' of null` error. I suppose that this can by a bug (it should be more investigated to be sure what is going on).

About `$timeout` it is safe workaround but it can be omitted. I've prepared demo for you where you don't need them. Here you find [optimized](https://jsbin.com/bilejamine/1/edit?html,console,output) version.

**Comment by pindamonhangaba** [comment]
I also get this same error when triggering changes to a store with React. Only seems to happen on `afterRemoveRow`, `afterChange` works fine. And both trigger actions to change a Redux store.

**Comment by AMBudnik** [comment]
I assume that we can close this issue but if it still occur please create a new topic at the ngHandsontable issue board.

**Comment by aaronbeall** [comment]
@AMBudnik I've run into this same issue while using `react-handsontable`. Basically I have source data called `projects`, I convert to handsontable data pass it like:
```
<HotTable data={ projects.map(projectToTableData) }>
```
When Handsontable adds a row (via `minSpareRows`) I handle `afterCreateRow` to add a new `project`:
```
handleAfterCreateRow = (index, amount) => {
  this.setState(prevState => ({ 
    projects: [...projects, createBlankProject()] 
  });
}
```
This triggers the error and stack trace in the start of this thread. 

If I wrap the `setState` in a timeout it avoids this error, but when pasting data into newly created rows I have problems because that data can't be handled to update projects via `afterChange`. I need to create the `projects` right away so that the subsequent `afterChange` can apply the cell changes to the associated projects. Any suggestion?

**Comment by AMBudnik** [comment]
Sorry for a delay. I am not a react expert so I am not sure if I'd be capable of sharing any code example.

Can you tell me if you have already tried some approaches?

**Comment by aaronbeall** [comment]
@AMBudnik Thanks for the reply. Basically [this is the same issue in react-handsontable](https://github.com/handsontable/react-handsontable/issues/18). In my case delaying the change causes other problems. What I ended up doing is directly mutating the source data without re-mapping to handsontable which causes the redraw (and the typeerror in theses issues). It would be great if handsontable could handle this without error, but I can't say how without getting deep into the source code. For now I guess my workaround is fine.
