### ISSUE TITLE
afterChange hook called with wrong arguments for 'external' event

### ISSUE THREAD

**Issue by renehamburger** [handsontable/handsontable#4045]
In the most recent Handsontable version, afterChange is [called with wrong arguments](https://github.com/handsontable/handsontable/blob/master/src/plugins/observeChanges/observeChanges.js#L110). It would need to be an array of arrays.

As an aside, the 'external' source isn't [documented](https://docs.handsontable.com/pro/1.9.1/Hooks.html#event:afterChange) yet.

**Comment by budnix** [comment]
Thanks for reporting this issue. You are right there should be an array of arrays.

And about `'external'` source this issue is strongly connected with https://github.com/handsontable/handsontable/issues/4017 and this was already fixed. This fix will be released probably in the next week with [corresponding](https://github.com/handsontable/docs/blob/3e664809a1bdca14acd7a45f36142e255b680de1/tutorials/using-callbacks.html#L171) changes in documentation.

**Comment by renehamburger** [comment]
I've just realised that this bug causes an exception when a paste is tried to be reverted with 'undo'.

**Comment by renehamburger** [comment]
Hi @budnix, has this bug made it onto your roadmap?

**Comment by budnix** [comment]
I've looked into the source code, and I must say that this bug still exists. My work was about fixing the `source` argument problem which is now fixed and documented ([http://docs.handsontable.com/pro/1.10.1/tutorial-using-callbacks.html#page-source-definition](http://docs.handsontable.com/pro/1.10.1/tutorial-using-callbacks.html#page-source-definition)).

**Comment by wojciechczerniak** [comment]
Was fixed a year ago: https://github.com/handsontable/handsontable/commit/592eae36ad331b2861f63db7ce91f074360fc96b

https://github.com/handsontable/handsontable/blob/c2ba2dc02e3eb883a58f976ef5944fa629dc981d/src/plugins/observeChanges/observeChanges.js#L106
