### ISSUE TITLE
preventOverflow breaks keyboard navigation

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#4084]
### Description

Viewport does not scroll when we use keybord navigation while using `preventOverflow: 'horizontal'`

### Steps to reproduce

1. Use arrow down to move down. When you'll reach row 9 table does not scroll to show the cell.

![example35](https://cloud.githubusercontent.com/assets/10757813/23071630/4f81b094-f52f-11e6-9427-d640ce9eb324.gif)

### Demo

https://jsfiddle.net/wojciech/r7sz9f0b/

### Your environment
* Handsontable version: 0.31.0
* Browser Name and version: Chrome 55
* Operating System: Windows 10

**Comment by krzysztofspilka** [comment]
@wszymanski @AMBudnik That JSFiddle demo is broken and one of the reason is wrong CSS.

1. Visit your demo at https://jsfiddle.net/wojciech/r7sz9f0b/ - try to scroll down, you will get a blank space (probably that's not a bug).
2. Now, remove from the CSS 'overflow:hidden' and 'height' properties. Also, add more columns to see the table scrolling. Result: https://jsfiddle.net/r7sz9f0b/1/

> If you set only the table's width, it won't render properly until you use the preventOverflow option. By setting it to horizontal your spreadsheet will have the width of a parent container and the height of the window. Scrollbars will appear if needed. Basically, the preventOverflow option prevents the table from overflowing the parent container in the provided dimension, in this case - horizontal.

**Comment by wszymanski** [comment]
So, as described it works properly - I close the ticket.
