### ISSUE TITLE
The TypeScript definition file inside project directory.

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#4112]
### Description
In last year the basic definition file was added to DefinitelyTyped. Unfortunately it's not convenient solution.
To improve support for TS users, we decided to keep definition file in our repository.

We're open for any suggestion what should be in our definition file.

### To-do
+ [x] Handsontable.baseVersion
+ [x] Handsontable.buildDate
+ [x] Handsontable.cellTypes
+ [x] Handsontable.Core
+ [x] Handsontable.Dom
+ [x] Handsontable.editors
+ [x] Handsontable.helper
+ [x] Handsontable.hooks
+ [x] Handsontable.plugins
+ [x] Handsontable.renderers
- [x] WalkontableCellCoords
- [x] WalkontableCellRange
+ [x] tests
+ [x] configuration in package.json

**Comment by deenairn** [comment]
Building on the previous handsontable.d.ts I would ensure the following:

- Use specific lambda definitions rather than merely Function where the actual HoT API defines this. The definitions of lambdas can be quite open ended by using ? to mark optional arguments, and also using union types to ensure all overloads are caught. Function is too vague when using intellisense - it means you still have to consult the API documentaton.
- Ensure the addition of Handsontable.Dom and other hooks that were missing before so that all hooks are available within the TypeScript API
- Ensure internal types are returned, see my contribution which defines what I'd called ht.Range and ht.Selection.
- Include either in the ngHandsontable, or within the Handsontable repository itself, anything specific to those libraries. The main one I am thinking of is HandsontableRegisterer but there may be others. I use this specifically with Angular bindings but it may be available from the main HoT library.

**Comment by swistach** [comment]
Thanks @deenairn for your suggestions. To-Do list was updated.

**Comment by panesofglass** [comment]
I started working on an update [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/15514). I hope that is helpful as a starting point.

**Comment by swistach** [comment]
Thanks a lot for your commitment!
Internal definition file is based on previous version from DefinitelyTyped/types/handsontable. You can check it out in this commit: https://github.com/handsontable/handsontable/commit/87550d0de751070b2db9066fdd75333d2e504acc

Could you send me any comments, which we should add to our definition file before next release?

**Comment by panesofglass** [comment]
@swistach could be that I'm testing this incorrectly, but when I drop the new `handsontable.d.ts` into my project, I cannot resolve any types using the import syntax. It's possible that would work differently once it's in the package and not in my local scripts folder.

**Comment by swistach** [comment]
Hi @panesofglass,
could you try ```npm install handsontable/handsontable#feature/issue-4112```
and then just ```import {Handsontable} from 'handsontable';``` into your .ts file?
I can prepare testing repository with the simplest configuration.

**Comment by panesofglass** [comment]
Yes, I will try by Monday at the latest.

**Comment by panesofglass** [comment]
I cannot complete the conversion to the new definitions. I can find no type declaration for custom `Handsontable.Validator`s. Also, the namespaces don't match up with those in the documentation, making it quite difficult to find the right types. I think the use of `import { Handsontable } from "handsontable"` is incorrect. The last I looked, `Handsontable` is a direct export and provides a constructor function, as well as properties to access additional options. If I recall correctly, the documentation assumes `import Handsontable from "handsontable"`, and the current DefinitelyTyped definition supports `import * as Handsontable from "handsontable"`. I am still a little confused myself on how TypeScript generates JS based on declaration files, so some of these things may work out just fine. However, I would appreciate if the namespaces matched up better so that declaring types matched what I read in the Handsontable source code. I hope that is helpful, and I'm happy to assist in adjusting the type declarations if that is useful.

**Comment by swistach** [comment]
I sent changes and `import Handsontable from 'handsontable';` should work properly.
`Handsontable.Validator` was never in under `Handsontable`, are you talking about cellValidators? They are available in Handsontable.cellTypes.<cell name>, eg. `Handsontable.cellTypes.numeric.validator`.
If you have any other ideas or solutions, I'll be really grateful for your comments.

**Comment by AMBudnik** [comment]
Thanks for adding @swistach 
@panesofglass hope it will work for you as well.
