### ISSUE TITLE
tempElem.className.indexOf is not a function

### ISSUE THREAD

**Issue by MarshallChen** [handsontable/handsontable#4120]
I'm using SVG element in table cell, so the problem is SVG element.className doesn't have indexOf function, error come from [this line](https://github.com/handsontable/handsontable/blob/f52419f500b11241c3c0d97a5bfa5574cc0e0006/src/3rdparty/walkontable/src/overlays.js#L337). Should I make a PR to fix this?

**Comment by AMBudnik** [comment]
Hi @MarshallChen 

If you have tested the example you can share a Pull request but please remember to compose it from the developer branch.

**Comment by MarshallChen** [comment]
I think it should be as simple as change this line
```js
if (tempElem.className.indexOf('wtHolder') > -1) 
```
to this
```js
if (tempElem.getAttribute('class').indexOf('wtHolder') > -1)
```
if the PR is needed let me know.

**Comment by AMBudnik** [comment]
Hi @MarshallChen 

Thank you for the pull request. Our devs will check it in the earliest convenience

**Comment by aaronbeall** [comment]
@AMBudnik FYI this bug looks obsolete or fixed by other changes. I was looking into [the same issue in another area of code](https://github.com/handsontable/handsontable/pull/6010), found this bug, saw @MarshallChen's PR never got merged but the [current code has changed](https://github.com/handsontable/handsontable/blob/671d7240267a11315f005a389728d113d9964313/src/3rdparty/walkontable/src/overlays.js#L347) such that the original bug-code here is gone. 🥂

**Comment by AMBudnik** [comment]
Thank you for the input :) I can see that @pnowak took his hands on it.

**Comment by AMBudnik** [comment]
Hey @MarshallChen  please update to 7.1.0 We've just fixed it :)
