### ISSUE TITLE
It is not possible to set row height less than 21px

### ISSUE THREAD

**Issue by haydave** [handsontable/handsontable#4140]
### Description
Table has several rows with different heights.

### Steps to reproduce
1. Set rowHeights with values less than 23 (e.g. [30, 14, 12])
2. Set default row height to 10
3. But table generates with [30, 23, 23] row heights

### Demo
[https://jsfiddle.net/31t63ydp/](https://jsfiddle.net/31t63ydp/)

### Your environment
* Handsontable version: 0.31.1
* Browser Name and version: Chrome Version 54.0.2840.90 (64-bit)
* Operating System: Ubuntu 14.04

**Comment by AMBudnik** [comment]
Hi @haydave 

Currently, the row height cannot be less than the value of a text line and it is an intended behaviour.

I will mark this issue as a 'doc needed' as we should add this information to the documentation.

**Comment by haydave** [comment]
Hi @AMBudnik ,

Thanks for the quick response.
Please confirm that my understanding is correct.
In this version of the spreadsheet library there is no functionality to reduce minimum row height (it is necessary because in our case font size in a table is small enough).

So we have to change height and line-height in source css.

Thanks

**Comment by AMBudnik** [comment]
In this version of the Handsontable CE and PRO (and since the beginning), there is no functionality to reduce minimum row height. 

Yes, as a workaround you can overwrite the default `height` and `line-height` values for the `TR` element, like here: http://jsfiddle.net/handsoncode/f6jnqrk9/ but doing this via CSS can be problematic cause it is harder to set the new values for some rows only.

**Comment by swistach** [comment]
Information about limitations was added in #3895
