### ISSUE TITLE
Not accepting pull requests

### ISSUE THREAD

**Issue by TRManderson** [handsontable/handsontable#4144]
### Description
The last non-documentation handsontable pull request that was merged was https://github.com/handsontable/handsontable/pull/3249, over a year ago. This was by a Handsontable developer.

The last non-documentation pull request from someone other than a Handsontable developer that was merged was https://github.com/handsontable/handsontable/pull/2796, in September 2015.

Very few of the PRs even get commented on.

Why isn't Handsontable accepting pull requests? If you aren't accepting pull requests, can you please let developers know in the README.

**Comment by AMBudnik** [comment]
Hi @TRManderson 

Thank you for creating this topic. I am glad that someone has raised the issue and as it already has 7 likes it means that it is something important to discuss.

First of all - you are right @TRManderson, most of the pull request aren't accepted. 

The main reason why the code is not pulled into the official version is the fact that we are [working on the developer branch](https://github.com/handsontable/handsontable/wiki/How-we-use-Git-Flow) and currently 27 out of 140 PRs are made to the **master** branch. I cannot count how many times I mentioned about this rule which we cannot break.

You can believe me or not but the very few pull requests that are made to developer branch often do not have tests, proper description or just doesn't follow 'good practices'. Yes, we as Handsoncode had some 'ups and downs' when it comes to coding 'style' but as we are slowly switching to Babel we hope that the code will be more organized.

At the end I can ensure you that I will do my best to share a reply on every PR made to developer branch that follow the tips of Git Flow and [Contributing guidelines](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md).

**Comment by TRManderson** [comment]
There's several very easy ways to improve the `develop` branch problem:
1. Actually tell people to make PRs to the develop branch in CONTRIBUTING.md. I will make a pull request for this shortly.
2. Change the default pull request template so that it explicitly mentions to make PRs to `develop`
3. Have a bot automatically comment on PRs that merge to the wrong branch - I am happy to provide code for this if you'd like.
4. Set the main branch on Github to be `develop`, which means that it will be Github's default target branch for PRs.

It's very simple to add a comment saying "please add tests" or "please add more description" in a one sentence comment, yet the majority of PRs don't have any comments whatsoever, so I honestly don't see that as a sufficient excuse. Making such comments takes _at most_ a minute, including time taken to checking the content of the PR.

**Comment by AMBudnik** [comment]
Thank you @TRManderson, as @budnix wrote few minutes before in your PR that was actually a very simple switch that hopefully will change the situation. It is definitely our bad that we didn't add the information to the Contributing file in the first place.

About the template, I can remember our CEO mentioning this subject few weeks ago and we have added a template to organize the information and inform developers to add tests. When it comes to branch information I will ask our devs about that and be back with news later today or tomorrow at the latest. 

The second case with PRs is the fact that the current structure of Handsontable is not fully organized and that's why if something is fixing one thing it can produce some new issues in other places. That is why when it comes to PR content and checking the solution... it does not take only a few minutes - and I'm thinking about the PR with fixes. It can take a minute if the solution is missing some logic or just 'not doing it right' however for complex solutions it could be more than an hour. But... it doesn't mean that it's not worth of checking, please do not understand me wrong here. I just wanted to say that we cannot say that checking the code is simple and quick. If someone spends few hour on creating the code we won't be able to check it and test it within few minutes. 

Also here I would like to thank everyone who has ever made a pull request. Me and one of our developers have raised the subject on our general chat to rethink the PR strategy and as soon as we will figure out a solution that will be the best for the software I'll be back with the details.

**Comment by AMBudnik** [comment]
Hi again,

We have finally got the CLA document that, if signed, will allow us to merge pull requests. It can be found in our new [Contributing file](https://github.com/handsontable/handsontable/blob/master/CONTRIBUTING.md).

After following all the steps from the mentioned file all opened pull requests will be marked with a label `Developed (ready for review)` and be tested by our developer in the earliest convenience.

Thank you again and feel free to open new PRs.
