### ISSUE TITLE
Hot disappears after last row removal

### ISSUE THREAD

**Issue by ankushgoel** [handsontable/handsontable#4169]
Description
After the deletion of last row present in the table, handsontable disappears leaving an empty cell behind.
Ideally if only one row is present in the table it should not be allowed for deletion.

 Steps to reproduce
1. On last existing row, Right click -> "remove row".
2. Row will be removed, along with the table.

 Demo
http://jsfiddle.net/rgxzmyxn/1/

Environment
* Handsontable version: 0.31.1
* Browser Name and version: 56
* Operating System: Ubuntu 16.04

**Comment by AMBudnik** [comment]
Thanks for sharing @ankushgoel 

An empty TH element is not what we would like to get after removing the last row from a table.

![gif](https://cloud.githubusercontent.com/assets/10757813/24741001/3823e918-1aa4-11e7-9e8f-80856e446d9c.gif)

**Comment by AMBudnik** [comment]
It works the same in v `5.0.1`. Updated demo http://jsfiddle.net/qj0no9h7/

**Comment by wojciechczerniak** [comment]
> An empty TH element is not what we would like to get after removing the last row from a table.

@AMBudnik What we would like to get?

The table in the example is defined by the `data` array. If all rows are removed the number of columns is 0, the number of rows is 0, we can only render the corner. If we define the `columns` the table won't disappear: https://jsfiddle.net/fw19gme4/ 

>  Ideally if only one row is present in the table it should not be allowed for deletion.

@ankushgoel We have an option for that: `minRows`: http://jsfiddle.net/04rLujsh/ But then again... we have to define the columns because the row will be empty and the columns cannot be calculated.

Done: http://jsfiddle.net/04rLujsh/1/

**Comment by AMBudnik** [comment]
@wojciechczerniak some of the users (I had 2 similar examples within the last 2 weeks) wanted the headers to stay. However, I wouldn't consider the lack of header as a bug. I just do not think that a single box (border header) is something that we would expect.

**Comment by wojciechczerniak** [comment]
I've asked devs about this one. Single box was done on purpose. Previously users had a problem, because they didn't had anything to click and show context menu after removing last row.

If our user wants the headers they can configure `columns`. If last row should stay, we have `minRows` option.

All of those use cases are possible right now.
