### ISSUE TITLE
Handsontable free version - formula support

### ISSUE THREAD

**Issue by andradobritoiu** [handsontable/handsontable#4228]
### Description
I'm using the 0.31.0 handsontable version on my project and can't get the formulas to work. I've set the options `formulas:true` and used the data array with formulas from your example and it seems it doesn't see the cell as a formula, rendering it as pure text. Am I missing something?

### Your environment
* Handsontable version: .31.0 
* Browser Name and version: Chrome
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Hi @andradobritoiu 

[Formulas Plugin](https://docs.handsontable.com/pro/1.10.2/demo-formula-support.html) is a part of Handsontable PRO feature list. 
To get moire information please visit [this topic](https://forum.handsontable.com/t/formulas-support/867/2)

**Comment by andradobritoiu** [comment]
I remember using handsontable the free version with formulas included. Was this a previous version? Are we able to still use it on older versions?

**Comment by AMBudnik** [comment]
@andradobritoiu we have a free formula repository called [RuleJS](https://github.com/handsontable/ruleJS) but the last commit were 2 years ago and we do not support it anymore. You are free to use it, however, since April 2015 we have fixed many bugs which you won't be able to handle while using the RuleJS.
