### ISSUE TITLE
removeCellMeta documentation needs to be updated to say physical index

### ISSUE THREAD

**Issue by jeremy-smith-maco** [handsontable/handsontable#4278]
### Description

The removeCellMeta method says "Row index" and "Column index" for the arguments when really it should say "Physical row index" and "Physical column index" or something because I was trying to figure out why I couldn't remove cell meta from a cell when the table was sorted. It just needs to be clearer in the documentation that it has to be physical and not visual indices since the setCellMeta method uses visual indices but removeCellMeta uses physical indices.

### Steps to reproduce

1. Sort the table
2. Set the cell meta to something (readOnly in the demo)
3. Using the same arguments as setting the meta try and remove the meta
4. Convert to physical indexes to fix issue

### Demo

Problem: http://jsfiddle.net/Lp4qn55v/667/
Solution: http://jsfiddle.net/Lp4qn55v/668/

### Your environment
* Handsontable version: 1.10.2
* Browser Name and version: Google Chrome: Version 58.0.3029.110 (64-bit)
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Thank you for your suggestion. I think that every change that will help us make docs better is highly needed.

**Comment by swistach** [comment]
Hi @jeremy-smith-maco,
In #3025 I'm working on standardize of the indexes names.

Double indexes of the cells was created to make possible moving, sorting and trimming.

Physical index is index in source data, which is "almost" permanent, unchangable. That means when something was initialize with coords (0, 0), after any transformation(move, sort, trim), have got the same physical coords like in the beginning.
Why "almost"? Because each `alter` (insert, remove) or `loadData` (new `data` within `updateSettings` is the `loadData` too) modifies physical indexes in whole table.

Visual index was called both ''logical" and "visual", but we decided to unify this as 'visual'. This is exactly this what you can see and it's changing after each transformation (move, sort, trim). That means when column 2 has been moved to the beginning, its visual index changed to 0.

@AMBudnik maybe this is good topic to the next blog post? :)

**Comment by AMBudnik** [comment]
@swistach sure, we should gather all needed points and create the article.

**Comment by twjacobsen** [comment]
A maybe-off-topic question: Does this go for all methods related to cell metadata?

Case: I'm trying to read meta data for a trimmed row, but I can't get it to play along.
When I pass my rowIndex (physical) to the `getCellMeta` method, I get the meta for the row with `visualRow` matching the index. If I do a `getCellMetaAtRow`, I get the proper meta data, but I get an incomplete set (or so it seems)

From the source, I can see that `getCellMeta` assumes input to be visual, and then translates input to physical. This makes it impossible to get meta for a trimmed row, because visual index is `null` in this case.

**Comment by jeremy-smith-maco** [comment]
@twjacobsen Can you not just use an index given in the "trimmedRows" [member](http://docs.handsontable.com/pro/1.11.0-beta2/TrimRows.html#trimmedRows) or even "removedRows" [member](http://docs.handsontable.com/pro/1.11.0-beta2/TrimRows.html#removedRows)? I haven't used the TrimRows plugin before.

**Comment by AMBudnik** [comment]
Thank you for your input @jeremy-smith-maco
