### ISSUE TITLE
Circular reference error in the formula

### ISSUE THREAD

**Issue by ssbunny** [handsontable/handsontable#4357]
### Description
If there is a circular reference in the formula plugin, the page hangs because it will cause a `Maximum call stack size exceeded` error.

### Steps to reproduce

1. let `A1` = 1, `B1` = 1, `A2` = `=A1+B1`;
2. After hot rendered, dblclick `B1`, set the value to `=A2`.

### Demo
https://jsfiddle.net/ssbunny/a1pLraxz/

### Your environment
* Handsontable version: pro 1.11.0
* Browser Name and version: Safari 9.0.2
* Operating System: OS X 10.11.2

**Comment by AMBudnik** [comment]
Thank you show sharing @ssbunny 

I have replicated the issue. `[GL #93]`

**Comment by AMBudnik** [comment]
It works the same in v 5.0.0

**Comment by OlgaIOn** [comment]
@AMBudnik is there any update on the issue?  Can we have an ETA on this? 
Will this be solved in a new formula plugin? Thanks in advance!

**Comment by AMBudnik** [comment]
Hey @OlgaIOn the new formula plugin is based on a different calculating engine and the connector (the code that helps the engine to work with Handsontable) is built from a scratch. 

The circular reference issue may now be replicable in the new plugin. However, as it is still a work in progress we need to keep all those formula issues in one place and test them after development.

**Comment by OlgaIOn** [comment]
@AMBudnik, thanks for your reply. We are waiting impatiently for the new formula plugin, since formulas are essential for our needs. When it will be ready?

**Comment by AMBudnik** [comment]
@OlgaIOn I highly encourage you to track progress on that topic https://github.com/handsontable/handsontable/issues/6466 and [here](https://github.com/handsontable/handsontable/issues?q=is%3Aissue+is%3Aopen+HyperFormula) is a full list of issues related to the formula engine.

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **New formula plugin** task reported at https://github.com/handsontable/handsontable/issues/6466

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Comment by aninde** [comment]
Updated demo
Bug reproducible with current v8.4.0 (https://jsfiddle.net/aninde/n49y86po/)
```
handsontable.full.js:14784 Uncaught RangeError: Maximum call stack size exceeded
```

v9.0.0 with HyperFormula as engine behavior is different (https://jsfiddle.net/aninde/o953u7c8/)
Table returns #CYCLE error due to https://github.com/handsontable/hyperformula/issues/362.

![Screenshot 2021-05-21 at 11 05 27](https://user-images.githubusercontent.com/30186818/119113049-fe1f8680-ba24-11eb-99c8-c3cdabd1f694.png)

**Comment by wojciechczerniak** [comment]
@aninde as it should 👍

**Comment by aninde** [comment]
> @aninde as it should 👍

@wojciechczerniak  so so we consider it as a fix?

**Comment by wojciechczerniak** [comment]
Yes

**Comment by AMBudnik** [comment]
It works the same (`#CYCLE` error) in official v9. Updated demo https://jsfiddle.net/crbt4xoj/
