### ISSUE TITLE
When changing cell type, cell editor does not dynamically change

### ISSUE THREAD

**Issue by ssbunny** [handsontable/handsontable#4360]
### Description
When changing cell type, cell editor does not dynamically change.

### Steps to reproduce

1. Set cell type to `numeric` (row 0, col 0 in demo);
2. Call the `setCellMetaObject` method to change the cell type (`date` in demo);
3. Rerender handsontable, The cell editor does not work.

### Demo
https://jsfiddle.net/ssbunny/4jrjsuts/

### Your environment
* Handsontable version: 0.32.0
* Browser Name and version: Safari 9.0.2
* Operating System: OS X 10.11.2

Seems to be due to `instance` can not get the latest `editorClass` when calling `getCellEditor`.(in prepareEditor, editorManager.js)

**Comment by AMBudnik** [comment]
Thank you for sharing @ssbunny 
I have replicated the issue. It seems like something missing there, as it works when we call the `updateSettings` to change `cell` like here https://jsfiddle.net/ky0sr2Ln/

**Comment by aninde** [comment]
Not repaired by 7.4.0 https://jsfiddle.net/aninde/820fsdeL/
For testing after cellMeta Refractor.

**Comment by AMBudnik** [comment]
**Solved in beta2** - https://jsfiddle.net/w1tfmdkn/ (`8.0.0-beta2-rev19`)
8.0.0-beta1 https://jsfiddle.net/w1tfmdkn/1/ broken
7.4.2 https://jsfiddle.net/w1tfmdkn/2/ broken

**Comment by pnowak** [comment]
Hi @ssbunny 

I have good news! We've just released 8.0.0-beta2 that fixes the mentioned issue. We won't be closing this ticket now. It will be closed after we release the final 8.0.0 version of Handsontable.

Here’s a full list of changes https://github.com/handsontable/handsontable/releases/tag/8.0.0-beta.2
NPM https://www.npmjs.com/package/handsontable/v/8.0.0-beta.2
 
All feedback's appreciated. Thank you for your input.

**Comment by AMBudnik** [comment]
Hi @ssbunny 

I’m glad to announce that Handsontable v8.0.0 that solves this issue is live!   

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases  

I highly encourage you to test the new version and leave some feedback. I hope that the amount of work that we put on the v8 will help you to improve your project.
