### ISSUE TITLE
Sheet scrollbar bounce in IE

### ISSUE THREAD

**Issue by arrdev** [handsontable/handsontable#4385]
### Description

On Internet Explorer when Handsontable is loaded with a large number of rows a fast top to bottom scroll of the sheet executed via grabbing the scrollbar box with the mouse, moving it to the bottom of the scrollbar area, and releasing it causes the scrollbar box to bounce back to the top of the table.  After the bounce the first rows in the table are displayed.

What should happen is that the scrollbar box will stay at the bottom of the scrollbar and the last rows in the table should be displayed.

### Steps to reproduce

1. Start Internet Explorer
2. Load a table with a large number of records (100,000+ rows, 30+ columns).
3. Table is styled with a vertical scrollbar. 
4. Using the mouse grab and quickly drag the scrollbar box from the top to the bottom of the scroll bar.  Release the scrollbar box.
5. The scrollbar box will bounce back to the top of the scroll area and the table will still display the first rows in the table.

### Your environment
* Handsontable version: latest pro
* Browser Name and version: Internet Explorer 11
* Operating System: Windows 10, Windows 8, Windows 7

**Comment by AMBudnik** [comment]
Hi @arrdev 

I think that the issue may be related to one of those two:
1. https://github.com/handsontable/handsontable/issues/4320
2. https://github.com/handsontable/handsontable/issues/4276

ps. IE is really slow and I do not recommend loading 100k rows without pagination.

**Comment by swistach** [comment]
Hi @arrdev.
In the current version of Handsontable, you should be able to scroll table in the way as you described.
Moreover, IE and Edge have an issue with elements bigger than ~1533917px.

Other libraries with a similar problem with support for huge elements:
https://github.com/codemirror/CodeMirror/issues/3757
https://github.com/aurelia/ui-virtualization/issues/30

**Comment by AMBudnik** [comment]
Hi @arrdev 

As [support for the Internet Explorer browser is to be deprecated in version 8.0.0](https://github.com/handsontable/handsontable/issues/7026) we decided to close all the issues that are only replicable on that browser. All IE-related workarounds implemented into Handsontable are still a part of the code, and we do not plan to remove them.

This issue is closed as **solved** as it does not cause any of the mentioned scrolling issues.

Tested on Windows 10
<img width="153" alt="edge_ver" src="https://user-images.githubusercontent.com/10757813/85011840-69504100-b162-11ea-92b4-6cba9d3eb761.png">

Tested version of Handsontable 8.0.0-beta2-rev15
