### ISSUE TITLE
Cannot Copy & Paste in Bootstrap Modal

### ISSUE THREAD

**Issue by cgatesman** [handsontable/handsontable#4412]
I am unable to copy and paste in a Handsontable when it is in a Bootstrap Modal.

Here is a jsfiddle demonstrating this using the latest Handsontable (0.33.0): https://jsfiddle.net/cgatesman/gxgxc217/

**Comment by swistach** [comment]
Hi @cgatesman,
I found this solution on the bootstrap' issue board: https://github.com/twbs/bootstrap/pull/12142#issuecomment-37618123
I've tried their solution and it's work properly: https://jsfiddle.net/657zdp8q/
I recommend you to use official solution.

**Comment by cgatesman** [comment]
Thanks for the additional info, @swistach.

I feel like the proper way for Handsontable to solve this would be to keep the CopyPaste textarea local to where the Handsontable div is (an immediate sibling?)--instead of out at the end of the `body` element.  I don't know if there is a strong reason for HOT to reuse this div if there are multiple HOT tables on a page...that could be a gotcha with this solution.

**Comment by swistach** [comment]
No problem.
Actually, it's not our fault. It's not bootstrap-ui authors fault too. It's an usual issue when many independent libraries running with use of preventing of the events.
We shouldn't overwrite more complex logic of the event preventing in the external libraries. In this case, they do it because of accessibility (click one of links in my last reply to find more complex explanation).
We append textarea element once per `document.onready` and we wouldn't like to manipulate an element.
Additionally, `Textarea` in `CopyPaste` is running as a Singleton and we haven't to care anymore to make a relation between each hot instance and our single textarea element. In my opinion this solution is really good.
I think we can close this issue. Feel free to reopen this issue, if you notice this bug occurs.
