### ISSUE TITLE
after autofill, how can i konw the direction ? 

### ISSUE THREAD

**Issue by aRealCat** [handsontable/handsontable#4466]
foe example,  i fill  row:0  to  row:5   ( col:3 ) ,  after  autofill , i want to konw the direction  is  vertical or another  direction  .

**Comment by AMBudnik** [comment]
Hi @aRealCat 

you can use the `beforeAutofill` hook's parameters of `start` and `end` coordinates. 
here is an example http://jsfiddle.net/2g3bj3zx/

**Comment by agreene-coursera** [comment]
Is there a solution that works in the case of dragging a cell only one space? In the `beforeAutofill` hook `start` and `end` coords are identical meaning comparing them is useless. I was looking into the `beforeAutfillInsidePopulate` hook but since all of it's coordinate values seem to be relative it doesn't have the information necessary for my usecase.

**Comment by AMBudnik** [comment]
Hi @agreene-coursera 

can you share a demo or a draft of the scenario? I am not sure what you would like to allow/block.
