### ISSUE TITLE
1.8.0   copy/paste  no work 

### ISSUE THREAD

**Issue by aRealCat** [handsontable/handsontable#4478]
### Description

Hello. i try to use contextMenu  copy/paste , but it didn`t work.    can only use ctrl +c/v .
How to solve ?    Thanks. 

### Your environment
* Handsontable version:1.8.0      /nghandsontable
  chrome

**Comment by aRealCat** [comment]
konw, copy can work,  but paste no work ,   by contextMenu

**Comment by AMBudnik** [comment]
Hi @aRealCat 

due to security reasons, reading from the clipboard is not possible that is why the paste button doesn't work from external data sources. Most of the bigger solutions like Kendo or FlexGrid also do not allow to paste data from an external data source. However, you can use key shortcuts. The key shortcuts are handled by the system so we are just switching on an ability to paste the data into the spreadsheet.

**Comment by aRealCat** [comment]
@AMBudnik   thanks your answer,
can ZeroClipBboard.js / .swf   solve ?

**Comment by AMBudnik** [comment]
I do not think so, however, we did not dig deeper into the subject. Maybe there is a way to do it

**Comment by swistach** [comment]
Hi @aRealCat,

> can ZeroClipBboard.js / .swf solve ?

Unfortunately not.

But, you can prepare your own browser extension. Extension can be used to read directly from the system clipboard.
Chrome: https://gist.github.com/srsudar/e9a41228f06f32f272a2 (unfortunately I've not found official example)
Firefox: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Interact_with_the_clipboard
In IE you can read directly from clipboard: `window.clipboardData.getData('Text')`
I found not working solution for Edge.
I don't know how it could work in Safari and Opera, you have to check this by yourself :)

**Comment by aRealCat** [comment]
Hi @AMBudnik  @swistach   , thanks your answer.
I have seen that have already solved in 1.13.0        https://docs.handsontable.com/pro/1.13.0/demo-copy-paste.html
In 1.8.0  . can achieve  by the same way or another way ?
