### ISSUE TITLE
Cell deleted on double-click when there's a dot in the column name

### ISSUE THREAD

**Issue by stla** [handsontable/handsontable#4487]
Hello, 

Fiddle: <https://jsfiddle.net/stla/m4x4yx5p/>

When one double-clicks on a cell in the column `"a.a"`, the content of the cell disappears.

**Comment by AMBudnik** [comment]
Hi @stla 

I couldn't replicate the issue. Does the Fiddle contain all the code you wanted to share?

I have added the dot to the example above https://jsfiddle.net/handsoncode/m4x4yx5p/1/ still wasn't able to erase the content as you wrote (by dbclicking).

I have tested it on Chrome 60/ Windows 10

**Comment by stla** [comment]
Sorry, here is the good fiddle: <https://jsfiddle.net/stla/m4x4yx5p/2/>

**Comment by AMBudnik** [comment]
Thank you. I have replicated the issue and simplified the example at https://jsfiddle.net/handsoncode/qf804nvj/

I guess that the `columns` are looking in this case for the nested object `a` key from `a`.

**Comment by swistach** [comment]
Hi @stla,
It's not a bug. Dot-notation is necessary to finding nested keys in dataset. That means you shouldn't define an array of objects with dots inside the keys: https://jsfiddle.net/nq7mdj90/
Otherwise you have to prepare custom editor: https://jsfiddle.net/8be2buh6/

In conclusion, we propose to avoid using dot-notation in object keys.
