### ISSUE TITLE
Dropdown behavior after paste value

### ISSUE THREAD

**Issue by mkhoa1412** [handsontable/handsontable#4595]
### Description
I have a Location dropdown field, try to copy location name  and paste them in screen. If pasting value match data source, i want to recognize input value as location. And if not match, the dropdown should show candidates and let user choose correct one.
I means, dropdown behavior after paste value exactly like after  edit and input value on dropdown.
### Your environment
* Handsontable version: 1.13.1
* Browser Name and version: Chrome Version 61.0.3163.100 (Official Build) (64-bit)
* Operating System:

**Comment by AMBudnik** [comment]
Hi @mkhoa1412 

I am not sure what you would like to achieve. Can you share a draft or a drawing?

**Comment by mkhoa1412** [comment]
Hi @AMBudnik . please view a demo at http://gph.is/2hcjW1y
I'm using google sheet dropdown for demo.
I have a dropdown with source: 'Ho Chi Minh', 'Yokohama', 'Yokosuka'
If i paste text 'Ho Chi Minh' i need dropdown recognize it.
If i paste text 'Yoko' , dropdown should show list 'Yokohama', 'Yokosuka' for user choose one.
How can i do that on Handsontable

**Comment by comictvn** [comment]
I also same issue

**Comment by AMBudnik** [comment]
Thank you for the demo.

It won't be that easy, as pasting doesn't open cell editor. And instead of a `['Yokohama', 'Yokosuka']` list while pasting `Yoko` you get an invalid `Yoko` cell.

![2gif](https://user-images.githubusercontent.com/10757813/32597057-bce03738-c535-11e7-990c-91bbba2d1727.gif)

However, when we edit a cell the list opens and the `['Yokohama', 'Yokosuka']` are highlighted.

**Comment by mkhoa1412** [comment]
@AMBudnik , thank you for your suggestion.
