### ISSUE TITLE
Formulas performance issue 

### ISSUE THREAD

**Issue by comictvn** [handsontable/handsontable#4600]
### Description
Our table have about 300 columns and 1000 rows. I have to use formulas for about 100 columns but it render very slow

### Your environment
* Handsontable version: 1.13.1
* Browser Name and version: Chrome
* Operating System: MacOS

Can you help ?

**Comment by AMBudnik** [comment]
Hi @comictvn 

I can check your example but a number of used formulas is really big and I am afraid that I won't be able to speed it up significantly

**Comment by AMBudnik** [comment]
I assume that we can close the issue as there is no reply for more than 20 days.

Feel free to leave a comment though if you still experience the same issue.

**Comment by makdv** [comment]
Hi there. 
1. There is an issue with =IF() formula as it's evaluates both expressions (for true and false) : IF(ISNUMBER(A1);A1/0;"");  - even if A1 = false, the result will give DIV/0 error instead of ""
2. How is it possible to use recalculateOptimized method ? If here are several hundread of cells with formulas, which depend on 1 cell , it takes ages to update,  spreadsheet just hangs

**Comment by AMBudnik** [comment]
Hey @makdv 
the `DIV/0` has been already mentioned here https://github.com/handsontable/formula-parser/issues/36 (open bug report).
When it comes to the performance we'd need to wait for the new formula engine and the eco-rendertsl

**Comment by makdv** [comment]
Hi @AMBudnik , thanks for the reply. So at some point the new formula engine will be rolled out ? -That's good. In meantime is there any way to work with a spreadsheet, which is using many formulas ? 
I saw "recalculateOptimized" method, but it's not clear how it can be used. While debugging I saw the spreadsheet evaluates EACH cell with formula, parses it and probably recalculates and all this freeze the UI ( in my case I had like 400 cells with formulas mentioned above and some cells with SUM). The only idea I have for now to overcome that is to create a custom method, which will make  calculations and  "setDataAtCell" only for particular cells, instead of using formulas.

**Comment by AMBudnik** [comment]
It is strictly connected to the way we pass data and how many times we call the renderer - that's why I've mentioned the eco-renders. We're finished [refactoring the core](https://github.com/handsontable/handsontable/pull/6089) (Walkontable) and will move on with improving the performance once we refactor how metadata are handled. Currently, once you trigger a change, each cell is being rerendered. In the future only changed (or chosen by the developer) cells will get a new render.
