### ISSUE TITLE
[0.28.0+] columnSorting: true breaks an ability to freeze columns properly.

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#4601]
### Description

`columnSorting: true` breaks an ability to freeze columns properly.

### Steps to reproduce

1.  Freeze column `D`

![gif](https://user-images.githubusercontent.com/10757813/32596156-9ccee352-c532-11e7-92e9-f8464e4cd12a.gif)
**Result**: Column `C` is frozen.

### Demo

http://jsfiddle.net/x2dkeyLh/

### Your environment
* Handsontable version: 0.43.5
* Browser Name and version: Chrome 62
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
The issue remains the same in version 0.35.1 http://jsfiddle.net/67afmhpm/

**Comment by AMBudnik** [comment]
The issue was produced by v `0.28.0` http://jsfiddle.net/tq9of0s5/
Here's version `0.27.0` http://jsfiddle.net/zvewm0he/

RN for `0.28.0` https://docs.handsontable.com/0.28.0/tutorial-release-notes.html

**Comment by AMBudnik** [comment]
It still works the same in v 5.0.1

**Comment by AMBudnik** [comment]
Still the same in v `6.0.1.`. Update demo http://jsfiddle.net/handsoncode/xatnsj1b/

**Comment by wojciechczerniak** [comment]
Looks like when `columnSorting` enables `observeChanges` the `updateSettings` disables `manualColumnMove` which is used by `manualColumnFreeze` 😓  to move and freeze the column.

Will be solved when we remove `observeChanges` from sorting plugins. Part of:  #5442,  #5649

**Comment by aninde** [comment]
In `8.0.0.-rc1` ` freezing column` with `column sorting` is fixed, but there is an additional error, which is repeated in the version 7.1.1.
1. There is a double border between column headers at index 0 and 1.
Appears when:
column 0 and column 1 are fixed.
columns 0 and column 1 are frozen.
fix + freeze combination on columns 0 and 1.
Same like in  [#5881](https://github.com/handsontable/handsontable/issues/5881), where it is caused by hiding column at index 0. 
@wojciechczerniak @wszymanski could you take a look at this?

Demo: http://jsfiddle.net/aninde/gLfj8qca/
![ #4601-8 0 0rc1](https://user-images.githubusercontent.com/30186818/65133330-b4d29480-da02-11e9-9a57-65a882ebac99.gif)


In `7.1.1.`  it still works the same with a bug. There is a double border, the same as above.
Demo: http://jsfiddle.net/aninde/v8a0ts1x/

![#4601-7 1 1](https://user-images.githubusercontent.com/30186818/65133164-74731680-da02-11e9-8efa-e213496c4c1f.gif)

**Comment by wojciechczerniak** [comment]
The bug with border is described here: #5881. Was in the previous versions, CSS is missing and it's not related to indexes. One bug fix at a time 😅

**Comment by aninde** [comment]
Yes, bug described here, in #4601, will be fixed by the new `index mapper.`

**Comment by AMBudnik** [comment]
Good job guys. It freezes `D` as it should in the 8.0.0-beta1 http://jsfiddle.net/d2v0qLyc/

**Comment by ashalatha279** [comment]
What is the work around for this issue? I will not be able to upgrade the handsontable version as of now. So please provide a work around in older version with column Sorting option on.

**Comment by AMBudnik** [comment]
Here's a demo that uses Handontable v 8.0.0 http://jsfiddle.net/ugp1t7ax/ 
I cannot replicate the same issue so I call this issue solved!
