### ISSUE TITLE
Context menu width isn't calculated properly

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#4658]
### Description
Part of context menu is not calculated properly. DOM element showed on the below screenshot is too wide. @swistach, who changed parts of `Walkontable` for purpose of improving scrolling, has fixed that partially in separate branch. 

![screen shot 2017-12-07 at 10 43 24](https://user-images.githubusercontent.com/141330/33708712-833e4f62-db3b-11e7-8476-63a23b5096d9.png)

**Comment by swistach** [comment]
Width of the `.wtHolder` element is improper, because of incorrect calculations in `wt.viewport.getWorkspaceWidth()`. Changes in `WalkOnTable` is a risk that something else in standalone instance might work different than contextmenu ([contextMenu is always append to document.body](https://github.com/handsontable/handsontable/issues/4652)). Moreover, it's important, what is a trimming container in calculation moment.

**Comment by AMBudnik** [comment]
Looks the same in v0.35.1

![zrzut ekranu 2018-01-31 o 11 07 18](https://user-images.githubusercontent.com/10757813/35616979-263af204-0677-11e8-96df-45ef4c9a4b31.png)

**Comment by AMBudnik** [comment]
The same in v 5.0.1

**Comment by AMBudnik** [comment]
![image](https://user-images.githubusercontent.com/10757813/104289282-39c7a400-54b9-11eb-8149-f095d4fac281.png)

This issue is no longe rreplicable in 8.2.0 
Tested in JSFiddle and on the website with Chrome 87 on Windows 10.
