### ISSUE TITLE
AVERAGE formula updates incorrectly

### ISSUE THREAD

**Issue by euggra** [handsontable/handsontable#4675]
### Description

When cell values are changed, the AVERAGE formula's recalculation is incorrect.

### Steps to reproduce

See instructions in JS Fiddle below.

### Demo

http://jsfiddle.net/euggra/z3aex4xx/

### Your environment
* Handsontable version: 1.15
* Browser Name and version: Safari 11.0.1
* Operating System: OS 10.13.1

**Comment by AMBudnik** [comment]
Thank you for sharing the bug. 

ps. We have published Formula Support on HAndsontable PRO but please remember that it is an alpha stage plugin and we do not recommend using more complicated calculations on production.

**Comment by AMBudnik** [comment]
It still doesn't count properly (tested on [v`5.0.1`](http://jsfiddle.net/2c43kq5e/))

But also sometimes you can get a `#NUM!` error. I have used the same demo as the one above and typed `2` in the first 3 cells. The result in 5th line (`Average`) should be `2` but I got `#NUM!`.

![image](https://user-images.githubusercontent.com/10757813/44724359-b9b06780-aad2-11e8-9b22-80cac84be944.png)

**Comment by jacekbogdanski** [comment]
I can also reproduce the issue with `#NUM!` using very simple initial settings: https://codepen.io/jacekbogdanski/pen/NWWYqJy

It seems to work fine if you pass data as `data: [ ... ]` configuration option, however, typing by hand results in error:

![average](https://user-images.githubusercontent.com/10279586/68213352-b28cbf80-ffdb-11e9-895f-983c7ddc3697.gif)

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **New formula plugin** task reported at https://github.com/handsontable/handsontable/issues/6466

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Comment by aninde** [comment]
This issue will be fixed by the new formulas engine in v.9.0.0 http://jsfiddle.net/aninde/y28pdwmk/ with [HyperFormula](https://handsontable.github.io/hyperformula/).
We currently test this version. 

![Kapture 2021-05-21 at 12 05 34](https://user-images.githubusercontent.com/30186818/119120880-14314500-ba2d-11eb-99af-968254eefe72.gif)

**Comment by AMBudnik** [comment]
I've also tested the case with the latest build for v9 http://jsfiddle.net/6eq1uyv3/3/
It works as expected, so I'm temporarily open the topic to close it after the official version of v9 is released.

**Comment by AMBudnik** [comment]
@aninde it **works well** in v9 (freeze) http://jsfiddle.net/h6y5gs4b/

**Comment by AMBudnik** [comment]
Hi @euggra @jacekbogdanski 

Good news! We just release Handsontable v9 with the fix for this issue included.

For everyone interested, here is a list of changes for the following version https://handsontable.com/docs/9.0.0/tutorial-release-notes.html and here https://handsontable.com/docs/9.0.0/tutorial-migration-guide.html is a migration guide (from v8 to v9)
