### ISSUE TITLE
[0.28.0+] Problem when undo removed row with a readOnly column

### ISSUE THREAD

**Issue by alexon1234** [handsontable/handsontable#4754]
### Description

When you undo a removed row with a readOnly column, the array of changes does not contain the readOnly cell deleted

### Steps to reproduce

1. You have a readOnly column
2. You remove a row
3. You undo de removed row
4. You do not see the information of the readOnly column

### Demo
https://jsfiddle.net/oe6v4c9w/

### Your environment
* Handsontable version: The same version as the one from the handsontable example
* Browser Name and version: Chrome 63.0.3239.132
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Thank you for sharing the issue @alexon1234 

I have replicated it

**Comment by alexon1234** [comment]
Same Issue in #4491

**Comment by AMBudnik** [comment]
Thank you @alexon1234 
I thought that I saw a similar issue somewhere.

**Comment by alexon1234** [comment]
Hello, 
Do you have any estimation on when this bug will be solved?

**Comment by AMBudnik** [comment]
Hi @alexon1234 

undo/redo plugin has to be refactored. I am not sure if we will be fixing bugs before we to the refactoring.

**Comment by AMBudnik** [comment]
Last working [version was `0.27.0` ](https://jsfiddle.net/ekuygh63/)so it is a regression in v `0.28.0`

**Comment by AMBudnik** [comment]
Still replicable in v 5.0.1

**Comment by AMBudnik** [comment]
Works the same in v `7.1.0`

**Comment by AMBudnik** [comment]
New feedback from `7.x.x` user

> all fields are blank (not just the read only ones)

**Comment by ope-nz** [comment]
Same experience as @AMBudnik 
Problem is even worse at 7.1.1 as now all fields are blank (not just the read only ones). We have had to stick with 7.1.0.

**Comment by AMBudnik** [comment]
Issue is also replicable in v 8.0.0.-beta1 
Example simplified

![issue](https://user-images.githubusercontent.com/10757813/80182776-ea2e0900-8607-11ea-8f2a-efab47d52b01.gif)

 https://jsfiddle.net/AMBudnik/kt9rbL3w/

**Comment by pnowak** [comment]
This issue is still replicable using v8.0.0. Here's an updated demo - https://jsfiddle.net/grbxd639/

**Comment by AMBudnik** [comment]
This issue is still replicable in v8.2.0 

Interestingly, it works differently with `cell` and `cells` methods.

### Cells
https://jsfiddle.net/handsoncode/znbmkr34/ `cells` method
![cells](https://user-images.githubusercontent.com/10757813/104319337-03058400-54e1-11eb-9ea6-8dc33372974b.gif)
**Result**: `ReadOnly` cells content is gone on undo.

### Cell
https://jsfiddle.net/handsoncode/h5f9dauw/ `cell` method
![cell](https://user-images.githubusercontent.com/10757813/104319460-30eac880-54e1-11eb-9dfe-6bc57e8e0f14.gif)
**Result**: `ReadOnly` cells content is back on undo but it is editable.

### setCellMeta / menu
When we use the `setCellMeta` to add readOnly property we get the same result as with the cell method https://jsfiddle.net/handsoncode/9ea4u72n/ (editable cell). The same effect we get when we use context menu to make the cell readOnly.

**Comment by aninde** [comment]
The exact case described in this issue has been fixed by v8.4.0. Unfortunately the rest of the cases have not been fixed.
Do we need to open a new issue for the unrepaired one to deal with it in the future? WDYT @AMBudnik ?

**Main case**
readOnly set at the column is fixed https://jsfiddle.net/txa2z83L/
Undo works correctly after removal and returns readOnly cell
![main-case-4754](https://user-images.githubusercontent.com/30186818/117171174-ef9d6200-adca-11eb-9559-55f6c851ea03.gif)

**Cells case**
readOnly set at cells is fixes
https://jsfiddle.net/8jbLm3ks/
![cells-4754](https://user-images.githubusercontent.com/30186818/117171695-63d80580-adcb-11eb-9b88-a101b4a8f658.gif)


**Cell case**
Still broken
https://jsfiddle.net/meLx3bad/

**setCellMeta case**
Still broken
https://jsfiddle.net/mbdu53jq/
![cell-4754](https://user-images.githubusercontent.com/30186818/117172190-d9dc6c80-adcb-11eb-89c5-9ff6e6c34f52.gif)

**Comment by AMBudnik** [comment]
Hey @aninde, I've transferred the unsolved cases to https://github.com/handsontable/handsontable/issues/8008.

@alexgann I'm closing this issue as solved. Please update to v8.4.0 and let me know if it works for you.
