### ISSUE TITLE
Zoomed out table doesn't look properly in specific situation

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#4767]
### Description
Within this task are collected cases when zoomed out table is misaligned.

### Steps to reproduce case 1
1. Open demo with Google Chrome and zoom set to `90%` or lower (sometimes it works correctly, just go on with trying values which will break the table).
2. Take a look at borders of headers.

**Zoom set to 80%**

![screen shot 2018-02-01 at 08 29 34](https://user-images.githubusercontent.com/141330/35666382-196fbcf4-072a-11e8-8ada-789b2e163b86.png)

**Zoom set to 50%**

![screen shot 2018-02-01 at 10 08 30](https://user-images.githubusercontent.com/141330/35670198-19d7626a-0738-11e8-89b7-f8b3be58a65c.png)

### Steps to reproduce case 2
1. Open demo with Google Chrome and zoom set to 90% or lower (sometimes it works correctly, just go on with trying values which will break the table).
2. Paste some long text to the table, for example from: https://pastebin.com/raw/uWW9TP92
3. Scroll down to a row below the viewport.
4. Take a look at the position of cells.

![screen shot 2018-02-01 at 08 40 49](https://user-images.githubusercontent.com/141330/35666800-aac4d2ec-072b-11e8-8f42-194d2b66e290.png)

### Demo
http://jsfiddle.net/whz5p7ty/3

### Your environment
* Handsontable version: 0.35.1, <= 0.32.0
* Browser Name and version: Google Chrome 63.0.3239.132
* Operating System: macOS Hight Sierra 10.13.2

**Comment by wszymanski** [comment]
Maybe related to #3118.

**Comment by wszymanski** [comment]
I've found the yet simpler example. It's not related to the viewport: http://jsfiddle.net/p9dyp1zd.

**Comment by krzysztofspilka** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fixing behavior for zoom-in/zoom-out](https://trello.com/c/wX0GL5Tc/108-fixing-behavior-for-zoom-in-zoom-out)

**Comment by wszymanski** [comment]
When zoom is set to `80%` there is also a problem with some cell's height. Cell with value `AAAA
AAAA` is too hight (shown in below image).
![screen shot 2018-02-06 at 14 03 51](https://user-images.githubusercontent.com/141330/35861114-dd10118e-0b46-11e8-8ea2-9fe8d7e43308.png)

**Comment by krzysztofspilka** [comment]
@wszymanski  Possibly it's connected with #3618 as well.

**Comment by wszymanski** [comment]
@krzysztofspilka Good case, I can replicate similar situation when zoom was set to `90%` or lower. It can be simplified yet (it's problematic event without `fixedColumnsLeft` and `autoRowSize` settings).

**Steps to reproduce the problem:**

2. Zoom out.
2. Go to http://jsfiddle.net/4jscano9
3. Open any cell and enter two lines there (e.g. "A1" ALT+Enter "B"). 
4. Confirm change.

As the result height of edited cell isn't proper.

**Comment by watnab** [comment]
> Within this task are collected cases when zoomed out table is misaligned.
> Maybe related to #4502, #3118, #3215, #4011, #4000.

It seems better this issue has the label "Core: alignment/height/width".

The title probably should show the intension to collect misalignment cases (when zooming).
It may be something like "(Collecting) The situations where(when?) zoomed out table doesn't look properly".

It's good there is a ticket to grasp, because there are so many issues.
It's hard for me to detect whether the issues are duplicated or not.

**Comment by AMBudnik** [comment]
The table looks good for `90%` (tested on Chrome) for v 0.38.1

![image.png](https://images.zenhubusercontent.com/5a96b5784b5806bc2bc8c7df/3a3862d1-afb3-4aff-b155-7e22873dd367)

but `80%` looks like this

![image.png](https://images.zenhubusercontent.com/5a96b5784b5806bc2bc8c7df/23868f0c-1e71-44c2-beae-273aa15c93c9)

Here is a look for `50%`. 

`50%` for v 0.38.1

![image.png](https://images.zenhubusercontent.com/5a96b5784b5806bc2bc8c7df/75e7ea22-7c51-46de-8e28-c1b3cf6c697d)

`50%` for v 0.35.1

![image.png](https://images.zenhubusercontent.com/5a96b5784b5806bc2bc8c7df/c1cb88ff-b080-4d0a-ab50-c1f89d9c8ec1)

**Comment by AMBudnik** [comment]
All the issue are still replicable in v 5.0.1

**Comment by aarondfrancis** [comment]
I realize this is a very old issue, but we're currently running into some of the same issues when our users zoom out. Weird alignment issues, half-rendered tables, etc. 

It's not too much of a problem because our app is internal, so I can just instruct our employees to not zoom at the moment. Unfortunately though, in Chrome zoom settings are _domain_ wide, which causes some inconveniences elsewhere. Still no biggie, just casting a vote for this issue to be resurrected!

**Comment by wojciechczerniak** [comment]
It's not dead! We just had to move the focus on tasks that will let us finish it afterward. There are so many places that the half a pixel (box-sizing, font sizing, line heights) changes all the calculations results that we have to fix them first. Step by step it will look better and in the end, we will finally close this issue.

@aarondfrancis It might be possible to use `<meta name="viewport" content="initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />` on some pages to avoid domain-wide Chrome settings? By no means I consider this as a solution or a workaround, just a thought for your use case and inconveniences.

**Comment by aarondfrancis** [comment]
> There are so many places that the half a pixel (box-sizing, font sizing, line heights) changes all the calculations results that we have to fix them first.

That sounds like a nightmare 😂 Good luck!

**Comment by swistach** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of Interoperability problems using zoom/system UI scaling and some core features task reported at #7527 

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behaviour feel free to contact me at

**Comment by AMBudnik** [comment]
Hi @watnab I know that it is been a long time since we discussed this topic. But I was investigating the misalignment issue and found our that the newest version of Handsontable looks good on the newest browsers. Did you notice any changes in your application?

**Comment by watnab** [comment]
Sorry, I don't investigate it now.
