### ISSUE TITLE
Tasks to be done for non-contiguous selection (phase 2)

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#4817]
### Description

This is a list of tasks to be done for the second phase of an implementation of non-contiguous selection:

***Resizing***
- Integrate with row resize - should resize all selected rows,
- Integrate with column resize - should resize all selected columns,

***Copy - cut - paste***
- Integrate with cut - it should allow to copy/cut two or more areas and paste them somewhere else. It should skip the empty columns and rows.

***Moving***
- We should DISABLE the UI for moving rows/columns when non-contiguous columns (or rows) are selected.

***Merging***
- General idea: We should HIDE the merging option when the context menu is invoked for headers of rows or columns.

***Auto-fill***
- We should HIDE the auto-fill handle when non-contiguous selection is detected.

***Checkbox***
- When multiple checkbox-type cells are selected, then by pressign <kbd>SPACE</kbd> we should be able to check/uncheck options.

***Hiding columns and rows***
- We should **handle** the hiding option when non-contiguous selection is detected.

***Fix***
- Fix selected headers, especially for Nested Headers option (Pro)

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **Selection grouped issue** task reported at https://github.com/handsontable/handsontable/issues/7514

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com
