### ISSUE TITLE
Multiple issues on mobile devices to be fixed

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#4829]
### Description

In the past, we developed three plugins which helped us with displaying Handsontable on mobile devices. It seems that at least some of them, don't work anymore. Please find below the list of current issues. All have been tested on handsontable.com/features and /examples on iOS (but we should make sure that it works for Android as well).

1. Rows are not being added properly while swiping down
2. When swiping with momentum, sometimes Handsontable "flies away" and only headers appear after some time - [link](https://css-tricks.com/snippets/css/momentum-scrolling-on-ios-overflow-elements/)
3. Remove the mobile editor (basically a pop-up that helps with editing and navigating on small screens)
4. To be confirmed: users cannot click on hyperlinks in cells (type:html) when viewing Handsontable on mobile devices
5. Selection for mobile devices should work as before `0.16.0`.

### Demo

https://handsontable.com/features

### Your environment
* Handsontable version: 0.36.0 / 1.16.0
* Browser Name and version: Chrome 64
* Operating System: macOS

### Connected tasks
* #4624 
* #4570 
* #4564 
* #3399

**Comment by wszymanski** [comment]
![img_0003](https://user-images.githubusercontent.com/141330/36526167-6bf38bac-17ad-11e8-8fda-fb6697f528b9.PNG)

**Comment by wszymanski** [comment]
Ad 1.

It hasn't worked properly since the beginning of Handsontable. Just found a difference in displaying the number of cells between Handsontable `0.15.0` and Handsontable `0.16.0`. The easiest example of `100 x 100` elements.

![img_0010](https://user-images.githubusercontent.com/141330/36531688-042a48d2-17bf-11e8-8c42-9cf5df96721a.PNG)
![img_0009](https://user-images.githubusercontent.com/141330/36531689-04420e86-17bf-11e8-90a5-53afd466dd4c.PNG)

**Comment by wszymanski** [comment]
The second problem was probably fixed within #4856. I can not reproduce the error again.

**Comment by wszymanski** [comment]
Ad. 4 Confirmed. Will be fixed within #4570.

**Comment by krzysztofspilka** [comment]
Looks good to me.
