### ISSUE TITLE
Merged Cells + selection causes improper merge cell highlight.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#4859]
### Description
After merging the Merge Cells plugin and changes in selections to the current `develop` (pre-0.37.0) branch, there seems to be a problem with the color of highlight of the merge cells.

### Steps to reproduce

1. Go to http://jsfiddle.net/js_ziggle/ubctt86o/2/
2. Select cells from `B1` to `B2`
3. Holding the <kbd>cmd/ctrl</kbd> key, select cells from `F1` to `F2`

**Result:** The `F2` cell has a darker highlight color than `B2`, which is not a desired behavior.

### Demo
http://jsfiddle.net/js_ziggle/ubctt86o/2/

**Comment by AMBudnik** [comment]
Same or related to https://github.com/handsontable/handsontable/issues/4940

**Comment by budnix** [comment]
It seems that refactored borders https://github.com/handsontable/handsontable/pull/6157 partially resolve this issue http://jsfiddle.net/hd5eojtL/.

**Comment by AMBudnik** [comment]
Another (simplier example) 

Loaded version `7.2.1` https://jsfiddle.net/0kLsnu27/
Tested on Windows 10 and Chrome 77

**Steps - columns** 
1. Go to the demo
2. Select column `B`

![image](https://user-images.githubusercontent.com/10757813/67282243-9cf2a280-f4d1-11e9-833d-e4a7fb840dab.png)

I guess that in this example we should remove borders from `B1:B3` and get something like this

![image](https://user-images.githubusercontent.com/10757813/67282377-f1961d80-f4d1-11e9-83e1-eab8378f26e2.png)

or even

![image](https://user-images.githubusercontent.com/10757813/67282455-230ee900-f4d2-11e9-8313-d1b60693f1ae.png)

**Steps - rows**
1. Go to the demo
2. Select row `2`

![image](https://user-images.githubusercontent.com/10757813/67282581-610c0d00-f4d2-11e9-9bec-3f5041acb9d9.png)

Option 1
![image](https://user-images.githubusercontent.com/10757813/67282598-6ec19280-f4d2-11e9-8fc9-5b9b5452f584.png)

Option 2
![image](https://user-images.githubusercontent.com/10757813/67282608-77b26400-f4d2-11e9-9738-9086a0ef41b5.png)

**Comment by aninde** [comment]
The new border drawing method [by svg](https://github.com/handsontable/handsontable/issues/6467) fixed many bugs, but unfortunately not this one.

**Case 1** in the [first](https://github.com/handsontable/handsontable/issues/4859#issue-300946270) description. 
http://jsfiddle.net/x5wkfy8d/1/ `7.2.2 v. with new svg borders` not fixed in 
`Firefox 70`, `Chrome 78` and `Safari 13`, `Brave 1.0.1` and `Opera` on Mac Os Catalina 10.15. and on `IE`, `Edge`, `Edge Dev` on Windows 10. 
There is still issue with different Colors of selection. 

**Result on `7.2.2 + svg borders`**
![Screenshot 2019-12-03 at 13 01 33](https://user-images.githubusercontent.com/30186818/70050203-b4dc3c80-15ce-11ea-9668-9716f3a0402d.png)

**Case 2**  [comment](https://github.com/handsontable/handsontable/issues/4859#issuecomment-544924146)
Not fixed
https://jsfiddle.net/9kj7wm8u/1/ not fixed `7.2.2 v. with new svg borders`

**Result `7.2.2 + svg borders`**
![Screenshot 2019-12-03 at 13 08 59](https://user-images.githubusercontent.com/30186818/70050167-a4c45d00-15ce-11ea-97f0-807405c4c68a.png)
![Screenshot 2019-12-03 at 13 08 44](https://user-images.githubusercontent.com/30186818/70050181-aa21a780-15ce-11ea-9610-0ef64c992194.png)

**Comment by warpech** [comment]
Related: https://github.com/handsontable/handsontable/issues/6761

**Comment by AMBudnik** [comment]
Main issue does not change in 8.0.0-beta2-rev13 http://jsfiddle.net/AMBudnik/xswpv8k3/

**Comment by AMBudnik** [comment]
### Bonus case (changed in rev1 of 8.0.0-beta2)
### Steps to reproduce

1. Select column `B`
2. Hold <kbd>CMD/CTRL</kbd> and keep it pressed for step 3
3. Select merged cell

**Result**
![rev21](https://user-images.githubusercontent.com/10757813/87138220-65fe3000-c29e-11ea-9068-b62e64cbe6eb.png)

**Expected Result**
![beta1](https://user-images.githubusercontent.com/10757813/87138329-8a5a0c80-c29e-11ea-8164-d9dc15940fe4.png)


### Demo

https://jsfiddle.net/egp8310k/3/ `7.4.2` (wroking)
https://jsfiddle.net/egp8310k/2/ `8.0.0-beta1` (working)
https://jsfiddle.net/egp8310k/4/ `8.0.0-beta2-rev1` (**first broken**)
https://jsfiddle.net/hvz3cyk6/2/ `8.0.0-beta2-rev21` (still broken)

**Comment by aninde** [comment]
Seems that nothing changed with `v8.0.0` https://jsfiddle.net/aninde/o4dg79mu/
https://jsfiddle.net/aninde/rpku8q4o/

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **MergeCells grouped issue** task reported at https://github.com/handsontable/handsontable/issues/7509

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com
