### ISSUE TITLE
Copy-cut-paste non-contiguous cells

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#4878]
### Description

It should be possible to copy/cut/paste the non-contiguous cells.

### Steps to reproduce

1. Go to https://docs.handsontable.com/pro/1.17.0/demo-scrolling.html
2. Select two non-contiguous ranges
3. Copy/Cut and Paste the data somewhere within the sheet

![screen shot 2018-03-01 at 16 30 32](https://user-images.githubusercontent.com/8048526/36853168-033801d0-1d6e-11e8-89b4-6fcbfe836f5e.png)

### Demo

https://docs.handsontable.com/pro/1.17.0/demo-scrolling.html

### Your environment
* Handsontable version: 1.17.0 / 0.36.0
* Browser Name and version: Chrome 64
* Operating System: macOS

**Comment by ottosson** [comment]
I have the same problem when pasting values to cells from multiple selections:

![sparse-series-paste-bug](https://user-images.githubusercontent.com/3355320/70226488-3a87f580-1751-11ea-96ad-c4d49e36a76d.gif)

**Comment by AMBudnik** [comment]
Works the same in 7.4.2 https://handsontable.com/docs/7.4.2/demo-scrolling.html and 8.0.0-beta2-rev15 https://jsfiddle.net/AMBudnik/981dac3m/

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **Selection grouped issue** task reported at https://github.com/handsontable/handsontable/issues/7514

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Comment by Serrrek89** [comment]
Note to @AMBudnik to open and close when https://github.com/handsontable/dev-handsontable/issues/556 is ready ;)

**Comment by adrianszymanski89** [comment]
Hi @KiddoV 

Not yet. We are currently focusing on other projects. You can check what's on our roadmap here to see what we are/will be working on: https://handsontable.com/docs/javascript-data-grid/roadmap/
