### ISSUE TITLE
Disable moving non-contiguous columns or rows

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#4879]
### Description

It should be prohibited to move columns (using the UI) when there is a non-contiguous selection.

### Steps to reproduce

1. Go to https://docs.handsontable.com/pro/1.17.0/demo-moving.html
2. Select two non-contiguous columns or rows
3. Move one of them

### Demo

https://docs.handsontable.com/pro/1.17.0/demo-moving.html

### Your environment
* Handsontable version: 1.17.0 / 0.37.0
* Browser Name and version: Chrome 64
* Operating System: macOS

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **Selection grouped issue** task reported at https://github.com/handsontable/handsontable/issues/7514

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com
