### ISSUE TITLE
Disable autofill option for non-contiguous selection

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#4880]
### Description

The fill-handle should be hidden when there is a non-contiguous selection detected.

https://docs.handsontable.com/pro/1.17.0/Options.html#fillHandle

### Your environment
* Handsontable version: 1.17.0 / 0.37.0
* Browser Name and version: Chrome 64
* Operating System: macOS

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **Selection grouped issue** task reported at https://github.com/handsontable/handsontable/issues/7514

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com
