### ISSUE TITLE
Hiding non-contiguous rows and columns

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#4883]
### Description

It should be possible to hide non-contiguous columns and rows.

### Steps to reproduce

1. https://docs.handsontable.com/pro/1.17.0/demo-hiding-columns.html#examples
2. Select columns B and H
3. Open context menu and choose HIDE COLUMN option

### Demo

https://docs.handsontable.com/pro/1.17.0/demo-hiding-columns.html#examples

### Your environment
* Handsontable version: 1.17.0 / 0.37.0
* Browser Name and version: Chrome 64
* Operating System: macOS

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **Selection grouped issue** task reported at https://github.com/handsontable/handsontable/issues/7514

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com
