### ISSUE TITLE
Vertical merge of cells in first column change rows heights

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#4907]
### Description
If you try to merge cells vertically on the very left and some of non-merged cells are still available on the right, then rows heights are calculated incorrectly.

### Steps to reproduce
1. Select `A1:A4`
2. Merge selected cells via context menu

### Demo
http://jsfiddle.net/0m89wjnp/

### Your environment
* Handsontable version: 0.15.0+
* Browser Name and version: any
* Operating System: any

**Comment by AMBudnik** [comment]
Related https://github.com/handsontable/handsontable/issues/3837
When we add `rowHeaders: true` the table looks as expected.

**Comment by AMBudnik** [comment]
![2gif](https://user-images.githubusercontent.com/10757813/45156292-0e906400-b1de-11e8-977f-d9aacb2e2c58.gif)

It still works the sam ein v `5.0.1`

**Comment by AMBudnik** [comment]
Updated demo (8.0.0-beta1) http://jsfiddle.net/AMBudnik/g0v1fkur/ but the effect stays the same.

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **MergeCells grouped issue** task reported at https://github.com/handsontable/handsontable/issues/7509

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com
