### ISSUE TITLE
Column reordering not working properly with an empty data source or not valid objects in columns.

### ISSUE THREAD

**Issue by MateuszG** [handsontable/handsontable#4926]
### Description
When there is more than 5 columns, then will appear a problem with reordering columns.
Source issue: https://github.com/handsontable/angular-handsontable/issues/60

There is "workaround" place deeply in documentation which solves problem (https://docs.handsontable.com/0.37.0/Options.html#dataSchema) but probably this extra step is unnecessary or maybe library should inform in console about that empty data source need dataSchemaObject.

### Steps to reproduce
1. Type in data to recognize columns 
2. Move the first column to the end
3. Move the last column to the front
![Image of Yaktocat](https://media.giphy.com/media/Ta5Kw0BxqMDSyX0gn8/giphy.gif)

### Demo
http://jsfiddle.net/mateuszg/wpL3vreq/6/

### Your environment
* Handsontable version: 0.37.0
* Browser Name and version: Chrome, 64
* Operating System: Mac

**Comment by AMBudnik** [comment]
Works as expected in `8.0.0-rc1` http://jsfiddle.net/handsoncode/zo3eLj8r/

![abc](https://user-images.githubusercontent.com/10757813/65246593-30aa0b00-daef-11e9-8a83-dcc1ec359fd2.gif)

**Comment by aninde** [comment]
@MateuszG this problem will be fixed by the new `index mapper`. It will be released soon.
We are currently testing a version with many breaking changes, I recommend observing information from issue [#5751](https://github.com/handsontable/handsontable/issues/5751). More about changes in the PR #[5945](https://github.com/handsontable/handsontable/pull/5945).

**Demo**
v. `8.0.0-rc1`
Case 1 http://jsfiddle.net/aninde/49wx5brd/
Case 2 (with set data) http://jsfiddle.net/aninde/n7skev61/

**Comment by AMBudnik** [comment]
Works well in the official beta 8.0.0-beta1 http://jsfiddle.net/rLc4ymgk/

**Comment by AMBudnik** [comment]
I'm glad to see this issue fixed. Updated demo v 8.0.0 http://jsfiddle.net/7ar0em5n/
