### ISSUE TITLE
Touch on row header sometimes doesn't work properly on iPad

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#4934]
### Steps to reproduce

1. Click on a cell from the third column 
2. Click on the row header corresponding to the clicked cell.

Effect on Handsontable >= `0.18.0`

![screen shot 2018-03-14 at 13 28 53](https://user-images.githubusercontent.com/141330/37402403-b57bdf3e-278b-11e8-95ac-01bbfe8fc8fd.png)

Effect on Handsontable <= `0.17.0`

![screen shot 2018-03-14 at 13 28 58](https://user-images.githubusercontent.com/141330/37402408-b9bfef7c-278b-11e8-86f1-8d32a47094fa.png)

### Your environment
* Handsontable version: >= 0.18.0
* Browser Name and version: Safari 10
* Operating System: iOS 10.3.3

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **Interoperability problems using Mobile devices and some core features** task reported at https://github.com/handsontable/handsontable/issues/7520

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com
