### ISSUE TITLE
Selection handles disappear on a mobile device in specific situation

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#4943]
### Description

Selection handle(s) disappear on the mobile device while trying to drag and drop.

### Related issue(s):
1. #4936 

### Steps to reproduce

1. Select a cell.
2. Drag and drop selection handle to another cell.

Effect on Handsontable >= `0.16.0`

<img width="491" alt="screen shot 2018-03-15 at 09 53 53" src="https://user-images.githubusercontent.com/141330/37453070-db8d2222-2836-11e8-92b2-d30eaf4eec45.png">

Effect on Handsontable <= `0.15.1`

<img width="489" alt="screen shot 2018-03-15 at 09 54 08" src="https://user-images.githubusercontent.com/141330/37453077-df20cb00-2836-11e8-9ba8-bfb905c5bdfe.png">

### Your environment
* Handsontable version: >= 0.36.0
* Browser Name and version: Safari 10
* Operating System: iOS 10.3.3

**Comment by wszymanski** [comment]
Must read: https://github.com/handsontable/handsontable/issues/4936#issuecomment-373324606.

**Comment by krzysztofspilka** [comment]
Hey @wszymanski, there are several issues I found when testing this fix. Could you review them and decide whether they are connected with this task or should be treated as separate problems?

- Testing on iPhone 5/SE: When tapping on a row or column header, the editor turns on and the virtual keyboard is being displayed.
- Testing on iPhone 5/SE/iPad: I can't make a selection in JSFiddle. I thought that is a problem with an iframe but @swistach made a demo that proves that it might be something different: http://jsfiddle.net/oz5wvc4h/3/ (just replace the localhost to *.js and *.css).
- Testing in a mobile mode in dev tools: When I played a little bit harder with the demo by dragging the dropping the selection (randomly, very fast), the console warning appears: 
![screen shot 2018-04-06 at 16 04 12](https://user-images.githubusercontent.com/8048526/38425454-322d6fc2-39b4-11e8-9979-8e3998a15977.png)
- Testing on iPad: I know we talked about it before, but I couldn't find an issue for that. When I select any cell and then tap on a header of any other row/column, then I get a selection from that first cell to the last tapped header. You can reproduce it like this:
1. Tap on C4.
2. Tap on a header of a second row.
(Use a real iPad, because I couldn't reproduce it in a mobile mode of dev tools).
- Testing in a mobile mode in dev tools / iPad: There is a selection handle visible from under the header (see the top-left corner). 
![screen shot 2018-04-06 at 16 55 19](https://user-images.githubusercontent.com/8048526/38428278-b8a154c2-39bb-11e8-9039-0102d8afffbe.png)
- Last but not least, I have this vague feeling that the selection works unstable. I think that is the result of the combined issues from above.
