### ISSUE TITLE
Editor doesn't looks good on mobile devices

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#4950]
### Description

After release `0.38.0` editor doesn't look properly.

### Related issue(s):
1. #4911

### Steps to reproduce

1. Open an editor.

### Demo

![image](https://user-images.githubusercontent.com/141330/37098667-bb0e576e-221e-11e8-9d92-22b02c6dcf5a.png)

![image](https://user-images.githubusercontent.com/141330/37098686-cc61954e-221e-11e8-8c41-5a833075bff0.png)

![image](https://user-images.githubusercontent.com/141330/37098707-d82ba482-221e-11e8-8eaa-425d084a7e92.png)

![image](https://user-images.githubusercontent.com/141330/37098763-fb570dc0-221e-11e8-9cc2-74fd9a59c4c6.png)

### Your environment
* Handsontable version: >= 0.38.0
* Browser Name and version: Safari 10
* Operating System: iOS 10.3.3

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **Interoperability problems using Mobile devices and some core features** task reported at https://github.com/handsontable/handsontable/issues/7520

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com
