### ISSUE TITLE
Scroll performance with narrower viewport

### ISSUE THREAD

**Issue by eric-chong-acl** [handsontable/handsontable#4970]
### Description
Hi, we are noticing some scrolling performance issue.  One thing we are noticing (from testing on jsfiddle), it looks like there are some scrolling issue when you have a view port that is narrower than the number columns.  (see fiddles in `Demo` section)

In the fiddles (And the screen capture gif), you notice when you scroll up and down, you can see the cells and headers are jumping up and down as well.

### Steps to reproduce
1. Create a large table that has more columns than the available view port.
2. Scroll up and down, and notice the jumping of cells and lag of scrolling.

### Demo
With narrower view port (headers and cells are jumping)
http://jsfiddle.net/8pajs0oz/
![scrollingwithnarrowviewport](https://user-images.githubusercontent.com/3878330/37992860-bd841544-31c1-11e8-8555-99b26071f2ff.gif)

With wide enough view port for all columns, scrolling is smooth
http://jsfiddle.net/7oom5n4e/
![scrollingwithwideviewport](https://user-images.githubusercontent.com/3878330/37992919-e0b8610a-31c1-11e8-9b11-1a5b6edf3388.gif)

### Your environment
* Handsontable version:
* Browser Name and version: Chrome 65.0.3325
* Operating System: OSX

**Comment by AMBudnik** [comment]
You're right. That is a significant difference.

Thank you for investigation @eric-chong-acl

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **Improve scroll experience** task reported at https://github.com/handsontable/handsontable/issues/4947

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com
