### ISSUE TITLE
Large table view jumps if updated after having been scrolled

### ISSUE THREAD

**Issue by pbadenski** [handsontable/handsontable#4997]
### Description
This is kind of tricky to explain, so bear with me... You need:
 - a large table - large enough so that the overflow is taking a few sizes of the visible area,
 - the table needs to be updated dynamically - by an external process (eg. through `setDataAtRowProp(array...)`).
 - cell widths need to be larger than the column widths

If you scroll into the middle of the overflowed view, while the contents get updated the display will keep jumping left and right.

Hopefully the gif below helps the explanation.. I'm only scrolling slowly, but you can see how the table jumps far from original position.

![2018-04-05 11_21_42](https://user-images.githubusercontent.com/68713/38360944-a8a97e30-38c3-11e8-8adf-6ce4353059ab.gif)

### Demo
http://jsfiddle.net/s6t768pq/1837/

### Your environment
* Handsontable version: 0.38.1
* Browser Name and version: Chrome 65
* Operating System: MacOS 10.13.3

**Comment by AMBudnik** [comment]
Thank you for sharing @pbadenski 

Do I need to do anything more besides scrolling? I'm using Windows so it may be different but I couldn't replicate the issue.

What I found instead is another odd behavior.

![gif](https://user-images.githubusercontent.com/10757813/38368311-4379d5ba-38e5-11e8-9ced-411b0b7e60cb.gif)

(it happens when I scroll to the right and keep my <kbd>LMB</kbd> pushed

**Comment by pbadenski** [comment]
There seems to be a step missing from what I see in your demo. After you scroll to the middle of the overflowed scrolled area you need to select a cell. Already at this point it is likely to start jumping. If not make a tiny horizontal scroll. It should most likely start jumping at this point - gentle scrolling left and right is enough to trigger it.

I just checked, same problem on Windows.

If you can't reproduce I'll try to record a video.

**Comment by AMBudnik** [comment]
You're right @pbadenski 

I kept my focus on checking the row headers while you meant the viewport/cells.
So basically what we want here is an ability to keep the focus on the same viewport even if new data is loaded.

**Comment by pbadenski** [comment]
Yes :) Thanks for putting the effort in trying to understand me :D

**Comment by AMBudnik** [comment]
I have an update on this issue. I'm testing v`6.2.0` on asimple project (any additional styles, one `DIV`).

```js
var box = document.querySelector('.box');

var settings = {
  data: Handsontable.helper.createSpreadsheetData(300, 200),
  colHeaders: true,
  rowHeaders: true,
  fixedRowsTop: 2
}

var hot = new Handsontable(box, settings);
```

and got the same behavior

![gif](https://user-images.githubusercontent.com/10757813/49222486-49b8c280-f3dc-11e8-99cc-618c2ef80281.gif)

**Demo**
[boot-test.zip](https://github.com/handsontable/handsontable/files/2629098/boot-test.zip)

**Comment by AMBudnik** [comment]
It doesn't seem to change in 8.0.0-beta1
[boot-test.zip](https://github.com/handsontable/handsontable/files/4527886/boot-test.zip)

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **Improve scroll experience** task reported at https://github.com/handsontable/handsontable/issues/4947

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com
