### ISSUE TITLE
Merging object cells in a horizontal direction doesn't work

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#5022]
### Description

Merge cells doesn't work when using an autofill option in a horizontal direction. Apparently, this bug occurs only at handsontable.com/examples

### Steps to reproduce

1. Go to https://handsontable.com/examples
2. Merge two cells in the column "Currency"
3. Use a fill handle to populate merged cells to the right

### Demo

https://handsontable.com/examples?manual-resize&manual-move&conditional-formatting&context-menu&filters&dropdown-menu&headers

![kapture 2018-04-11 at 15 55 15](https://user-images.githubusercontent.com/8048526/38621262-cc901a34-3da0-11e8-8a0f-54167c89175f.gif)

### Your environment
* Handsontable version: 2.0.0
* Browser Name and version: Chrome 65.0
* Operating System: macOS

**Comment by AMBudnik** [comment]
It looks like the behavior is caused by object data source. Here https://jsfiddle.net/qw6catpc/we can test (on minimal settings) that when we pass as array the merging is passed via autofill.

![array](https://user-images.githubusercontent.com/10757813/39037587-34e3d508-4481-11e8-95de-349b9f354748.gif)


And here is an object: https://jsfiddle.net/g3cnuzm6/

![object](https://user-images.githubusercontent.com/10757813/39037631-5b507d40-4481-11e8-92b3-da011942a16c.gif)

It doesn't seem to work fine in any of the previous versions. Tested with latest `2.0.0.` and versions as old as `0.15.0`
