### ISSUE TITLE
Can not paste the contents of the system paste board when pasted?

### ISSUE THREAD

**Issue by setWan** [handsontable/handsontable#5045]
@AMBudnik Can not paste the contents of the system paste board when pasted?

**Comment by AMBudnik** [comment]
Hi @setWan 

Do you want to paste a clipboard content by the contextMenu?

**Comment by setWan** [comment]
Hi @AMBudnik
Yes, I want to paste the content of non browsers

**Comment by setWan** [comment]
Hi @AMBudnik 
I want to copy the data from my Excel and paste it into the table

**Comment by AMBudnik** [comment]
Due to security reasons, reading from the clipboard is not possible that is why the paste button doesn't work from external data sources. Most of the bigger solutions like Kendo or FlexGrid also do not allow to paste data from an external data source. 
However, you can use key shortcuts. The key shortcuts are handled by the system so we are just switching on an ability to paste the data into the spreadsheet.

**Comment by setWan** [comment]
thank you very much.

**Comment by AMBudnik** [comment]
You're welcome @setWan 

I think that we can close this topic.
