### ISSUE TITLE
[1.11.0-beta1+] Padding for header names is cut

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5086]
### Description

As reported on [Forum](https://forum.handsontable.com/t/css-regression-header-is-misaligned-between-two-versions/2035) there seems to be a regression with header name padding handling.

Now (`1.11.0-beta1`+) the header is nearly cut
![1d945e28561d467702d2565ea0eca2012a2c158c](https://user-images.githubusercontent.com/10757813/39747922-f3c293ca-52ae-11e8-9c58-456ba93a7815.png)

Before `1.11.0-beta`, (`1.10.2`) the header name has a correct padding.
![72a28f3f66ed0240880edf46f51e6cb59935e981](https://user-images.githubusercontent.com/10757813/39747925-f52c88f6-52ae-11e8-91d7-2a3fd0caffa6.png)

### Steps to reproduce

1. Just load the example to see the gap is smaller

### Demo

http://jsfiddle.net/aq9r7rL4/

### Your environment
* Handsontable version: `1.11.0-beta1`+
* Browser Name and version: Chrome 66
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Works the same in 8.0.0-beta1

**Comment by aninde** [comment]
This issue has been fixed by v8.3.2 http://jsfiddle.net/y15qzeab/.

Tested on 
macOS 11.2.2 (20D80) - Chrome  `88.0.4324.192`, Safari  `14.0.3 (16610.4.3.1.4)`, Firefox `86.0` , Edge `89.0.774.48`, Opera `74.0.3911.203` 
Windows 10 - Chrome  `88.0.4324.192` , Edge `89.0.774.48`, IE `11`, Firefox `86.0`.

**Comment by AMBudnik** [comment]
Thank you, guys. I'm closing this issue as solved in v8.3.2.
