### ISSUE TITLE
CMD + arrow key shortcut behavior

### ISSUE THREAD

**Issue by krzysztofspilka** [handsontable/handsontable#5169]
### Description

On MacOS, <kbd>cmd</kbd>+<kbd>arrow</kbd> should move the selection to the last element in the **data region** (last filled cell in a row/col, then skip to another one or to the end of the row/col). 

Instead, while you keep pressing arrow it selects non-consecutive cells which... feels like playing a SNAKE game;)

**Let's discuss this issue as it is not clear what this shortcut should do.**

![bug-command-shortcut](https://user-images.githubusercontent.com/8048526/41226722-a8a60208-6d72-11e8-8290-3bead83b18a2.gif)

### Steps to reproduce

1.  Go to https://handsontable.com/examples
2. Select cell A1
3. Keep pressing <kbd>cmd</kbd> and start pressing ARROW DOWN / LEFT / RIGHT / DOWN etc.

### Your environment
* Handsontable version: 3.0.0
* Browser Name and version: Chrome 67
* Operating System: MacOS

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **Selection grouped issue** task reported at https://github.com/handsontable/handsontable/issues/7514

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com
