### ISSUE TITLE
Persisted manualColumnMove not restored when using loadData()

### ISSUE THREAD

**Issue by cgatesman** [handsontable/handsontable#5207]
I am using `loadData()` to populate my table from data retrieved through Ajax.  If the table is set up with `manualColumnMove`, `persistentState`, and `minSpareRows = 0`, upon initialization, the table does not restore the saved moved columns.

Debugging, it appears to be an issue with it depending on the fact that the initializing table settings actually contains data.  In my case, it does not until later.  However, I am setting a dataSchema, so I'm not sure why it wouldn't just use that for column initialization.  It shouldn't need actual data.

Here is a JSFiddle demonstrating the issue: http://jsfiddle.net/cgatesman/31Lnhk4p/

**Comment by AMBudnik** [comment]
Thank you for sharing this issue @cgatesman 

The `minSpareRows` shouldn't have any impact on saving the `manualColumnMove` order.

**Comment by AMBudnik** [comment]
This issue is fixed with `8.0.0-beta1` https://codesandbox.io/s/wizardly-hypatia-oko8y
Now the column position is kept after reloading the demo

**Comment by AMBudnik** [comment]
Hi @cgatesman 

I’m glad to announce that Handsontable v8.0.0 that solves this issue is live!   

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases  

I highly encourage you to test the new version and leave some feedback
