### ISSUE TITLE
after insert row the formula calculate wrong

### ISSUE THREAD

**Issue by rianran1993** [handsontable/handsontable#5239]
### Description
after insert row the formula calculate wrong
![bug-formula](https://user-images.githubusercontent.com/22359049/42355560-4806d908-8100-11e8-99f5-17a96f082e45.gif)

### Steps to reproduce

1.
2.
3.

### Demo
http://jsfiddle.net/jk91cd7f/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Thank you for reporting. The same issue has been already reported at https://github.com/handsontable/handsontable/issues/4654 so please track progress to that issue

**Comment by AMBudnik** [comment]
The mentioned issue #4654 is fixed in v9. @iaminvictus1993 please let me know if it works for you after updating to v9

For everyone interested, here is a list of changes for the following version https://handsontable.com/docs/9.0.0/tutorial-release-notes.html and here https://handsontable.com/docs/9.0.0/tutorial-migration-guide.html is a migration guide (from v8 to v9)
