### ISSUE TITLE
Row height incompatible when there're wordwraps

### ISSUE THREAD

**Issue by swk777** [handsontable/handsontable#5241]
just squeeze column  'A' until word wraps
https://jsfiddle.net/58rwf127/4/

**Comment by AMBudnik** [comment]
I believe that you refer to this case

![image](https://user-images.githubusercontent.com/10757813/42433088-06a91b24-834e-11e8-95f9-4cba0d2b68cc.png)

(the row Header is missing).

It looks like the issue is gone when we move scroll to the top and to the bottom. It measns that adding `renderAllRows: true` will solve the issue. Here is an updated demo https://jsfiddle.net/mbnuryvh/

Nevertheless, we shouldn't be forced to enable this option as it can cause performance issues with a large dataset.

**Comment by budnix** [comment]
Probably, in that case, there is missing `autoRowSize` option. Enabling this option overwrites the simplified auto resize mechanizm (implemented in Walkontable) which is less performant but more accurate. I've updated [demo](https://jsfiddle.net/58rwf127/31/) which uses this plugin.
