### ISSUE TITLE
loadData() breaks column filters

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5244]
### Description

As reported at https://forum.handsontable.com/t/loaddata-breaks-column-filters/1763

> After applying column filters and loading new data via loadData(), the filter menu behaves weirdly.

### Steps to reproduce

> 1. Filter column A to hide "Lorem"
> 2. Load new data via the any of the buttons (rerun before pressing another button)
> 
> **Result** for 1st button: The table contains only 1 row, and you can only filter 1 value for column A. No way to display the second column.
> 
> **Result** for 2nd button: The table contains only 1 row, but the filter menu still contains all old value, even those that don't exist in the data anymore
> 
> **Result** for 3rd button: The table contains 2 rows, filters are reset and work properly

### Demo

http://jsfiddle.net/do23rv6x/1/

### Your environment
* Handsontable version: 4.0.0
* Browser Name and version: Chrome 67
* Operating System: Windows 10

**Comment by aninde** [comment]
This bug is fixed partially in v. `8.0.0-rc1`.
Case 1 is fixed, but in case 2 there is still not fixed. 

**Demo**

v. `4.0.0` forked original http://jsfiddle.net/aninde/qrfL7gz1/
clearFormula() has been changed into clearConditions(). This ends up the same result as in above.

v. `7.1.1` http://jsfiddle.net/aninde/e01cf63a/
The bug is still replicable.

v. `8.0.0-rc1` http://jsfiddle.net/aninde/wz846sqe/

**Case 1**  
Button 1 - fixed 
![Screenshot 2019-09-29 at 09 43 49](https://user-images.githubusercontent.com/30186818/65828775-d6533c00-e29e-11e9-9b41-2d673a6d9b0b.png)


**Case 2** 
Button 2 - partially 
Proper data update, improper filters. And focus is on filter in first column (green arrow).
![Screenshot 2019-09-29 at 09 44 42](https://user-images.githubusercontent.com/30186818/65828763-c176a880-e29e-11e9-9c3b-996754f4491a.png)


**Case 3** 
same as in original - works fine

**Comment by wojciechczerniak** [comment]
@AMBudnik mark this as fixed iv `v8`. Case 2 is described in #5859 and not related to index mapper. I propose to move all examples related to #5859 there and keep issues as small as possible.

**Comment by AMBudnik** [comment]
Main case for all the 3 buttons is solved in v8.0.0 http://jsfiddle.net/7o6e2zL3/
as well the case 2

![image](https://user-images.githubusercontent.com/10757813/89787027-1b7e0680-db1d-11ea-9de1-f599400a11c9.png)
