### ISSUE TITLE
Validate on initial table load

### ISSUE THREAD

**Issue by Paul-A-Kavan** [handsontable/handsontable#5283]
I know this has been discussed in some detail previously ( such as #3676 ) but I think the discussion should be extended. I'm going to describe the issue as I see it but perhaps there is already a way to achieve validation on initial rendering of a table that I am after. 
<br/>
Validation is performed after cell changes are made but when invalid data is pre-populated in the table the cells are not validated until the user clicks the cell and fires an onChange mechanism. Would it be possible to introduce a table setting such as "validate_on_initial = true/false" that would call the validators when the table is rendering the first time?
<br/>
I think this would be a good idea because there are many use cases where a table is initialized with invalid data. And unfortunately, the only fix I could find for this is to run validateCells such as in this example http://jsfiddle.net/q92om1w2/4/. The problem with this is that for larger tables you can actually see the table load up without validation and then a moment later the validation queue starts emptying and the cells turn red as you watch.

**Comment by AMBudnik** [comment]
Hi @Paul-A-Kavan 

That would be a breaking change and our core mechanisms would need to be modified but... I think that this is a neat idea. Lots of online forms have this functionality since web 2.0 so we can also think about adding it to Handsontable.

I believe that as the editor stays open we do not need to work on the renderer level (which usually related to performance issues and complicated workarounds) so it shouldn't be too complicated.

**Comment by AMBudnik** [comment]
related https://github.com/handsontable/handsontable/issues/3101

**Comment by AMBudnik** [comment]
This feature request is closed. It will be automatically reopened after we attach it to a milestone.
Thank you very much for share it. I hope that we'll be able to publish it soon.
