### ISSUE TITLE
Using selectCell after a copy+paste while displaying a javascript alert makes moving with the arrows select cells

### ISSUE THREAD

**Issue by rvelhote** [handsontable/handsontable#5289]
### Description
We are using the beforeChange event to check for duplicate values in a grid. Sometimes the user types the value, sometimes it can be a copy+paste. This bug only happens with copy+paste!

If a duplicate is found a javascript `alert` is shown to the user and `selectCell` is used to point the user to the already existing value.

After the user dismisses the alert (it's irrelevant if you show the `alert` before or after `selectCell`) the cell is correctly selected however if you try to move to another cell with the arrow keys or click on another cell with the mouse it's like the CTRL key got stuck and selects everything you touch.

### Demo
http://jsfiddle.net/3d8w4por/

### Your environment
* Handsontable version: 5.0.0
* Browser Name and version: Firefox 61.0.1
* Operating System: Ubuntu 16.04

**Comment by AMBudnik** [comment]
I have replicated the issue. 

You're right - it works well for editing but breaks for pasting.

![bug](https://user-images.githubusercontent.com/10757813/43319410-e8c37018-91a4-11e8-9147-71b3397b819d.gif)

We need to investigate this subject

**Comment by swistach** [comment]
Hi @rvelhote,
It works correctly in the newest Handsontable: http://jsfiddle.net/40jmwgco/

By the way, CopyPaste plugin will overwrite your selection (`hot.selectCell(2, 1)`) because of the order of its actions: https://github.com/handsontable/handsontable/blob/master/src/plugins/copyPaste/copyPaste.js#L510 
`beforeChange` will be called after `beforePaste` and `CopyPaste`.
