### ISSUE TITLE
[4.0.0+] Dot-separated data aren't pasted with the same data type

### ISSUE THREAD

**Issue by JJertok** [handsontable/handsontable#5386]
Hello. 

I found a new bug after the update to new version. 

### Description
Inserting data into a table does not work

### Steps to reproduce

1. Go to https://handsontable.com/examples?headers
2. Copy a chunk of data (rows: 3 - 10) (columns: Currency, Level) 
3. Insert to excel table
4. Copy a same data from excel
5. Insert to handsontable

### Demo
1) ![image](https://user-images.githubusercontent.com/22245022/44983826-45b70900-af83-11e8-8e65-e5fc516f32ae.png)
2) ![image](https://user-images.githubusercontent.com/22245022/44983853-62534100-af83-11e8-880f-bca0f36dfe10.png)

### Your environment
* Handsontable version: 5.0.0
* Browser Name and version: Chrome 68
* Operating System: Windows 10

**Comment by JJertok** [comment]
Thank you @AMBudnik. It helped me

**Comment by AMBudnik** [comment]
I can see that it only happens when our number is a dot-separated decimal number and it happens regardless the `numericFormat`.

Also it looks like the version `4.0.0` is the first one that changed the behavior. In the version `3.0.0` the validation works fine. 

The `afterPaste` and `afterValidate` hooks work in the same order for the `3.0.0` and `4.0.0`. What has changed is the 2nd parameter of the `afterValidate` hook which retuned numbers in the `3.0.0` but is returning strings in `4.0.0`.

Here are the results of logging the arguments of the `afterValidate`

### `3.0.0`
![300](https://user-images.githubusercontent.com/10757813/44985752-bbba7080-af81-11e8-98d3-f8fd3d6b990d.png)



### `4.0.0`
![400](https://user-images.githubusercontent.com/10757813/44985757-bd843400-af81-11e8-8485-58854cf421e8.png)

[Release notes for `4.0.0`.](https://docs.handsontable.com/pro/4.0.0/tutorial-release-notes.html) May it be related to new version of Numbro?

**Comment by AMBudnik** [comment]
Fixed in 6.1.0 https://jsfiddle.net/zL9f8hgm/
