### ISSUE TITLE
Pasting multiple rows adds carriage return '\r' symbol to cell values

### ISSUE THREAD

**Issue by evgendkv** [handsontable/handsontable#5477]
### Description
Pasting multiple rows adds carriage return '\r' symbol to cell values. Maybe related to #3801

### Steps to reproduce
1. Copy a range of multiple rows from excel or from text file
2. Paste to HT
3. Cell values contain carriage return symbols

### Demo
https://codesandbox.io/s/7m45r98y8j

### Your environment
* Handsontable version: 6.0.1
* Browser Name and version: Chrome 69.0.3497.100
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Thank you, I have replicated the issue. When I log the data instead I do not get any extra characters

**Comment by evgendkv** [comment]
Thank you for a prompt response!

It seems that string representation of an array in console does not show non-printable characters.
I've updated the example to console.log the positions of '\r' symbols in cell values. They're definitely there.

**Comment by wojciechczerniak** [comment]
Ping @swistach. Might not exist in his copy-paste branch.

**Comment by JSalter02** [comment]
Hi guys-

This is a major bug!

It appears to be caused by this line in copyPaste.onPaste:

`
pastedData = event.clipboardData.getData('text/plain');
`

This returns line feeds as "\r\n" in windows.

Later, in SheetClip.parse, you use:

`
rows = str.split('\n');
`

which leaves behind the \r. I suggest you do this:

`
rows = str.replace(/\r\n|\r|\n/g, "\n").split("\n");
`

**Comment by AMBudnik** [comment]
Hey @evgendkv @JSalter02 we've released a new version where this issue is fixed.
Let me know if it works for you.
