### ISSUE TITLE
after remove columns get wrong sourceData with formulas enabled

### ISSUE THREAD

**Issue by iaminvictus1993** [handsontable/handsontable#5550]
### Steps to reproduce

plz see gif , my expect result is row 4 should have only 3 columns

### Demo

https://jsfiddle.net/7hLcbqnk/
![drag](https://user-images.githubusercontent.com/22359049/47698910-1273bc00-dc4c-11e8-9960-20e500263c7f.gif)

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Thank you for sharing @rianran1993 

I got the same result.

**Comment by AMBudnik** [comment]
Whenever I paste the line in `B2` I get

![image](https://user-images.githubusercontent.com/10757813/65039281-2b638980-d952-11e9-8d24-61ef09e6a254.png)

https://jsfiddle.net/handsoncode/b4cp62gu/ (`8.0.0.-rc1`)

Handsontable treats the line as one value and puts it all int `B2`

![image](https://user-images.githubusercontent.com/10757813/65039378-682f8080-d952-11e9-9217-9d58c3419cc3.png)
but it works the same in Google Sheets
![image](https://user-images.githubusercontent.com/10757813/65039550-ce1c0800-d952-11e9-9ebc-efac1b90f81e.png)

so I've 
* copied the formulas,
* placed them into Google Sheets,
* copied to `B2`

![image](https://user-images.githubusercontent.com/10757813/65039813-5ef2e380-d953-11e9-87ba-c77fc7e43960.png)

and the issue stays the same in `8.0.0.-rc1` 
![image](https://user-images.githubusercontent.com/10757813/65039937-9a8dad80-d953-11e9-99c3-a279a1934a3a.png) 
https://jsfiddle.net/handsoncode/fy1wg58s/

**Comment by AMBudnik** [comment]
[With the latest build from @aninde](https://jsfiddle.net/7c1qm6rh/) it works exactly the same as I described on the 17 of September. Meaning the data is pasted to `B2` and does not create new columns.

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **New formula plugin** task reported at https://github.com/handsontable/handsontable/issues/6466

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Comment by AMBudnik** [comment]
This issue is no longer replicable using v9 (with the new _HyperFormula_ engine).

Updated demo https://jsfiddle.net/2s1cLnrz/
When we add those columns and remove them the `getSourceData()` method returns exactly what we need.

For everyone interested, here is a list of changes for the following version https://handsontable.com/docs/9.0.0/tutorial-release-notes.html and here https://handsontable.com/docs/9.0.0/tutorial-migration-guide.html is a migration guide (from v8 to v9)
