### ISSUE TITLE
The "manualColumnMove" operation affects the column order of data loaded by "loadData".

### ISSUE THREAD

**Issue by utsushiiro** [handsontable/handsontable#5591]
### Description
If some columns have been moved by "manualColumnMove”, these columns are reordered when new data is loaded by loadData.
Has this behavior been assumed? I misunderstood and thought new data would not be affected by the previous operation...

### Steps to reproduce
For exmaple,

1.  Initialize a hansontable by the following data
```
[ 
 [1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5],
 [1, 2, 3, 4, 5],
]
```
2.  move the 4, 5 columns to the 2 column position by "manualColumnMove"
```
[ 
 [1, 4, 5, 2, 3],
 [1, 4, 5, 2, 3],
 [1, 4, 5, 2, 3],
]
```
3. load [['a', 'b', 'c', 'd', 'e']] by "loadData"

4. The loaded data is reordered based on the above moving operation.
```
I assumed
[
 ['a', 'b', 'c', 'd', 'e']
]

Actual data
[
  ['a', 'd', 'e', 'b', 'c']
]
```

### Demo
https://jsfiddle.net/8ffpsqt6/325/

### Your environment
* Handsontable version:  6.1.1
* Browser Name and version: Google Chrome 70.0.3538.77 (Official Build)
* Operating System: macOS High Sierra

**Comment by AMBudnik** [comment]
Thank you for sharing. We will discuss this subject and get back soon.

**Comment by AMBudnik** [comment]
Example updated to 8.0.0-beta1 https://jsfiddle.net/8atmrpwn/ and it seems to work as @utsushiiro wanted - the data is moved and then the new data is loaded and end up as 

>  ['a', 'd', 'e', 'b', 'c']

@utsushiiro am I right?

**Comment by utsushiiro** [comment]
@AMBudnik
I confirmed that the loaded data isn't affected by the previous operation. 
Thanks a lot for your work!!!
## before
https://jsfiddle.net/8ffpsqt6/325/
> ['a', 'd', 'e', 'b', 'c']
## after
https://jsfiddle.net/8atmrpwn/
> ['a', 'b', 'c', 'd', 'e']

**Comment by AMBudnik** [comment]
Great :) Thank you for confirmation. We will close the topic after releasing 8.0.0 as a stable version.

**Comment by AMBudnik** [comment]
Hi @utsushiiro 

I’m glad to announce that Handsontable v8.0.0 that solves this issue is up and running.   

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases  

I highly encourage you to test the new version and leave some feedback. 
I hope that the amount of work that we put on the v8 will help you to improve your project.
