### ISSUE TITLE
[6.0.0+] Error after updating data when using columnSorting

### ISSUE THREAD

**Issue by swk777** [handsontable/handsontable#5617]
### Description

I m having issues when I try to update data using updateSettings.It's linked to the plugin columnSorting.

### Steps to reproduce

1.create a table using plugin columnSorting.
2. update data using updateSettings.
3.check the console.

### Demo

https://jsfiddle.net/swk777/mz4tpuk2/3/

### Your environment
* Handsontable version:6.2.0
* Browser Name and version:all
* Operating System:all

**Comment by AMBudnik** [comment]
Hey @swk777 

it looks like the line `18` is an issue.

**Comment by swk777** [comment]
> Hey @swk777
> 
> it looks like the line `18` is an issue.

Sorry I didn't get your point.It occurs every time when I update the data after the table is rendered,setTimeout is just a simulation.

**Comment by AMBudnik** [comment]
Sorry @swk777 

I was doing the investigation and posted a comment without any clue.

The `columnSorting` is looking for an indicator of a column that is not yet rendered. (to be confirmed)
The issue is also return when we use `loadData` without `updateSettings` method. This is a serious issue, as `columnSorting` is one of our main features.

It looks like the version `6.0.0` broke this functionality as it works fine in `5.0.2` https://jsfiddle.net/fb7dacry/

Thank you very much for sharing

**Comment by AMBudnik** [comment]
Updated and simplified example

When we want to load more columns then we had before we get the issue (load at least two more columns)

https://jsfiddle.net/3paz14v6/

**Comment by AMBudnik** [comment]
Hey @swk777 

we've just released v`6.2.1` where this issue is fixed :)

**Comment by swk777** [comment]
> Hey @swk777
> 
> we've just released v`6.2.1` where this issue is fixed :)

cheers:)
