### ISSUE TITLE
Undo doesn't work with columnSorting

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#5636]
### Description
`Undo` doesn't work with `columnSorting`.

### Steps to reproduce

1. Edit `A1` to `A100`.
2. Sort `desc` or `asc`.
3. Use <kbd>CTRL/CMD</kbd> + <kbd>Z</kbd>

Result: The value of the first cell changes.
Expected: The edited cell value `A100` should go back to the previous value `A1`.

### Demo

https://jsfiddle.net/gp67weq9/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by bitwolfe** [comment]
I ran into this issue today with 7.2.1 as well. Surprised this isn't fixed yet. By looking in the beforeUndo and afterChange hooks, the row indexes there seem to be the old visual index. This of course is of no use since the sorting can have changed multiple times since then. I would have expected to see the physical index there so that we could figure out the current visual index based on that.

@wszymanski Is this something that will be fixed with https://github.com/handsontable/handsontable/issues/5751 ?

**Comment by wszymanski** [comment]
Hello, @bitwolfe. Thanks for your feedback. The real problem is that the `ColumnSorting` plugin isn't compatible with the `UndoRedo` plugin. It isn't handled now. We've already discovered some problems with `UndoRedo` and `PersistantState` plugins, with @wojciechczerniak, related to the fact that some changes on indexes aren't handled globally. The mentioned task won't fix this problem yet.

**Comment by AMBudnik** [comment]
Example for `7.2.2` https://jsfiddle.net/phdt276m/1/ not fixed within `8.0.0-beta1` as mentioned above.

![GIF_](https://user-images.githubusercontent.com/10757813/68765977-497dfb00-061e-11ea-8947-76d8aed6bec7.gif)

**Comment by AMBudnik** [comment]
Just to add - it also applies to `multiColumnSorting`
https://jsfiddle.net/dmn6c1a2/ (v`7.4.2`)

**Comment by AMBudnik** [comment]
Demo updated to v8.0.0 https://jsfiddle.net/tmvpo5ck/1/ (works the same)

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **UndoRedo grouped** issue task reported at https://github.com/handsontable/handsontable/issues/7508

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com
