### ISSUE TITLE
When we enable filters we aren't able to add new rows while pasting data

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5648]
### Description

When we enable filters we aren't able to add new rows while pasting data.

### Steps to reproduce

1. Copy this data

```
2/5/2018
2/11/2018
2/11/2018
2/11/2018
2/5/2018
22/11/2018
2/5/2018
2/5/2018
22/5/2018
```

2. Paste it to cell `0,0`

**Result:**
You should get a couple of new lines with data but you get only one.

### Demo

https://jsfiddle.net/91c2va3z/1/

### Your environment
* Handsontable version: 6.1.1
* Browser Name and version: Chrome 69
* Operating System: Windows 10

[`Inform Zen#22029` ](https://handsontable.zendesk.com/agent/tickets/22029)

**Comment by AMBudnik** [comment]
Issue reproduced in v `8.0.0.-rc1` https://jsfiddle.net/handsoncode/uoa8hcr7/

**Comment by wojciechczerniak** [comment]
This issue might not be related to index mappers and has a wrong description. I can paste into second column and new rows are created. Pasting to first column breaks even if I disable filters.

Problem is with `dateValidator`, which calls `setDataAtCell` with `null` row and col parameters because `this.instance.toVisualRow(this.row)` returns noting. Probably rows are not created yet in the indexMapper

https://github.com/handsontable/handsontable/blob/98878a6bb6edbed065b7961bc97d4b799e908503/src/validators/dateValidator.js#L39-L42

Looks more like a general problem in our data flow.

**Comment by wojciechczerniak** [comment]
And why does the validator has to apply data? It supposed to just return the status info. Maybe an error msg. Not all validators do that. Maybe this is an unnecessary operation?

----
`correctFormat` is the villain here. Without forcing the correct format the `setDataAtCell` won't be called. This should be the bug description and an example @AMBudnik

**Comment by AMBudnik** [comment]
> This should be the bug description and an example

Agree. This might be a lack of understanding and proper documentation.

**Comment by wojciechczerniak** [comment]
@handsontable/devs  Can we move `correctFormat` to the editor or a hook that has access to `value` and can modify it without calling `setDataAtCell` after `setDataAtCell`?

IMO Validator should have a single purpose. Return `true` / `false` and an error message eventually.

**Comment by AMBudnik** [comment]
This issue remains the same after updating to v 8.0.0 https://jsfiddle.net/2mfr79c4/

**Comment by AMBudnik** [comment]
Fixed by https://github.com/handsontable/handsontable/pull/10957for Handsontable v14.4.0
