### ISSUE TITLE
 Alignment is useless when the table content is html

### ISSUE THREAD

**Issue by ByboyCn** [handsontable/handsontable#5716]
### Description

Alignment is useless when the table content is html

I used vuedraggable in vue, and then his rendering tag is set to i, this problem occurs, I found an official example, found that the official example also has this problem, please help me to view the problem I wrote Or the plugin itself has a problem, thank you~

### Steps to reproduce

![image](https://user-images.githubusercontent.com/17998816/51223204-ea0e7a80-197b-11e9-87dc-903717caf97b.png)

### Demo

https://jsfiddle.net/Byboy/ruswxc7d/2/

### Your environment
* Handsontable version:6.2.2
* Browser Name and version:Chrome latest version
* Operating System:maxos latest version

**Comment by ByboyCn** [comment]
I found this html tag, if it is plain text, his classname will be loaded in the html tag. If it is an embedded html tag, his classname will remain empty.
![image](https://user-images.githubusercontent.com/17998816/51223489-ecbd9f80-197c-11e9-9993-c2e2667c1d4e.png)

**Comment by AMBudnik** [comment]
Thank you for sharing @ByboyCn 

we should consider adding alignment to the HTML content as well. It is not easy and won't please all of the developers but as long as we do not grey it out it appears like a bug.

**Comment by ByboyCn** [comment]
I think that no matter what is in td, you should increase its alignment. If there are other issues, you can use css to control it. But in the current situation, I can only implement it by modifying the style of the html tag. Compared with these two methods, I think the second method is more uncomfortable.

**Comment by AMBudnik** [comment]
Update: we can also think about turning off (grey out) those options for cells with the HtmlRenderer.

The following alignment has been added to:
1. give control to the developers 
2. align text

When you load DIVs, images it is a completely new way of alignment.

**Comment by AMBudnik** [comment]
We did not decide what to do with this task yet. We'll be planning a new sprint in February, but there is no precise date yet.

**Comment by wojciechczerniak** [comment]
Hi @ByboyCn, Thanks for the demo. 

You're creating a custom renderer. This means you're responsible for the TD element. Most of our renderers apply our `base` renderer:

https://github.com/handsontable/handsontable/blob/c2ba2dc02e3eb883a58f976ef5944fa629dc981d/src/renderers/textRenderer.js#L19

which is basically a [cellDecorator](https://github.com/handsontable/handsontable/blob/master/src/renderers/_cellDecorator.js) and was created for that (adding css classes) purpose. 

And since this is an HTML and the content can vary you have to align it with your own styles that can be based on the classes we provide. Custom renderers are out of our control, but we're providing all the tools you need: https://jsfiddle.net/jbzdkw4q/1/

If you're custom renderer does not support alignment then you can configure contextMenu to hide or disable alignment options. You have to do it on your own because we don't know what you're custom renderer do or do not support.

@AMBudnik  In our HTML renderer the alignment is supported: https://jsfiddle.net/jbzdkw4q/

![screenshot 2019-01-23 at 14 34 27](https://user-images.githubusercontent.com/4718998/51610065-11d18580-1f1c-11e9-96b8-df2b6e4a1bb1.png)

**Comment by ByboyCn** [comment]
Thanks 
My problem is solved, thank you @wojciechczerniak  @AMBudnik support
