### ISSUE TITLE
Handsontable hide many non-contagious columns

### ISSUE THREAD

**Issue by eason123deng** [handsontable/handsontable#5733]
### Description
Problem: Suppose we have a dataset with 1000 columns by 1 million rows, and we hide all but the last 5 columns. Based on my observation, it seems like HoT will render all 1000 columns in this situtation, and this has resulted in a large amount of "unnecessary" elements in the DOM and makes scrolling unbearably slow.

Is there any way to hide any number of columns without making scrolling unbearably slow/flooding the DOM with `th` elements?

Thanks for the help.

### Your environment
* Handsontable version: Pro 3.0.0
* Browser Name and version: Google Chrome
* Operating System: Mac

**Comment by AMBudnik** [comment]
Hi @eason123deng 

That is a really large dataset. Itself it has 1kkk cells, loading that amount of TD elements it is already a challenge for a browser, and when you recalculate the width of columns data types, cell properties (while hiding) you force the browser to re-render the whole table again.
I can recommend tracking down this issue https://github.com/handsontable/handsontable/issues/4381 when it comes to the hiddenColumns performance. It should get a bit faster after we finish this task.

**Comment by eason123deng** [comment]
Hi @AMBudnik, thanks for the reply. I will definitely track that issue.. 👍 
I think I should have mentioned a bit more detail, we are currently employing lazy loading and pagination, so we will probably be rendering 20 columns by 50 rows of cells at any given time... Based on my observation, when we hide all the columns, we will still be rendering the same amount of rows per column (maybe a few more rows will be rendered). The bigger problem is that all the columns seem to be rendered and the DOM was flooded by the hidden columns....

**Comment by eason123deng** [comment]
I was able to steal someone else's fiddle to demonstrate what I meant:
http://jsfiddle.net/vh4mbz5n/, scrolling vertically seems to be an issue

**Comment by wojciechczerniak** [comment]
That's an extreme use case you've got here.

When it comes to rows (you want column, bare with me for a sec) we differentiate between hiding and trimming them. Trimming removes items from rendering but when we talk about hiding we want the rows / columns to be rendered with width / height as 1px to indicate they are still there. They are not "unnecessary", you can select them, copy them, resize, use in formulas etc.

For better performance you want them to be skipped, for sure. That's why we have `trimRows` plugin. Sometimes you just don't need some items. There's no `trimColumns` plugin though. So we have to remove unnecessary columns from the data set by ourselves. Or... we can get creative 🤔

Rough and dirty demo: http://jsfiddle.net/tkxzv4m8/
I've used your `hiddenCol` array to create `columns` array for Handsontable settings. With `columns` you can select which columns from `data` object you want to display. This way you keep your data intact and skip columns from the rendering process.

Let me know if this meets your use case.

**Comment by eason123deng** [comment]
Oh thanks so much for the help, I think i have an idea on how i may fix the issue 👍 👍 👍

**Comment by eason123deng** [comment]
Actually, this may break a lot of features that we are currently have (e.g. we want to have the hidden column indication dashed line), can you please share some ideas on how this may be handled?
Thanks for the help

**Comment by AMBudnik** [comment]
> can you please share some ideas on how this may be handled?

as it not a part of our official API we can create a POC for you in terms of the commercial service or the extended support plan (for PRO users).

Please contact me at support@handsontable.com
