### ISSUE TITLE
ColumnSummary: Extra row + unchangeable values

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5794]
### Description

ColumnSummary: Extra row + unchangeable values

### Steps to reproduce

1. The summary is doubled
2. If you change any value in the 2nd column to `0` you get only one of the summaries showing the correct value.

### Demo

http://jsfiddle.net/AMBudnik/g2f8h6dt/

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: Chrome 71
* Operating System: Windows 10

`Moved from GL #123`

**Comment by AMBudnik** [comment]
Issue moved to [handsontable/handsontable-pro #209](https://github.com/handsontable/handsontable-pro/issues/209) via [**ZenHub**](https://www.zenhub.com/)

**Comment by aninde** [comment]
Issue is fixed by the new version `8.0.0-rc1`. Instead of error, there is a warring in console, which leads a developer to create a spare row for calculations. @wojciechczerniak is that by design?

**Demo**
Change: requires leaving empy row
forked from original v. `8.0.0-rc1` http://jsfiddle.net/aninde/wtsgv2r1/

**Comment by AMBudnik** [comment]
After all the changes we made it works well in 8.0.0-beta1 (with the added new row for summaries)
http://jsfiddle.net/f352zc9n/
![image](https://user-images.githubusercontent.com/10757813/68861572-19049280-06ec-11ea-949a-938f2087a9dd.png)

**Comment by AMBudnik** [comment]
Works like a charm in 8.0.0 http://jsfiddle.net/vu7f49od/. I'm glad to close this issue as solved.
