### ISSUE TITLE
The focus from input in a header is stolen - version IE and Edge

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#5820]
### Description
The focus from input in a header is stolen after the second try.

Related issue #5541

### Steps to reproduce
![ie9](https://user-images.githubusercontent.com/1555809/53415428-855e2b00-39d1-11e9-86c0-05264ee611f7.gif)

### Demo

https://handsontable.com/docs/6.1.0/demo-filtering.html in IE or Edge

**Comment by AMBudnik** [comment]
As [support for the Internet Explorer browser is to be deprecated in version 8.0.0](https://github.com/handsontable/handsontable/issues/7026) we decided to close all the issues that are only replicable on that browser. All IE-related workarounds implemented into Handsontable are still a part of the code, and we do not plan to remove them.

After testing this issue on Edge / Windows 10
<img width="153" alt="edge_ver" src="https://user-images.githubusercontent.com/10757813/85019745-91926c80-b16f-11ea-9252-b4cf34f64801.png">

we get exactly the same issue in all versions all the way to 8.0.0-beta2-rev15. We need to click the input twice to focus on it. That's why I keep this issue opened with the changed label ('IE/Edge' > 'Edge')

**Comment by aninde** [comment]
I'm very glad to see that this issue is fixed since v8.0.0 https://handsontable.com/docs/8.0.0/demo-filtering.html

Also I test if <kbd>Tab</kbd> works. It works.

I tested it on Windows 10 / IE 11 and real Edge without Chromium.

@AMBudnik can you double check it before we close it?

**Comment by AMBudnik** [comment]
@aninde true. It did not work for me using IE with 7.4.2 but since 8.0.0 we're able to proceed with filling other inputs.
I'm closing this issue as solved.
