### ISSUE TITLE
colHeaders together with spaces in their text and hiddenColumns creates an extra line within the header.

### ISSUE THREAD

**Issue by craigbenstock** [handsontable/handsontable#5832]
### Description
When using colHeaders that include a space within their text in conjunction with hiddenColumns, there appears an extra line within the column headings.

note: 

* In my example I am using html spans as headings, as I later hook in to their data attr to create custom actions, but it still happens if you just provide plain text.

* Also, if you add multiple non-consecutive spaces you get multiple blank lines added to the bottom of the header

### Steps to reproduce

1. Create column headings with spaces in their name
2. Hide a column using hidden columns

### Demo
https://jsfiddle.net/cab79/k74Lb5fw/1/

### Your environment
* Handsontable version: latest cdn - "https://cdn.jsdelivr.net/npm/handsontable-pro/dist/handsontable.full.min.js"
* Browser Name and version: So far tested and found in Chrome, Edge & Firefox
* Operating System: Windows 10

**Comment by craigbenstock** [comment]
I forgot to mention that this issue is also when in conjunction with:

.handsontable table thead th {
    white-space: pre-line;
}

However, this is a requirement for our implementation, as per: https://github.com/handsontable/handsontable/issues/923

**Comment by AMBudnik** [comment]
Hey @craigbenstock 

Sorry, but I do not see a point in using `white-space: pre-line;` in headers. Why did you want to keep those in the CSS settings?

**Comment by craigbenstock** [comment]
@AMBudnik 

Because I want column header text to wrap on to a new line rather than be cut off or force my columns to be very wide.  Exactly as the reason stated in #923 which I cited in my post.

If there is a better or more official way of getting column headers to wrap text other than using 'white-space: pre-line;' please let me know?

**Comment by craigbenstock** [comment]
@AMBudnik  

I've only every logged 1 other issue on here before so not sure the expected wait time between Q&A.  Just wondering if/when I should expect a further reply to this issue?  Thanks.

Not 100% clear on what the status 'Answered' actually means.

**Comment by wojciechczerniak** [comment]
Sorry for the delay, finding a solution sometimes takes time. Especially for custom ideas.

You want to wrap text and expand header, that's exactly what happens here.

When you've added `white-space: pre-line;` the text will wrap if the header width is small enough. Since HiddenColumns plugins sets the width for hidden column to `1px` it will always wrap text inside. And the nature of HTMLTable will always expand cell height. This affects all cells (THs) in the row.

There's no official support for wrapping text in headers. 
1. We've got HeaderTooltips if header text doesn't fit the column width.
2. You can remove column from `columns` and it will not be rendered at all, therefore its height will not affect all siblings.
3. 🤔 Mark somehow that only headers that are not hidden should have `white-space: pre-line;`

https://jsfiddle.net/bLt2auyk/ 🎉

**Comment by craigbenstock** [comment]
Thanks for getting back to me.

*Solution 1 - Is unfortunately not suitable for what we are doing.

*Solution 2 - I'm sure this would work but not been able to try this in our code yet.

*Solution 3 - Whilst it works in the jsdiddle, in our more complex implementation it only works partly.  Although I am continuing to try similar solutions.

I personally think it would be a good feature for HT to implement a flag for wrapping in colHeaders, however as it's not currently supported I'm happy for this to be closed.
