### ISSUE TITLE
Add a similar option to `skipColumnOnPaste` for autoFill 

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5845]
### Description

The option is useful when we use autoFill on hidden rows.

### Your environment
* Handsontable version: 7.0.0
* Browser Name and version: Chrome 72
* Operating System: Windows 10

**Comment by wojciechczerniak** [comment]
I think that the option is already here and is called `skipRowOnPaste`:

https://github.com/handsontable/handsontable/blob/d0aac96b07497347eba7d8307c5b70e0081410f4/src/core.js#L749

But there is a small difference to `skipColumnOnPaste`:

https://github.com/handsontable/handsontable/blob/d0aac96b07497347eba7d8307c5b70e0081410f4/src/core.js#L766

One has condition `source === 'Autofill.fill'` while the other `source === 'Autofill.autofill'`.

The source that autofill calls `populateFromArray` is `Autofill.fill`:

https://github.com/handsontable/handsontable/blob/d0aac96b07497347eba7d8307c5b70e0081410f4/src/plugins/autofill/autofill.js#L203

That's why it works for columns but not rows.

**Comment by AMBudnik** [comment]
Thanks!
