### ISSUE TITLE
System's context menu captures a scrolling of the table's container.

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#5846]
### Description
System's Context Menu captures a scrolling of the table's container  - until you click on the table again.

### Steps to reproduce
1. Go to https://handsontable.com/docs/7.0.0/demo-scrolling.html
2. Click <kbd>RMB</kbd> on `A1`.
3. Press <kbd>ESC</kbd> to close context menu.
4. Move the cursor outside of the table's container (on the right side or below)

### Demo
https://handsontable.com/docs/7.0.0/demo-scrolling.html

![Nov-15-2019 16-11-28](https://user-images.githubusercontent.com/11849621/68953666-a7e3de80-07c2-11ea-827f-3d641a686eea.gif)

### Your environment
* Handsontable version: any

**Comment by aninde** [comment]
This issue will be fixed in `7.3.0` v.  I tested it on `Chrome 78`. `Firefox 70`, `Safari 10.13`, `Microsoft Dev Edge`,` Opera`.

Described here case is related with Chrome. 
![cointextMenu7 3 0](https://user-images.githubusercontent.com/30186818/68957852-2e042300-07cb-11ea-90e9-f0e5ee2f21de.gif)


**Case 2**  `Firefox`
Don't release <kbd>RMB</kbd>
On previous version there it caused scrolling.
![scroll-7 2 2ff](https://user-images.githubusercontent.com/30186818/68957821-1af15300-07cb-11ea-8874-1f2d58075d7c.gif)

`7.3.0 v.` fixed it.
`Firefox`
![scrolling-7 3ff](https://user-images.githubusercontent.com/30186818/68957828-22b0f780-07cb-11ea-8340-be06de1b0816.gif)

`Chrome`
![scrolling-holding7 3chrome](https://user-images.githubusercontent.com/30186818/68958692-e8485a00-07cc-11ea-9b74-759873b8590f.gif)

**Demo** 
`7.3.0 v` forked from scrolling demo https://jsfiddle.net/aninde/bz3uw64e/
`7.3.0 v.` `iframe` https://jsfiddle.net/jysznLxe/

**Comment by AMBudnik** [comment]
Fixed for Firefox 70 / Chrome 78

**Comment by AMBudnik** [comment]
After loading the latest build (6.12) issue is still fixed https://jsfiddle.net/AMBudnik/t8podj5z/

Tested on Catalina with Chrome 78, FF 70 and Safari.

**Comment by aninde** [comment]
Confirmed, like @AMBudnik  wrote it still works good during testing `7.3.0  v.` (6.12) on Chrome 78, Firefox 70, Safari 13, Microsoft Dev Edge / Mac OS Catalina and latest IE, Edge, Edge Dev / Windows 11
https://jsfiddle.net/aninde/qmvLy7hn/ 
https://jsfiddle.net/aninde/1n2usx6h/
