### ISSUE TITLE
'AVERAGE' formula dosen't work correctly

### ISSUE THREAD

**Issue by palespring** [handsontable/handsontable#5868]
### Description
I want to calculate the average of 3 numbers, the data is 

`var dataObject = [
	[1,2,3,'=average(A1:C1)']
]`

When I first calculated, their results were correct. But when I change the value of one of the cells, D1 (calculated in D1) only calculates the average of the remaining two Cell values, and I already have set the cell type to 'numeric'.
### Steps to reproduce

1.Change the value of A1 or B1 or C1
2.Press enter
3.The result of D1 is wrong

### Demo

https://jsfiddle.net/Jeremy_Chan/8thf5byq/5/

### Your environment
* Handsontable version:7.0
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Welcome @palespring 

the following issue with the Average formula oddity has been reported here https://github.com/handsontable/handsontable/issues/4675

If we're missing something crucial in that post please leave a comment.

**Comment by AMBudnik** [comment]
This issue is fixed with https://github.com/handsontable/handsontable/issues/4675 in v9
For everyone interested, here is a list of changes for the following version https://handsontable.com/docs/9.0.0/tutorial-release-notes.html and here https://handsontable.com/docs/9.0.0/tutorial-migration-guide.html is a migration guide (from v8 to v9)
