### ISSUE TITLE
Calculation issue when IF is used on FALSE data

### ISSUE THREAD

**Issue by LoveOfLava** [handsontable/handsontable#5870]
Hello

I don't know why the formula on B3 cell display  "#VALUE!" when the value on A3 is "nd"

<script async src="//jsfiddle.net/Hun7er/h4bsqwtr/41/embed/"></script>

Thanks
Regards

**Comment by AMBudnik** [comment]
We have the same result in v 8.2.0 https://jsfiddle.net/0hkw1fvb/

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **New formula plugin** task reported at https://github.com/handsontable/handsontable/issues/6466

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Comment by AMBudnik** [comment]
This issue is not replicable using the pre v9.0.0 https://jsfiddle.net/handsoncode/dms82o5k/

![image](https://user-images.githubusercontent.com/10757813/119117103-2f9a5100-ba29-11eb-8e47-477fbb3117b6.png)

**Comment by AMBudnik** [comment]
@aninde it **works well** in v9 https://jsfiddle.net/vx7zc2po/1/ (today's build, - freeze)

**Comment by AMBudnik** [comment]
Hi @LoveOfLava 

I'm happy to announce that I'm closing this issue as **fixed** for v9.0.0. Thank you for your patience and constant feedback.

For everyone interested, here is a list of changes for the following version https://handsontable.com/docs/9.0.0/tutorial-release-notes.html and here https://handsontable.com/docs/9.0.0/tutorial-migration-guide.html is a migration guide (from v8 to v9)
