### ISSUE TITLE
nestedRows does not allow to keep rowHeaders after collapsing

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#5874]
### Description

We have custom row headers
`rowHeaders: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L']`
When we collapse first section (parent A) next parent should still be named `G`, but it becomes `B`.

### Steps to reproduce

1. Collapse the first arent row

### Demo

http://jsfiddle.net/handsoncode/2quf1ejm/

### Your environment
* Handsontable version: 6.2.2
* Browser Name and version: Chrome 71
* Operating System: Windows 10

`Moved from GL #155`

**Comment by AMBudnik** [comment]
The issue evaluated. 
ps. The demo above did not have the `bindRowsWithHeaders` option attached.

Here's what happens now, in v`7.0.0`

![GIF](https://user-images.githubusercontent.com/10757813/54201077-17375f00-44cd-11e9-870b-23e0d181daf1.gif)

When we load table the row headers show `1` instead of a header. They are fine when we edit a cell so it looks like that we're missing one rendering.

**Comment by wojciechczerniak** [comment]
@AMBudnik @aninde Fixed in `v8` ? https://jsfiddle.net/yf7wkm0b/

**Comment by AMBudnik** [comment]
@wojciechczerniak works well for collapsing. `G` header is on its position.
![GIF](https://user-images.githubusercontent.com/10757813/66291605-96193c80-e8e2-11e9-8f60-471190315d9a.gif)

But I think that we should create a new issue report for altering.
![GIFdf](https://user-images.githubusercontent.com/10757813/66291686-bf39cd00-e8e2-11e9-8615-3a7a28213593.gif)
In this case, we should get something like?

![image](https://user-images.githubusercontent.com/10757813/66291976-67e82c80-e8e3-11e9-8b63-a385a366476d.png)

and even if NOT, then we should get the `G` parent when we remove a child row.

![GIF_erewr](https://user-images.githubusercontent.com/10757813/66292099-bf869800-e8e3-11e9-8aba-0d8938a0381a.gif)

It makes sense when we have `A, B, C, D...` but if those were categories and subcategories of products? I can't imagine changing their names.

**Comment by aninde** [comment]
@wojciechczerniak , the issue described here will be fixed by `8.0.0-rc1`. 

However, in latest `8.0.0-rc1` there is additional, **regression** error. 
You can not collapse two parents. @wszymanski will the latest fix handle this?

v. `8.0.0-rc1` Bug - you can collapse only one parent. When you tried to collapse the second parent, when first is collapsed,  the first one unwinds
![nested-8 0 0-rc1 2019-10-07 09_29_12](https://user-images.githubusercontent.com/30186818/66294611-aaad0300-e8e9-11e9-8f77-f6ec9f58218d.gif)

It works in original demo
v. `6.2.2`, also in latest `7.1.1`
![Screenshot 2019-10-07 at 09 24 58](https://user-images.githubusercontent.com/30186818/66292614-045efe80-e8e5-11e9-9730-8bd5f3ae7299.png)

Demo:
works `7.1.1` http://jsfiddle.net/aninde/v1Lcunjm/
bug v. `8.0.0-rc1` https://jsfiddle.net/yf7wkm0b/

**Comment by aninde** [comment]
Lates build of `8.0.0-beta1` still fixed issue https://jsfiddle.net/aninde/erkh7t2w/

**Comment by aninde** [comment]
Sadly, this bug appears in the latest build of `8.0.0-beta.1.  http://jsfiddle.net/aninde/zwnyLdt3/ I missed it due to problems with `cashe` of `jsfidle` and `jsdelivery`. It was fixed on the build from 8/11/19 as I wrote above.
![Screenshot 2019-11-14 at 14 53 36](https://user-images.githubusercontent.com/30186818/68863063-e4dea100-06ee-11ea-9b26-3c18de4a44b2.png)

**Comment by aninde** [comment]
I was wrong. I forgot to add  `bindRowsWithHeaders: true`, with that it fixed. @wszymanski thank you for noticing this 
http://jsfiddle.net/aninde/sg9b13yt/

**Comment by AMBudnik** [comment]
Still works well in 8.0.0.-beta2-rev6 http://jsfiddle.net/a1w03pvz/

**Comment by AMBudnik** [comment]
Yay! Thank you for fixing this issue in v8.0.0.

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases
