### ISSUE TITLE
scrollToCell option in selectCell doesn't work properly without default height of rows

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#5885]
### Description
When we use the `selectCell` with the option `scrollToCell` `true` with non-standard rows height it doesn't work properly - not scrolling automatically to reach the position of that selected cell.

### Demo

https://jsfiddle.net/yx7bm1hn/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
Hey @pnowak 

It looks like this issue is the same as @jansiegel 

The difference is that you're using `hot1.selectCell(106, 0, 106, 6, true);` and he's using
`hot1.scrollViewportTo(99, 0)`. As he's example is simpler I would close this one and leave a comment in @jansiegel 's issue to mention selectCell() function.

What do you think?

**Comment by pnowak** [comment]
Ok. I think it's fair enough.

**Comment by AMBudnik** [comment]
Thanks for the immediate feedback.
