### ISSUE TITLE
Filters doesn't work with nestedRows

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#5889]
### Description
When we have both plugins `nestedRows` and `filters` on, the whole table doesn't appear - it shows only the first nested rows (the row and its children). The rest of the table appears after clicking the button of parent row header.

### Steps to reproduce
![filtersWithNestedRows](https://user-images.githubusercontent.com/1555809/54351834-b33da380-4650-11e9-83bf-6e16f2be9ff1.gif)

### Demo
https://jsfiddle.net/k34gqmuj/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
`inform Gr #22621`

**Comment by AMBudnik** [comment]
Issue fixed with `8.0.0-rc1`

Before `8.0.0.-rc1` most of data was missing and we could see a header misalignment

![image](https://user-images.githubusercontent.com/10757813/65029994-07e31380-d93f-11e9-9fb1-1ca6a5d396a5.png)

thanks to @wszymanski in `8.0.0-rc1` it works like a charm

![image](https://user-images.githubusercontent.com/10757813/65030060-28ab6900-d93f-11e9-9b51-da8797241aaf.png)

**Comment by aninde** [comment]
Demo where `8.0.0` fixed described here issue: https://jsfiddle.net/aninde/zs563uf4/
Still fixed in latest `8.0.0.-rc1` https://jsfiddle.net/aninde/wb92so75/

**Comment by AMBudnik** [comment]
Works well in the official 8.0.0-beta 1
https://jsfiddle.net/3ycof7hu/

**Comment by AMBudnik** [comment]
We have missed one thing - rows are back which is OK, but the filter list is incomplete

![Zrzut ekranu 2020-05-11 o 12 20 30](https://user-images.githubusercontent.com/10757813/81551315-e9c09c80-9381-11ea-9de6-a7b650377dd4.png)

**Result**
There're only
* blank cells
* Best Rock Performance

**Expected result**
* blank cells
* Best Rock Performance
* Best Metal Performance
* Best Rock Song
* Best Rock Album

This issue **hasn't been solved** in 8.0.0.-beta1 and works the same way in 8.0.0-beta2-rev2 https://jsfiddle.net/9phsmtrL/

**Comment by AMBudnik** [comment]
This issue is also replicable in v 8.0.0 https://jsfiddle.net/79s081jk/
Surprisingly when we check filter_by_value list for the `B` column, two children, from the first parent are not listed in the filter

![image](https://user-images.githubusercontent.com/10757813/89787401-abbc4b80-db1d-11ea-92bd-ea04dd61694a.png) and here's what happens when you try to filter out 1 child

![GIF](https://user-images.githubusercontent.com/10757813/89787522-e2926180-db1d-11ea-98a1-e900e5091358.gif)

**Comment by AMBudnik** [comment]
Missing **filter by value** values issue is reported here https://github.com/handsontable/handsontable/issues/6858 so we can close this topic.
