### ISSUE TITLE
Wrong position of buttons in nestedRows after use detach from parent

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#5900]
### Description
When we use contextMenu options `Insert child row` and next `Detach from parent` button of parent row header is in the wrong rows.

### Steps to reproduce

1. Add row by `contextMenu` `Insert child row`
2. Remove row by `contextMenu` `Detach from parent` 

![nestedRowsDetach](https://user-images.githubusercontent.com/1555809/54540040-9201ed80-4997-11e9-98aa-04a77a3042dc.gif)

### Demo

https://jsfiddle.net/bgv7ej5z/

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by AMBudnik** [comment]
I get the error

![image](https://user-images.githubusercontent.com/10757813/60102027-30eb7200-975d-11e9-89a3-231f747f3b2d.png)

when I want to use the `Detach from parent` option.
https://jsfiddle.net/handsoncode/b6rdx85o/1/ Tested on Windows 10 / Chrome 75 
I've tested it with the latest 7.1.0 but also with 6.2.2 and a couple of older versions and got the same result.

**Comment by aninde** [comment]
This bug will be fixed in the new `8.0.0-rc1`. There is no error in the console after you Deatach from parent newly inserted row.
However in `8.0.0-rc1`, there is another, regression error described here

**Demo**
bug v. `7.1.1` https://jsfiddle.net/aninde/s20qfajo/
first of`8.0.0-rc1` fixed bug, https://jsfiddle.net/aninde/rjm36nkh/
latest v. `8.0.0-rc1` same as above https://jsfiddle.net/aninde/fpgyd5Lm/

**Comment by AMBudnik** [comment]
Remains solved in 8.0.0-beta2-rev6 https://jsfiddle.net/2ykzec7g/

**Comment by AMBudnik** [comment]
Demo updated to version 8.0.0 https://jsfiddle.net/bxqtj1nh/
We can officially closed this issue as fixed 👍
