### ISSUE TITLE
[7.0.0.+] Bug when open contextMenu by API method

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#5939]
### Description
After try open `contextMenu` by plugin method `open` we have a bug - `Uncaught TypeError: Cannot read property 'ownerDocument' of undefined`.

### Steps to reproduce

1. Use `e` key
2. Open `console`.

### Demo

https://jsfiddle.net/v8hyL02d/

### Your environment
* Handsontable version: 7.0.0
* Browser Name and version:
* Operating System:

**Comment by wojciechczerniak** [comment]
It's because `target` is needed. `container` should be enough: https://jsfiddle.net/kLrambc6/

Docs states that "This object is structurally compatible with native mouse event so it can be used either." but mentions only `pageX` and `pageY`.

We could improve the docs here, and maybe add a fallback to the container if `target` is not defined.

Why is it a regression? Is there a previous version that was working ok? Which one?

**Comment by pnowak** [comment]
In an earlier version - `6.2.2` https://jsfiddle.net/9nvzgast/ - everything works ok.

If we clarify in docs and add the fallback to the container if the target is not defined I think is enough.

**Comment by wojciechczerniak** [comment]
You're right. This has changed with `iframe` support. `target` is now used to find root window, and I guess it wasn't needed earlier so it just worked. The problem here is that the method `open` expects `event` object. We should change the API so it accepts only what is needed.

**Comment by pnowak** [comment]
Good news! This issue got solved v8.0.0. Here's an updated demo - https://jsfiddle.net/cboe5j86/
