### ISSUE TITLE
Fixed bottom rows, weird effect on zoom

### ISSUE THREAD

**Issue by tjgambs** [handsontable/handsontable#5943]
### Description

When increasing or decreasing the zoom, fixed rows are acting strangely. It looks like this only happens when there is a fixed row at the bottom of the table. It appears to work fine when the fixed rows are elsewhere.

### Steps to reproduce

1. Increase or decrease the zoom level of the browser
2. Look at the bottom of the screen and see the weird effect
3.

### Demo

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10355191/55904181-dfd3d500-5b94-11e9-8fbf-779fc835e838.gif)

### Your environment
* Handsontable version: 7.0.2
* Browser Name and version: Google Chrome, 73.0.3683.86
* Operating System: MacOS

**Comment by AMBudnik** [comment]
Thank you for sharing the issue report @tjgambs I have replicated the issue.

Here's how the demo looks on 175% zoom on Chrome 73/ Win 10.

![image](https://user-images.githubusercontent.com/10757813/55938662-23cde500-5c3c-11e9-96e4-a4f3dbc36041.png)

The above issue does not happen all the time. Sometimes when we rapidly change the zoom in and out.

![image](https://user-images.githubusercontent.com/10757813/55938904-be2e2880-5c3c-11e9-9059-15af334be720.png)

Happens all the time.

**Comment by tjgambs** [comment]
@AMBudnik Any update on this? Should I seek out a solution on my own or are you guys on it? Thanks.

**Comment by AMBudnik** [comment]
Sorry @tjgambs not yet

**Comment by dingrf** [comment]
@AMBudnik  it seemingly  still exist on v7.1.1

**Comment by wojciechczerniak** [comment]
Related #4454

**Comment by AMBudnik** [comment]
The same behavior we get after using v8.0.0 official fixing demo https://handsontable.com/docs/8.0.0/demo-fixing-bottom.html

**Comment by swistach** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of Interoperability problems using zoom/system UI scaling and some core features task reported at #7527 

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behaviour feel free to contact me at

**Comment by AMBudnik** [comment]
Hi @tjgambs @dingrf It seems that this issue is no longer replicable in Handsontable v12.1.0 where we fix a  similar issue https://github.com/handsontable/handsontable/issues/4454.

Demo for test http://jsfiddle.net/qoa8ws60/1/

I'm closing this issue as solved. However, please send me an email at support@handsontable.com if you'll still have issues with this functionality.

**Comment by karan-provusinc** [comment]
We are seeing the similar issue again in 14.5.0. We forward for a fix or temporary workaround.

**Comment by AMBudnik** [comment]
Hi @karan-provusinc 

Could you please share a screenshot/recording and your browser/OS version?

I purchased their latest version of Safari, Chrome, and Firefox on macOS Ventura, and I wasn't able to replicate the issue.

![zoomin](https://github.com/user-attachments/assets/237dd55a-775f-495c-a1f1-2e6ae40cc2f0)


The only issue I found is a slight misalignment of the fixed row on some value of the zoom.

![Zrzut ekranu 2024-09-27 o 13 37 54](https://github.com/user-attachments/assets/fd043bf9-cb12-4704-bee5-d75103e67711)

**Comment by karan-provusinc** [comment]
@AMBudnik I am using 16 inch mac with 1312*848 resolution and 90% zoom on chrome. It may be reproduced with large data set.
![image](https://github.com/user-attachments/assets/4495215b-801e-4c86-be70-af2562253e4c)
