### ISSUE TITLE
What is the difference between physical index and logical index?

### ISSUE THREAD

**Issue by daext** [handsontable/handsontable#5992]
I notice that the terms "physical index" and "logical index" are used in many questions available here and in the Handsontable forum.

Since I can't find anything on this subject in the Handsontable documentation I was wondering if someone can provide a link or more details to understand the difference.

Thank you.

**Comment by AMBudnik** [comment]
Hey @daext 

the **visual index** is a position of the row/column that we see. Whatever you see in the first row it has an index of `0`.
Once you sort or filter a table the rows/columns change their positions and their visual indexes change. To keep access to the default state of the table we needed to attach **physical indexes** to those rows and columns. 
The physical index never changes it is a key for the plugins. They use this key to alter row/column position.

### Example
![image](https://user-images.githubusercontent.com/10757813/56949130-592a6c00-6b32-11e9-9101-e0f95bccdda2.png)

Anna before sorting had a physical index of `0` and visual index of `0`.
Anabelle before sorting had a physical index of `1` and visual index of `1`.
Adam before sorting had a physical index of `2` and visual index of `2`.

After sorting Anna's and Adam's visual indexes changes but physical indexes say the same.
Anna's physical index is `0` and the visual index of `2`.
Anabelle's physical index is `1` and the visual index of `1`.
Adam's physical index is `2` and the visual index of `1`.

Anabelle is on the same position so her visual index = physical index.

**Comment by bahaar1715** [comment]
**Physical Index:**
The physical indexing is referred as the actual indexing structure as it is stored on disk.
Meanwhile, physical Indexes Oracle is the world’s most flexible and robust database because it is
vulnerable to almost every plausible algorithm for speeding-up access to data.
**Physical Index Structures can be:**
 B-tree indexes
 Bitmap Indexes
 Bitmap join indexes
 Hash key indexes
 Hash partitioned indexes
 Index-organized tables
 Con*Text Indexes
**Key Features of Physical Index:**
 The physical index need not use a traditional index structure and can be stored either in the
Oracle database as tables or externally as a file.
 A reverse key index is a type of B-tree index that physically reverses the bytes of each index key
while keeping the column order.
 All leaf records in a B–tree contain keys and pointers.
 The actual physical implementation and naming varies.
 No matter what physical method is used to implement a B–tree index.
 Physically, data is organized on disk across thousands or numerous of disk or data blocks.
 Physical indexes for temporary tables are not shared.
**Usage of Physical Index:**
Since the primary index contains a direct reference to the data block address through the virtual
address space and disk blocks are physically organized in the order of the index key, every time the
operating system does some disk page split due to the DML operations. For a clustered index, it’s not
obligatory that all the disk blocks are stored contagiously. Physical data blocks are all the time moved
around here and there by the Operating System whenever it’s necessary.
Limitation for Physical Index:
 For a physical index to satisfy the requirements of a logical index, the columns, column order
and the ordering which is either ascending or descending of data, for each column must be
identical.
 Physical indexes are not created for remote or isolated tables.
 A database system does not have any unconditional control over how physical data space is
managed, but inside a data block, records can be stored or managed in the logical order of the
index key.
 For temporary tables, physical indexes are created, but they are not recorded and are rejected
after the use.
**Logical Index:**
The logical indexing is referred as a reference to a physical index. When a primary key,
secondary key, foreign key, or unique constraint is defined, the database server confirms the referential
integrity by creating a logical index for the certain constraint. The logical indexing approaches are
organized at the analytical level and do not include any knowledge of the underlying physical database
structures such as:
 Function-based Indexes
 Multi-column indexes
 Virtual column indexes
 STAR transformation indexing
**Key Features of Logical Index:**
 Using logical indexes means that the database server does not need to create and maintain
duplicate physical indexes.
 More than one logical index can point to a single physical index.
 The components of the index i.e. the metadata and physical indexes are managed by different
index servers.
 A logical index is an index that consists of several physical indexes and metadata.
 The metadata contains information about which physical indexes belong to which logical
indexes.
 Using logical indexes means that the database server does not need to create and maintain
duplicate physical indexes, since more than one logical index can point to a single physical
index.
**Usage of Logical Index:**
The database server looks to see if a physical index already exists that fulfills the constraint. In
case a suitable physical index already exists, the database server points the logical index towards it. In
case no such physical index already exists, the database server creates a new physical index and then
points the logical index towards it. Whenever a logical index is removed or deleted, its definition is
simultaneously removed or deleted from the system table. The physical index is defined in the system 
table; and a reference to the physical index used to satisfy the logical index is recorded in the table with
the physical index identity column.
**Limitation of Logical Index:**
 When a logical index is deleted or removed, its definition is removed from the system table too.
 After the constraint is defined, if it is the only logical index referencing a particular physical
index, the physical index is also deleted, including its corresponding entries in physical index
identity system table.
 In case the physical addresses change either by insertion, deletion or any reason, the physical
index must be updated as well too.
 Changes to physical addresses don't affect the logical index.
Preferences to use Logical and Physical Index:
 Physical indexing is preferred because it leverage as much database power as possible. For
instance, if an index is to be created for the date field and in descending sequence
 Most indexing systems use character sequence sorting. If a signed numeric fields is used i.e.
packed, binary, or decimal within the keys, then it could end up with logically duplicated keys if
one value is positive, and another is negative.
 Physical index is faster and hence preferred to use.
 Since more than one logical index can point to a single physical index, therefore it takes more
number of logical indexes to be created as compared to physical.
 In case of remote tables, physical indexing cannot be preferred.
 Logical index can demand for more space and complexity than the physical indexes and hence
with large database, it will not be suitable.
 If the data is to be stored permanently, then physical indexes cannot be used.
