### ISSUE TITLE
onBeforeEditing and onAfterEditing

### ISSUE THREAD

**Issue by Aymkdn** [handsontable/handsontable#61]
I need to customize my cells. For example with showing a calendar or other stuff. For that I need a onBeforeEditing and onAfterEditing events that will trigger my other plugins (e.g. to show the calendar and then destroy it).

I've simply added the below code at the end of the beginEditing function:

``` javascript
if (priv.settings.onBeforeEditing)
  priv.settings.onBeforeEditing.call(priv.editProxy,priv.selStart.row,priv.selStart.col,datamap.get(priv.selStart.row, priv.selStart.col),priv.colHeader.columnLabel(priv.selStart.col));
```

And in the finishEditing function:

``` javascript
if (priv.settings.onAfterEditing)
  priv.settings.onAfterEditing.call(priv.editProxy,priv.selStart.row,priv.selStart.col,datamap.get(priv.selStart.row, priv.selStart.col),priv.colHeader.columnLabel(priv.selStart.col));
```

What do you think about adding something similar ?
The difference with the onChange event is this one is called all the time.

EDIT: I didn't work with your last commit so the code is not totally correct but you got the idea I think :)

**Comment by AMBudnik** [comment]
For anything looking for a tip here: You can use beforeChange/afterChange hooks and an `edit` (2nd parameter) to get the same actions that you'd get from onAfterEditing / onBeforeEditing

**Comment by imageslr** [comment]
Hello @warpech , is there a hook named 'afterFinishEditing' just like 'afterBeginEditing'? I want to redo something that I did in 'afterBeginEditing' hook. Thanks!

**Comment by AMBudnik** [comment]
Hey @imageslr 

we have a similar request here https://github.com/handsontable/handsontable/issues/6044

If you think that we need anything there please leave a comment.

**Comment by imageslr** [comment]
Thanks for your quick reply @AMBudnik ! So this hook hasn't been implemented yet? I prepare to use `afterChange` but as you said, it won't be fired when click `ESC`. Well...

I want to implement a edit toolbar, which can modify style of cells, such as font style(bold, font-size, font-family), background-color of the cell. My implementation is like this:

```js
 <HotTable
   customCellStyle
   cell={[
     { row: 1, col: 1, customCellStyle: { fontSize: 14, backgroundColor: red }},
     { row: 2, col: 2, customCellStyle: { fontSize: 12, color: yellow }}
   ]}
 />
```

I use a custom plugin which will add these `customCellStyle` into the `style` property of `TD` element. 

```js
this.addHook("afterRenderer", (TD, row, col, prop, value, cellProperties) =>
  this.addStyles(TD, cellProperties)
);
```

But such change will only influence Renderer's TD, not Editor's TD. And since editor is singleton, so I want to add custom styles `after beging editing` and remove them `after finish editing`.

I will appericiate it if you could give me some instructions for this toolbar implementation.

**Comment by AMBudnik** [comment]
@imageslr 

Can I ask you to share the requirements to support@handsontable.com as we don't want to exchange comments on a closed topic from 2012?

**Comment by imageslr** [comment]
Sorry! I'll send an email and I'll delete the comment above.

**Comment by AMBudnik** [comment]
Please send it again. I did not receive it (checked SPAM as well).
