### ISSUE TITLE
Rows cannot be resized to less than rowHeights

### ISSUE THREAD

**Issue by andreiaugustin** [handsontable/handsontable#6149]
### Description

If using manualRowResize set to true while passing a value to rowHeights, you will find that rows cannot be resized to their minimum of 23 but will take the value of rowHeights as the new minimum.

Doing the same with manualColumnResize and colWidths allows you to resize the columns' width to their minimum of 50.

### Steps to reproduce

1. Add manualRowResize to true.
2. Add rowHeights.
3. Try to resize row, it will not go lower than the value passed to rowHeights.

### Demo

https://jsfiddle.net/z46cLnrb/

### Your environment
* Handsontable version: 7.1.0
* Browser Name and version: Google Chrome Version 75.0.3770.142 (Official Build) (64-bit) 
* Operating System: macOS 10.14.5

**Comment by AMBudnik** [comment]
Good day @andreiaugustin 

I simplified the example https://jsfiddle.net/AMBudnik/79bys6xv/ and you're right - the resize should work the same for columns and row.

Currently, resize for columns can set a smaller width than `colWidths` but resize for rows cannot do the same with `rowHeights`.

**Comment by AMBudnik** [comment]
I've just checked that on Excel and it also allows me to manually set narrower width and height then defined.

**Comment by AMBudnik** [comment]
Works well in 8.0.0-beta2-rev18 https://jsfiddle.net/5bdwvgkz/1/

**Comment by AMBudnik** [comment]
Hi @andreiaugustin 

I’m glad to announce that Handsontable v8.0.0 that solves this issue is live!   

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases  

I highly encourage you to test the new version and leave some feedback. I hope that the amount of work that we put on the v8 will help you to improve your project.

Demo updated to v 8.0.0 (stable) https://jsfiddle.net/woj8q1fb/
