### ISSUE TITLE
[Edge] Cannot zoom in/out with Ctrl + Wheel

### ISSUE THREAD

**Issue by vkum** [handsontable/handsontable#6150]
### Description
With Edge and IE, when you point with your mouse in the grid content and then use the Ctrl button + mouse wheel combination in order to zoom in and out of the page, Handsontable instead scrolls up and down.

### Steps to reproduce

1. Point your mouse in the grid content of the Handsontable.
2. Use the Ctrl button + mouse wheel combination.
Result: the content scrolls up and down instead of zooming in and out.

### Demo

https://handsontable.com/examples?headers

### Your environment
* Handsontable version: 0.35.0, 6.2.2, latest...
* Browser Name and version: Edge 42.17134.1.0, Internet Explorer 11.829.17134.0
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Thank you for sharing the issue report.

I have replicated the behavior.

**Comment by AMBudnik** [comment]
Hi @vkum 

I'm happy to announce that this issue is not replicable on the latest Handsontable 8.0.0-beta2-rev15

![wheel](https://user-images.githubusercontent.com/10757813/85023885-978b4c00-b175-11ea-98f9-edbbd123ce66.gif)

I've just tested it on my Edge
<img width="153" alt="edge_ver" src="https://user-images.githubusercontent.com/10757813/85023925-a1ad4a80-b175-11ea-832a-a97b4bbb4b5b.png">

on Windows 10 and it works as expected when we have nothing selected or a cell selection.

I've tested the following settings

```js
                data: Handsontable.helper.createSpreadsheetData(10, 10),
                contextMenu: true,
                colHeaders: true,
                rowHeaders: true,
                contextMenu: true,
                hiddenColumns: {
                    columns: []
                }
```

However, it also works well on 7.4.2 so I'm closing this issue as **solved**.
