### ISSUE TITLE
JSON data with empty value will lose some double quotes when pasted into a cell

### ISSUE THREAD

**Issue by onecai** [handsontable/handsontable#6167]
### Description

When pasting JSON data with empty value into a cell, some double quotes will be missing.

### Steps to reproduce

1. copy & paste {"k1":"1","k2":2,"k3":"","k4":""} into a hansontable cell, you will get {"k1":"1","k2":2,"k3":","k4":"}

![图片](https://user-images.githubusercontent.com/8509769/62180555-06578f00-b383-11e9-96ca-c81be564e06c.png)

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version: 7.1.0
* Browser Name and version: Chrome 75
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
You're right @onecai 

The empty space is the value of `k3` key but after the changes, it got the comma as a value and `k4` got broken.

It looks like it worked that way all along. I've tested 7.1.1 and some versions back.

**Comment by swistach** [comment]
`SheetClip.parse()` parses incorrectly `JSON`-like values. `text/html` works properly.

**Comment by AMBudnik** [comment]
**Solved** in 8.0.0-beta2-rev14 https://jsfiddle.net/AMBudnik/m9cvgu4r/

**Comment by AMBudnik** [comment]
Hi @onecai, 

I have good news! We've just released 8.0.0-beta2 that fixes the mentioned issue. We won't be closing this ticket now. It will be closed after we release the final 8.0.0 version of Handsontable.

Here’s a full list of changes https://github.com/handsontable/handsontable/releases/tag/8.0.0-beta.2
NPM https://www.npmjs.com/package/handsontable/v/8.0.0-beta.2 

All feedback's appreciated. Thank you for your input.

**Comment by aninde** [comment]
Still works good with `pre-8.0.0-rev1` https://jsfiddle.net/aninde/ugv07rLx/

**Comment by AMBudnik** [comment]
Hi @onecai 

I’m glad to announce that Handsontable v8.0.0 that solves this issue is live!   

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases  

I highly encourage you to test the new version and leave some feedback. I hope that the amount of work that we put on the v8 will help you to improve your project.
