### ISSUE TITLE
We can't resize the bottom row when we use `fixedRowsBottom`.

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#6180]
### Steps to reproduce

1. Scroll to the bottom.
2. Try to resize the last row.

### Demo

https://jsfiddle.net/k2r5cwz7/
![Kapture 2019-08-05 at 13 25 08](https://user-images.githubusercontent.com/1555809/62461510-5a98af80-b785-11e9-8c33-0b2f64ed64c1.gif)

### Your environment
* Handsontable version:
* Browser Name and version:
* Operating System:

**Comment by wojciechczerniak** [comment]
I know this is out of the scope for the linked issue, but while we're near `z-indexes` for overlas there is one more issue whe there is more fixed bottom rows:

https://jsfiddle.net/tohnkvsd/

![obraz](https://user-images.githubusercontent.com/4718998/65123366-56ea8080-d9f3-11e9-97bc-e74eda074e47.png)

It's because `.ht_clone_bottom_left_corner` and `.ht_clone_top_left_corner` have the same `z-index` but bottom one is later in DOM structure. We should split those two and set `z-index: 108` for the top header.

And BTW. if I remember correctly @budnix removed debug overlay. Can we clean up `.ht_clone_debug` class from CSS @budnix ?

**Comment by wojciechczerniak** [comment]
What you're actually doing is changing the size of 99th row. It can't go lower than text height so you see no effect.

To change the bottom row height you have to use the bottom handle:

![Jul-01-2020 23-10-09](https://user-images.githubusercontent.com/4718998/86292067-545abf80-bbf0-11ea-84c8-50f1c114406e.gif)
