### ISSUE TITLE
[7.0.0+] Size no longer works correctly when underneath a transform

### ISSUE THREAD

**Issue by chearon** [handsontable/handsontable#6201]
### Description
Hopefully this isn't a duplicate, it could be a similar underlying problem to some of the open issues.

Since 7.0.0, if you have a transform on some parent, Handsontable does not set dimensions correctly. The master table is too small (it seems to be checking the size of the post-transform parent via `getBoundingClientRect` or something) and everything else is correct.

![Screen Shot 2019-08-12 at 2 44 00 PM](https://user-images.githubusercontent.com/78187/62889609-b7f5a900-bd0f-11e9-83a3-e244c425232a.png)

### Steps to reproduce

1. Make a Handsontable instance with width and height set
2. Set a transform like `transform: scale(0.9) on a parent, such as body
3. The `.wtHolder` of the `.ht_master` gets whatever width and height you set multiplied times 0.9, so it gets scaled twice instead of just by the parent

### Demo

http://jsfiddle.net/1u94hrdy/

### Your environment
* Handsontable version: 7.0.0 - 7.1.1
* Browser Name and version: any
* Operating System: any

**Comment by AMBudnik** [comment]
I can see that we had a couple of similar issues before 

https://github.com/handsontable/handsontable/issues/5886
https://github.com/handsontable/handsontable/issues/5050
https://github.com/handsontable/handsontable/issues/3946

all closed and fixed but there's an unquestionable bug - it's broken again. So thank you very much for sharing, Caleb.

The issue came back with v `7.0.0` http://jsfiddle.net/6j7mh0bn/
`6.2.2` works fine.

**Comment by DongShi** [comment]
...please get this fixed. We have deployed HOT in production under transform in many cases.

**Comment by AMBudnik** [comment]
Hey @DongShi 

It was just added yo the `September's` milestone. I'll let you know as soon as we get this done.

**Comment by nikersify** [comment]
The problem seems to be even more severe in 8.2.0 as in addition to the table size being wrong, the row header background and the highlight area are also wrong:

`scale(0.75)`:
<img width="163" alt="image" src="https://user-images.githubusercontent.com/7091471/104906740-6598cd00-5984-11eb-9143-cf47a547dfc7.png">

`scale(1.5)`:
<img width="335" alt="image" src="https://user-images.githubusercontent.com/7091471/104906872-8a8d4000-5984-11eb-9eea-762e41181b00.png">

**Comment by AMBudnik** [comment]
Hi @chearon @DongShi 

https://jsfiddle.net/1u94hrdy/ please check the new version - Handsontable v14.0.0 where with this pull request https://github.com/handsontable/handsontable/pull/10482 we fixed this issue.

Here https://handsontable.com/docs/javascript-data-grid/release-notes/#_14-0-0 you can read ore about the changes.

If you'd have any questions about the new release please leave a comment here or write to us at support@handsontable.com
