### ISSUE TITLE
[7.1.1] Crash Pasting data into mixed read only and non read only cells

### ISSUE THREAD

**Issue by ZachHaber** [handsontable/handsontable#6209]
### Description

On the latest version (7.1.1), HoT throws a type error which is causing an application I'm building to crash. It doesn't occur on HoT 7.1.0, so the latest update was likely the cause. This only occurs when the HoT instance has not been edited yet (e.g. just loaded the page). The Error is "Uncaught TypeError: Cannot read property 'removeEventListener' of undefined".
### Steps to reproduce

1.  Make sure that no editing has been done on the HoT instance. (e.g. just refreshed the page).
2.  Select a read only cell with non read only cells below it. Paste multi row data starting at the read only cell where some of that multi row data will be put into a non read only cell.
3.  See that in the console there was a type error thrown in the console. Depending on the set up, it might crash the whole application.

### Demo

[https://jsfiddle.net/jsgL9ko0/1/](https://jsfiddle.net/jsgL9ko0/1/)

### Your environment
* Handsontable version: 7.1.1 with React Wrapper
* Browser Name and version: Chrome 74.0.3729.131
* Operating System: Windows 10 1803

**Comment by AMBudnik** [comment]
Thank you for sharing the issue.

I've also replicated the same using vanilla with the latest `7.1.1` version of Handsontable https://jsfiddle.net/mjeng4oy/

It looks that
1. The number of `readOnly` rows doesn't matter as long as you paste the data into a `readOnly` row as a first cell.
2. We get the error only once
3. The number of pasted rows has to be higher than the number of `readOnly` rows (if we have `3` `readOnly` rows, you need to paste `4` rows to get the error).
4. Got broken in `7.1.1`. `7.1.0` works fine https://jsfiddle.net/mjeng4oy/1/

**Comment by aninde** [comment]
@ZachHaber this error will be fixed in new release `7.1.2`. It will be introduced next week. 
Correct behavior has been restored. There will be no error in console when you will try to paste data into the cell with `readOnly`.

**Fixed result** in `7.1.2` https://jsfiddle.net/aninde/vgepd5un/ 
![6209](https://user-images.githubusercontent.com/30186818/66496395-23af8480-eabb-11e9-8562-48fa5174bb21.gif)

During testing, I noticed a different behavior than described above. Maybe we can use that information in future regression. 
Bug in  `7.1.1` https://jsfiddle.net/mjeng4oy/
Error in console appears even when number of pasted rows is smaller then `readOnly` rows.
I tried to paste 2 rows when I got 3 with `readOnly`.
![7 1 1 rows 2019-10-09 at 17 12 19 2019-10-09 17_39_17](https://user-images.githubusercontent.com/30186818/66496867-de3f8700-eabb-11e9-878c-97d3ef9c8405.gif)

An error in the console appears every time you try to paste data on each `readOnly` cell or the same cell without first editing the table.
![multi error 7 11](https://user-images.githubusercontent.com/30186818/66497351-a6850f00-eabc-11e9-853c-2faae0bb0689.gif)

After you try to paste into a cell, when you move the selection down to a cell without `readOnly`, its edition opens
Reproduction:
1. Paste data to `readOnly` cell
2. Move selection down with <kbd>down arrow</kbd>
![edition 7 1 1](https://user-images.githubusercontent.com/30186818/66497681-201cfd00-eabd-11e9-83a5-09f7437ba9cd.gif)

**Demo:**
fixed `7.1.2` v.  https://jsfiddle.net/aninde/vgepd5un/ 
with a bug  `7.1.1` https://jsfiddle.net/mjeng4oy/

**Comment by AMBudnik** [comment]
Again. Thank you for sharing the issue.

It has been fixed and the new version is ready for download - [7.2.0](https://handsontable.com/docs/7.2.0/tutorial-release-notes.html)
