### ISSUE TITLE
Paging

### ISSUE THREAD

**Issue by djkuddel** [handsontable/handsontable#623]
Hello,

I would be great if there will be a paging navigation too.

Many thanks
DJ

**Comment by Software-Design** [comment]
Are there any plans to add a complete built-in pagination? The code demo mentioned is not helpful if you plan to edit data across multiple pages. 

If you add a row on page one and switch to another page all data is lost. Additionally adding new rows should append them at the last page not at the end of the page I'm looking at because this may lead to chaotic data orders.

**Comment by AMBudnik** [comment]
you're right @Software-Design there are some things that should change to make the feature comprehensive. 
Currently it's not on our [Roadmap](https://trello.com/b/PztR4hpj/handsontable-roadmap-2016-login-to-vote-for-features), but it's definitely of of those ideas we should reconsider.
