### ISSUE TITLE
paste <> turns into &lt;&gt;

### ISSUE THREAD

**Issue by DanielWLam** [handsontable/handsontable#6271]
### Description
paste <> turns into &lt;&gt;

### Steps to reproduce

1. copy <>
2. paste

### Demo

https://jsfiddle.net/gomdcju6/

### Your environment
* Handsontable version: 7.1.1
* Browser Name and version: chrome 76
* Operating System: mac os

**Comment by AMBudnik** [comment]
Hey @DanielWLam 

how do you want this to work

> paste <> turns into <>
![image](https://user-images.githubusercontent.com/10757813/65139556-23b4eb00-da0d-11e9-85ad-c55d69164be4.png)


is that the full issue description?

**Comment by DanielWLam** [comment]
Hi, @AMBudnik . 
Please try paste content from google sheet here: https://docs.google.com/spreadsheets/d/1e6JwctPuytj0dthF3pDL6oZ-TG-ALsAqUySXrRITAys/edit?usp=sharing

to js fiddle: 
https://jsfiddle.net/gomdcju6/

When I try to copy content which contains "<" and ">" html tags, it will turn out to be &lt; and &gt; , which is not what I except. Are there any ways I can paste what it used to be?

**Comment by AMBudnik** [comment]
If you want the HTML to work you need to add `renderer: 'html'`. When by copying `123<strong>323</strong>54`

you'll get this
![image](https://user-images.githubusercontent.com/10757813/65243878-998e8480-dae9-11e9-9adb-33b632602707.png)

instead of
![image](https://user-images.githubusercontent.com/10757813/65243908-ab702780-dae9-11e9-8d89-903d703fc622.png)




demo https://jsfiddle.net/handsoncode/z3aps8u7/

**Comment by AMBudnik** [comment]
Please let me know it if meets your project requirements.

**Comment by AMBudnik** [comment]
I guess that we can close the topic as there are no additional questions or comments. 
But if there's something else that we'd need to cover here please let me know.
