### ISSUE TITLE
iPadOS 13 issues

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#6286]
### Description

Yesterday Apple released iPadOS 13 for (obviously) tablet devices. After short testing, it seems that from now on devices which have installed this system behaves as **non-mobile** devices. Handsontable for iPadOS behaves as if it were running on a PC which reveals some new issues:
 * There is no possibility to select more than one cell due to missing mobile handlers;
 * There appeared again bug related to pop up a keyboard on every cell tapping.

### Your environment
* Handsontable version: 7.1.1
* Browser Name and version: Safari
* Operating System: ipadOS13

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **Interoperability problems using Mobile devices and some core features** task reported at https://github.com/handsontable/handsontable/issues/7520

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Comment by aninde** [comment]
Both cases described here also appear on the latest iOs 14 version.

**Comment by aninde** [comment]
#### Bug #3

Right border of corner becomes bold when scrolling vertically and horizontally.
@wojciechczerniak  commented that it looks like the corner changes size during the scroll, the overscroll probably affects it somehow.
![image](https://user-images.githubusercontent.com/30186818/108525900-d9eec500-72d0-11eb-9a6e-6b82192e449a.png)

https://user-images.githubusercontent.com/30186818/108525951-e4a95a00-72d0-11eb-9623-6cc3ed107a93.mp4

**Comment by AMBudnik** [comment]
Editor self-opening on tap is no longer replicable using Handsontable v14.0.0
