### ISSUE TITLE
updateSettings can not update tableClassName

### ISSUE THREAD

**Issue by DongShi** [handsontable/handsontable#6295]
### Description

It seems tableClassName can not be updated via updateSettings API.

### Steps to reproduce

1. just try this fiddle https://jsfiddle.net/qwpdneoj/
2. you can see that the class name "table_green" is not applied after hitting the button.
3.

### Demo

https://jsfiddle.net/qwpdneoj/

### Your environment
* Handsontable version: latest
* Browser Name and version:  latest
* Operating System: MacOS

**Comment by AMBudnik** [comment]
This demo uses version `0.32.0` but in `7.1.1` it happens the same https://jsfiddle.net/c2z36xeo/

Once the `htCore` gets a class there's no way to update it.

![Zrzut ekranu 2019-09-27 o 10 40 21](https://user-images.githubusercontent.com/10757813/65755510-898f2a00-e113-11e9-8736-a631f9725888.png)

However, it is set in the settings correctly. We can check it by executing `hot.getSettings().tableClassName`.
when we run it inside the button we get `table_green` > https://jsfiddle.net/xw5o47bu/

And the hook

```js
afterUpdateSettings: function(){
    	console.log(arguments)
}
```

returns `{tableClassName: "table_green"}`

**Comment by AMBudnik** [comment]
Hi @DongShi 

I have good news! We've just released 8.0.0-beta2 that fixes the mentioned issue. We won't be closing this ticket now. It will be closed after we release the final 8.0.0 version of Handsontable.

Here’s a full list of changes https://github.com/handsontable/handsontable/releases/tag/8.0.0-beta.2
NPM https://www.npmjs.com/package/handsontable/v/8.0.0-beta.2 

All feedback's appreciated. Thank you for your input.

**Comment by aninde** [comment]
Working demo with `pre-8.0.0-rev1` https://jsfiddle.net/aninde/3m5gce0t/. After pressing the button the class changes., updateSettings can update tableClassName.

![Screenshot 2020-07-20 at 14 24 36](https://user-images.githubusercontent.com/30186818/87937439-07526680-ca95-11ea-99f7-21b5ddf7c2db.png)

**Comment by AMBudnik** [comment]
Hi @DongShi 

I’m glad to announce that Handsontable v8.0.0 that solves this issue is up and running 👍  Thank you again for your input. I hope that the amount of work that we put on the v8 will help you to improve your project.

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases  

I highly encourage you to test the new version and leave some feedback.
