### ISSUE TITLE
[7.1.1] Disappearing column header with auto height

### ISSUE THREAD

**Issue by jacekbogdanski** [handsontable/handsontable#6302]
### Description

Once you set `height: 'auto'` with col headers enabled, headers get `visibility: hidden` CSS property. It seems like a regression starting from `7.1.1`.

### Steps to reproduce

1. Initialize Handsontable instance with configuration:

```javascript
new Handsontable( container, {
  colHeaders: true,
  rowHeaders: true,
  height: 'auto'
} );
```
2. Verify Handsontable instance in a browser.

### Demo
https://codepen.io/jacekbogdanski/pen/mZvyYb

You can also change Handsontable version to `7.1.0` to see it has been working correctly.

### Your environment
* Handsontable version: 7.1.1
* Browser Name and version: Chrome 76.0.3809.132 (Official Build) (64-bit)
* Operating System: Linux Fedora 30

**Comment by wojciechczerniak** [comment]
Note: We should test #6213 with after we fix this issue

**Comment by aninde** [comment]
@jacekbogdanski this bug will be fixed in `7.1.2` version.  The new version will be released next week.
When  `height: 'auto'` column headers are still visible.

![Screenshot 2019-10-09 at 11 30 46](https://user-images.githubusercontent.com/30186818/66469825-e6320380-ea88-11e9-9ae5-d52f83599a20.png)

**Demo:**
v. `7.1.2` https://jsfiddle.net/aninde/vq0m3ta4/

**Comment by jacekbogdanski** [comment]
Awesome, thanks for the quick response :)

**Comment by ispyhumanfly** [comment]
Very much looking forward to this fix!

**Comment by aninde** [comment]
@ispyhumanfly if the new version passes the tests, we plan to release it on Tuesday, October 15.

**Comment by AMBudnik** [comment]
Hey @jacekbogdanski @ispyhumanfly we've just release Handsontable `7.2.0`. Where this issue is fixed.
