### ISSUE TITLE
Add optional chaining and nullish operator to Babel config

### ISSUE THREAD

**Issue by wojciechczerniak** [handsontable/handsontable#6308]
### Description
We should add those three Babel plugins for cleaner code and an easier migration to Typescript in the future:

- [ ] https://babeljs.io/docs/en/babel-plugin-proposal-private-methods
- [ ] https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining
- [ ] https://babeljs.io/docs/en/babel-plugin-proposal-nullish-coalescing-operator
- [ ] Refactor one private pool, optional chaining and nullish operator to demonstrate the use case example to the team

**Comment by budnix** [comment]
And maybe it's a proper time to rethink about adding support for `for of` loops? Currently, using `for of` loops causes bigger generated dist files. Maybe `assumeArray`  could balance that https://babeljs.io/docs/en/next/babel-plugin-transform-for-of#assumearray.

**Comment by wojciechczerniak** [comment]
@budnix What if someone will use it with something that isn't an array? Will he get an error or will it compile and fail later?

**Comment by pnowak** [comment]
It seems if in `for of` loops with `assumeArray` we use something that isn't an array we can't iterate over them.
With this config, babel plugin creates ordinary `for` loop: `for (let _i = 0; _i < iterable.length; _i++)`. If we try to iterate over `Map` or `Set` we couldn't enter to this loop because we don't have `.length` property. 
So we can iterate only on `array` and `string`.

**Comment by aninde** [comment]
Notes from testing release of 7.4.0: 
**How it was tested?**
I did a build on which I tested according to the [checklist](https://github.com/handsontable/quality/issues/22) and checked the [size of the version](https://github.com/handsontable/quality/issues/22#issuecomment-581815016). Looks good.
