### ISSUE TITLE
Row header height and row columns height - Aligment issue

### ISSUE THREAD

**Issue by nicgutierrez** [handsontable/handsontable#6317]
### Description
The height of the header doesn't match the height of the content. I've seen an opened and resolved issue very similar to this, but I just installed `handsontable` and encountered the same problem.

### Steps to reproduce
Here's how I'm setting the component in RactJS

```js
<HotTable
  colHeaders={headers}
  contextMenu
  data={table}
  id="hot"
  rowHeaderWidth={200}
  rowHeaders={i => data.keys[i]}
  search
  settings={{
      autoRowSize: true,
      readOnly: !editable,
      stretchH: 'all',
  }}
/>
```

I also have a tiny bit of CSS to give a max-width to columns:
```css
.handsontable tbody td,
.handsontable tbody th {
  max-width: 200px;
}
```

### Demo
![Annotation 2019-10-07 104342](https://user-images.githubusercontent.com/436432/66302009-172b0080-e8f0-11e9-81f5-2a097b7c8d0b.png)
![Annotation 2019-10-07 105852](https://user-images.githubusercontent.com/436432/66302796-7fc6ad00-e8f1-11e9-9ae0-f44db8f0edd8.png)

### Your environment
* Handsontable version: 7.1.1
* Browser Name and version: Chrome 77.0
* Operating System: Windows 10

Thanks!

**Comment by AMBudnik** [comment]
Please share a demo where the issue can be replicable.

**Comment by nicgutierrez** [comment]
Sure, here you go:

https://jsfiddle.net/t07jq4ma/1/

Thanks

**Comment by AMBudnik** [comment]
It does not misalign on my device when I comment out the CSS part. This is how it looks on the initialization.

![image](https://user-images.githubusercontent.com/10757813/66312610-4a31bc00-e911-11e9-9830-b89b7e14c70d.png)

After adding `colWidths: 100` to get a fixed with of a column

![image](https://user-images.githubusercontent.com/10757813/66312681-659cc700-e911-11e9-9b24-5c905420d759.png)

I'm on Chrome 77 / Windows 10.

I think that you might have zoom settings (system or browser) turned on.

**Comment by nicgutierrez** [comment]
Hey @AMBudnik  - damn, you are right. I didn't even think about the zoom. I do have some zoom on my external monitor. I put that one back to 100% and it looks great... 

Thanks for your help here!
