### ISSUE TITLE
We're not able to undo removing of columns when all are gone

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6328]
### Description

We're not able to undo removing of columns when all are gone. Check the below cases.

### Steps to reproduce

1. Select one column by clicking its header
2. Use context menu to remove it
3. Use <kbd>CTRL/CMD</kbd> + <kbd>Z</kbd> to undo the action

**Result**
The column is back

Now

1. Select both columns via <kbd>CTRL/CMD</kbd> + <kbd>A</kbd>
2. Use context menu to remove it
3. Use <kbd>CTRL/CMD</kbd> + <kbd>Z</kbd> to undo the action

**Result**
Nothing changes and we're left alow with an empty space.

### Demo

https://jsfiddle.net/handsoncode/raf2shyt/3/

### Your environment
* Handsontable version: 7.1.1
_Doesn't relate to any version._
* Browser Name and version: Chrome 77
* Operating System: Windows 10

**Comment by aninde** [comment]
While using <kbd>CTRL/CMD</kbd> + <kbd>A</kbd> all table is selected. Cells and headers are included in selection. However, when you tried to `copy and paste` selected table in that case, headers are not included when you tried to paste them. 
IMHO the ability to select the entire table including headers is a bug because you can't do anything with these selected headers anyway.
![Screenshot 2019-10-09 at 13 39 45](https://user-images.githubusercontent.com/30186818/66478438-b3910680-ea9a-11e9-88e0-cdfe7c9ee330.png)
Result of pasting all selected table - Column Headers are missing. 
` <meta charset='utf-8'><meta name="generator" content="Handsontable"/><style type="text/css">td{white-space:normal}br{mso-data-placement:same-cell}</style><table><tbody><tr><td>A1</td><td>B1</td></tr><tr><td>A2</td><td>B2</td></tr><tr><td>A3</td><td>B3</td></tr><tr><td>A4</td><td>B4</td></tr><tr><td>A5</td><td>B5</td></tr><tr><td>A6</td><td>B6</td></tr><tr><td>A7</td><td>B7</td></tr><tr><td>A8</td><td>B8</td></tr><tr><td>A9</td><td>B9</td></tr><tr><td>A10</td><td>B10</td></tr></tbody></table>`


You can remove cells while use `select` manually. 
![Screenshot 2019-10-09 at 13 39 26](https://user-images.githubusercontent.com/30186818/66478423-aa079e80-ea9a-11e9-92e2-9d0376dd15fd.png)
@AMBudnik, @wojciechczerniak WDYT?

**Comment by AMBudnik** [comment]
Copying headers is a feature mentioned here https://github.com/handsontable/handsontable/issues/52

Agree. That could be useful in some cases.

**Comment by aninde** [comment]
Another cases related to that issue:
Demo v. `7.2.2` https://jsfiddle.net/aninde/twu7so5g/

**Case 1**
1.Selecting all rows by mouse.
2. Remove row by `contextMenu`.
3. Click <kbd>CTRL/CMD </kbd>+ <kbd>Z</kbd> to undo the action.

**Result:** 
You aren't able to undo removing. Table and div `wtHolder` was removed.
![Screenshot 2019-10-29 at 10 37 38](https://user-images.githubusercontent.com/30186818/67755578-b4351100-fa38-11e9-8ccd-a3cd693af1b5.png)

**Case 2**
1.Selecting all rows by mouse.
2. Remove colums by `contextMenu`.
3. Click <kbd>CTRL/CMD </kbd>+ <kbd>Z</kbd> to undo the action.

**Result:** 
You aren't able to undo removing.  `wtHolder` div has remained.
![Screenshot 2019-10-29 at 10 37 00](https://user-images.githubusercontent.com/30186818/67755550-a97a7c00-fa38-11e9-9e9f-6f9bd1929afb.png)

**Expected result:**
We should be able to undo removing and maybe we should think about standardizing  results of removing operations.

**Comment by AMBudnik** [comment]
My bad. Case 2 should be described as below (just like you did @aninde)

1. Select both columns by clicking them with mouse
2. Use the context menu to remove it
3. Use CTRL/CMD + Z to undo the action

![GIF](https://user-images.githubusercontent.com/10757813/67759771-5dcbd080-fa40-11e9-956f-4262a8510537.gif)

**Result**
Nothing changes and we're left alone with an empty space.

**Comment by AMBudnik** [comment]
Works the same (**broken**) in 8.0.0.-beta2-rev3 (11/05) https://jsfiddle.net/860Lv2cb/
However, when we have rowHeaders turned on we can see some deterioration (issue reported https://github.com/handsontable/handsontable/issues/6865).

**Comment by pnowak** [comment]
This issue is still replicable using v8.0.0. Here's an updated demo - https://jsfiddle.net/543dwprL/

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **UndoRedo grouped** issue task reported at https://github.com/handsontable/handsontable/issues/7508

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com
