### ISSUE TITLE
Add `loadData` support for Nested Rows.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#6339]
### Description
Issue #3914 pointed to a problem with `loadData` not being covered by the Nested Rows plugin. 

@frankie567 made a pull request (#6015) that adds the `loadData` support to the plugin, which fixes the problem with replacing data with another dataset, but not loading data when it was previously defined as an empty array.

### Demo
* fixed: https://jsfiddle.net/aninde/1dqceLwj/
* not fixed: https://jsfiddle.net/aninde/5a109gso/

**Comment by aninde** [comment]
The cases from #3914 will be fixed by new index mapper in `8.0.0-rc1`. 

**Demo**
Case 1
still fixed in v. `8.0.0-rc1` https://jsfiddle.net/aninde/hLf2nw7v/
v. `7.2.0` fixed: https://jsfiddle.net/aninde/1dqceLwj/

Case 2
still fixed in v. `8.0.0-rc1`https://jsfiddle.net/aninde/rgdop7yn/
v. `7.2.0` not fixed: https://jsfiddle.net/aninde/5a109gso/

Data and headers updates and renders right after clicking on a button.
![Screenshot 2019-10-15 at 11 56 40](https://user-images.githubusercontent.com/30186818/66821728-360a4200-ef43-11e9-94e7-0ec8b484a1ca.png)

**Comment by aninde** [comment]
Case 2 is still fixed by `8.0.0-beta1` https://jsfiddle.net/aninde/ysmn10xu/
