### ISSUE TITLE
[IE11] helper.htmlToGridSettings throws error when used with iframe child table

### ISSUE THREAD

**Issue by jacekbogdanski** [handsontable/handsontable#6350]
### Description

The issue exists on IE11 (didn't test on lower IE versions) when the target table is a part of an iframe. Using `Handsontable.helper.htmlToGridSettings` throws an error when at some point `HTMLCollection` is checked against array type.

Note that everything works fine if a table is not a part of an iframe.

### Steps to reproduce

1. Create iframe element with nested sample table.
2. Execute `Handsontable.helper.htmlToGridSettings` on the table queried from iframe element.

## Expected

The table should be successfully converted into settings object.

## Actual

![image](https://user-images.githubusercontent.com/10279586/66993334-ab088380-f0cb-11e9-9650-791f06cd8e66.png)

### Demo
https://jsbin.com/hequkic/edit?html,js,console,output

### Your environment
* Handsontable version: 7.1.1
* Browser Name and version: latest IE11
* Operating System: Windows 10

**Comment by AMBudnik** [comment]
Thanks, Jacek. Already on it. We'll stay in touch.

**Comment by aninde** [comment]
@jacekbogdanski  this issue will be fixed by `7.2.2`. We plan to release it tomorrow. 
In `7.2.2` v. there isn't error in console. 

I'm working on MacOS, so I tested it on Browserstack/Win 10/ IE 11.
I asked our support for help with testing directly on Windows 10 and IE 11 and results are the same.

This bug is only replicable on IE.

**Demo:**
v. `7.2.2` fixed https://jsbin.com/zuvawex/3/edit?html,js,console,output
Browser Name and version: Windows 10
Operating System: IE 11

**Comment by AMBudnik** [comment]
Windows user confirming - works well now :)

**Comment by jacekbogdanski** [comment]
That was quick, thank you :)

**Comment by AMBudnik** [comment]
Hey @jacekbogdanski already published.
