### ISSUE TITLE
Some classes for table are missing if one of them is empty

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6371]
### Description

>  if an empty string class name is introduced into an array of
classes, all classes after the empty string will be ignored.

### Steps to reproduce

1. Set up an array of classes for the table where one of them should be an empty string

`className: ["First", "Second", "", "Third"]`

![image](https://user-images.githubusercontent.com/10757813/67277830-feae0f00-f4c7-11e9-8731-510632d836d7.png)

**Result**
`className` `Third` is missing.

### Demo

https://jsfiddle.net/7sndg6v0/

### Your environment
* Handsontable version: 7.2.1
* Browser Name and version: Chrome 77
* Operating System: Windows 10

**Comment by pnowak** [comment]
PR https://github.com/handsontable/handsontable/pull/6369 after merge resolve this bug.

**Comment by aninde** [comment]
This issue is fixed by `v. 8.0.0` https://jsfiddle.net/aninde/9yakvnhc/

![Screenshot 2020-07-20 at 12 55 15](https://user-images.githubusercontent.com/30186818/87930626-b472b200-ca88-11ea-9c57-9c3798f7eae5.png)
![Screenshot 2020-07-20 at 12 58 00](https://user-images.githubusercontent.com/30186818/87930635-b89ecf80-ca88-11ea-8257-f70d533b1b4b.png)

**Improper result with `v6.2.2`**
![Screenshot 2020-07-20 at 12 55 26](https://user-images.githubusercontent.com/30186818/87930632-b5a3df00-ca88-11ea-81bb-706ccb0804fb.png)
![Screenshot 2020-07-20 at 12 57 28](https://user-images.githubusercontent.com/30186818/87930633-b76da280-ca88-11ea-9049-879d988acd3f.png)

**Comment by AMBudnik** [comment]
Thank you for fixing. Issue solved in v8.0.0
