### ISSUE TITLE
Inconsistent behaviour of AutoColumnSize and AutoRowSize

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#6401]
### Description
For unknown to me reasons, we use a completely different way to define when and how `AutoColumnSize` and `AutoRowSize` should work. Because these plugins are similar it would be better to keep its configuration similar too.

Look at default settings in the following code:

https://github.com/handsontable/handsontable/blob/b9e14ee9c45dc8f42e23414c93e82e6b805f6879/src/defaultSettings.js#L2197-L2248

Particularly at:
```
(...) Default value is `undefined`, which has the same effect as `true` (...)
...
@default {syncLimit: 50}
```
for `AutoColumnSize`

and 

```
(...) Default value is `undefined`, which has the same effect as `false` (disabled) (...)
...
@default {syncLimit: 500}
```
for `AutoRowSize`.

Moreover, `GhostTable` has the option to use headers in calculations but you cannot use it to calculate multiline `rowHeaders` in `AutoRowSize`.

Related with: #4122

**Comment by swistach** [comment]
Additionally, `autoColumnSize.useHeaders` should be enabled as default, otherwise horizontal scroll is jumpy if headers contain some additional elements (as an arrow in columnSorting).

1. Go to https://jsfiddle.net/h6L5kbe4/
2. Scroll to the last column,
3. Scroll to the last row.

Result:
![Oct-29-2019 15-58-52](https://user-images.githubusercontent.com/11849621/67779607-2ae80380-fa65-11e9-8fc4-874f672e3a40.gif)

**Comment by AMBudnik** [comment]
This issue is no longer replicable in v8.2.0 https://jsfiddle.net/handsoncode/gk835afj/. Tested on Chrome 87 / Windows 10.

**8.2.0**
![8 2 0](https://user-images.githubusercontent.com/10757813/105826848-86cf6e00-5fc1-11eb-86e5-1301ae2cb169.gif)
* we stay at AT column while scrolling vertically
* horizontal scroll jumps

**before (8.1.0 and lower)**
![v8](https://user-images.githubusercontent.com/10757813/105826884-90f16c80-5fc1-11eb-8ab4-7976aac6c901.gif)
* we jump from AT column to AO column while scrolling vertically
* no jumping scrollbars

**Comment by AMBudnik** [comment]
We can close this issue as solved.
