### ISSUE TITLE
Can I update undo history while using loadData function?

### ISSUE THREAD

**Issue by Ingyu0414** [handsontable/handsontable#6415]
I want to implement find & replace function like Excel. Since setDataAtCell() is too slow, I have used loadData function. However, undo history is not updated. Is there a way to update undo history while changing data faster than setDataAtCell?

**Comment by aarondfrancis** [comment]
Unfortunately `loadData` is [specifically excluded](https://github.com/handsontable/handsontable/blob/master/src/plugins/undoRedo/undoRedo.js#L698) from the `undoRedo` plugin, presumably because that's typically only called once, and undoing it would set your data back to nothing.

It's possible that you are doing this already, but `setDataAtCell` accepts batch changes, which is the preferred way of making many changes at once. HoT will apply _all_ of the changes in your batch and then render once instead of many times. Typically this is extremely fast in my experience, < 85ms.

From https://handsontable.com/docs/7.2.2/Core.html#setDataAtCell:
> To change many cells at once (recommended way), pass an array of changes in format
[[row, col, value],...] as the first argument.

Hope that helps!

**Comment by AMBudnik** [comment]
Thank you for your input, Aaron. That guides us to the discussion we had before here https://github.com/handsontable/handsontable/issues/6358 and the [hook request.](https://github.com/handsontable/handsontable/issues/5866)
