### ISSUE TITLE
Undoing removing nested row doesn't work

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6433]
### Description
Undoing removing nested (child) row doesn't work properly. The wrong row is restored instead.

### Steps to reproduce

1. Select a first nested row - child row e.g. `Alabama shakes`
2. Remove it via `contextMenu`.
3. Undo removing by <kbd>ctrl/cmd</kbd>+ <kbd>z</kbd> or undo in `contextMenu`

### Actual result:

Undoing removing of first child of second parent - `Ghost` from `Best metal performance`.
`Best metal performance` is restored instead of `Ghost` and it is the child of the first parent.
![undo-remove-nestedr](https://user-images.githubusercontent.com/30186818/68405493-7fcffc00-0180-11ea-9b52-9ab324ee7bc5.gif)
![Screenshot 2019-11-07 at 17 05 53](https://user-images.githubusercontent.com/30186818/68405765-f40a9f80-0180-11ea-9caf-b9063a9cd879.png)

**Expected result:** 
Undoing should restore removed row on the same position that It was before removing.

### Demo

`7.2.2` http://jsfiddle.net/aninde/ab041sk7/

### Your environment
* Handsontable version: any
* Browser Name and version: Firefox 70, Chrome 78, Edge 
* Operating System: MacOsPro Catalina 10.15

**Comment by aninde** [comment]
A bug is replicable on `8.0.0-rc1` http://jsfiddle.net/aninde/87zmt0sq/

**Comment by AMBudnik** [comment]
I'm adding **Case 2** with **parent removal**

1. Go to row no 7 - parent `Best Metal Performance` here https://jsfiddle.net/k1wzsce4/ (`8.0.0-beta1`)
2. Use `Remove row` from the context menu
3. Use <kbd>CTRL/CMD</kbd> + <kbd>Z</kbd> to undo
![parent_small](https://user-images.githubusercontent.com/10757813/75153122-db5fce80-570a-11ea-9dbe-044ab199e874.gif)

**Result**
We are left with our old row `Best Metal Performance` which is a parent (in the wrong position), with another parent that seems to be duplicated from the one below it - `Best Rock Performance` and all the children are gone.

### Additional info
* it doesn't seem to change if we have 5 or 15 children in the parent row
* the duplication is gone when we remove all the children from the data of the parent https://jsfiddle.net/k1wzsce4/1/
* works the same in `7.4.2` https://jsfiddle.net/k1wzsce4/2/

**Comment by AMBudnik** [comment]
@aninde 's case for this Issue is **solved** in 8.0.0.-beta2-rev2 http://jsfiddle.net/kupL1cns/

#### @aninde case
![case1](https://user-images.githubusercontent.com/10757813/81558569-33af7f80-938e-11ea-8946-d8d6171f3016.gif)

#### case 2 - broken
when we undo 
* does not bring back the rows
* shows the error in the console
![Zrzut ekranu 2020-05-11 o 13 52 06](https://user-images.githubusercontent.com/10757813/81558879-bb958980-938e-11ea-9aca-30d761ccf6e4.png)

It looks like we are able to remove a parent - but only if it's not the last one.
![parent](https://user-images.githubusercontent.com/10757813/81559013-feeff800-938e-11ea-859d-6a7f979e9b02.gif)

**Comment by AMBudnik** [comment]
Case with the broken undo for the last parent issued separately https://github.com/handsontable/handsontable/issues/6860

**Comment by AMBudnik** [comment]
Demo updated to v 8.0.0 http://jsfiddle.net/kwf3u9xo/. Issue officially fixed.
