### ISSUE TITLE
Wrong selecting with ctrl + left click on mac

### ISSUE THREAD

**Issue by somename85** [handsontable/handsontable#6441]
### Description
After I select something with ctrl, it keeps selecting cells even if I release ctrl.

### Steps to reproduce
1. press ctrl
2. click on a few cells
3. release ctrl
4.  click on a few cells
5. click outside of table
6.  click on a few cells

### Demo
It can be reproduced on initial example.
https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version: 7.2.2
* Browser Name and version: Chrome 78.0.3904.97 (64), Safari 13.0.3 (14608.3.10.10.1)
* Operating System: macOS Mojave 10.14.6 (18G1012)

[Screen recording.zip](https://github.com/handsontable/handsontable/files/3830049/Screen.recording.zip)

**Comment by AMBudnik** [comment]
Thank you for sharing @somename85 

the issue is not replicable on Windows. We'll test it on other devices.

**Comment by aninde** [comment]
@AMBudnik I was able to reproduce this bug on Firefox 70 / MacOs Pro Catalina 10.15 
https://jsfiddle.net/handsoncode/8ffpsqt6/

![image](https://user-images.githubusercontent.com/30186818/68743455-ceebb600-05f2-11ea-906d-d918a3f6a91d.png)

**Comment by AMBudnik** [comment]
Thanks for checking @aninde I'm attaching the labels.

**Comment by AMBudnik** [comment]
@somename85 @aninde 

Can you check it once again? I'm on macOS Catalina and tested it on Chrome 83 and Firefox 74. I do not see any issues with the selection.

Maybe I'm doing something wrong - do you hold <kbd>ctrl/cmd</kbd> only for the first few cells and then the selection is done only by the <kbd>LMB</kbd>?

**Comment by aninde** [comment]
This bug is still present on Catalina 10.15.3/ Firefox 75/ Chrome/ Safari I couldn't reproduce it on Linux (Ubuntu) or on Windows.

The problem occurs when you click the cells while holding down the ctrl key. After leaving the control key the selection there is still displaying, although it shouldn't be there. 
Selection stops displaying when you click outside the table (different than in the original issue reported).

In addition, when clicking with the control button pressed, the menu opens. It is because in macOS `click + ctrl` works like a right-click and its opening menu https://support.apple.com/en-gb/guide/mac-help/mh35853/mac.

You can reproduce it without the mouse using the trackpad itself on your MacBook.
![hold-ctrl](https://user-images.githubusercontent.com/30186818/79344328-f80ccb80-7f2f-11ea-9866-738116670120.gif)

Same reproduction with pushed `cmd` do not create any bugs.
![hold-cmd](https://user-images.githubusercontent.com/30186818/79344333-f9d68f00-7f2f-11ea-955e-94116111d9ca.gif)

**Comment by AMBudnik** [comment]
Great! Thank you for explanation @aninde

**Comment by AMBudnik** [comment]
I still get the same issue using v8.0.0 https://jsfiddle.net/handsoncode/8ffpsqt6/ on macOS Catalina 10.15.3 and Chrome 85

**Comment by ottosson** [comment]
Adding test case from https://github.com/handsontable/handsontable/issues/10062

1. Hold down the Command button
2. Select a few ranges / make sure the grid is active
3. While still holding down Command, press Tab to select another window.
4. Use mouse to select another window.
5. Release Command
6. Click the browser window with mouse to activate it again.
7. Select ranges
8. Grid behaves as if Command is still pressed
9. Press and release Command to return to normal behavior

**Comment by ben-carmichael-dentsu** [comment]
I've just noticed a similar issue. (Adding case from https://github.com/handsontable/handsontable/issues/10062)

### Steps to reproduce

- Capture a screenshot using the macOS keyboard shortcut CMD+SHIFT+4
- Select a spreadsheet cell
- Grid behaves as if Command is still pressed

### Environment

- Handsontable version: 12.1.0
- Browser name and version: Chrome (106)
- Operating system: macOS 12.6

**Comment by AMBudnik** [comment]
Thank you @ottosson @ben-carmichael-dentsu

**Comment by AMBudnik** [comment]
We also got a notification to test the fix with the following steps.

> 1. Click on the cell
> 2. ⌘ + C
> 3. Click on another cell

Inform [Zen](https://handsontable.zendesk.com/agent/tickets/30500)

**Comment by adrianszymanski89** [comment]
Inform [Forum](https://forum.handsontable.com/t/grid-selection-bugs-after-browser-search/6638/2)

**Comment by AMBudnik** [comment]
Hi @ottosson @somename85 @ben-carmichael-dentsu I am glad to announce that the issue is fixed. Please update to Handsontable v12.3.1 and let me know if it works for you.
