### ISSUE TITLE
It seems that the Formulas plugin doesn't work well with sorting.

### ISSUE THREAD

**Issue by jansiegel** [handsontable/handsontable#6480]
### Description
In version `6.0.0` the arguments for the `afterColumnSort` and `beforeColumnSort` changed: [docs](https://handsontable.com/docs/6.0.0/Hooks.html#event:beforeColumnSort).

The Formulas plugin [was not rewritten to the new structure](https://github.com/handsontable/handsontable/blob/master/src/plugins/formulas/formulas.js#L399), though, which causes some problems with sorting the formulas.

### Steps to reproduce

1. Go to https://jsfiddle.net/vefcq4wL/ (an example from our docs)
2. Note, that the `Dove` row, contains `D` in the third column
3. Select the `D` cell in the `Dove` row, press <kbd>ENTER</kbd> twice
4. Sort the table by clicking on the `A` header

**Result:** The `Dove` row contains `B` in the third column.

### Note:
It's worth checking if there are any more places, where the `afterColumnSort`/`beforeColumnSort` hooks are not handled properly after the `6.0.0`'s change.

**Comment by AMBudnik** [comment]
Demo updated to v 8.0.0 https://jsfiddle.net/dvbn2ez9/ (issue remains the same)

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **New formula plugin** task reported at https://github.com/handsontable/handsontable/issues/6466

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Comment by AMBudnik** [comment]
This issue is no longer replicable using v9 https://jsfiddle.net/5md2evLx/ with the new HyperFormula engine.
