### ISSUE TITLE
Setting fixedRowsTop as string has unintended consequences (single selection scrolls to far, selects too many cells)

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#6494]
### Description

If the value of `fixedRowsTop` is provided as a string, it seems to work for the beginning. However, after weeks of using it, we have discovered a bug by chance.

Probably there are more bugs, because as it turns out, the value of `fixedRowsTop` (and maybe other properties, starting with `fixedColumnsLeft`?) is not type-checked nor normalized.

### Steps to reproduce

1. Prepare a grid that has `fixedRowsTop` value provided as a string and a big merged cell, which is used to emphasize the problem (though I think the problem is not limited to merged cells)
2. Scroll down the table, so that only the part of the merged cell is visible
3. Click on the merged cell

Expected:
The table should be scrolled up to show the top of the merged cell.

Actual:
The table is scrolled up few rows above the merged cell and we have range selection that has more cells than just the cell that I clicked.

### Demo

https://jsfiddle.net/k0y84mqz/2/

### Your environment
* Handsontable version: 7.2.2
* Browser Name and version: Chrome
* Operating System: Windows

## Screenshot

![bug](https://user-images.githubusercontent.com/566463/69421071-669e8200-0d20-11ea-95bb-603c040c9174.gif)

**Comment by aninde** [comment]
The bug can be reproduce since  `4.0.0.` v.  
In v.  `3.0.0` is fixed https://jsfiddle.net/aninde/ky4e5zfa/1/
`5.0.2` v.  https://jsfiddle.net/aninde/ky4e5zfa/ broken even worse, improper selection was bigger, + 3 rows
<img width="190" alt="Screenshot 2019-11-22 at 12 17 49" src="https://user-images.githubusercontent.com/30186818/69537538-a368b400-0f80-11ea-82ca-25856147ee49.png">

`6.2.2` improper selection was smaller +1 row in the `6.2.2 v.` https://jsfiddle.net/aninde/3mwpLr2v/
<img width="216" alt="Screenshot 2019-11-22 at 12 15 14" src="https://user-images.githubusercontent.com/30186818/69537565-af547600-0f80-11ea-9210-d64f8f3af12d.png">

**Comment by pnowak** [comment]
Good news! This issue got solved v8.0.0. Here's an updated demo - https://jsfiddle.net/f2jkhz78/
