### ISSUE TITLE
Lack of consistency in how the ContextMenu reacts on clicking the menu items

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#6507]
### Description

This issue https://github.com/handsontable/handsontable/pull/6304/ changed behavior on how the context menu items are executed. Since 7.3.0 (and beta 8.0.0) the ContextMenu triggers action on `mouseup` event. Playing with that changes a little bit I've found that RMB click hasn't changed. This leads to some no consistences where LMB executes on `mouseup` and RMB on `mousedown`.

I've compared the behavior with system context menu on Windows OS and all mouse button triggers action on `mouseup` event.

### Steps to reproduce

1. Go to https://jsfiddle.net/9c7kp14n/;
2. Trigger context menu and click some menu item;
3. For comparing click LMB without releasing the button then the same with RMB;

### Demo

https://jsfiddle.net/9c7kp14n/

### Your environment
* Handsontable version: 7.3.0
* Browser Name and version: Chrome
* Operating System: macOS

**Comment by swistach** [comment]
I guess `afterOnCellContextMenu` https://github.com/handsontable/handsontable/blob/develop/src/plugins/contextMenu/menu.js#L189 should only call `event.preventDefault()` and let `beforeOnCellMouseUp` execute a command.

**Comment by aninde** [comment]
If I understood the reproduction correctly, holding or clicking RMB on context menu triggered immediately selected option from context menu. 

So our faulty, actual result from 7.3.0 was:
_Green circle = RMB
Black circle = LMB_
![cm-broken-7 3](https://user-images.githubusercontent.com/30186818/73750507-970d8e00-475d-11ea-878d-a07525a41721.gif)

On 7.4.0 currently tested version that issue is fixed
https://jsfiddle.net/aninde/su0kyo7j/
![cm-fixed-ff-7 4](https://user-images.githubusercontent.com/30186818/73750911-5b26f880-475e-11ea-932f-886367e8779a.gif)

**Comment by AMBudnik** [comment]
While testing on Windows 10 (Chrome 79)

I got a disappearing menu on <kbd>LMB</kbd> and the same for <kbd>RMB</kbd>
![old](https://user-images.githubusercontent.com/10757813/73843040-1cf10e00-481e-11ea-9a73-eb0d85dea842.gif)

Now, in `7.4.0`

The <kbd>LMB</kbd> closes the menu but <kbd>RMB</kbd> executes the command and keeps the menu opened
![new](https://user-images.githubusercontent.com/10757813/73843089-37c38280-481e-11ea-8607-74b970f8b414.gif)

**Comment by aninde** [comment]
This bug no longer occurs on Windows on updated 7.4.0 (build 11.02.20). https://codesandbox.io/s/cold-dew-9kztj
Tested on Windows 10/ Edge 44, Edge Dev 81, Firefox 73, Chrome 79.
It is fixed by new build of release 7.4.0 (11.02.20).
This bug does not occur on Ubuntu / Firefox 68.On Ubuntu contextMenu works like on macOs.

**Comment by AMBudnik** [comment]
Thank you for doing final fixes. The issue fixed officially in 7.4.0

**Comment by aninde** [comment]
Still working with `7.4.1` https://codesandbox.io/s/mystifying-mccarthy-z1md4 on Windows 10 / Edge 44 and Chrome 79.
