### ISSUE TITLE
Allow to change styling for selected areas by introducing currentSelectionClassName 

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6538]
### Description

As @warpech mentioned the following case for border styling https://jsfiddle.net/kayw7e20/1/ won't be possible after publishing the SVG borders. 

As we already have those classes
* activeHeaderClassName
* className
* commentedCellClassName
* currentColClassName
* currentHeaderClassName
* currentRowClassName
* invalidCellClassName
* noWordWrapClassName
* placeholderCellClassName
* readOnlyCellClassName
* tableClassName

I suggest adding currentSelectionClassName that would cover the cases provided in the demo https://jsfiddle.net/kayw7e20/1/ 

![Zrzut ekranu 2019-12-6 o 10 57 40](https://user-images.githubusercontent.com/10757813/70314174-40e0a500-1817-11ea-88cf-69dd356f16ae.png)

### Your environment
* Handsontable version: 7.2.2+
* Browser Name and version: n/a
* Operating System: n/a

**Comment by wojciechczerniak** [comment]
SVG is stylable with CSS. It should be possible but with different CSS properties. 

Are the classes removed from the borders in SVG implementation and we cannot differentiate which belong to the selection?

**Comment by AMBudnik** [comment]
> SVG is stylable with CSS. It should be possible but with different CSS properties.

It might be. Nevertheless, if we allow users to add classes for styling elements we should stay consistent with that rule when it comes to selection. 

Adding `currentSelectionClassName` not only will speed up the process of styling but it will also improve our documentation with an option that is a continuation of previously introduced options (listed above). This might be obvious, but only by providing an option and publishing in the official documentation we give a guarantee of feature maintenance.

**Comment by warpech** [comment]
> SVG is stylable with CSS. It should be possible but with different CSS properties.

It is possible, but pointless. In SVG borders, I have made optimizations that merge multiple borders on a single SVG `<path>` element. For example there will be a single element `<path stroke="#4b89ff" stroke-width="2" stroke-dasharray="5,5"></path>` for multiple cells that have this style of border on any of the edges. At this point, doing any manipulations in CSS to change this `<path>` seem pointless.

I think this issue is incorrect. A correct way would be to expose a JS API for customizing all of the Selection settings (`className`, `border.width`, `border.color`, `border.cornerVisible`, in future: `border.lineStyle`): https://github.com/handsontable/handsontable/blob/84a330dbb5a418fe06f79b7c5c97efbdc44080de/src/selection/highlight/types/cell.js#L11-L16. Curently these settings (or at least `border.*`) are read-only. Even if you find a deep object path to alter them in the runtime, there is no effect of that.

**Comment by warpech** [comment]
This issue was obsoleted by https://github.com/handsontable/handsontable/issues/6656

**Comment by AMBudnik** [comment]
Thank you for the update. I'm closing this feature request.
