### ISSUE TITLE
beforeRowMove args have wrong types

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#6539]
### Description
`beforeRowMove` the first arg has `column` not `row`. 
Also have wrong types [per docs](https://handsontable.com/docs/7.2.2/Hooks.html#event:beforeRowMove) in `settings.types.ts`.

**Comment by aninde** [comment]
This issue is fixed with `7.4.2` https://jsfiddle.net/aninde/zms5o4vg/  by https://github.com/handsontable/handsontable/commit/f83cc5f9db2c1376748659ac0e26011272574f59 and still works well with `8.0.0-beta-rev21` https://jsfiddle.net/aninde/6b3L97dz/.

8-beta2 introduced new one argument because the plugin has been refactored https://github.com/handsontable/handsontable/issues/5068. @scarletfog is it included in the documentation for 8?

![Kapture 2020-07-10 at 14 15 59](https://user-images.githubusercontent.com/30186818/87153561-fa28c100-c2b7-11ea-9df4-c10d79b6be25.gif)

![Screenshot 2020-07-10 at 14 00 25](https://user-images.githubusercontent.com/30186818/87152963-f5174200-c2b6-11ea-8c2e-50d346952e98.png) ![Screenshot 2020-07-10 at 14 00 54](https://user-images.githubusercontent.com/30186818/87152966-f7799c00-c2b6-11ea-8ea8-47fd89a9db4e.png)

**Comment by scarletfog** [comment]
Ooh! Overlooked info in the docs! If it worked well in 7.4.2 I should have changed the description already. And I don't see this issue listed in https://github.com/handsontable/handsontable/releases/tag/7.4.2 as well.

Should we mention it in the release notes of 8.0.0 @wojciechczerniak ?

**Comment by wojciechczerniak** [comment]
No. It should be added to release notes of the release in which it was fixed and removed from all v8 releases/lists.

**Comment by aninde** [comment]
This issue does not apply to Release notes of v8, but additional event parameters should be described in docs https://handsontable.com/docs/7.4.2/Hooks.html#event:beforeRowMove v8's.

**Comment by AMBudnik** [comment]
This issue is solved in v8.0.0

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases
