### ISSUE TITLE
[svg] Borders are blurred and moved when using non-pixel values eg. rem, em like Bootstrap

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6667]
### Description
Borders are blurred when using non-pixel values eg. `rem`, `em` 
After adding bootstrap 
and surrounding div with Handsontable table  with this bootstrap `<h3>test</h3>` (1,75 rem) Handsontable starts to be blurry. 

![Zrzut ekranu 2020-01-27 o 12 32 46](https://user-images.githubusercontent.com/30186818/73177761-14a71d80-4110-11ea-820c-c9be12066c9c.png)

### Demo

https://codesandbox.io/s/bootstrap-800-svg-je9wr

### Your environment
* Handsontable version: 8.0.0-svg
* Browser Name and version: IE, Edge
* Operating System: Windows

**Comment by warpech** [comment]
Please provide more details. I can't see `<h3>test</h3>` in https://codesandbox.io/s/bootstrap-800-svg-je9wr. Is this the correct link? I tried this link but the borders are not blurry. Tested in Chrome/Mac and Firefox/Mac.

**Comment by AMBudnik** [comment]
Here's @aninde demo on **Edge** @warpech 

![GIF](https://user-images.githubusercontent.com/10757813/73634174-de622480-4660-11ea-829e-6c9b7982e858.gif)

The bottom border seems to be fine, but the left and right are blurry.
![image](https://user-images.githubusercontent.com/10757813/73634238-094c7880-4661-11ea-82ad-9bd367697cd7.png)

the same on **Chrome** looks well
![image](https://user-images.githubusercontent.com/10757813/73634327-44e74280-4661-11ea-8ec5-b36b197305a6.png)

also looks well in **Firefox**
![image](https://user-images.githubusercontent.com/10757813/73634448-824bd000-4661-11ea-9a6d-03c248128e81.png)

**Comment by aninde** [comment]
Unfortunately, I can't reproduce this on Codesandbox. @budnix is able to repdocute a blur locally with this code https://codesandbox.io/s/800beta-svg-blur-opolh

**Comment by warpech** [comment]
The problem is related to blurry rendering of SVG when it is preceded by another element that does not have dimensions expressed in pixels.

I can simulate the same problem with a simple SVG object and:
- a native button: https://jsfiddle.net/7btjcy18/
- a font sized with REM units: https://jsfiddle.net/ptzs71ba/

The problem is reproducible in IE and Edge (EdgeHTML).

I don't know what to do :( I will seek help on Stack Overflow.

![2020-02-19 13_00_43-Window](https://user-images.githubusercontent.com/566463/74832698-25664000-5318-11ea-9959-c571b682aad1.png)
![2020-02-19 13_04_01-Window](https://user-images.githubusercontent.com/566463/74832704-25fed680-5318-11ea-9b50-56577d3672fc.png)

### Screenshots

The below screenshots illustrate the problem using the JSFiddles linked above. The left part of the screenshot is Chrome, the right part is Edge (EdgeHTML).

**Comment by warpech** [comment]
After investigation, I have to admit that the problem is not fixable in IE. This is a similar problem to 125%, 150%, 175% DPI. Whenever sub-pixel values come to play, there is very high chance that they will be rendered blurry in IE.

**Comment by krzysztofspilka** [comment]
This is an issue reported for the SVG borders project, which was rejected and won't be implemented in Handsontable.
