### ISSUE TITLE
How can I to do a map in column ? This it's being very bad!

### ISSUE THREAD

**Issue by Wellers0n** [handsontable/handsontable#6675]
E.G.:  columns: props.properties?.map((element: any) => {
            return {
                data: element,
                editor: false,
                type: element.type === "number" ? 'numeric' : 'text',
                renderer: (instance, td, row, col, prop, value, cellProperties) => {}
           }

**Comment by Wellers0n** [comment]
Many renders!

**Comment by Wellers0n** [comment]
I am trying to do a dynamic render with a json, it is possible ?

**Comment by AMBudnik** [comment]
Hey @Wellers0n 

Can you share an example of an input and desired output? If you can't share the code on Github please send it to me on my email support@handsontable.com

**Comment by Wellers0n** [comment]
Oh, I don't can shared the code! :( but I'm trying to do a dynamic render with the json. Do someone tried  this ?

**Comment by Wellers0n** [comment]
I'm bad performance when multiple columns

**Comment by AMBudnik** [comment]
OK so let me describe the situation.

What happens if you load data via `data` / `loadData`. Those methods are used to load data to Handsontable as a complete set of columns and rows. Demo https://jsfiddle.net/9jvgcn5p/
In this case, you can only pass a 2D data - it meats that you pass data for each cell as a sibling - we do not support nested objects.

>  bad performance when multiple columns

The performance doesn't change if you load data via a variable that holds the data or via JSON.parse(). I can imagine a different while using 500k data but it is only a theory. The reason it works slowly has to be connected to the way you operate on the table (adding cell dependencies formulas) or/and how do you style it.

> I can not share the code! 

Would you be able to share the code without the data that you load? We can replace it with our helper while testing.

**Comment by AMBudnik** [comment]
> Would you be able to share the code without the data that you load? We can replace it with our helper while testing.

If you cannot share it here please send it over to support@handsontable.com
