### ISSUE TITLE
[8.0.0-beta1] Doesn't load the table in JFSiddle using Edge

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6700]
### Description

The table does not appear and we get [Access Denied error](https://support.microsoft.com/en-us/help/2623670/access-denied-or-other-errors-when-you-access-or-work-with-files-and-f).

### Steps to reproduce

1. Just open the demo for `8.0.0-beta1` on Edge

Result
![image](https://user-images.githubusercontent.com/10757813/74217979-4b9d3780-4ca9-11ea-88d0-41ebf131f6ed.png)
`Access Denied` error.

### Demo

https://jsfiddle.net/mxdy8rb9/1/ 7.3.0
https://jsfiddle.net/mxdy8rb9/2/ 8.0.0/beta1

### Your environment
* Handsontable version: 8.0.0-beta1
* Browser Name and version: Edge
* Operating System: Windows 10

**Comment by aninde** [comment]
I was able to reproduce it on Edge/ Windows 10.
![Microsoft Edge 11 02 2020 10_43_47 (2)](https://user-images.githubusercontent.com/30186818/74226741-6679a700-4cbd-11ea-9874-84982656954c.png)

It can't be reproduced on Edge or Edge Dev on macOS, so we can assume that it's releted to Windows.

**Comment by AMBudnik** [comment]
Remains the same in 8.0.0.-beta2-rev2 [https://jsfiddle.net/zfe965Lw/](https://jsfiddle.net/zfe965Lw/)

**Comment by aninde** [comment]
As[ support for the Internet Explorer browser is to be deprecated in version 8.0.0](https://github.com/handsontable/handsontable/issues/7026) we decided to close all the issues that are only replicable on that browser. All IE-related workarounds implemented into Handsontable are still a part of the code, and we do not plan to remove them.

This issue is still solved with `8.0.0-beta2-rev15` https://jsfiddle.net/3xwsjbod/. Tested on real Edge 44 and Edge Dev 85.
