### ISSUE TITLE
What JS framework do you use?

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6706]
We’ve been thinking lately about which framework (Vue, Angular, React) should be a priority for us. 
Can you tell us which of them you use and why? 

Many thanks!

**Comment by aninde** [comment]
Maybe we can ask about it on Twitter? @AMBudnik WDYT?

**Comment by aarondfrancis** [comment]
I use Vue. 

I originally heard about Vue because I'm heavily invested in the Laravel ecosystem and it started to gain traction there. Historically I've hated frontend frameworks because I found them to be overly complicated. 

I've stuck with Vue because I find it extremely intuitive and easy to use in conjunction with Laravel. We use server rendered pages with lots of vue components, but never an SPA. 

I started using the Vue wrapper for HoT early on, but quickly ditched it because I needed to do a lot of more complicated stuff and it was easier to just use the vanilla library. 

Hope that helps!

**Comment by m4m4m4** [comment]
Angular here!
We have a lot of history of where I work with angular 1 and are currently trying to find a better option to the stale "UI-Grid" project. Any work to the angular wrapper would help us immensely.

**Comment by guchengjie** [comment]
React, better free control of data, and a more comprehensive ecosystem

**Comment by ottosson** [comment]
Angular in the past but switched to React recently.

**Comment by DongShi** [comment]
React. FP(hooks), one-way data flow, view data seperation,  just name it.

**Comment by zyzhu** [comment]
Angular

**Comment by yimseknyCorarl** [comment]
Angular and AngularJs here

**Comment by gutinono** [comment]
React: it's simple, flexible and powerful.
A really good reason to use it is that Facebook (it's creator) is using it for real in it's biggest applications (Facebook, Instagram, WhatsApp). You can't say the same for Angular & Google (it's creator).

**Comment by AMBudnik** [comment]
Thank you for all your feedback. 🥇 

It looks like there's not a single winner, so keeping all the wrappers in the possible shape should be our plan for the upcoming year. 

As there hasn't been any additional feedback after May 2020, I'm closing this ticket. If anyone else wants to share their opinion, I'd be more than glad to read it.
