### ISSUE TITLE
[7.4.0] After Updating mobile editing does not work

### ISSUE THREAD

**Issue by mariomacedo** [handsontable/handsontable#6707]
### Description
After updating for this new minor release (7.4.0) I can't edit value in a cell on mobile devices. 

### Demo
http://jsfiddle.net/handsoncode/s6t768pq

### Your environment
* Handsontable version: 7.4.0
* Browser Name and version: Chrome 80.0.3987.87
* Operating System: Android 9 / iOS 13

**Comment by aninde** [comment]
The same demo doesn't work on iPad via BrowserStack.

**Comment by aninde** [comment]
@mariomacedo this bug will be fixed by `7.4.1 v.`. We plan to release it soon.

Tested on:
iPhone S / iOS 13.3.1 / Safari (live)
iPad / iOS 13.3.1 (live)
Huawei Mate 20 / Android 10 / Chrome / Chrome Canary / Edge /  Firefox (live)
Mi A2 Lite / Android 8.1.0 / Chrome (live)
Galaxy J4+ / Android 8.1.0 / Chrome (live)

**Comment by AMBudnik** [comment]
Hey @mariomacedo 

Please update to 7.4.2 and let us know if it works for you - the issue should be gone.
