### ISSUE TITLE
Allow to stack changes in the undoRedo plugin

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6731]
### Description

The request is pretty similar to https://github.com/handsontable/handsontable/issues/6358 is a way that it allows users to control what is stacked in the `undoRedo` queue.

Those could be a couple of changes that a developer defines as a single action, like adding a row and attaching a blue background to it.

There is also one example that will help us to imagine how uncomfortable it is to use `undoRedo`. Please take the steps below to replicate.

### Steps to reproduce

1. Select all the cells in the table
2. Copy those cells
3. Select `B10`
4. Paste the cells
5. Undo

![undo](https://user-images.githubusercontent.com/10757813/75251569-1fba9f80-57db-11ea-83c4-e9ba93720d4d.gif)

**Result**
For a user this undo should perform in one step. However, it takes 11 use of undo to get to the state where there are 2 column with data from x1 to x10.

### Demo

https://jsfiddle.net/j8fyhn7x/ `7.4.2`

### Reltaed
* https://github.com/handsontable/handsontable/issues/6358

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: n/a
* Operating System: n/a

**Comment by AMBudnik** [comment]
Update https://github.com/handsontable/handsontable/issues/7324 after adding support for stacking changes

**Comment by john-swallow-cenduit** [comment]
As I suggested on #7501 I reckon that undoing the entire action as a block is probably a relatively tall order due to the way that the Undo/Redo basically puts event invocations onto a stack and there is no composite "make a bunch of rows that look like this" type change. This is probably why this feature has remained static for a year now. 

**However, the situation could be SIGNIFICANTLY improved if the paste operation caused a SINGLE add row instruction to go onto the stack that could then be undone in a single action. That way a paste resulting in 10 new rows would only take 2 undo actions to reverse rather 10 + 1 = 11.

Right now the paste action will fire afterCreateRow 10 times once each for each of the 10 rows it wants rather than once with row count = 10**

**Comment by AMBudnik** [comment]
Thank you for all the likes and feedback on my topic.

I'm moving this topic to Github Discussions. And I welcome everyone to discuss this functionality and share your feedback.
See you there!
