### ISSUE TITLE
Double click on the column resize handle does not adjust size correctly

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#6755]
### Description
When we use `colWidths` within `updateSettings` don't adjust the column’s width to the contents.
In 7.4.2 and previous, after double click on the column resizes handle there is not enough space to contents. 
But in version 8.0.0-beta1 is even worse - nothing change.

### Steps to reproduce

**7.4.2**
1. Open https://jsfiddle.net/nscm6rfb/
2. Double click in the first or second column resize
![mar-04-2020 16-14-54](https://user-images.githubusercontent.com/1555809/75893718-8838fa80-5e33-11ea-8bea-99264851a325.gif)

**8.0.0-beta1**
1. Open https://jsfiddle.net/home7kjv/
2. Double click in the first or second column resize
![mar-04-2020 16-15-17](https://user-images.githubusercontent.com/1555809/75893729-8c651800-5e33-11ea-849f-1096cd00b270.gif)

**Comment by AMBudnik** [comment]
inform [forum](https://forum.handsontable.com/t/gh-6755-double-click-on-the-column-resize-handle-does-not-adjust-size-correctly/4197)

**Comment by aninde** [comment]
Unfortunately, it's not fixed by new `8.0.0-beta2` 

https://jsfiddle.net/aninde/wej42tmv/ `v8.0.0-beta2-rev13` (broken)
https://jsfiddle.net/cjhvg2eb/ `v8.0.0-beta2-rev1` (broken)

**Comment by wojciechczerniak** [comment]
@aninde So it is a v8 regression and should be added to your list?

**Comment by AMBudnik** [comment]
@wojciechczerniak it never worked well as we get this
![Zrzut ekranu 2020-06-15 o 12 05 15](https://user-images.githubusercontent.com/10757813/84645196-84bc1180-af00-11ea-9bb2-25d4812f970f.png)
instead of
![Zrzut ekranu 2020-06-15 o 12 06 20](https://user-images.githubusercontent.com/10757813/84645322-a917ee00-af00-11ea-998e-1374891980a0.png)
(as it happens when we remove `colWidths` and `updateSettings` from the demo).

However, as @pnowak discovered in 8.0.0-beta.1 when we db-click nothing happens, so that's a regression, and should be added to the list.

**Comment by aninde** [comment]
This issue is solved by `8.0.0-beta2rev15` double click on columns resize the width correctly.
https://jsfiddle.net/aninde/v2rm57ag/

![6755-rev15](https://user-images.githubusercontent.com/30186818/84881795-a4814000-b08e-11ea-8526-f0503bdbb938.gif)

**Comment by aninde** [comment]
Still works with `pre-8.0.0-rev1` https://jsfiddle.net/aninde/f1nybdco/.

**Comment by AMBudnik** [comment]
Issue fixed in v 8.0.0.

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases
