### ISSUE TITLE
Undo/Redo on setMeta / custom render

### ISSUE THREAD

**Issue by nicholaskong** [handsontable/handsontable#6759]
### Description
To Whom It May Concern,

Does any one who know how to handle the meta change?
I have create a custom render, but I also want it support Undo/Redo function.
How to do it?

I also find that the Handsontable v6.2.2 does not support these function undo/redo:
1, Border,
2, Freeze Column,
3, Readonly
4, Create Comment.

### Demo
https://jsfiddle.net/8ffpsqt6/298/

### Your environment
* Handsontable version: v6.2.2
* Browser Name and version: Chrome
* Operating System: Linux

**Comment by pnowak** [comment]
Hi @nicholaskong 

Yes, we know of the limitations `undoRedo` plugin - https://github.com/handsontable/handsontable/issues?q=is%3Aissue+is%3Aopen+undo+label%3AUndo-redo

It's hard to achieve `unroRedo` functionality in your custom renderer, because after action of clicking button and change the cellProperties don't call `afterChange` hook. 

On the other hand, you operate on `cellProperties` so you could  use `afterGetCellMeta` hook - https://handsontable.com/docs/7.4.2/Hooks.html#event:afterGetCellMeta - and based on it create a stack of changes. Next you need to react on the undo and redo action and reflect on the handsontable.

Yes, it requires a lot of work ;)

**Comment by nicholaskong** [comment]
> Hi @nicholaskong
> 
> Yes, we know of the limitations `undoRedo` of the plugin - https://github.com/handsontable/handsontable/issues?q=is%3Aissue+is%3Aopen+undo+label%3AUndo-redo
> 
> It's hard to achieve `unroRedo` functionality in your custom renderer, because after action of clicking button and change the cellProperties don't call `afterChange` hook.
> 
> On the other hand, you operate on `cellProperties` so you could use `afterGetCellMeta` hook - https://handsontable.com/docs/7.4.2/Hooks.html#event:afterGetCellMeta - and based on it create a stack of changes. Next you need to react on the undo and redo action and reflect on the handsontable.
> 
> Yes, it requires a lot of work ;)

Hi @pnowak ,

Thanks for you replay.

I have saw that the limitations of UndoRedo plugin.
I see the handson source code, the infrastructure supports well.
That means if user want to undo,redo the custom renderer, he need add the event on the specific  hook (like: afterGetCellMeta / afterSetCellMeta) and custom define some custom undo redo action to handle the this situation. Am I right?

**Comment by pnowak** [comment]
Hi @nicholaskong 

Yes, you right.

Maybe I close this issue, and when you encounter some difficulties you'll open this issue or create the new one. What do you think?

**Comment by nicholaskong** [comment]
Hi @pnowak ,
Thanks.
It's OK. Please Close it. If I have any question, I will ask here.
Thanks a lot.
