### ISSUE TITLE
On "Enter" Press move the focus to the Cell in the Right

### ISSUE THREAD

**Issue by Dinesh-Ramakrishnan** [handsontable/handsontable#68]
On Pressing  "Enter" Key I want to  move the focus to the Cell in the Right instead of moving to the cell below it.  I tried to achieve this by the following hack @line 1450

``` javascript
 if (event.shiftKey) { //if shift+enter, finish and move up
                      editproxy.finishEditing(false, 0 , -1, ctrlDown);
                    }
                    else { //if enter, finish and move down
                      editproxy.finishEditing(false, 0 , 1, ctrlDown);
```

This hack helps me to move the focus to the cell in Right, but after reaching the last cell in the row it is going to the cell directly below it, but I expect it to go to the first cell in the next row.
Please help me to achieve this feature

**Comment by RubbelDieKatz** [comment]
I'm using Handsontable in order to allow people to input data. I want them to either use tab or enter when they are done with a cell, hitting these keys whenever they are done filling a cell.

When a row is completed, they would obviously use enter too, kind of like a typewriter. However, they don't jump to the first cell in the next row.

I can configure this with the `enterMoves` option:

        minSpareCols: 0,
        minSpareRows: 1,
        enterMoves: {row: 0, col: 1}

According to one person on GitHub, [this feature should be in the main code][1]:

> I implemented your suggestion into core :) Please use the following
> set of params and let me know what you think:
> 
> 
>
>     minSpareCols: 0, 
>     enterMoves: {row: 0, col: 1}

[Here's a JSFiddle with my code.][2]

I filled a row with data and pressing enter does nothing.

[![handsontable image][3]][3]

Is there any way to enable this feature?

-------------------------------------

I've copypasted this from [my Stackoverflow question](https://stackoverflow.com/q/46339456/6203984). Maybe some of you can help me with this, I have pretty much the same issue as the OP. 

  [1]: https://github.com/handsontable/handsontable/issues/68
  [2]: http://jsfiddle.net/s6t768pq/971/
  [3]: https://i.stack.imgur.com/sf44Y.png

**Comment by AMBudnik** [comment]
Hi @RubbelDieKatz 
`enterMoves` can be a functions as well, so you can determine how to move when selection reaches the last column.

Here is a demo http://jsfiddle.net/qtfam5v1/ where I move the selection one column left and after we reach the last column we pick the first cell in the next row.
