### ISSUE TITLE
Hide column error after move column

### ISSUE THREAD

**Issue by liuqiurong** [handsontable/handsontable#6819]
### Description
I used handsontable for vue

### Steps to reproduce

![image](https://user-images.githubusercontent.com/5915700/79677305-597bb580-8222-11ea-9982-80d3b8800b5c.png)
1.Move column 'year' to B
![image](https://user-images.githubusercontent.com/5915700/79677337-c7c07800-8222-11ea-85c3-295fe6a797c6.png)

2. Hide column A
![image](https://user-images.githubusercontent.com/5915700/79677346-e45cb000-8222-11ea-9620-05d6db7745f2.png)

**Comment by AMBudnik** [comment]
Hi @liuqiurong 

as you did not provide a demo I've made something similar to what I see in this topic https://jsfiddle.net/AMBudnik/8e7w05bc/

We are able to get merged cells working right, but the cell 0,0 content is lost.
This issue has been already raised here https://github.com/handsontable/handsontable/issues/6668 and should be fixed with https://github.com/handsontable/handsontable/pull/6547

I will update you once it's ready.

**Comment by liuqiurong** [comment]
Dear AMBudnik

Thank you very much for your reply.

May I know your plan about this issue?

**Comment by AMBudnik** [comment]
Hey @liuqiurong last commit to that topic was yesterday and this is a work in progress. I hope that we will be able to push a new version in May.
