### ISSUE TITLE
undo option doesn't work properly with contextMenu

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#6823]
### Description
If the `undo` option - https://handsontable.com/docs/7.4.2/Options.html#undo - is set to `false`  in `contextMenu` both `Undo` and `Redo` are active even without any change.

After clicking any of these options we have an error - `Uncaught TypeError: this.undo is not a function` or `Uncaught TypeError: this.redo is not a function` respectively.

It seems that we rewrite a reference in `contextMenu` callback from function to `false`. 
`this` inside a callback -https://github.com/handsontable/handsontable/blob/master/src/plugins/contextMenu/predefinedItems/undo.js#L12 - is an instance of Handsontable.  

### Steps to reproduce

1. Open an `contextMenu`.
2. Click `Undo` or `Redo`.
3. See console.

### Demo

https://jsfiddle.net/xpswdLyr/

### Releated issue
https://github.com/handsontable/docs/issues/107

**Comment by AMBudnik** [comment]
It works the same in v 8.0.0 https://jsfiddle.net/AMBudnik/L0n861am/

**Comment by aninde** [comment]
This issue is fixed on v8.3.2 https://jsfiddle.net/on6ax5sv/

Undo has no effect while the option set to false and is not in the context menu.

<img width="365" alt="Screenshot 2021-05-07 at 15 01 43" src="https://user-images.githubusercontent.com/30186818/117453394-31521800-af45-11eb-92e3-a8db94bc4e29.png">
