### ISSUE TITLE
Altering columns does not update filters attached to columns.

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6830]
### Description

Altering columns does not update filters attached to columns.

### Steps to reproduce

1. Filter out `C2` from the `C` column
2. Use `Insert column right` on the B column
![Zrzut ekranu 2020-04-23 o 10 20 01](https://user-images.githubusercontent.com/10757813/80076171-108e6e80-854c-11ea-964f-2b05b0567317.png)

**Result**
* dropdown menu icon stays the same for `C` column.
* filter is kept on the `C` column, while is should move to `D`.
![Zrzut ekranu 2020-04-23 o 10 21 29](https://user-images.githubusercontent.com/10757813/80076254-36b40e80-854c-11ea-9dc7-b1073894dba9.png)

### Additional info
It works the same in `8.0.0-beta1` https://jsfiddle.net/AMBudnik/wavpcbjf/

### Demo

https://jsfiddle.net/AMBudnik/28rdamxu/ 

### Your environment
* Handsontable version: 7.4.2
_It doesn't seem to be version related._
* Browser Name and version: Chrome 83
* Operating System: macOS Catalina

**Comment by AMBudnik** [comment]
Demo updated to v 8.0.0 https://jsfiddle.net/ygw3ckpt/ - the issue remains the same.
Related topic https://github.com/handsontable/handsontable/issues/7003

**Comment by aninde** [comment]
This issue will be fixed by v8.3.0.

![6830-chrome-beta-88](https://user-images.githubusercontent.com/30186818/106020083-a8b11980-60c3-11eb-898c-c755550d4ea0.gif)

### Demo
https://jsfiddle.net/aninde/mhuLgvx4/ v8.3.0

### Environment
macOS Big Sur 11.1
- Chrome 87 & Beta 88.0.4324.96
- Safari 14.0.2
- Firefox 85.0 
- Opera 73.0.3856.344
- Edge 88.0.705.5

Windows 10
- Edge 86
- IE 11

**Comment by AMBudnik** [comment]
Works like a charm. Thanks for fixing it.
