### ISSUE TITLE
We're not able to fix a given column index after doing certain operations

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6845]
### Description

We're not able to fix a certain column index after doing certain operations. Those include
* sorting
* filtering
* moving
* resizing
* changing cell meta

I think that it might be related to rendering. 

#### 1. Sorting
1. Go to https://jsfiddle.net/8m3k429e/6/
2. Sort any column
3. Scroll to right
4. Sort another column

![sorting](https://user-images.githubusercontent.com/10757813/80583095-0e2a8980-8a10-11ea-9ad1-b145ac5c34ce.gif)

#### 2. Filtering
1. Go to https://jsfiddle.net/8m3k429e/7/
2. Filter any value from column `B`
3. Filter any value from column `C`
3. Filter any value from column `D`
3. Filter any value from column `E`

**Result**
You'll notice that now you have 3 fixed columns and adding next filtering on any other columns does not change this state.

#### 3. Moving
1. Go to https://jsfiddle.net/8m3k429e/8/
2. Move any row
3. Move any row again

![moving](https://user-images.githubusercontent.com/10757813/80584660-4d59da00-8a12-11ea-8982-2d92f782621f.gif)

**Result**
You'll notice that now you have 3 fixed columns and adding next row movement on any other row does not change this state.

#### 4. Resizing
1. Go to https://jsfiddle.net/8m3k429e/9/
2. double-click any row to autoresize
3. double-click any row to autoresize again

![resizing](https://user-images.githubusercontent.com/10757813/80585060-f4d70c80-8a12-11ea-84cd-dd437b8506e4.gif)

#### 5. Cell meta
1. Go to https://jsfiddle.net/8m3k429e/10/
2. Make any cell [readOnly](url)
3. Make any cell `readOnly` again

![meta](https://user-images.githubusercontent.com/10757813/80585625-f8b75e80-8a13-11ea-9d0e-ae04d6e76389.gif)

### Additional info
* it doesn't seem to be fixed using latest develop (beta2) https://jsfiddle.net/cuhtao9k/
* It always ends up with columns `C`, `B`, and `A` (in that order) being fixed.

### Demo

https://jsfiddle.net/8m3k429e/6/ (8.0.0-beta1)

### Your environment
* Handsontable version: 8.0.0-beta1
_it doesn't seem to be version related_
* Browser Name and version: Chrome 83
* Operating System: macOS Catalina

**Comment by AMBudnik** [comment]
**Case 1** was not clear enough and demo lacked the contextMenu: true 

1. Use this demo https://jsfiddle.net/zutk60h9/
2. Scroll to cell `O` and use 'Freeze column' from the context menu
3. Scroll to cell `AB` 
4. Sort frozen column

**Result**
An additional new column gets frozen.
![Zrzut ekranu 2020-07-17 o 14 12 19](https://user-images.githubusercontent.com/10757813/87784949-8c404480-c837-11ea-87a8-e3d777f43e07.png)
![Kapture 2020-07-17 at 14 12 42](https://user-images.githubusercontent.com/10757813/87784977-a0844180-c837-11ea-8263-299a9eb91be4.gif)

Works the same in `8.0.0-rev1` https://jsfiddle.net/gfjz3L9x/

**Comment by pnowak** [comment]
**Case 1** is still replicable using v8.0.0. Here's an updated demo - https://jsfiddle.net/fs1vkaLz/

**Case 2** is still replicable using v8.0.0. Here's an updated demo - https://jsfiddle.net/rytv8jeh/

**Case 3** is still replicable using v8.0.0. Here's an updated demo - https://jsfiddle.net/hzy0Lspb/

**Case 4** is still replicable using v8.0.0. Here's an updated demo - https://jsfiddle.net/n0hakmru/

**Case 5** is still replicable using v8.0.0. Here's an updated demo - https://jsfiddle.net/a8p62xde/

**Comment by swistach** [comment]
From the architecture perspective, post-v8 behaviour is correct, accordingly to the documentation for `ManualColumnFreeze.freezeColumn`, we operate on the visual indexes. Freezing columns means: "move a column from the passed visual index to the visual position equal to `fixedColumnsLeft` and then increase `fixedColumnsLeft` by 1". In this example that means we freeze columns in the following order:
1) move column `C` to the visual position: 0 and set `fixedColumnsLeft` as: 1
2) move column `B` to the visual position: 1 and set `fixedColumnsLeft` as: 2
3) move column `A` to the visual position: 2 and set `fixedColumnsLeft` as: 2
...
each next try to set `A` as a fixed column will do nothing, because of the fact that it is already the "frozen" column.

Here is a visual presentation of the above steps:
![image](https://user-images.githubusercontent.com/11849621/106456399-c5679b80-648d-11eb-9d1e-63699a5fb180.png)
