### ISSUE TITLE
[8.0.0.-beta2-rev2] NestedRows: we are able to remove a parent - but only if it's not the last one.

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6860]
### Description

Issue extracted from https://github.com/handsontable/handsontable/issues/6433 > Case 2.
The following issue contained too many examples so I decided to split those which are solved from those which aren't solved.

### Steps to reproduce

1. Choose 'Remove row' from the context menu for `Best Metal Performance`.
2. Undo

**Result**
* you cannot undo
* you get a console error
![Zrzut ekranu 2020-05-11 o 13 52 06](https://user-images.githubusercontent.com/10757813/81559558-ed5b2000-938f-11ea-8a9b-e869a1d8e471.png)

It's a regression case in 8.0.0.-beta1 we did not get an error and some rows were back.

![beta1](https://user-images.githubusercontent.com/10757813/81559764-4e82f380-9390-11ea-8ccf-bd24a0b35113.gif)

### Demo

https://jsfiddle.net/k5nav2rw/ (8.0.0.-beta2-rev2)

### Additional info
* breaks only when the last parent is removed

### Your environment
* Handsontable version: 8.0.0.-beta2-rev2
* Browser Name and version: Chrome 80
* Operating System: macOS Catalina

**Comment by wszymanski** [comment]
May be related to the https://github.com/handsontable/handsontable/pull/6678.

**Comment by aninde** [comment]
This bug is fixed with `8.0.0.-beta2-rev8`, there's no error in console and parent, a removed row is back, but without their children rows. Is that a result that we want to achieve?

![6860-rev8](https://user-images.githubusercontent.com/30186818/82917616-efb6a000-9f73-11ea-8137-8469dbb12e08.gif)
https://jsfiddle.net/aninde/ykdnh710/  
https://jsfiddle.net/aninde/th2uxok4/ - both `v8.0.0.-beta2-rev8`

**Comment by aninde** [comment]
This issue is still fixed with `8.0.0-beta2-rev22` https://jsfiddle.net/aninde/xfmgeq3o/ so I'm closing it.
