### ISSUE TITLE
[7.0.0] If the first part of the merged area is hidden the value does not show

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6871]
### Description

If the first part of the merged area is hidden the value does not show. It seems that the merged area is empty.

### Steps to reproduce

1. Open the example and check the value of the merged area

**Result**
![Zrzut ekranu 2020-05-12 o 15 29 59](https://user-images.githubusercontent.com/10757813/81697883-a2abd780-9465-11ea-98b7-cb39906f1c5c.png)

When we open the editor we see that `C2` is there
![Zrzut ekranu 2020-05-12 o 15 31 46](https://user-images.githubusercontent.com/10757813/81698032-bc4d1f00-9465-11ea-8079-b873b781b686.png)

### Demo

https://jsfiddle.net/sm7d8x4n/4/ 7.4.2

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: Chrome 80
* Operating System: macOS Catalina

**Comment by aninde** [comment]
Probably this bug was introduced by `7.0.0v.`. It cannot be reproduced in earlier versions, because there were some issues with hidden and mergedCells  https://github.com/handsontable/handsontable/issues/6376

https://jsfiddle.net/aninde/bmf5dkhn/ - `6.2.2` partially fixed, content is visible, but `hiddenColumns` are broken.
<img width="338" alt="Screenshot 2020-06-04 at 11 39 58" src="https://user-images.githubusercontent.com/30186818/83741247-40a35400-a658-11ea-8636-9eb502f6ebdf.png">

https://jsfiddle.net/aninde/tv07ak3n/ - `7.0.0` broken

**Comment by wszymanski** [comment]
FYI: Pull request https://github.com/handsontable/handsontable/pull/7172 fixing the issue is ready for the CR. Hope it will solve your problems @warpech, @leriel.

**Comment by AMBudnik** [comment]
v 8.0.0 https://jsfiddle.net/AMBudnik/2ngfjre1/ demo works the same.

**Comment by aninde** [comment]
This issue will be fixed by the upcoming `v8.1.0` 
https://jsfiddle.net/aninde/rz31kdcv/
https://jsfiddle.net/aninde/7521avbr/

Works well on every supported browser.
Tested on `Firefox 81.0`, `Safari 14`, `Chrome 85.0.4183.121`, `Edge 85`, `Opera 71.0.3770.171` / latest `macOS Catalina 10.15.17`

**Comment by AMBudnik** [comment]
We can close the issue as solved in v 8.1.0. 
Thank you for updating demos @aninde
