### ISSUE TITLE
When the dropdown is clicked, the afterInit hook is triggered.

### ISSUE THREAD

**Issue by ahndohun** [handsontable/handsontable#6931]
### Description
When the dropdown is clicked, the afterInit hook is triggered.
Is this the intended function? Or is it wrong to register the hook?

### Steps to reproduce
1. Click the dropdown.
2. afterInit hook is triggered.

### Demo

https://codesandbox.io/s/affectionate-gagarin-s0440?file=/src/App.vue

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: chrome 81.0.4044.138
* Operating System: mac os catalina 10.15.4

**Comment by pnowak** [comment]
Hi @ahndohun 

`dropdown` editor is based on `autocomplete` which in turn is based on `handsontable` editor. `handsontable` editor is a completely new instance of Handsontable.

So `afterInit` is from not the main instance of Handsontable, but form the `dropdown` instance. Therefore, it is intended and expected behaviour.
