### ISSUE TITLE
[8.0.0-beta2-rev8] Undoing removal of nestedrows when all collapsed parents are selected don't work

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6941]
### Description
When all collapsed parents rows are selected, removing all of them by `contextMenu`  can not be undone. 
In 8.0.0-rev8 only corner left after that, with is a regression for 7.4.2, where colHeaders stay with the corner.

Expected result: we want to be able to delete rows and undo this operation.
The question remains whether we want nested children-rows to return after the undo.

#### Case 1
1. Collapse each parent row.
2. Select all of them by dragging the selection.
3. Remove rows by contextMenu

#### Case 2
1. Collapse each parent row.
2. Select all of them by clicking and holding rowHeaders.
3. Remove rows by contextMenu

**Actual result of all cases in 7.4.2, 1.14.0**
colHeaders left, cannot undo.
<img width="389" alt="Screenshot 2020-05-27 at 12 11 05" src="https://user-images.githubusercontent.com/30186818/83006969-458e5500-a013-11ea-8d72-a5911ca19b2c.png">

**Actual result of all cases in 8.0.0-beta2-rev.8**
Only corner left, cannot undo.
<img width="363" alt="Screenshot 2020-05-27 at 12 12 13" src="https://user-images.githubusercontent.com/30186818/83007003-5048ea00-a013-11ea-9615-ea17f19d8b5c.png">

**Actual result 8.0.0-beta1:**
Nothing happens +  the same error in console
handsontable.full.js:108164 Uncaught TypeError: Cannot read property '__children' of undefined
handsontable.full.js:108164 
![chrome-case3](https://user-images.githubusercontent.com/30186818/82996148-d7db2c80-a004-11ea-90bd-89db660078f4.gif)

### Demo

https://jsfiddle.net/wojciech/j4fs38oz - vbeta1 (broken worse, with error in console)
https://jsfiddle.net/aninde/9q5hjobm/1/ - v8.0.0-beta2-rev1 (broken)
https://jsfiddle.net/572Lefpz/ - v7.4.2 (partially fixed, cannot undo)
http://jsfiddle.net/aninde/65ur7aLb/ - v1.14.0 (partially fixed, colHearders stays, cannot undo)
http://jsfiddle.net/aninde/ekLrxap4/ v8.0.0-beta2-rev8 (partially fixed, can not undo, only corner left)

### Your environment
* Handsontable version: 8.0.0-beta1 (the worst),  v1.14.0 can not undo
* Browser Name and version: Firefox, Chrome
* Operating System: macOs Catalina

**Comment by aninde** [comment]
Can be related to https://github.com/handsontable/handsontable/issues/6890

**Comment by aninde** [comment]
8.0.0.-beta2-rev-10 still got same bug https://jsfiddle.net/aninde/xmgvnyj5/

**Comment by jansiegel** [comment]
If the only difference between `7.4.2` and the current version is the fact that there are no column headers left (which I think is intentional: https://github.com/handsontable/handsontable/pull/6947#issuecomment-635383671), and undo doesn't work in both cases, is this _really_ a regression? @aninde @wojciechczerniak

**Comment by wojciechczerniak** [comment]
@aninde As @jansiegel mentioned, the difference in headers display is intentional.

@jansiegel Undo/redo issue might be a regression? But I think this issue is the same @budnix already solved in #6947. When we remove **all rows** the columns can't be restored. It should be fixed on develop so you don't see it anymore.

**Comment by AMBudnik** [comment]
Here's a demo made out of the [`latest commit`](https://github.com/handsontable/handsontable/commit/9c857eaacc73976419837b2e8111c00bbb7d9a49) on the `develop` branch http://jsfiddle.net/AMBudnik/47xyb90m/ and with @aninde 's scenario it breaks the same way.

![issue](https://user-images.githubusercontent.com/10757813/83606494-ffd50d80-a579-11ea-9c11-c69ab1f1d71a.gif)

It is broken really bad, as any interaction with the table throws the same error.

**Comment by wojciechczerniak** [comment]
@AMBudnik latest commit on develop branch doesn't have `/dist` rebuild. You're checking 7.2.2 build with the `buildDate`: 07/11/2019 19:18:08

**Comment by AMBudnik** [comment]
You're right @wojciechczerniak I guess I got too excited about solving this one... 🙈 

Here's the proper demo http://jsfiddle.net/AMBudnik/o1v0z3af/

**Reproduction**
![ok](https://user-images.githubusercontent.com/10757813/83612646-f9975f00-a582-11ea-8e20-32b57de3c4c9.gif)

We **do not** get any console errors, we're able to get back all the parents with undo.

**Comment by jansiegel** [comment]
@AMBudnik  So basically it works like `7.4.2` and we can close this one, right?

**Comment by aninde** [comment]
@jansiegel true,  the regression error is that after removing only the corner remains. However, this is planned, so I think we can close this issue.

**Comment by wojciechczerniak** [comment]
Just a note to @AMBudnik gif. For future generations 

As you can see the headers are kept in this example. It's because they are deliberately defined in the config and have custom names, therefore they should always be displayed. The columns and rows headers that were kept in v7 and are gone now, are the ones that are generated from the data set. Because the whole data set is removed, there are no rows, nor columns that can (or should) be shown

**Comment by aninde** [comment]
@scarletfog this may be useful to you for Release Notes.
