### ISSUE TITLE
Safari draws different borders than Chrome and FF, when editor is opened

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6955]
### Description

Safari draws different borders than Chrome and FF, when editor is opened. 

You'll see that Firefox does not select content, but this behavior is already mentioned here https://github.com/handsontable/handsontable/issues/6954

### Steps to reproduce

1. Open editor for any cell

![Zrzut ekranu 2020-05-28 o 15 28 58](https://user-images.githubusercontent.com/10757813/83147914-90ce6380-a0f8-11ea-9369-876ff1e05993.png)
Firefox

![chrome](https://user-images.githubusercontent.com/10757813/83147924-94fa8100-a0f8-11ea-8346-fda30dbd1e9f.png)
Chrome

![safari](https://user-images.githubusercontent.com/10757813/83147930-975cdb00-a0f8-11ea-9c32-43199f6137ba.png)
Safari

### Demo

https://jsfiddle.net/AMBudnik/hfokp5ze/ 7.4.2 (browser incompatibility)
https://jsfiddle.net/AMBudnik/54qn1fp2/ 8.0.0-beta2-rev10 (browser incompatibility)

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: Safari 13.0.5
* Operating System: macOS Catalina

**Comment by aninde** [comment]
I'm not sure if this is a bug. After you noticed that my editor is purple I discuss it with @wojciechczerniak and @wszymanski. It turns out that in Os X there is an `accent` and `highlight colour` that can be changed in System Preferences/General. It's an extra shell on the active element. It's blue by default.

In other browsers, this does not affect Handsontable, what is strange.
You can see it after choosing the focus on the browser address bar. On the PrintScreen from my Chrome, there's a delicate green border.

<img width="789" alt="Screenshot 2020-05-28 at 17 13 45" src="https://user-images.githubusercontent.com/30186818/83159752-a0ed3f80-a106-11ea-8a9f-7c60c27ed102.png">

![Screenshot 2020-05-28 at 17 12 56](https://user-images.githubusercontent.com/30186818/83159785-aa76a780-a106-11ea-9ae8-16d2bd9433f7.png)

**Comment by aninde** [comment]
@wojciechczerniak are we able to fix it in Handsontable or do we close this report as `won't do`?

**Comment by wojciechczerniak** [comment]
Safari user-agent has additional styles of `outline`. This is fixable.

Maybe with the Design Patch Project?

**Comment by jansiegel** [comment]
I think it's resolved with #7113?

**Comment by AMBudnik** [comment]
@jansiegel it looks same in pre 8.0.0-beta2 on my Macbook Air (Catalina 10.15.3)

Chrome
![Zrzut ekranu 2020-07-14 o 14 23 47](https://user-images.githubusercontent.com/10757813/87425309-b4346b80-c5dd-11ea-9691-38ed31ef2bbb.png)


Safari 
![Zrzut ekranu 2020-07-14 o 14 24 01](https://user-images.githubusercontent.com/10757813/87425314-b7c7f280-c5dd-11ea-8449-944bcc8393a8.png)

When it comes to border @aninde discovered that newer versions of Catalina provide some changes https://github.com/handsontable/handsontable/issues/7103

**Comment by aninde** [comment]
@AMBudnik #7113 isn't yest merged to 8.0.0-beta2 :)

**Comment by aninde** [comment]
It's fixed with pre-8.0.0 https://jsfiddle.net/aninde/c0awdm89/. There is no additional border on  `Safari 13.1.2 (15609.3.5.1.3)` and `Safari Technology Preview Release 110 (Safari 14.0, WebKit 15610.1.21.0.2)` anymore.
I have added this for #6465. CC: @scarletfog

**Comment by AMBudnik** [comment]
Thank you for fixing guys! 

For anyone watching the changes to this thread. We just released v 8.0.0 of Handsontable that solves the issue with the border inconsistency. Feel welcome to share any feedback.

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases
