### ISSUE TITLE
[7.0.0] The editor is moved by 1px when the first row / column is hidden

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#6982]
### Description

The first row/column has a border added to fit with overlays.  But if the first row/col is hidden then this 1px was also hidden, so the editor is also moved by 1px.

Related to https://github.com/handsontable/handsontable/issues/5817
### Steps to reproduce

1. Open demo https://jsfiddle.net/aninde/u62059q7/
2. Click and open editor in B1.
3. Click and open editor in B2.
![7 0 0](https://user-images.githubusercontent.com/30186818/83765122-144cff00-a67b-11ea-8228-605c510235bb.gif)

**Reproduction in current version 7.4.2**
<img width="277" alt="Screenshot 2020-06-04 at 15 50 55" src="https://user-images.githubusercontent.com/30186818/83765495-87ef0c00-a67b-11ea-89a8-83d21ff566eb.png">

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/ - `v7.0.0`
https://jsfiddle.net/aninde/cbez3pyw/ - `v7.4.2`

### Your environment
* Handsontable version: 7.0.0
* Browser Name and version: any
* Operating System: any

**Comment by AMBudnik** [comment]
Issue's fixed in `8.0.0-beta2-rev21` https://jsfiddle.net/Lmzf0152/ after the merge of #7084

**Comment by AMBudnik** [comment]
This issue is solved in v 8.0.0 of Handsontable.

CDN https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.css
https://cdn.jsdelivr.net/gh/handsontable/handsontable@latest/dist/handsontable.full.js
NPM npm i handsontable
Release Notes https://github.com/handsontable/handsontable/releases
