### ISSUE TITLE
[8.0.0-beta2-rev7] When fixedRowsBottom are applied and we filter out all data fixedRowsBottom remains

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7004]
### Description

When `fixedRowsBottom` are applied and we filter out all data `fixedRowsBottom` remains.

### Steps to reproduce

1. Go to any column's dropdown menu
2. Click 'Clear' on the 'Filter by value' section 
3. Click green OK button

**Result**
![bad](https://user-images.githubusercontent.com/10757813/84138611-d2db9b80-aa4e-11ea-8640-4bbf9e066006.gif)

When you try to edit `A48` you get

![Zrzut ekranu 2020-06-9 o 12 45 10](https://user-images.githubusercontent.com/10757813/84138828-38c82300-aa4f-11ea-8b99-5e2f99c8dcd0.png)

**Expected result**
![good](https://user-images.githubusercontent.com/10757813/84138607-d111d800-aa4e-11ea-966f-5c1bbff8f600.gif)

### Demo

https://jsfiddle.net/AMBudnik/2rutqkyo/ 7.4.2 (works well)
https://jsfiddle.net/AMBudnik/fk74tecz/ 8.0.0.-beta2-rev1 (works well)
https://jsfiddle.net/AMBudnik/oqpL120r/ 8.0.0.-beta2-rev6 (works well)
https://jsfiddle.net/AMBudnik/7w4Lfv05/ **8.0.0.-beta2-rev7 (broken)**
https://jsfiddle.net/AMBudnik/tonesx4z/ 8.0.0.-beta2-rev12 (still broken)

### Your environment
* Handsontable version: 8.0.0-beta2-rev7
* Browser Name and version: Chrome 80
* Operating System: macOS Catalina

**Comment by AMBudnik** [comment]
It may change something for https://github.com/handsontable/handsontable/issues/6703

**Comment by wojciechczerniak** [comment]
Might be connected with #6922

**Comment by wszymanski** [comment]
Problem partially doesn't exist for simple API calls such like:

- ```js
  hot.getPlugin('trimRows').trimRows(Array.from(Array(50).keys())); hot.render()
- ```js
  hot.getPlugin('filters').addCondition(0, 'contains', ['b']); hot.getPlugin('filters').filter();
- ```js
  hot.getPlugin('hiddenRows').hideRows(Array.from(Array(50).keys())); hot.render();

We can't see cells, however, `TD` elements still exist here. Please look at the below image.

![Screenshot 2020-06-10 at 12 25 17](https://user-images.githubusercontent.com/141330/84257358-827b4100-ab15-11ea-8ad7-640b9808432d.png)

**Comment by aninde** [comment]
https://jsfiddle.net/aninde/x8hL0pfv/ without `updateSettings` this issue is fixed. Same with `fixedColumnsLeft`, `fixedRowsTop` and `HiddenColumns`. Individual classes associated with them do not contain `TD` elements in `tbody`.
https://jsfiddle.net/aninde/aeoz4jyq/  (**solved**) `v.8.0.0-beta.2-rev15`

![7004-rev15](https://user-images.githubusercontent.com/30186818/84921399-b67dd580-b0c4-11ea-8078-e598c4c177a9.gif)

**Case 2**
However when we try to reproduce it according to a very smart suggestion of @wszymanski with `updateSettings`, the bug is still there. 
This is not regression, it can also be reproduced in version `7.4.2.` 

So I suggest closing this issue and we will move **Case 2** to a new one. 
@wojciechczerniak WDYT?

![with updatesettings](https://user-images.githubusercontent.com/30186818/84921444-c5fd1e80-b0c4-11ea-8a24-c44c4b252a27.gif)
https://jsfiddle.net/aninde/vw6kqnm0/ - (**broken**) `v.8.0.0-beta.2-rev15`
https://jsfiddle.net/aninde/zsby6kc1/ - (**broken**) `v7.4.2`

**Comment by AMBudnik** [comment]
> So I suggest closing this issue and we will move Case 2 to a new one.
@wojciechczerniak WDYT?

👍

**Comment by wojciechczerniak** [comment]
> > So I suggest closing this issue and we will move Case 2 to a new one.
> 
> @wojciechczerniak WDYT?
> 
> 👍 

👍

**Comment by AMBudnik** [comment]
Glad we agree. I've created the `updateSettings'` topic here https://github.com/handsontable/handsontable/issues/7024 so we can close this regression as **solved**.
