### ISSUE TITLE
Usage of nestedrows and data in "updateSettings"

### ISSUE THREAD

**Issue by gianadrias** [handsontable/handsontable#7017]
### Description
I've been trying to use the nestedrows inside updatesettings function but it seems the data is not displaying according to the nested data.

I tried to add the nestedrows on first initialize but it gives me an error too.
![image](https://user-images.githubusercontent.com/11287662/84755420-39832b00-aff4-11ea-8628-d4eaa283a3b3.png)

![image](https://user-images.githubusercontent.com/11287662/84755322-19ec0280-aff4-11ea-96f6-63d5243ff4d2.png)

### Steps to reproduce
1. Go To [https://jsfiddle.net/86gnmtxs/](https://jsfiddle.net/86gnmtxs/)

### Demo
[https://jsfiddle.net/86gnmtxs/](https://jsfiddle.net/86gnmtxs/)

### Your environment
* Handsontable version: 8.0.0-beta.1

**Comment by pnowak** [comment]
Hi @gianadrias 

I can't see any console error in your demo:
<img width="371" alt="Zrzut ekranu 2020-06-16 o 11 37 51" src="https://user-images.githubusercontent.com/1555809/84759246-beefe680-afc6-11ea-9198-8c6170189644.png">

Nevertheless, thank you for test our beta version.
Could you check the newest version of beta.2 - https://cdn.jsdelivr.net/gh/handsontable/handsontable@730c08e62d04b028092f4078c95d2b417aafdec9/dist/

Maybe your issue will disappear in that version.

**Comment by AMBudnik** [comment]
When I use @gianadrias demo https://jsfiddle.net/86gnmtxs/ and collapse the parent I cannot expand the rows. I've replaced 8.0.0-beta1 with 8.0.0-beta2-rev16 (latest) https://jsfiddle.net/z94agwxe/ and got the same issue.
It did not work well in 7.4.2 https://jsfiddle.net/L7kn0d64/ where we experienced a lack of data, so that's not a regression. Nevertheless, that's a bug.

I wasn't able to generate the console error tough.

**Issue origin**
The issue is gone if we move `nestedRows` declaration from `updateSettings` to the initialization settings https://jsfiddle.net/z94agwxe/2/

**Comment by AMBudnik** [comment]
This issues
* incorrect columns widths
* inability to expand collapsed parent

are still replicable in v8.0.0 https://jsfiddle.net/AMBudnik/3zL6vya9/

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **NestedRows grouped issue** task reported at https://github.com/handsontable/handsontable/issues/7510

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Comment by AMBudnik** [comment]
The issue works the same in the newest version - 11.0.1 https://jsfiddle.net/p4Lo93ve/1/

**Comment by adrianszymanski89** [comment]
Inform [Forum](https://forum.handsontable.com/t/changing-nested-rows-after-initialization/6142)
