### ISSUE TITLE
MinSpareRows input is cleared in NestedRows

### ISSUE THREAD

**Issue by gianadrias** [handsontable/handsontable#7019]
### Description
Whevener I enter data in cell it always cleared on first attempt.

Reference Video:
[https://www.dropbox.com/s/q0icn0ef0y5d5tc/Handsontable.avi?dl=0](https://www.dropbox.com/s/q0icn0ef0y5d5tc/Handsontable.avi?dl=0)

### Steps to reproduce
1. Go to [https://jsfiddle.net/xfngjo24/1/](https://jsfiddle.net/xfngjo24/1/)
2. Input any data in spare rows

### Demo
[https://jsfiddle.net/xfngjo24/1/](https://jsfiddle.net/xfngjo24/1/)

**Comment by AMBudnik** [comment]
Thank you for sharing the issue I see that you're already testing rev14 of 8.0.0-beta2.

When we check it with 
* 7.4.2 https://jsfiddle.net/AMBudnik/xtdhLzbr/2/,
* and 7.0.0 https://jsfiddle.net/AMBudnik/5btrv0ny/,
* and beta1 of 8.0.0 https://jsfiddle.net/AMBudnik/vojy19fu/

we get a console error and the table does not display itself, so we cannot call it a regression.

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **NestedRows grouped issue** task reported at https://github.com/handsontable/handsontable/issues/7510

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com
