### ISSUE TITLE
Wrong formula value after double-clicking dependent cell

### ISSUE THREAD

**Issue by chrisxue815** [handsontable/handsontable#7041]
### Demo
https://jsfiddle.net/s8y7r6p9/

Double-clicking A1 or A2 and pressing Enter makes formula cell D1 or D2 change to a wrong value.

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: Chrome Version 83.0.4103.106 (Official Build) (64-bit)
* Operating System: macOS Catalina 10.15.4

**Comment by AMBudnik** [comment]
Hi @chrisxue815 

You're right. It looks like it returns MAX, not MIN.
The issue remains broken on 8.0.0-beta2-rev16 https://jsfiddle.net/yv4wtoLx/
This issue might be related to https://github.com/handsontable/handsontable/issues/4675

Tested on Chrome 83 / macOS Catalina.

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **New formula plugin** task reported at https://github.com/handsontable/handsontable/issues/6466

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Comment by AMBudnik** [comment]
Hi @chrisxue815 

This issue is no longer replicable using v9 with the new _HyperFormula_ engine. Updated demo https://jsfiddle.net/egbowtLv/

Here is a list of changes for the following version https://handsontable.com/docs/9.0.0/tutorial-release-notes.html and here https://handsontable.com/docs/9.0.0/tutorial-migration-guide.html is a migration guide (from v8 to v9)
