### ISSUE TITLE
SUMIF support for optional sum_range

### ISSUE THREAD

**Issue by jacekbogdanski** [handsontable/handsontable#7072]
### Description
According to https://support.microsoft.com/en-us/office/sumif-function-169b8c99-c05c-4483-a712-1697a653039b SUMIF function also accepts third, optional argument which will be used as a sum range if provided. Signature looks like:

```
SUMIF(range, criteria, [sum_range])
```
However, it seems like Handsontable doesn't support this option and uses only the first range if criteria succeed.

The original issue has been reported at https://github.com/ckeditor/ckeditor4/issues/4133

### Steps to reproduce
1. Open https://codepen.io/jacekbogdanski/pen/LYGeBOK
2. Verify the value of `C1`.

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: Chrome Version 81.0.4044.122 (Official Build) (64-bit)
* Operating System: Linux Fedora 31

**Comment by AMBudnik** [comment]
True. There's something wrong with the calculation. We should get `30` in `C1`.

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **New formula plugin** task reported at https://github.com/handsontable/handsontable/issues/6466

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Comment by AMBudnik** [comment]
Hi @jacekbogdanski @kilanoff

I've just checked the following issue with Handsontable v9.0.0 with the new HyperFormula engine and this issue is no longer replicable.

Here's an updated demo https://codepen.io/aleksandra-budnik/pen/RwpBNOK

And here is a full list of changes https://handsontable.com/docs/9.0.0/tutorial-release-notes.html
