### ISSUE TITLE
Add the beforeSelection hook

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7111]
### Description

I had a discussion on the ability to add this hook. It would be a great idea to **be able to block** the selection for 
* some of the cells
* in some circumstances 

I would like the hook to use coordinates as parameters, for example

```js
beforeSelection: function(row, column){
  if(row === 0 && column === 0){
   return false
  }
}
```

would block the selection on the first cell in the spreadsheet (coordinates `0, 0`).

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: any
* Operating System: any

_Inform Zen 25108_

**Comment by mcastro84** [comment]
It would be great to also have the prevRow and prevColumn available.

A possible use case for this:
While using the keyboard to navigate through rows, I want to skip a row and select the next available row.
Now since there's no way of knowing if the user pressed ArrowUp or ArrowDown, I could infer the direction of the navigation based on the prevRow value

Example:

A1
A2 - should skip this row
A3
A4

If I'm on row A1 and press ArrowDown, beforeSelection() runs, I see that prevRow=0 and row=1 so I know the next available row should be A3. The opposite would happen if I'm on row A3 and press ArrowUp it should see that prevRow=2 and row=1, so find the next available row above.

I hope this makes sense, please let me know if there's any further detail I can provide.

**Comment by AMBudnik** [comment]
Thank you for sharing feedback on my idea.

I'm moving this topic to Github Discussions. And I welcome everyone to discuss this functionality and share your feedback.
See you there!
