### ISSUE TITLE
Disable deselect when clicked outside of the table

### ISSUE THREAD

**Issue by Xenorage** [handsontable/handsontable#7140]
### Description
When you click outside of the table selections will be cleared.
I figured out if you remove 'mousedown' event handler from 'html' element  then selection wont be cleared.
However I was unable to do it from code.

### Steps to reproduce
Select a cell in the table then click outside of the table.

### Your environment
* Handsontable version: 7.4.2
* Browser Name and version: chrome 83.0.4103.116
* Operating System: win 7

**Comment by pnowak** [comment]
Hi @Xenorage 

This is intentional behaviour. If we click outside the table, we close an editor. 
Here is a tutorial about the cell editor - https://handsontable.com/docs/7.4.2/tutorial-cell-editor.html

Could you explain to me what is your project requirements?
What exactly you'd like to get? 

Can you attach a demo where we can reproduce the issue? Please describe all the steps to do so.

**Comment by Xenorage** [comment]
Look at the table in this example.
https://handsontable.com/docs/7.4.2/demo-scrolling.html
You click on a cell. The cell gets a blue outline and row and column headers get darker.
It is selected.
But you when click out side of the table the blue outline goes away (deselected).
I want to keep the selection if I click outside of the table.
I don't know  what editor are you talking about...
I was not editing the cell, only selecting it.
Can this behavior be disabled?
if not it should be implemented.
I did remove 'mousedown' event handler from 'html' element with chrome devtools then the selection wont be cleared.
But I cant do it from javascript.

**Comment by pnowak** [comment]
Deselecting after clicking outside the table is default and intentional behaviour.

Fortunate you could use a `outsideClickDeselects` options to change this. Here is a link to our docs - https://handsontable.com/docs/7.4.2/Options.html#outsideClickDeselects and to the demo - https://jsfiddle.net/mwqf4c07/

**Comment by Xenorage** [comment]
Exactly what I wanted.
Thank you!
