### ISSUE TITLE
Misalignment problem when scrolling the Handsontable with fixed columns

### ISSUE THREAD

**Issue by pnowak** [handsontable/handsontable#7149]
### Description
This issue occurs only if you use a FF and Windows machine and when we zoom after the page/Handsontable has loaded.
Further information - https://forum.handsontable.com/t/misalignment-problem-when-scrolling-the-handsontable-with-fixed-columns/4563

### Steps to reproduce

1. Zoom the page, scroll down to the end of the table.

### Demo

https://jsfiddle.net/nma9tgr6/

### Your environment
* Handsontable version: 
* Browser Name and version: FF 78.0.2
* Operating System: Windows

**Comment by AMBudnik** [comment]
Demo updated to v8 https://jsfiddle.net/AMBudnik/3h81j0y2/ also ends up with a misalignments

![not-ok](https://user-images.githubusercontent.com/10757813/92596405-0de7a800-f2a6-11ea-9a7e-d75b71fcab8a.gif)

it works well if we zoom and them reload the page

![ok](https://user-images.githubusercontent.com/10757813/92596477-2788ef80-f2a6-11ea-9fd0-5dc5107da681.gif)

**Comment by swistach** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of Interoperability problems using zoom/system UI scaling and some core features task reported at #7527 

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behaviour feel free to contact me at

**Comment by Farid566** [comment]
Hello! I just found a solution for my problem: I just put <!DOCTYPE html> at the beginning of the page and misalignment issue gone for me! Hope this helps someone.
