### ISSUE TITLE
date background color missing

### ISSUE THREAD

**Issue by emanuallan** [handsontable/handsontable#7151]
![Screen Shot 2020-07-27 at 3 45 10 PM](https://user-images.githubusercontent.com/22531461/88590372-3b430400-d020-11ea-8d18-d3f08cd591d2.png)

Hello, See the attached picture to see the problem. Really odd. 

These are the settings I set: 
```

                       {
                            type: "date",
                            dateFormat: "MM/DD/YYYY",
                            correctFormat: true,
                            defaultDate: "01/01/1900",
                            // datePicker additional options (see https://github.com/dbushell/Pikaday#configuration)
                            datePickerConfig: {
                                // First day of the week (0: Sunday, 1: Monday, etc)
                                firstDay: 0,
                            },
                        },
```

didnt think I did anything too crazy but not sure why its doing this, any suggestions?

**Comment by pnowak** [comment]
Hi @emanuallan 

It seems like an issue with the CSS. 

As you can check in this demo (and the screenshot below) - https://jsfiddle.net/28a4Lchk/- everything is displaying correctly.
![Zrzut ekranu 2020-07-28 o 09 18 19](https://user-images.githubusercontent.com/1555809/88632148-7b06fb80-d0b3-11ea-91da-40afc22673fd.png)

It would be great if you could share a demo where the issue is replicable.

**Comment by emanuallan** [comment]
I think you're right, going to close the issue for now. Thanks for your assistance! :)
