### ISSUE TITLE
Can I create a custom function ?

### ISSUE THREAD

**Issue by Warrens-yg** [handsontable/handsontable#7178]
For example, I create a function , I want use it like use excel function.
const KM = function(value, value2) {
    ......
}
  var container = document.getElementById('example1'),
    hot = new Handsontable(container, {
      data: [
      	[2],[6],['=KM(123, 456)']
      ],
      rowHeaders: true,
      colHeaders: true,
      formulas: true
    });

**Comment by AMBudnik** [comment]
Hi @Warrens-yg 

Can you translate your message? **We provide support in English** the experience has shown me that depending on Google Translate is not always a good idea.

**Comment by AMBudnik** [comment]
> Can I create a custom function

In the actual formula plugin, you can only set up custom variables https://handsontable.com/docs/8.0.0/demo-formula-support.html However, you will be able to create custom functions once we move to the HyperFormula https://handsontable.github.io/hyperformula/guide/custom-functions.html which is our goal.

To get updates on the Hyper Formula you can follow this topic https://github.com/handsontable/handsontable/issues/6466 or wait for my updates. I will make sure to inform you once we replace the formulaJS with HyperFormula.

**Comment by Warrens-yg** [comment]
That's cool. How long will it move to the HyperFormula?

**Comment by AMBudnik** [comment]
https://github.com/handsontable/handsontable/issues/6466 is missing some important changes so it's hard to tell. I will keep you updated on every important change.

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **New formula plugin** task reported at https://github.com/handsontable/handsontable/issues/6466

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com
