### ISSUE TITLE
Incorrect column width calculation of AutoColumnSize on Safari

### ISSUE THREAD

**Issue by swistach** [handsontable/handsontable#7262]
### Description
As a part of #6602, I found an issue related to incorrect column calculation of AutoColumnSize.
If we have default column width (50px) - on Safari occurs a bug with calculating the true size of the cell's content (only for the first column).
The effect of setting value as `Longer\ntext` is as you can see below:
![image](https://user-images.githubusercontent.com/11849621/92603523-b2221c80-f2af-11ea-8b99-2b1a323255c8.png)

### Steps to reproduce
1. Initialize Handsontable (even with an empty config object)
2. Insert:
```
Longer
text
```
using an editor or using API: `setDataAtCell(row, column, 'Longer\ntext')` to any of the cells in the first column.

Result: Cell takes 3 lines instead of 2.

### Demo
I added `setDataAtCell` for `A2`, right after initialization to simulate the manual change:
https://jsfiddle.net/ovs2uw9t/

### Your environment
* Handsontable version: 8.0.0
* Browser Name and version: Safari 13.1.2
* Operating System: macOS 10.15.6

**Comment by aninde** [comment]
This issue will be fixed by the upcoming `v8.1.0`. https://jsfiddle.net/p38hts1d/

Tested on Safari 14.0 / macOS Catalina 10.15.7 and Safari 13.1 / macOS Catalina via BrowserStack.

<img width="137" alt="Screenshot 2020-09-29 at 14 26 47" src="https://user-images.githubusercontent.com/30186818/94558229-f9bd1800-025f-11eb-9f3b-2dc073d22b8b.png">

**Comment by AMBudnik** [comment]
I'm glad to see this issue solved.

For anyone having the same issue - please update to v 8.1.0.
