### ISSUE TITLE
[8.0.0+] The table validation causes incorrect data rendering when Hidden plugin is enabled

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#7301]
### Description

When the _HiddenRows_ or _HiddenColumns_ plugin are enabled and the first row is hidden after the table validation the cells missing their values and cell meta objects. 

The bug occurs only when the first row or column is hidden and when the `columns` options have declared different cell types than `text`.

### Steps to reproduce

1. Go to https://jsfiddle.net/budnix/epg560nh/;
2. Click on the "Validate table" button;
3. As a result, the C column gets the value and cell meta object from column D.

The same happens for rows: https://jsfiddle.net/budnix/gq892afe/

### Demo

https://jsfiddle.net/budnix/epg560nh/

### Your environment
* Handsontable version: 8.0.0
* Browser Name and version: -
* Operating System: -

**Comment by aninde** [comment]
This issue will be fixed by the upcoming v8.2.0. 

**Demo** 
Columns: https://jsfiddle.net/aninde/7vteLsaz/1/
Rows: https://jsfiddle.net/aninde/9vx3zsu6/1/

Tested on macOS Catalina 10.15.7
-  Chrome Beta 87 and stable 86
-  FF 83.0b7 and stable 82
-  Safari 14 and Safari Technology Prev 14.1

Windows 10
- IE 11
- Chrome 86
- Edge 86
- Edge Dev 88

**Comment by AMBudnik** [comment]
Regression fixed in v 8.2.0.
