### ISSUE TITLE
How I use Column Summary with multiple nested rows ?

### ISSUE THREAD

**Issue by ikeryo1182** [handsontable/handsontable#7388]
### Description
I want to calculate multiple nested row values with column summary. 
In demo ( https://jsfiddle.net/tb78o5c4/19/ ) , Line 1 should be the total Line2, Line3 and Line 4 but  Line4 that is calculated cell was not included. 
If I let Line1 include Line4, how should I set it ? 

### Steps to reproduce

See JSFiddle sample.

### Demo
https://jsfiddle.net/tb78o5c4/19/

### Your environment
* Handsontable version: 7.4.0
* Browser Name and version: Chrome
* Operating System: macOS

**Comment by AMBudnik** [comment]
Hi @ikeryo1182 

Thank you for sharing. I've simplified the demo a bit https://jsfiddle.net/AMBudnik/4ce0pna3/ but I was able to replicate the issue. 

The `ranges` option of the summary calculations allows us to 

![Zrzut ekranu 2020-11-17 o 10 42 37](https://user-images.githubusercontent.com/10757813/99373380-a1021700-28c1-11eb-94b3-3311237de0e4.png)

src: https://handsontable.com/docs/8.2.0/demo-summary-calculations.html

so if I define that the range for the SUM in cell 0,0 should take into account rows `[1,2,3]` in means that I should get `35` instead of `11` in cell 0,0.
![Zrzut ekranu 2020-11-17 o 10 43 57](https://user-images.githubusercontent.com/10757813/99373531-d0188880-28c1-11eb-96e5-341d1a1f209b.png)

I've checked if the issue relates to the fact that we've doing some nesting but adding parent index `9` also did not change the value of `11`. It seems that `nestedRows` do not fully support summary calculations and we need to make further investigation on this subject.

**Comment by ikeryo1182** [comment]
Thanks for your answer!
I see that nestedRows don't completely support column summary.

**Comment by AMBudnik** [comment]
This issue is closed temporarily. It will be reopened for development as it became a part of **NestedRows grouped issue** task reported at https://github.com/handsontable/handsontable/issues/7510

I will make sure to inform everyone interested in this topic after the official fix.

Please feel welcome to makes any comments on this issue. And if you experience similar behavior feel free to contact me at support@handsontable.com

**Comment by Sapphire2k** [comment]
![image](https://user-images.githubusercontent.com/17328005/113400803-fe13ea80-93d4-11eb-99ee-26372f62bff6.png)
What‘s more, i add three nested rows, the first column style become wired, is there any way to change the style or fixing the width? 
And i also wish that there is the way to toggle / collapse in the other column, not only the first column , thanks

**Comment by AMBudnik** [comment]
Hi @Sapphire2k if you want to collapse a header you can use `collapseChildren` method at the moment. But it not a part of the official API yet. Here's a demo http://jsfiddle.net/handsoncode/gceqrLd2/

ps. I recommend adding [rowHeaderWidth](https://handsontable.com/docs/8.3.2/Options.html#rowHeaderWidth) for expanding that row header. Then if you set it up to ~50 your 9-11 rows would fit better within the column space.
