### ISSUE TITLE
HiddenRows documentation clarification: does it still use height: 0px?

### ISSUE THREAD

**Issue by camilstaps** [handsontable/handsontable#7390]
### Description
This is a question, not a bug / feature request.

The [documentation for the `HiddenRows` plugin](https://handsontable.com/docs/8.2.0/HiddenRows.html) says:

> Plugin allows to hide certain rows. The hiding is achieved by rendering the rows with height set as 0px.

Is this still true after the 8.0.0 refactoring and the addition of `rowIndexMapper`? In particular, https://github.com/handsontable/handsontable/commit/2796dc9451780b568df24430dd0085ae951f097c#diff-22ebdb9efbd3783ad7fa874f3cdf6af17887c24d772ebb5bda6cbc5deb042152 added a comment to `onModifyRowHeight`:

https://github.com/handsontable/handsontable/blob/34793d5e9ee10176941ebe2589996daa80b5effd/src/plugins/hiddenRows/hiddenRows.js#L303-L311

Reading "Hook is triggered internally only for the visible rows" I would think that the `rowIndexMapper` takes care of hiding the rows more efficiently than setting a `0px` height. That is also based on the [8.0.0 release blog post](https://handsontable.com/blog/articles/2020/8/the-new-handsontable-8-is-now-available):

> When columns or rows are hidden, they are not physically rendered. This applies to several plugins that can “hide” rows and columns, namely: ...

### Context
I am migrating to 8.2.0 from 7. I previously hid rows using `modifyRow` (the first way described in https://handsontable.com/blog/articles/2016/3/3-ways-to-hide-rows-in-handsontable - it may be useful if that blog post received a warning message that it is not up to date for 8.x). I used `modifyRow` because `HiddenRows` was not fast enough for my data sets (several thousands of rows, with often many being hidden). I'm wondering whether I should be using `HiddenRows`, or add a `HidingMap` to `rowIndexMapper` myself.

### Your environment
* Handsontable version: master
* Browser Name and version: N/A
* Operating System: N/A

**Comment by wojciechczerniak** [comment]
You're right, the documentation is misleading and outdated. Sorry, thanks for pointing it out.

Since v8, hidden rows and columns are not rendered as DOM elements. They will be handled in memory only.

> I'm wondering whether I should be using `HiddenRows`, or add a `HidingMap` to `rowIndexMapper` myself.

You can use both. Our plugin should be an easy win. But you can create your own or just register a `HidingMap` and have your specific hiding next to the build-in plugin. We will join them internally with logical OR, if any `HidingMap` hides the row it will remain hidden.

The difference between HidingMap and TrimmingMap is that hidden rows are still part of the data and selection, trimmed will be absent when requested through data APIs, selection, or copy&paste.


@scarletfog: 
- [ ] fix any reference to hiding by setting the height/width ie. "The hiding is achieved by rendering the rows with height set as 0px.". 
- [ ] We should do something with the outdated blog post: I'm wondering whether I should be using HiddenRows, or add a HidingMap to rowIndexMapper myself. Should we write a new one and mark this as obsolete with a link to the new one?

**Comment by camilstaps** [comment]
Thanks for the explanation! :clap:

**Comment by kirszenbaum** [comment]
- [x] fix any reference to hiding by setting the height/width ie. "The hiding is achieved by rendering the rows with height set as 0px.". 
Fixed in https://github.com/handsontable/handsontable/pull/8692

- [x] We should do something with the outdated blog post: I'm wondering whether I should be using HiddenRows, or add a HidingMap to rowIndexMapper myself. Should we write a new one and mark this as obsolete with a link to the new one?
I added a note to the blog post: https://handsontable.com/blog/articles/2016/3/3-ways-to-hide-rows-in-handsontable
