### ISSUE TITLE
[8.2.0] Enabling column sorting with multi column sorting crashes the table

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#7415]
### Description

Since 8.2.0 enabling the _ColumnSorting_ and _MultiColumnSorting_ plugins crashed the table.

![image](https://user-images.githubusercontent.com/571316/100460596-bf3cf380-30c7-11eb-9da7-202039fb57fd.png)

### Demo

https://jsfiddle.net/budnix/dLrbtx7n/

### Your environment
* Handsontable version: 8.2.0
* Browser Name and version: -
* Operating System: -

**Comment by AMBudnik** [comment]
Related https://github.com/handsontable/docs/issues/252

**Comment by aninde** [comment]
This issue will be fixed by v8.3.0.
Browser's console logs warning:

>  "Plugins `columnSorting` and `multiColumnSorting` should not be enabled simultaneously. Only `multiColumnSorting` will work."

### Demo
https://jsfiddle.net/aninde/s5w41hup/ v8.3.0

### Your environment: 
**macOS Big Sur 11.1**
- Chrome 87 & Beta 88.0.4324.96
- Safari 14.0.2
- Firefox 85.0
- Opera 73.0.3856.344
- Edge 88.0.705.5

**Windows 10**
- Edge 86
- IE 11

**Comment by aninde** [comment]
👍
