### ISSUE TITLE
[8.0.0+] Renderer is cutting out spaces inside a query

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#7458]
### Description

Since v8 a cell renderer is cutting out spaces inside a query.

### Steps to reproduce

1. Type `A              B` inside the cell (but a couple of spaces between A and B)
2. Click <kbd> Enter</kbd> to confirm
3. Open the editor to check the value

Behavior for v8
![image](https://user-images.githubusercontent.com/10757813/103885974-19769e80-50e1-11eb-8e9c-1097ccb4360e.png)

Behavior for v7.4.2
![image](https://user-images.githubusercontent.com/10757813/103886082-3f9c3e80-50e1-11eb-808e-baab731754ea.png)

### Demo

https://jsfiddle.net/handsoncode/e27t80cL/ v7.4.2 - working well
https://jsfiddle.net/handsoncode/a0qk71fe/ v8 - broken
https://jsfiddle.net/handsoncode/dwcj4z10/ v8.2.0 - broken

### Your environment
* Handsontable version: 8+
* Browser Name and version: Chrome 87
* Operating System: Windows 10

Update [forum](https://forum.handsontable.com/t/gh-7458-stop-handsontable-compressing-whitespace-between-characters/4908)

**Comment by henricook** [comment]
Is this the offending piece of code? https://github.com/handsontable/handsontable/blob/master/src/renderers/textRenderer.js#L27

**Comment by AMBudnik** [comment]
The `trimWhitespace` is an option that is responsible for cutting the first and last char if that's a space 
docs: https://handsontable.com/docs/8.2.0/Options.html#trimWhitespace and here we want to keep the spaces between other chars.

**Comment by aninde** [comment]
This issue has been fixed by v8.3.2 https://jsfiddle.net/pbhtkw49/
Render doesn't cut out spaces inside a cell. 

<img width="170" alt="Screenshot 2021-03-10 at 16 16 31" src="https://user-images.githubusercontent.com/30186818/110651866-1e78cc80-81bc-11eb-852f-dd474576eac7.png">
<img width="176" alt="Screenshot 2021-03-10 at 16 16 39" src="https://user-images.githubusercontent.com/30186818/110651874-20db2680-81bc-11eb-9c33-42bccd0bd70c.png">



Tested on 
macOS 11.2.2 (20D80) - Chrome  `88.0.4324.192`, Safari  `14.0.3 (16610.4.3.1.4)`, Firefox `86.0` , Edge `89.0.774.48`, Opera `74.0.3911.203` 
Windows 10 - Chrome  `88.0.4324.192` , Edge `89.0.774.48`, IE `11`, Firefox `86.0`.

**Comment by AMBudnik** [comment]
Hi @henricook 

I've updated our forum topic, but I guess that you'll get this update sooner :-) 
I hope that now all the charts and spaces are placed correctly. If something doesn't work, let me know via email.

**Comment by henricook** [comment]
Thanks @AMBudnik and team!
