### ISSUE TITLE
Feature Request: setRowMeta / getRowMeta

### ISSUE THREAD

**Issue by henricook** [handsontable/handsontable#7492]
### Description
In a system that requires rows to change colors based on who they were last edited by, day they were created etc I find myself maintaining a hidden first column in the table data to run all these flags and it's extremely ardous. Especially because some flags are only relevant for 24 hours at which point data gets ported to the table for the next day.

Having a separate rowMeta system similar to cellMeta (but for a row) that I could manage and persist separately would be very useful and presumably is quite easy to action

**Comment by AMBudnik** [comment]
Hi Henri 👋 

We should be able to **set** cell meta for rows via https://github.com/handsontable/handsontable/issues/4055 but this feature hasn't been added yet.

And for getting the row meta there's a method called [getCellMetaAtRow](https://handsontable.com/docs/8.2.0/Core.html#getCellMetaAtRow). Here's an example with some different cell types https://jsfiddle.net/handsoncode/gLpewr9a/.

However, in both cases, this is metadata for all the cells in the row (TDs), not for the TR element. As I assume you'd want to loop through all the TRs in the table rather than the TDs, right?

**Comment by henricook** [comment]
That sounds about right @AMBudnik - yes I'm looking to attach meta to a row only (tr) rather than a cell

At the moment I use the hidden column i've mentioned to do this, so the first cell in each row holds a JSON object of flags etc to represent the row's state. This comes with problems though, for example I have to bend over backwards to make sure updating this row doesn't trigger much in the `afterChange` handlers etc, or have weird interactions with UndoRedo - so it's very painful.

**Comment by AMBudnik** [comment]
What about that approach https://jsfiddle.net/handsoncode/craLd76j/ ? I'm just adding a custom meta to the parent of the TD. It doesn't get erased on data change.

**Comment by henricook** [comment]
Ah cunning! Yes it could work, of course i'm also needing to persist it server-side and syndicate it to other users in real time - so I'd end up writing quite a lot of my own code to manipulate this custom row meta idea.

This could presumably be the core of the implementation for the official handsontable feature though, as long as I can throw a whole json object in there and fetch a row -> meta map for all rows (`getAllRowsMeta`)

**Comment by AMBudnik** [comment]
The feature itself has been already reported here https://github.com/handsontable/handsontable/issues/4901
Due to our ticket management policy, we are closing most of the features and improvements suggestions that haven't been scheduled. It doesn't mean that we don't want to add them. It's a matter of doing what's on the Roadmap first.
