### ISSUE TITLE
Allow autoColumnSize to work with colWidths

### ISSUE THREAD

**Issue by Maxoudela** [handsontable/handsontable#7507]
### Feature request
It should be possible to specify some column widths and let the plugin compute the others. 

### Description
It is not mentioned in the [autoColumnSize documentation](https://handsontable.com/docs/8.3.0/Options.html#autoColumnSize) nor the [colWidths documentation](https://handsontable.com/docs/8.3.0/Options.html#colWidths) that using `colWidths` will deactivate the autoColumnSize plugin.

However it is indeed what's happening ([here](https://github.com/handsontable/handsontable/blob/8b6e9c404ac0aa4fb211a6bedbd68b7fbd81c658/src/plugins/autoColumnSize/autoColumnSize.js#L173)).

### Details
In fact, it seems practically already done since it's possible to specify a colWidths function that would return empty for the columns that should be autosized. *_see comment below_

And during the [column width computation](https://github.com/handsontable/handsontable/blob/8b6e9c404ac0aa4fb211a6bedbd68b7fbd81c658/src/plugins/autoColumnSize/autoColumnSize.js#L266), the width is first checked before the computation begin. Therefore, removing the restriction on the `isEnabled` of the plugin should be working out of the box if I'm not missing something.

Relate to #1294

\* Technically, it is not possible to set `undefined` for a column width as seen [here](https://github.com/handsontable/handsontable/blob/master/handsontable.d.ts#L1659) so this should be addressed as well.

**Comment by swistach** [comment]
Hi @Maxoudela,
That's right, we should mention in [autoColumnSize](https://handsontable.com/docs/8.3.0/Options.html#autoColumnSize) description that `colWidths` as an array will disable auto calculation. Moreover, we should review our TS definition for `colWidths` because we support `undefined` widths in `getColWidth`: https://github.com/handsontable/handsontable/blob/8.3.0/src/core.js#L3480-L3490

Fortunately, there are other options you can use to have autoColumnSize and constant width in some columns at the same time.
1) Use `columns` as an array of objects with `width` property - useful if you know data schema: https://jsfiddle.net/d9jaseu2/
2) Use `modifyColWidth` hook instead of `colWidths` as a function - useful not only for TS validation but also due to performance in a case you have dynamic data schema: https://jsfiddle.net/3yr5bnqp/

Thank you for your help and detailed investigation!

**Comment by Maxoudela** [comment]
Hi,

Thanks a lot for the response. Do you want me to open a PR regarding the TS definition? 

I've tested the first solution described by removing the `colWidths` and adding a `columns` array with the width only defined where I want. It seems to run pretty smooth. Does this solution (using `columns` over `colWidths`) has any unwanted side-effects that I should known?

**Comment by swistach** [comment]
> Thanks a lot for the response. Do you want me to open a PR regarding the TS definition

We appreciate PRs from the community so it's up to you 🙂 If you want to send us your PR remember to fill [Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLScpMq4swMelvw3-onxC8Jl29m0fVp5hpf7d1yQVklqVjGjWGA/viewform?c=0&w=1) first.

By the way, I guess we can add this adjustment right next after v8.3.1.

> Does this solution (using columns over colWidths) has any unwanted side-effects that I should known?

It depends on the use case but in general, it should work without unwanted side-effects.

**Comment by aarondfrancis** [comment]
@Maxoudela You might find this issue interesting re: auto vs manual columns: https://github.com/handsontable/handsontable/issues/6676

**Comment by aninde** [comment]
Documentation has been fixed and will be published with v8.3.2.

**Comment by AMBudnik** [comment]
I'm officially closing this issue after @swistach PR from https://github.com/handsontable/handsontable/pull/7524/files for version v8.3.2
