### ISSUE TITLE
Wrapper does not work in Vue v3.0.0 environment

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#7545]
### Description
Vue-Handsontable does not work in the newly released [Vue v3.0.0](https://github.com/vuejs/vue-next/releases/tag/v3.0.0) environment. 

Vue v3 isn't an LTS version yet, but we should be prepared for it. Details are described in the [migration guide](https://v3.vuejs.org/guide/migration/introduction.html#overview).

For the purposes of testing, I prepared two environments made of [Vue-CLI](https://github.com/vuejs/vue-cli) which did not differ in anything other than the Vue version.

#### Vue v2.6.12 (works)
<img width="465" alt="vue2 6+vue-hot" src="https://user-images.githubusercontent.com/30186818/93869386-070c5c80-fccc-11ea-9376-dffaafbbcbd1.png">

#### Vue v3.0.0 (broken)
<img width="621" alt="vue3 0+vue-hot" src="https://user-images.githubusercontent.com/30186818/93869382-05db2f80-fccc-11ea-8a13-e5db886ceb5a.png">

**Details of the error**
<img width="534" alt="Screenshot 2020-09-22 at 11 29 11" src="https://user-images.githubusercontent.com/30186818/93869409-0c69a700-fccc-11ea-9688-dc9b153d60c4.png">

**The line of code that throws an error**
<img width="733" alt="Screenshot 2020-09-22 at 11 29 02" src="https://user-images.githubusercontent.com/30186818/93869403-0b387a00-fccc-11ea-9bc1-a4f0e57d24d9.png">

### Your environment
* Vue wrapper version: 5.0.1
* Handsontable version: 8.0.0
* Browser Name and version: Firefox 80.0.1, but it's not related
* Operating System: macOS Catalina 
* Vue version: 3.0.0

Inform [Zen](https://handsontable.zendesk.com/agent/tickets/26331)

**Comment by fengjac** [comment]
So what' s the release date? Thanks

**Comment by Osky772** [comment]
We've found that this task is more difficult than we expected. It's more likely we will have to implement a brand new wrapper especially for Vue 3, which requires a lot of work. Vue 3 has a different API than Vue 2 and requires updating dependencies as well (and because of the monorepo it's not that easy).

After estimation this task being made, we've decided that this is out of scope for now. We will work on it in the future, but it's not scheduled yet.

**Comment by AMBudnik** [comment]
_No to myself - update Zen 26477_

**Comment by VictorManco87** [comment]
So what' s the release date? Thanks

**Comment by AMBudnik** [comment]
Hi @VictorManco87 

Vue3 wrapper hasn't been scheduled yet. Our current scope of work is described by Projects https://github.com/handsontable/handsontable/projects

**Comment by ValeoPrime** [comment]
I want to buy a paid subscription, but I heard that tables do not work with vue 3 ?? Are you going to adapt them for vue 3 ??

**Comment by AMBudnik** [comment]
I'm sorry to hear that @ValeoPrime 
We have been notified multiple times about the need for Vue3 support and we will try to adjust our Roadmap.
I will keep everyone updated here once we start the work.

**Comment by ValeoPrime** [comment]
Hi @AMBudnik.
I've checked everything, and indeed there is no support for vue 3 yet. More and more projects are starting on vue 3. I think it would be a good idea to adapt tables for vue 3 as soon as possible.
Are you going to update the roadmap in July ??

**Comment by AMBudnik** [comment]
Hey @ValeoPrime The Roadmap is set for the whole 2021, but those are general topics. More information (with details) is provided by our Projects https://github.com/handsontable/handsontable/projects where we can see that
- we're launching new documentation soon
- we still have some things to do with the HyperFormula project

We should get more updates to the Projects tab after the official release of the new documentation. But as we're before the planning meeting I can't tell now what will be added to the list.

**Comment by miskying** [comment]
it's a pity

**Comment by luisdnodrizat** [comment]
Release date? Thank you

**Comment by AMBudnik** [comment]
@luisdnodrizat we still investigate the subject and should have some updates in 2-3 weeks,

**Comment by krzysztofspilka** [comment]
@marinsky @fengjac @luisdnodrizat @ValeoPrime @VictorManco87 @miskying

Thanks for requesting the new wrapper. The good news is that we've already started working on it.

**Comment by Siemienik** [comment]
# VUE 3 migration status

## The process

Wanting to keep our wrapper's API the same as possible, I chose to go step by step (test by test) and add, adapt, and write code to makes all tests green. 

There are tests files: (in planned order)
* hotTableHelpers.spec.ts
* hotTable.spec.ts
* hotColumnHelpers.spec.ts
* hotColumn.spec.ts
* baseEditorComponent.spec.ts

## Chalanges / Main problems:

1. Vue3 removes property `this.$children`, which we use to scan `hot-table` offsprings and set up the handsontable instance. 
  * This is not a big issue for the `hot-column` component. It should be enough to change communication flow and inform the `this.$parent` component (`hot-table`) about itself. 
  * It is potentially breaking change for directives `hot-renderer` and `hot-editor` - I have to investigate this area yet.

2. Vue changes the API of VNode, which wasn't documented in the best way. That forces me to find a new way to handle directives `hot-renderer` and `hot-editor`. Obviously needs to be researched.

3. Something is on the top about `Proxy` introduced in Vue3. The `Proxy` objects wrap whole properties. Which makes them observable and much smarter to use. Proxy objects override APIs of arrays and objects (f.i `Array.map` or `Array.pop`  functions). Unfortunately, during migrating codebase, I found that mutation by reference happens differently compared to Vue2.

For instance, `data.pop()` instead of removing the last element of the array, left it as a table of nulls.
I suspect that it has reference to the https://github.com/handsontable/handsontable/issues/7263

## Current progress:

*As the initialization API was changed in Vue3, all tests were red at the beginning, and all of them need to make some adjustments to create components and check the assertions. I use this fact to calculating current progress. However, keep in mind that some tests need more time effort to accomplish the target.*

File Name | All | Passes | Skipped | Failed | Note
---|---|---|---|---|---
hotTableHelpers.spec.ts | 3 | 3 | 0 | 0 | **Accomplished**, All is right.
hotTable.spec.ts | 17 | 8 | 3 | 6 | **Work in progress** <br/> Some tests have temporarily changed assertions according to challenge 3. <br/> 3 skipped tests check directive `hot-renderer` and `hot-editor`,  probably completly deprecated (according to challenge 1) 
hotColumnHelpers.spec.ts | 1 | 1 | 0 | 0 | Not started yet. Probably outdated (according to challenge 2).
hotColumn.spec.ts | 6 | 0 | 0 | 6 | Not started yet. Needs redesing internal logic (according to challenge 1).
baseEditorComponent.spec.ts | 2 | 0 | 0 | 2 | Not started yet. 
**SUM:** | 29 | 12 | 3 | 14 | 41,3% Done, <br> 10,3% postponed (skipped for now), <br>  48,3% not started yet.

**Comment by Siemienik** [comment]
Ad. Proxies:
```
externalData.pop();
externalData.pop();
externalData[0].pop();
externalData[0].pop();

debugger;
```

results:

![image](https://user-images.githubusercontent.com/2893099/133301087-b24d05f7-2afa-438e-a069-d1972e92bdc3.png)

However, the hot instance has data:

![image](https://user-images.githubusercontent.com/2893099/133301350-b555b1ec-560c-4d21-951b-1a8165709766.png)

I am doing research on how to change the flow of updating data.

**Comment by eliasbermudez** [comment]
Release date? Thank you

**Comment by AMBudnik** [comment]
Hi @eliasbermudez, we plan to release the new version with the wrapper in the 2nd part of January. I will make sure to send you a notification on the day of the release.

**Comment by m-towery** [comment]
Hi @AMBudnik, can you please include me on that notification?

**Comment by AMBudnik** [comment]
Hi @m-towery yes. I will update you as soon as we publish an official version. You can already get to it on npm https://www.npmjs.com/package/@handsontable/vue3 as an -rc version. The official release is planned for the middle of January.

**Comment by AMBudnik** [comment]
Hi @m-towery @eliasbermudez @luisdnodrizat @miskying @ValeoPrime @VictorManco87 @fengjac @marinsky 

We are happy to announce that the new wrapper for Vue 3 is ready to try out.
Here https://handsontable.com/docs/vue3-installation/#overview you can find the tutorial on how to set it up and here https://handsontable.com/docs/release-notes/ is a full list of changes within the new version of Handsontable - 11.1.0.
