### ISSUE TITLE
 import { NumericCellType } from 'handsontable/cellTypes/numericType' does not work

### ISSUE THREAD

**Issue by bbonch** [handsontable/handsontable#7597]
### Description
 import { NumericCellType } from 'handsontable/cellTypes/numericType' does not work

### Steps to reproduce
import { NumericCellType } from 'handsontable/cellTypes/numericType'

Guys! You should copy/paste carefully. Check exports in package.json.

### Your environment
* Handsontable version: 8.3.1

**Comment by bbonch** [comment]
Thanks guys!

**Comment by aninde** [comment]
This issue is fixed by v8.3.2.
We have improved the paths and imports will work.

Tested on 
macOS 11.2.2 (20D80) - Chrome  `88.0.4324.192`, Safari  `14.0.3 (16610.4.3.1.4)`, Firefox `86.0` , Edge `89.0.774.48`, Opera `74.0.3911.203` 
Windows 10 - Chrome  `88.0.4324.192` , Edge `89.0.774.48`, IE `11`, Firefox `86.0`.

**Comment by AMBudnik** [comment]
Hi @bbonch 

I just wanted to let you know that we've just released Handsontable v8.3.2 where those paths are corrected. Thank you again for your feedback.
