### ISSUE TITLE
Indicator for the CollapsibleColumns plugin doesn't look good for styled TH element

### ISSUE THREAD

**Issue by wszymanski** [handsontable/handsontable#7970]
### Description
After styling `TD` with `text-align` CSS property (by default used for styling text within cells by `htLeft`, `htRight` and `htCenter` classes) indicator is displayed not properly.

Is:

![Screenshot 2021-05-05 at 16 01 24](https://user-images.githubusercontent.com/141330/117153365-2d928a00-adbb-11eb-9035-1df03c7d5658.png)

Should be:

![Screenshot 2021-05-05 at 16 01 29](https://user-images.githubusercontent.com/141330/117153349-28cdd600-adbb-11eb-9489-07bf405a5766.png)

### Your environment
* Handsontable version: 8.3.2

**Comment by AMBudnik** [comment]
This issue is fixed in v9 https://jsfiddle.net/yctsh2fr/

For everyone interested, here is a list of changes for the following version https://handsontable.com/docs/9.0.0/tutorial-release-notes.html and here https://handsontable.com/docs/9.0.0/tutorial-migration-guide.html is a migration guide (from v8 to v9)
