### ISSUE TITLE
[9.0.0] Validation does not work for cells that contain formulas

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#8053]
### Description

The validation does not work for cells that contain formulas. The value is "observed" by the cell formula but the validation status is not updated.

### Steps to reproduce

1. Go to https://jsfiddle.net/budnix/5yndofja/1/;
2. Change the B1 cell value to `a`;
3. In results, the E2 cell has changed its value but it is not marked as invalid.

![Kapture 2021-05-18 at 09 58 43](https://user-images.githubusercontent.com/571316/118614102-b1874180-b7bf-11eb-8489-b33d330662dc.gif)

### Demo

https://jsfiddle.net/budnix/5yndofja/1/

### Your environment
* Handsontable version: 9.0.0
* Browser Name and version: -
* Operating System: -

**Comment by budnix** [comment]
Can be related to https://github.com/handsontable/handsontable/issues/8050.

**Comment by aninde** [comment]
**Case 2**
Opening editor on the cell containing formulas marks them red.

Reproduction:
1. Open editor on selected cell.
2. Click ENTER once again.
https://jsfiddle.net/h7dmarv4/

Result:
The cell is marked red when it shouldn't. 
<img width="358" alt="Screenshot 2021-05-18 at 10 27 40" src="https://user-images.githubusercontent.com/30186818/118618296-c1a12000-b7c3-11eb-85b6-1fb55e856478.png">

**Comment by aninde** [comment]
All cases are fixed by v9.0.0 https://jsfiddle.net/aninde/35tjoqry/
Validation works like charm with editor and with autofill :) 

![validation](https://user-images.githubusercontent.com/30186818/119651202-0ad91b80-be25-11eb-87b2-bc5a1f5251ba.gif)
![validation-autofill](https://user-images.githubusercontent.com/30186818/119651211-0d3b7580-be25-11eb-903c-b371bd9069d4.gif)
