### ISSUE TITLE
The table throws errors when the formulas sheet name contains a dash

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#8057]
### Description

When I try to add custom named expression with my own sheet name that contains a dash:
```js
  formulas: {
    engine: HyperFormula,
    sheetName: 'my-sheet',
    namedExpressions: [
      {
        name: 'myOwnCalc',
        expression: '=my-sheet!$A$1+100',
      }
    ],
  },
```
I get nasty errors that prevent the table to be rendered.

![image](https://user-images.githubusercontent.com/571316/118627902-632c6f80-b7cc-11eb-91a9-45e8ea5dcd08.png)

Changing the sheet name to the camelCase variant makes everything works. I think there is room here to improve the developer experience by implementing better error/warning messages.

### Demo

https://jsfiddle.net/budnix/zdr0sp6m/

### Your environment
* Handsontable version: 9.0.0
* Browser Name and version: -
* Operating System: -

**Comment by wojciechczerniak** [comment]
Standard notation says that SheetName as a reference in expression/formula has to be enclosed in quotes when it is not a single word: 

```diff
- '=my-sheet!$A$1+100'
+ '='my-sheet'!$A$1+100'
```

A better error handling is a good idea.

**Comment by nikersify** [comment]
In this case as the error suggests, the `expression` is being interpreted as another named expression.

I didn't find a way to check if a named expression will be valid in this way - `HyperFormula#validateFormula` returns `true` for anything parseable, even expressions that include non-existing named expressions, as does `HyperFormula#isItPossibleToAddNamedExpression`.

The bug seems to be the following:
```ts
import {HyperFormula} from 'hyperformula'

const hf = HyperFormula.buildEmpty()

hf.addNamedExpression('expression', '=random') // throws the error mentioned above
```

...but weirdly enough when the expression is already used somewhere in a sheet, there's no error being thrown and a simple `#NAME?` cell error is returned instead (as probably expected):

```ts
import {HyperFormula} from 'hyperformula'

const hf = HyperFormula.buildFromArray([['=expression']])

hf.addNamedExpression('expression', '=random')

console.log(hf.getSheetValues(0))
// [
//   [
//     DetailedCellError {
//       value: '#NAME?',
//       address: 'expression',
//       type: 'NAME',
//       message: 'Named expression random not recognized.'
//     }
//   ]
// ]
```

---

Unfortunately in our case named expressions are getting registered after data is being loaded, so a user can't work around this problem as shown in the last snippet.

cc @wojciechczerniak

**Comment by wojciechczerniak** [comment]
We should have a fix for this in HF: https://github.com/handsontable/hyperformula/pull/679

**Comment by AMBudnik** [comment]
Today's build still shows the

>handsontable.full.min.js:110 Uncaught Missing named expression

error https://jsfiddle.net/1etamp9g/4/
Tested on Chrome 89 / Windows 10

**Comment by jansiegel** [comment]
@aninde Could you re-check if it's working correctly now (with the current `develop` state)?

**Comment by aninde** [comment]
This case is fixed by v10 https://jsfiddle.net/kua7p8vg/
