### ISSUE TITLE
Moving a column with a formula breaks addressing and might lead to cyclic errors

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8114]
### Description

Moving a column with a formula in a cell changes the formula to its value.
In the previous formula engine when we moved the column we got a string - not a formula so we shouldn't call it a regression (check v8.4.0 demo).

### Steps to reproduce

1. Move `C` column to be the first one (`C1` contains a formula)

**Result**
`C` becomes the first column but the formula in C1 is converted to its value.

### Demo

https://jsfiddle.net/xn19v8k5/1/ v9 - broken
https://jsfiddle.net/4qo3w7p6/2/ v8.4.0 - broken with a different result

### Your environment
* Handsontable version:
* Browser Name and version: Chrome 89
* Operating System: Windows 10

**Comment by aninde** [comment]
It seems that the v9 itself, even without the fix from https://github.com/handsontable/handsontable/pull/8130, fixes this case.
v9.0.0 https://jsfiddle.net/gmyfp271/.
![v9-chrome](https://user-images.githubusercontent.com/30186818/120458494-9d366d80-c397-11eb-9d66-eb0c20386ae6.gif)

**Comment by AMBudnik** [comment]
Stil works the same in v12.2.0 https://jsfiddle.net/u4gcxbda/

**Comment by warpech** [comment]
It seems that the description in the OP is wrong. It is easy to mistake the formula with its value, because of the values that were used in the JSFiddles.

The real problem is better seen with more distinct data: https://jsfiddle.net/warpech/Lr18nq9k/9/

The correct title should be **Moving a column with a formula breaks addressing and might lead to cyclic errors**

It is hard for me to pin the exact problem right now, but I can tell the steps to reproduce problems with my fiddle:

1. Move column C before A
2. Error 1: Double click on A1 and A2 and notice that they show `=$B1`/`=B2` as the formula text. If I understand correctly, though the user expects the formulas to use visual indexes in cell addresses, so the formulas should be updated to `=$C1`/`=C2` after moving. 
3. Error 2: Double click on B1, then B2, then C1, then C2, then outside of the table. Notice that all cells in row 1 and 2 were changed to `#CYCLE!`

**Comment by AMBudnik** [comment]
That's you for doing the investigation @warpech 
I'll change the title.
