### ISSUE TITLE
[8.4.0] Click inconsistency within the Filter Values component

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#8196]
### Description

The items within the Values Component of the Filters plugin work inconsistently. When the cursor is over the `checkbox` element it can be toggled by a single click. When the cursor is next to it you need to double-click to change the state.

![Kapture 2021-06-11 at 14 23 51](https://user-images.githubusercontent.com/571316/121685798-ad99c700-cac0-11eb-8ef9-4091eabc1bc7.gif)

### Demo

https://handsontable.com/docs/9.0.0/demo-filtering.html

### Your environment
* Handsontable version: 8.4.0 and later
* Browser Name and version: -
* Operating System: -

**Comment by aninde** [comment]
This issue is fixed on vRC-9.0.1 https://jsfiddle.net/aninde/zm7qgrx2/

**v9.0.1**
<img width="346" alt="Screenshot 2021-06-14 at 16 22 30" src="https://user-images.githubusercontent.com/30186818/121909300-133ebb00-cd2e-11eb-9b53-16f248a64c43.png">

**Was in v8.4.0**
<img width="318" alt="Screenshot 2021-06-14 at 16 21 36" src="https://user-images.githubusercontent.com/30186818/121909311-15087e80-cd2e-11eb-90a1-b64c56de362e.png">

**Comment by aninde** [comment]
Work well with v9.0.1 https://jsfiddle.net/aninde/tnra9bzo/.
