### ISSUE TITLE
Merged cells miss some borders in Chrome

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8400]
### Description

* The issue is not reproducible in Firefox
* Rerender of the table does not help (example by cell edition)

The issue works the same in older versions of Handsontable but seems to be visible only in the newest version of Chrome 91.0.4472.124. However, it works well on Brave v 1.26.74 Chromium: 91.0.4472.124.

### Case - merge via menu
1. Go to https://jsfiddle.net/9rz4yoj2/3/
2. Merge B1:D4

**Output**
![Screenshot 2022-06-08 at 12 56 29](https://user-images.githubusercontent.com/10757813/172599760-c821a41e-6565-44ea-a08e-31e63f64037d.png)

### Case - autofill merged cell

1. Go to https://jsfiddle.net/2048vmfL/
4. Autofill any merge cell

If you autofill them to the point that the scroll moves the borders are correctly attached. But when the viewport does not change some borders are gone.
It also works the same if you merge some cells using the context menu.

![merge](https://user-images.githubusercontent.com/10757813/124918838-c9c45180-dff5-11eb-95c2-f2c39ba5ae45.gif)

### Demo

https://jsfiddle.net/handsoncode/8ffpsqt6/

### Your environment
* Handsontable version: 9.0.1
* Browser Name and version: Chrome 91.0.4472.124
* Operating System: Windows 10

**Comment by zhaofang** [comment]
background color also miss after merge cells, How to fix it?

**Comment by AMBudnik** [comment]
Hi @zhaofang 

Can you share a demo? The Autofill does not 'copy' cell meta. You can test it here https://jsfiddle.net/r6us5kq8/1/

**Comment by zhaofang** [comment]
Hi:&nbsp;
my demo: https://jsfiddle.net/72yjafu9/
google chrome version:&nbsp;版本 96.0.4664.45（正式版本） （64 位）









------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "handsontable/handsontable"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月3日(星期五) 晚上8:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [handsontable/handsontable] Merged cells miss some borders in Chrome (#8400)





 
Hi @zhaofang
 
Can you share a demo? The Autofill does not 'copy' cell meta. You can test it here https://jsfiddle.net/r6us5kq8/1/
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AMBudnik** [comment]
@zhaofang when I run your demo it merges the cell with green background

![Kapture 2021-12-08 at 15 21 00](https://user-images.githubusercontent.com/10757813/145224143-20728c74-1683-4fe1-a516-24abc0d17b49.gif)


I've tested it on Chrome 96 and macOS Monterey 12.0.1

**Comment by zhaofang** [comment]
@AMBudnik My operating system is windows 10 .You can test again, and maybe you'll need to repeat it to be able to reproduce.
![GIF 2021-12-15 15-30-50](https://user-images.githubusercontent.com/6812077/146143852-be91e680-3a04-4960-85e2-d88046d3696e.gif)

**Comment by AMBudnik** [comment]
Thank you for sharing the steps to replicate the issue. I will test it further and update you as soon as I get a full scope of the issue.

**Comment by fansgithub** [comment]
@zhaofang  I solved a similar problem by adding the following css code
![image](https://user-images.githubusercontent.com/22794174/146348864-56e102e1-c237-4d5a-aa68-374694045ff7.png)

**Comment by fansgithub** [comment]
My phenomenon is that the background color does not take effect after merging
![image](https://user-images.githubusercontent.com/22794174/146349175-fb3ed1ab-49ae-460b-927f-72710ed4ad62.png)

**Comment by AMBudnik** [comment]
Hi @zhaofang @fansgithub thank you for all your feedback. I have posted the report on that issue separately here https://github.com/handsontable/handsontable/issues/9053
I will notify you once we solve it.

**Comment by adrianszymanski89** [comment]
The issue persists in version 12+

https://jsfiddle.net/ydo7cejm/1/

**Comment by AMBudnik** [comment]
Hi @zhaofang @fansgithub, I am more than happy to inform you that the issue is solved. Please update to Handsontable v12.3.1 to see the changes.
