### ISSUE TITLE
Options>cells - define what are the cell properties

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8467]
### Description
Similar issue as https://github.com/handsontable/docs/issues/175 

We allow to set up cell properties but we do not list possible options.

Reference: handsontable/docs#9
The issue has been reported as a part of the handsontable/support#254 investigation

**Comment by kirszenbaum** [comment]
@AMBudnik - since the descriptions of all configuration options changed, this issue is no longer valid: https://handsontable.com/docs/api/options/#cells

Now, we're explicitly saying that the `cells` option lets you apply any other configuration options (or "cell properties"):
> The cells option lets you apply [configuration options](https://handsontable.com/docs/setting-options/) to individual grid elements (columns, rows, cells), based on any logic you implement.

I'll just change the wording slightly, in #9702 (which fixes #8468 too).

**Comment by AMBudnik** [comment]
@kirszenbaum agree. I am closing this issue as done.
