### ISSUE TITLE
How to pass an id to each cell and get it back with getData() or any other way

### ISSUE THREAD

**Issue by kolyasya** [handsontable/handsontable#8539]
### Description
I'm trying to use Handsontable to display and manipulate the data which I have in such format: 

```
[
  { id: 1, value: 'First', row: 0, col: 0, ...otherProps },
  { id: 2, value: 'Second', row: 0, col: 1, ...otherProps },
  { id: 3, value: 'Third', row: 1, col: 0, ...otherProps },
  { id: 4, value: 'Fourth', row: 1, col: 1, ...otherProps },
  ...etc.
]
```

I need to get data back in the same format after Handsontable manipulations. At the moment `.getData()` returns just an array of values like: 
```
[
 ['First', 'Second'],
 ['Third', 'Fourth'],
]
```

Obviously I can't compare items by `value`. I would like to pass an `id` to each cell so I can easily convert an array back into my format and merge related `...otherProps` for each cell.

Is that possible? I've read Data Binding section of docs, but can't find an answer. All my attempts are resulting in a 2-dimensional array without additional props.

**Comment by swistach** [comment]
Hi @kolyasya,
I think the [`getSourceData()`](https://handsontable.com/docs/api/core/#getsourcedata)/[`getSourceDataAtRow()`](https://handsontable.com/docs/api/core/#getsourcedataatrow) are the methods do you look for.

Please notice, to use these functions properly, you have to use physical indexes. You can use [`toPhysicalRow`](https://handsontable.com/docs/api/core/#tophysicalrow) to transform indexes.

_*_ `toPhysicalColumn` is not necessary if your dataset's type is an array of objects.

**Comment by Bboyredstar** [comment]
HI @swistach, 
Can you explain better what need to do with toPhysicalRow method?
When we must use it?

**Comment by swistach** [comment]
Hi @Bboyredstar,

>Can you explain better what need to do with toPhysicalRow method?
>When we must use it?

Since v8, we have 3 presentation layers.

1) Physical - it’s a 1:1 reflection of the dataset you attached to Handsontable. We do not put any transformation here (hiding, filtering, sorting, moving).
2) Visual - Responses to transform dataset into 2d array with attached data transformations (filtering, sorting, moving)
3) Renderable - Responses to apply visual attributes, like hiding. It does not interfere with the data addressing for getting cells’ values from Handsontable. We use that layer to reduce over-rendering DOM elements and for other performance reasons.

If you use filtering, sorting, moving - then you should translate indexes depending on the indexes you start with.
You can check that information in our documentation. In the arguments' description, we put information on what kind of indexes you should use in methods or what kind of indexes you get in hooks.

> And can we bind data like {row:0, col:0, value:'value', ...otherProps} to cell(0;0)?

Not directly, I explained that on our forum: https://forum.handsontable.com/t/custom-object-data-binding-problem/5410
