### ISSUE TITLE
Cut/copy then Paste with objects as cell value

### ISSUE THREAD

**Issue by Renrhaf** [handsontable/handsontable#862]
Hello and thanks for this great plugin,

I think I discovered a bug in Handsontable, or more precisely, in the copypaste.js library. But I am not sure about that.

My table cells contains objects like :  {'workload' => 1, 'id' => 1242}
When I want to copy/cut and then paste data, the pasted data is a string '[object Object]'.

I found a workaround which is to stringify my JSON object, so that the pasted string contains all my information. 

![image 1](https://f.cloud.github.com/assets/690629/748320/285bd5f2-e486-11e2-86c8-0adc576b38c6.png)

Is it a known bug, or am I doing something wrong ?
Thanks

**Comment by ziaulrehmandevsinc** [comment]
@Renrhaf @lucamaral @codename-  @AndreasBieri 
Thanks for this help guys, i was facing same issue and it solved this.
Also facing another related issue, i am asking here, becuase it is closely related and chances are you might have faced it too.
When i try to 'paste' some copied columns or even single cell value to other cell, it does not work, on debugging i found that on edit i have functions bound which converts our data to object, but on paste, no function to parse it to object before actual paste is there, so because of type miss-match it doesn't actually paste, and returns without showing any kind of error.
I couldn't find any beforepaste callback or anything like that in handsontable docs. Can you help me(and possibly others) in this issue. I just need to process values being pasted to convert them to objects before the actual paste happens. I don't want to edit source of handsontable.js of-course.

**Comment by lucamaral** [comment]
Maybe you could copy a stringify representation (JSON.stringify) and parse (JSON.parse) the value on `afterChange/beforeChange` hook. But doing that, when you copy a cell to Excel, the stringify will be pasted.

Do you need to paste somewhere else, like Excel, Text editors, etc?

**Comment by ziaulrehmandevsinc** [comment]
@lucamaral Thankyou for the suggestion, i have solved this issue by:
https://github.com/handsontable/handsontable/issues/588#issuecomment-259652186

Actually before change is called when a change is approved, on paste, change was not being approved because of type mismatch(data being pasted is string and saved type is object). So, i needed to parse data being pasted before paste actually tries to check and paste it. I added a hook beforePaste in which i converted the pasted strings to object. Everything working fine.
