### ISSUE TITLE
[8.0.0+] `autoRowSize` does not work well with `hiddenColumn`

### ISSUE THREAD

**Issue by gianadrias** [handsontable/handsontable#8667]
### Description
I was wondering whenever I hide columns, autoRowSize is not working and each row size becomes large.
I also tried to change row height by adding rowHeights and it doesn't work too.

Hidden Columns is enabled
Result:
![image](https://user-images.githubusercontent.com/11287662/130268101-23b33721-32a6-4c13-b5ee-709c711ae04b.png)
Debug:
![image](https://user-images.githubusercontent.com/11287662/130268175-318e4442-6616-44a9-9d3f-7579d53ca45a.png)

Hidden Columns is disabled
Result:
![image](https://user-images.githubusercontent.com/11287662/130268646-e84a61b3-1a25-4af8-a056-267840fade94.png)
Debug:
![image](https://user-images.githubusercontent.com/11287662/130268415-6ad0c0ac-62e0-44f4-8a44-2d826d26c2c5.png)

### Demo

https://jsfiddle.net/1d0uyf27/2/

### Your environment
* Handsontable version: 9.0.2
* Browser Name and version: Chrome
* Operating System: Any

**Comment by AMBudnik** [comment]
Thank you for sharing the bug report @gianadrias 

I have simplified the demo and found out that this issue is a regression from v8.0.0.

Here is how it works in v7.4.2. https://jsfiddle.net/4yn5kgv6/8/
![image](https://user-images.githubusercontent.com/10757813/130421880-21c1e072-679d-4da1-94fd-1435b440b6f5.png)


And here is v8 https://jsfiddle.net/4yn5kgv6/9/
![image](https://user-images.githubusercontent.com/10757813/130421957-59069560-e22e-4961-9263-864fbc325dda.png)

And since v8.0.0, nothing has changed. It works the same as v9.0.2

I will notify you as soon as we fix it.
