### ISSUE TITLE
[8.4.0+] NestedHeaders doesn't respect no. columns defined in `columns`

### ISSUE THREAD

**Issue by mrpiotr-dev** [handsontable/handsontable#8694]
### Description
The regression occurs if the first row of our dataset contains fewer columns than we defined in the `columns` option.
If we do so, Handsontable will render the exact number of columns (by `columns` configuration), but headers for the part of columns will be empty.
Using `startCols` or `dataSchema` options doesn't help. If we use `minCols` (without `columns`), then Handsontable will properly render headers.

### Steps to reproduce
1. Go to the demo
2. Look at the `nestedHeaders` configuration and the rendered table

### Demo
https://jsfiddle.net/9y6zs0L5/

### Your environment
* Handsontable version: 8.4.0+
* Browser Name and version: any
* Operating System: any

**Comment by AMBudnik** [comment]
_Note to myself - update Client after release ZD - 27423_

**Comment by AMBudnik** [comment]
This issue is solved for v11.1.0

Headers before the fix (broken)
![Zrzut ekranu 2022-01-20 o 09 30 10](https://user-images.githubusercontent.com/10757813/150301740-9d3720bd-aeee-44d7-8b05-8f5fdd7fb825.png)


Headers after the fix (v11.1.0)
![Zrzut ekranu 2022-01-20 o 09 30 30](https://user-images.githubusercontent.com/10757813/150301784-42ca875d-1a3f-4402-a7f4-6894ed20e6ce.png)

_(ps. Client updated)_
