### ISSUE TITLE
Dynamic column adding / deleting

### ISSUE THREAD

**Issue by hhasenauer** [handsontable/handsontable#8705]
### Description
Dynamically adding or removing multiple columns is very slow and leads to unresponsive Browser.
When working with Angular components (hot-column) and using *ngFor to manage columns, this can break the application very fast.

### Steps to reproduce
1. Click on "Generate Columns" - 300 columns are now generated and it takes almost 10 seconds
2. Click on "Delete Columns" - all columns are removed which takes again almost 10 seconds

### Demo
https://stackblitz.com/edit/angular-ivy-xbfcbf?file=src/app/app.component.ts

### Your environment
* Angular version: 12.2.4
* Handsontable version: 9.0.2
* Wrapper version: 9.0.2
* Browser Name and version: Version 14.1.2 (16611.3.10.1.6)
* Operating System: MacOS BigSur 11.5.2 (20G95)

**Comment by mrpiotr-dev** [comment]
Hi @hhasenauer
Thank you for your reporting. At the moment this issue is unfixable.
If you create elements by `NgForOf` directive, then in each loop newly created `hot-column` component propagates change to the parent component (`hot-table`). Parent component - our wrapper - react on that propagaton by collecting `hot-table` childrens. From collected children elements prepares new configuration object and pass it through Handsontable instance using `updateSettings`.
Reffering to your example - even if you change `columns` property once, the parent-child propagation invokes `updateSettings` x300 with incremental number of columns.
The only suggestion I have at the moment is to use `columns` option over `hot-column`: https://stackblitz.com/edit/angular-ivy-wz4hve?file=src%2Fapp%2Fapp.component.html
