### ISSUE TITLE
Pressing ENTER key not move to the next cell

### ISSUE THREAD

**Issue by giorgitus** [handsontable/handsontable#8863]
### Description
In a table with only a row when I edit a cell and press ENTER the selected cell remain the same and it's not moving to the next one. (Is it change the default behaviour?)

### Steps to reproduce
1.Start to edit a cell
2.Press ENTER

v9
https://user-images.githubusercontent.com/56067680/137134402-99eaf5d9-bf55-4878-ada7-7bbb76fbc8b4.mov
v10

https://user-images.githubusercontent.com/56067680/137134513-9ceeddd2-08ad-40b3-a9cc-d9792614d75f.mov

### Demo
https://jsfiddle.net/gtoniolo/drk3c1m9/   v9.0
https://jsfiddle.net/gtoniolo/drk3c1m9/2  v10.0

### Your environment
Handsontable version: 10
Browser Name and version: Chrome 94
Operating System: MacOS Big Sur 11.6

**Comment by mrpiotr-dev** [comment]
Hi @giorgitus,
This behavior is caused by one of our recent breaking changes you can find in [release notes](https://github.com/handsontable/handsontable/releases/tag/10.0.0):
- Changed the autoWrapRow and autoWrapCol options` default values from true to false. #8662 (Breaking change)
Between [v4.0.0](https://github.com/handsontable/handsontable/releases/tag/4.0.0) and v9.x  `autoWrapRow` and `autoWrapCol` were enabled. In your example, pressing <kbd>ENTER</kbd> key to apply changes in the editor, automatically moves the selection to the next selectable cell below. Because there is only one row, cell selection seeks for next selectable cell in the column on the right.

If `autoWrapCol` is disabled, then if cell selection reaches the very bottom cell in the column - it will stay on that cell.

These options are responsible for controlling keyboard navigation if your selection lies at the edge of the table. It allows jumping to the next/previous column or row depending on what the end-user used.

In our documentation, you can find a detailed description of both options:
- https://handsontable.com/docs/api/options/#autowrapcol
- https://handsontable.com/docs/api/options/#autowraprow
