### ISSUE TITLE
Distribute CodeSandbox demos under the Handsontable official account

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#8909]
### Description

Distribute CodeSandbox demos under the Handsontable official account and **freeze** them.

### Links

1. https://handsontable.com/docs/hello-world/
2. https://handsontable.com/docs/react-hot-column/#declaring-column-settings
3. https://handsontable.com/demo

**Comment by warpech** [comment]
I think this should be closed, because we tried that while working on https://github.com/handsontable/handsontable/issues/8927 and CodeSandbox did not support our use case, mildly speaking.

@kirszenbaum is working on moving snippets as *inline* snippets into our docs, tracked in https://github.com/handsontable/handsontable/issues/8927

**Comment by warpech** [comment]
Now tracked in https://github.com/handsontable/handsontable/issues/8980
