### ISSUE TITLE
[RTL] No RTL support in Internet Explorer

### ISSUE THREAD

**Issue by aninde** [handsontable/handsontable#8911]
### Description

As in the title, `dir ="rtl"` [is not supported](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir#browser_compatibility) by Internet Explorer. 
Therefore, Handsontable placed in RTL div does not display at all on IE page.

![Windows_10_0__IE_11_0_2021-10-28T13 48 36](https://user-images.githubusercontent.com/30186818/139260308-e5d81155-6d2a-48e9-9baf-9786e9a0ea46.jpg)

### Your environment
* Handsontable version: n/a
* Browser Name and version: Internet Explorer 9, 10, 11
* Operating System: Windows 10 Pro

**Comment by warpech** [comment]
In this case, MDN must be wrong, because `dir` is a very old HTML attribute. For example, it exists in HTML4 spec: https://www.w3.org/TR/html401/struct/dirlang.html#h-8.2

I made a test and it works:

```html
<!DOCTYPE html>
<html>
  <head>
    <title>Test</title>
  </head>
  <body>
    <div dir="rtl">Test RTL</div>
    <div dir="ltr">Test LTR</div>
  </body>
</html>
```

![image](https://user-images.githubusercontent.com/566463/142949763-5aef2970-8c3b-4e41-a186-625cf49ee5a2.png)

So if something does not work in IE11, it must be on our end.

**Comment by budnix** [comment]
I've checked that using the codebase from the latest `rtl` branch + codebase that fixes overlays and borders (#9104, #9098) and everything seems to work ok.

**Comment by aninde** [comment]
Since version 12 IE is no longer supported.

**Comment by warpech** [comment]
Closing as won't fix
