### ISSUE TITLE
Docs: Broken links report

### ISSUE THREAD

**Issue by kirszenbaum** [handsontable/handsontable#8973]
There are 40 links coming up in the broken links report:

[report-check-links.xlsx](https://github.com/handsontable/handsontable/files/7595649/report-check-links.xlsx)

UPDATE: After #8991 , there will be 75 broken links coming up

To do :
- [x] Analyze each broken link
- [x] ~~Fix what can be fixed~~
- [ ] For the rest, prepare a whitelist

**Comment by kirszenbaum** [comment]
I checked all the broken links:
- Every broken link in the report is caused by a situation of the same kind: a linked-to page doesn't exist for another docs version. For example:
  - You're on a page that was added in version 11 (a new feature). When you try to change the version to 10, you get 404 (because the page doesn't **and shouldn't** exist  in version 10).
  - You're on version 10, on a page that was removed in version 11. When you try to change the version to 11, you get 404 (because the page doesn't **and shouldn't** exist  in version 11).

While this behavior is correct, it has two drawbacks:
- The broken links report gets muddled (this could be fixed by a whitelist, but we'd need to update it every time we add/remove a page)
- From the user's perspective, it's a 404 like any other. There's no message saying `This feature/page didn't exist in HoT 10 yet` or `This feature/page was removed in 11`.

I'm guessing that the end-user impact is minor (we don't track users' navigation around the docs site, though, so we can't say for sure).

@warpech @Siemienik - should we do anything about it, WDYT?

**Comment by kirszenbaum** [comment]
Update: #9043 makes it easier to add links rewrite rules manually. That could be one way of fixing the links mentioned in this issue (although they'd still come up in the broken links report generated locally).

**Comment by Siemienik** [comment]
@kirszenbaum when I was implementing the documentation engine, there was a plan to add smart 404 pages, which in cases like that will show suggested pages (search results) + 404 response code. That was never done. I'm happy that here is an attempt to improve the situation by #9043.

Another way to accomplish this problem is to make links in the version's dropdown disabled when the page doesn't exist in the target version. That should be able to do by custom vuepress plugin.

**Comment by warpech** [comment]
If I understand it correctly, the problem is when the user uses the version picker (pictured below) while being on a page?

<img width="386" alt="Screenshot 2021-12-30 at 12 43 34" src="https://user-images.githubusercontent.com/566463/147748975-188b5fea-5a52-4700-adf1-91d2efef7478.png">
 
My recommendation is to redirect to the home page of the current category (if it makes sense) or to the home page of the docs. This will be useful and will silence the broken links report.

For example, if the missing page is about React, load the first page about React.

**Comment by AMBudnik** [comment]
@kirszenbaum @warpech I assume that this situation changed over the last month or two. Is this issue still valid?

**Comment by kirszenbaum** [comment]
@AMBudnik – that's right: there are no more broken linkes coming up in the report (I've just checked now on `develop`, to be sure), and we're using Ahrefs now anyway. Closing
