### ISSUE TITLE
Got t.tostring() error when using config autoRowSize: {syncLimit: '100%'}

### ISSUE THREAD

**Issue by joechanhk** [handsontable/handsontable#9062]
### Description
Got t.tostring() error when using config autoRowSize: {syncLimit: '100%'}
It should be a case error in the script, change it to t.toString() the issue can be solved

### Steps to reproduce
1. let any = new Handsontable( dom , {autoRowSize:{syncLimit:'100%'},data:any})
2.
3.

### Demo
N/A

### Your environment
* Handsontable version: 11.0.1
* Browser Name and version: Microsoft Edge 96.0.1054.62
* Operating System: Window 10

**Comment by AMBudnik** [comment]
Thank you for sharing the issue report @joechanhk 
This issue is already addressed within this topic https://github.com/handsontable/handsontable/issues/9006 
It is already fixed and waits for release on the `develop` branch. I will update notify you after the release of the new version, which is planned for January.

**Comment by AMBudnik** [comment]
Hi @joechanhk 

we released version 11.1.0 that solves that issue.
Please update and let me know if it works for you.
