### ISSUE TITLE
[RTL] Jumping horizontal scroll

### ISSUE THREAD

**Issue by budnix** [handsontable/handsontable#9107]
### Description

There is an issue with the jumping horizontal scroll when the table is initialized without `width` and `height` options (the scrollable element is the Window object). Based on the #9104 and #9098 fixes I can reproduce the issue by scrolling the horizontal bar and selecting some cells in the middle of the table. The issue should be fixed after merging the mentioned PR to the `rtl` branch.

![Kapture 2022-01-13 at 10 27 31](https://user-images.githubusercontent.com/571316/149302832-96ed15f6-e813-4ca4-bfde-e828dcffe333.gif)

**Comment by aninde** [comment]
Looks like this issue is not solved by v12.0.0.
There is no horizontal scroll the table is initialized without width and height options.
Demo https://jsfiddle.net/cL7e5h02/

**Comment by aninde** [comment]
I was wrong. The above comment is invalid. 

Author's  explanation @budnix:
 _In this configuration, HoT sets the scrolled element as Window object. But it is not possible in such a LTR-> RTL mix, I think that it results from the limitations of the browser (because how would it show the browser scroll)._

Proper demo resolving this issue with v12.0.0 https://jsfiddle.net/budnix/hf6qrz0d/

**Comment by warpech** [comment]
I think that the above explanation is good, but the "proper demo" link is not good. The proper demo is to show that if you don't provide the dimensions, you must have the same direction of the document and the component. See line 15 in my changed example: https://jsfiddle.net/warpech/vs8y46cu/

@kirszenbaum I propose to change the explanation in https://handsontable.com/docs/grid-size/#what-if-the-size-is-not-set

**From:**

If you don't define the dimensions, Handsontable will generate as many rows and columns as possible to fill available space.

**To:**

If you don't define the dimensions, Handsontable will generate as many rows and columns as possible to fill available space. If the grid content does not fit in the viewport, native window scrollbars will be used for scrolling.

Note that for this to work, the [layout direction]() of the component must be the same as the document. Otherwise, if the document is LTR and the component is RTL (or the other way round), horizontal scrolling will not be possible.

**Comment by kirszenbaum** [comment]
@warpech 
> @kirszenbaum I propose to change the explanation

Done in #9271: [commit](https://github.com/handsontable/handsontable/pull/9271/commits/f0a387eacc2ed5d9ff69e280f05dc9072074c40e)

**Comment by warpech** [comment]
Thanks, looks good to me

**Comment by AMBudnik** [comment]
Closed with https://github.com/handsontable/handsontable/issues/8760 and developed and done in Handsontable v12.

For more information please check out our Release Notes - https://handsontable.com/docs/release-notes/#_12-0-0
