### ISSUE TITLE
Custom borders add too much event to body

### ISSUE THREAD

**Issue by le0l1** [handsontable/handsontable#9145]
Each custom border will add a mouse event to the body, which causes the performance issue.

![image](https://user-images.githubusercontent.com/20632096/150932055-791354c5-3ea2-4dbc-8251-bb3522699223.png)
![image](https://user-images.githubusercontent.com/20632096/150932184-1cbb21a9-f71b-45f4-a3ba-1fe4ed41ec2d.png)

### Your environment
* Handsontable version: 11.0.1
* Browser name and version: chrome
* Operating system: mac

**Comment by le0l1** [comment]
it will take more time when clicking the cell when more custom borders added

**Comment by warpech** [comment]
Please note that some improvements were released in version 11.1.0 (https://github.com/handsontable/handsontable/pull/9044)

I can confirm there is an event for each custom border and that it seems redundant. These events are registered here:

https://github.com/handsontable/handsontable/blob/4c2858deffdb19f733978f8990886f300fb80183/handsontable/src/3rdparty/walkontable/src/border.js#L72-L73

However, @le0l1, can you paste a link to your JSFiddle that confirms that the poor performance is caused by the DOM events? The DevTools should show that. I thought that the main problem are the DIVs themselves, which is part of a larger issue that will take some time (https://github.com/handsontable/handsontable/issues/6467).

**Comment by le0l1** [comment]
Sorry, we don`t init handsontable  with runOutSideAngular, that`s why the performance bad
