### ISSUE TITLE
Prevent history navigation on horizontally-scrolling elements

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#9272]
### Description

Scrolling left in the grid triggers the page-back navigation.

### Steps to reproduce

1. Go to demo at https://handsontable.com/docs/demo/#try-out-the-demo-s-features
2. Scroll to the right, and then to the left
3. See how the page-back indicator comes up. If you let go, you leave the page

### Demo

https://handsontable.com/docs/demo/#try-out-the-demo-s-features

### Your environment
* Handsontable version: 11.1
* Browser name and version: Safari 15.3
* Operating system: macOS Monterey

Inform [Zen](https://handsontable.zendesk.com/agent/tickets/28215)

**Comment by budnix** [comment]
The issue is hard to fix. Thanks to the `overscroll-behavior` CSS property, we can prevent the browser from navigating, but it turned out that it works only on FF. On Safari (15.4), I was not able to find any working solution. For Chrome (100, 103 - canary) I was able to find a workaround (with dynamically added style to the document `body`) but it worked unstably.

**Comment by AMBudnik** [comment]
As established in the meeting today

> Handsontable uses native browser scrollbars to prevent the content from overflowing from the container boundaries. On some OS, the same gestures are used both for scrolling and for history navigation. Handsontable does not limit the gestures in any way. This behavior can be configured in the OS settings.

That is why this issue won't be further processed and is closed as `Won't fix`.

For anyone interested in a workaround we suggest trying to use `overscroll-behavior-x: none;` on the `body` element in Chrome and adding the same settings on Firefox to all the scrollable elements.
