### ISSUE TITLE
After filtering, insert data backwards

### ISSUE THREAD

**Issue by ananzhusen** [handsontable/handsontable#9471]
### Description

When I filter and insert data after a row, unfilter and find that the insert position is not after that row。

### Steps to reproduce

1.
2.
3.

### Demo

https://jsfiddle.net/handsoncode/dezfbgjt/

### Your environment
* Vue wrapper version:2.0
* Handsontable version:^11.1.0
* Browser name and version:chrome
* Operating system:windows

**Comment by AMBudnik** [comment]
Hi @ananzhusen 

I made this demo https://jsfiddle.net/91hna8r3/1/ to replicate the issue. But it seems that I'm missing some steps. This is what I was doing.

![filtering](https://user-images.githubusercontent.com/10757813/167597110-96e221ed-aded-4a6d-ae91-3b8f059d43be.gif)

**Comment by ananzhusen** [comment]
why not try 'row_below'？As shown in the figure below。
![font](https://user-images.githubusercontent.com/48847159/167609736-38603df8-3b1e-4c2c-88e1-8e45685336a5.gif)
)

**Comment by AMBudnik** [comment]
Thank you for sharing the scenario to replicate the issue. You are right, the row should not be kept as the last one after we retrieve the data. I'm marking this issue as a bug and will notify you as soon as we fix it.

**Comment by ananzhusen** [comment]
Thank you for your attention

**Comment by aninde** [comment]
@ananzhusen this issue will be fixed by the upcoming v12.2 https://jsfiddle.net/aninde/6btv2c3n/2/.

https://user-images.githubusercontent.com/30186818/196985238-4b7a1da4-e05e-4b46-801b-8a9876264f83.mov

**Comment by AMBudnik** [comment]
Thank you for your input once again, @ananzhusen 

We just released Handsontable v12.2.0, where this issue is fixed. Also, we made some beneficial changes to the `alter()` method you can read more about it [here in the release notes](https://handsontable.com/docs/react-data-grid/release-notes/#_12-2) or check the altered [method in the documentation](https://handsontable.com/docs/react-data-grid/api/core/#alter).
