### ISSUE TITLE
afterFormulasValuesUpdate triggered at startup with all the data as changes

### ISSUE THREAD

**Issue by pabloimrik17** [handsontable/handsontable#9598]
### Description
At the mount of the HotTable component, the afterFormulasValuesUpdate callback is triggered with all the data in the table as "changes".

### Steps to reproduce

1. Run a HotTable with data, formulas engine and afterFormulasValuesUpdate callback implemented
2. Check the changes parameter on the first call.

### Demo

https://jsfiddle.net/3serxp5o/3/

### Your environment
* React wrapper version: 12.0.1
* Handsontable version: 12.0.1
* Browser name and version: Chrome 102
* Operating system: Windows 10

**Comment by pabloimrik17** [comment]
Also i just realized that the callback is called when i edit a cell without any kind of formula or formula dependency

**Comment by AMBudnik** [comment]
That's true. I did some tests but still need to consult the team. 

Thank you for the report. I will get back with updates shortly.

**Comment by pabloimrik17** [comment]
No problem, so far im using this temporal fix to get only the changes triggered by formulas inside the callback

```typescript 
const hotInstance = this.gvSpreadSheetRef.current?.hotTableRef.current?.hotInstance;
const formulaPlugin = hotInstance?.getPlugin("formulas");

// Actualmente en el array de changes vienen todos los cambios, no solo los de por formulas
const formulaChanges = changes.filter(({ address: { row, col } }) => formulaPlugin?.isFormulaCellType(row, col));
```

**Comment by warpech** [comment]
Hi @pabloimrik17, thanks for the questions!

> At the mount of the HotTable component, the afterFormulasValuesUpdate callback is triggered with all the data in the table as "changes".

It is by design. 

The `afterFormulasValuesUpdate`, in its first call after the initialization, contains all of the calculated values. For example, if your data set contains formulas, the first call of `afterFormulasValuesUpdate` will contains the calculated results of these formulas.

> Also i just realized that the callback is called when i edit a cell without any kind of formula or formula dependency

It is by design.

When there are no dependent cells, the array in the callback will only contain the edited cells.

---

I agree that the name of the `afterFormulasValuesUpdate` hook might sound misleading, because the word "formulas" suggests that it only fires when there are formulas and the word "update" suggests that it only fires on updates. I think we can clarify that in the hook's description in the API reference.

cc @kirszenbaum

**Comment by pabloimrik17** [comment]
Hi @warpech 

> It is by design.
> 
> The afterFormulasValuesUpdate, in its first call after the initialization, contains all of the calculated values. For example, if your data set contains formulas, the first call of afterFormulasValuesUpdate will contains the calculated results of these formulas.

In my case at initialization there is no formula in my data set, and still called once the table is mounted, with all the data in the data set as changes. Is this also by design?

---

Could you give more detail about how `afterFormulasValuesUpdate` and `afterChange` interact and what each one "do" when a change is fired?

Im my current project i need to track all the changed cells (final values) and im using both callbacks. Before i added the formula engine i was using only `afterChange`.

After i added the Hyperformula engine, i thought that `afterFormulasValuesUpdate` was the callback where to get only the formula related edited cells. 

After some time debugging both callbacks and making changes on the table im not sure if i still need to listen both callbacks or just `afterChange`

To be clear i just need the final values (visible values) on cells. I dont need to store the formulas, instead i need the value calculated from the formula.

**Comment by AMBudnik** [comment]
>Could you give more detail about how afterFormulasValuesUpdate and afterChange interact and what each one "do" when a change is fired?

Let me answer that question in detail.

| afterChange                                                                         | afterFormulasValuesUpdate                                                     |
|-------------------------------------------------------------------------------------|-------------------------------------------------------------------------------|
| Has 2 parameters: array of changes, source of change                                | Has 1 parameter: array of changes                                             |
| The array of changes on initialization returns `null`                              | The array of changes on initialization returns an array of all of the cells |
| On a single value change it returns [row_index, column_index, old_value, new_value] | On a single value change it returns { address: { sheet, row, col}, newValue}  |
| Runs after beforeChange and afterFormulasValuesUpdate                               | Runs before beforeChange and afterFormulasValuesUpdate                        |
| Shows new_value as a formula for formula cell                                       | Shows new_value as a calculated formula for formula cell                      |

And the answer to 

>In my case at initialization there is no formula in my data set, and still called once the table is mounted, with all the data in the data set as changes. Is this also by design?

is YES. The formulas engine (HyperFormula) watches all the cells (not only the ones with formulas) since formulas often depend on cells with simple values. When the value changes in cell X, the `afterFormulasValuesUpdate` fires returning cell X and all cells that have been updated automatically by the formula engine (because they contain formulas dependent on cell X or volatile formulas e.g. `RAND()`).

When it comes to the name of the hook we agree that the name `afterFormulasValuesUpdate` is indeed misleading. The better name for this hook would be `afterValuesUpdateInFormulaEngine` because it is just a wrapper for [the *valuesUpdated* hook from the formula engine (HyperFormula)](https://handsontable.github.io/hyperformula/api/interfaces/listeners.html#valuesupdated). 

Also, there's one tip here: to avoid the initial call of all of the cells in the `afterFormulasValuesUpdate` hook you can use the [`addHook` method](https://handsontable.com/docs/api/core/#addhook) to attach the hook after initialization. 

I hope that it helped to clarify what is the concept of `afterFormulasValuesUpdate`. But feel free to share any additional questions. That helps a lot to improve our documentation.
