### ISSUE TITLE
After deleting a row in nested rows the column width jumps

### ISSUE THREAD

**Issue by Paqura** [handsontable/handsontable#9754]
### Description
After deleting a row in nested rows the column width jumps

### Steps to reproduce
1. Open https://handsontable.com/docs/row-parent-child/#preparing-the-data-source
2. Click to `preview`
3. Remove row

**Comment by AMBudnik** [comment]
Thank you for sharing the issue report, @Paqura 
I replicated it using Chrome 103 on macOS Monterey.

It seems that the `rowHeaders` gets wider after we remove the row for the first time (afterward nothing like that happens again)

<img width="640" alt="Screenshot 2022-08-08 at 14 33 49" src="https://user-images.githubusercontent.com/10757813/183418565-5b1a94c5-4c46-4ab9-b04a-668e7bb7c942.png">


Related topics:
* https://github.com/handsontable/handsontable/issues/6006
* https://github.com/handsontable/handsontable/issues/6456

**Comment by AMBudnik** [comment]
Hi @Paqura 

we just fixed this issue! The fix is awaiting in Handsontable v14.0.0

Here https://handsontable.com/docs/javascript-data-grid/row-parent-child/#preparing-the-data-source in the new demo it already works as desired.

If you would like to read more about the changes in this version please visit https://handsontable.com/docs/javascript-data-grid/release-notes/#_14-0-0
