### ISSUE TITLE
Change file extension of react wrapper js files to mjs/cjs for jest compatibility

### ISSUE THREAD

**Issue by danyx23** [handsontable/handsontable#9843]
### Description

We have a medium size react/node codebase that uses jest for testing. We are in the process of [converting that codebase to esm](https://github.com/owid/owid-grapher/pull/1619). During this process we ran into some issues with tests running in jest not importing some libraries as esm modules and then crashing with weird errors.

File extensions take precedence in node's resolution strategy for imports (.mjs uses esm, .cjs uses commonjs). Since changing file extensions is otherwise mostly benign, I would like to ask if you would be willing to switch to compiling the output js files for the react wrapper modules to these file extensions. We have [a branch](https://github.com/handsontable/handsontable/compare/develop...owid:handsontable:react-wrapper-switch-to-cjs-and-mjs) with the (very small) changes for the react wrapper. If you think this is a reasonable thing to do and want it uniformly applied then I could of course make similar changes for the other wrappers.

### Steps to reproduce
Since this is a build issue when using jest to test things I don't include repo steps here. If you want I can try to create a minimal repo that shows the test issue with jest

### Your environment
* React wrapper version: 12.0
* Handsontable version: 12.0

**Comment by warpech** [comment]
Thank you @danyx23 for this report.

> If you want I can try to create a minimal repo that shows the test issue with jest

That would be more than welcome, thanks.

A few things for us to consider here:
1. are there any workarounds until we fix that? @danyx23 is there anything that works for you now to workaround this problem?
2. are all the tools/bundlers ready for the change. If I understand correctly, the `cjs` extension has only been supported since Node 16. What about users who are on Node 14? So far, they were supported.
3. how deep does this change need to go. Is only the wrapper code troublesome or also the core library, which also uses the `js` files.
4. are vanilla JS, Angular, Vue 2 and Vue 3 files equally affected. Probably yes, but that doesn't necessarily mean that we need to change all of them in a single release.

**Comment by tk-o** [comment]
As for `jest` & ESM/TS mix, consider switching to https://vitest.dev/guide/migration.html#migrating-from-jest

**Comment by AMBudnik** [comment]
Hi @danyx23 

We can call this issue solved, as React is published under .mjs now. Could you confirm that there is nothing else left in the subject to be changed?

**Comment by danyx23** [comment]
@AMBudnik I'm not 100% sure but I think a coworker of mine said something along those lines. I think we can close this issue and I'd re-open if there is still something to be done here - does that sound good?

**Comment by AMBudnik** [comment]
@danyx23 sure, that's a good plan. Thank you for the fast feedback.
