### ISSUE TITLE
Docs: add CSS import to all JS, Angular, Vue 2, Vue 3 examples

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#9887]
Extracted from #9877, leftover from #9886 planned to be done later

add CSS import to all JS, Angular, Vue 2, Vue 3 examples
- in consequence, we need to verify what will happen in the docs and JSFiddle (it should work, because it already works on https://dev.handsontable.com/docs/next/react-data-grid/installation/)

**Comment by kirszenbaum** [comment]
Adding `import 'handsontable/dist/handsontable.full.min.css';` breaks down JavaScript examples (both in the docs and in JSFiddle), giving this error:

<img width="457" alt="1" src="https://user-images.githubusercontent.com/29247866/194280903-30544254-1bac-4dcf-a998-647ae7c89a5c.png">

**Comment by aninde** [comment]
All of them work well locally, I tested each on develop. Four examples with [Vue Hot Column demos](http://localhost:8080/docs/javascript-data-grid/vue-hot-column/#using-the-hotcolumn-component-in-vue-2) have different templates than the rest. 
Maybe we could change or simplify them in the future so that they have `export `instead of `new Vue`.
